In [1]:
### ValDXer testing
import os
os.environ["HDXER_PATH"] = "/home/alexi/Documents/HDXer"

from ValDX.ValidationDX import ValDXer
from ValDX.VDX_Settings import Settings
import pandas as pd
import MDAnalysis as mda
from MDAnalysis.coordinates.XTC import XTCWriter

from pdbfixer import PDBFixer
from openmm.app import PDBFile

settings = Settings(name='allHOIPdab27')
settings.replicates = 1
settings.gamma_range = (2,6)
settings.train_frac = 0.5
settings.RW_exponent = [0]
settings.split_mode = 'R3'
settings.stride = 1000
# settings.HDXer_stride = 10000

settings.RW_do_reweighting = True
settings.RW_do_params = False
import pickle

VDX = ValDXer(settings)
expt_name = 'Experimental'
test_name = "HOIPdab27_allres"
import icecream as ic
# ic.disable()

/home/alexi/Documents/ValDX

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-1e790d77f81672c49be070e04474901747115651/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name testHOIP already exists. Attempting to change name to testHOIP0
Experiment name testHOIP already exists. Attempting to change name to testHOIP1
Experiment name testHOIP already exists. Attempting to change name to testHOIP2
Experiment name testHOIP already exists. Attempting to change name to testHOIP3

In [2]:
# ### add code to read in sequence from CIF file instead of copying it manually

# cif_file = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/AF-Q96EP0-F1-model_v4.cif"

# sequence_header = "_entity_poly.pdbx_seq_one_letter_code"
# sequence = ""
# seq_head_idx = 0
# with open(cif_file, 'r') as f:
#     lines = f.readlines()
#     for idx, line in enumerate(lines):
#         if sequence_header in line:
#             seq_head_idx = idx+1
#             break
    
#     for idx, line in enumerate(lines[seq_head_idx:]):
#         if idx > 0 and line[0] == ";":
#             break
#         sequence += line.strip()


# # print(sequence)



# # strip sequence of non letters
# sequence = ''.join([i for i in sequence if i.isalpha()])

# print(sequence)

# print("Sequence length: ", len(sequence))


# # convert sequence to FASTA format
# def write_fasta(sequence, header, file_name):
#     """
#     Writes a single-letter amino acid sequence to a FASTA file.
    
#     Parameters:
#     - sequence: A string containing the amino acid sequence.
#     - header: A string to be used as the header in the FASTA file.
#     - file_name: The name of the FASTA file to be created.
#     """
#     print(f"Writing sequence to {file_name}")
#     with open(file_name, 'w') as fasta_file:
#         # Write the header with the '>' symbol
#         fasta_file.write(f">{header}\n")
        
#         # Write the sequence in lines of 80 characters
#         for i in range(0, len(sequence), 80):
#             fasta_file.write(sequence[i:i+80] + "\n")

In [3]:

# fasta_path = os.path.join("raw_data", "HOIP", 'HOIP_apo.fasta')
# write_fasta(sequence, 'HOIPapo', fasta_path)

In [29]:
!pdb_fetch 6SC6 > 6SC6.pdb

In [76]:
import MDAnalysis as mda

u = mda.Universe("6SC6.pdb")

chain_A = u.select_atoms("protein and segid A")

print(len(chain_A.residues.resids))
# select residues in Chain A that are in 4A of Chain B and C
import numpy as np
selection_string = "protein and (segid A and around 4 (segid B or segid C))"

interface = u.select_atoms(selection_string)
interface_resids = interface.residues.resids  

print(interface_resids)


first_resid = chain_A.residues[0].resid
print(first_resid)

original_resids = chain_A.residues.resids

non_interface_resids = np.setdiff1d(original_resids, interface_resids)
non_interface_resids = non_interface_resids - (first_resid - 1)
print(non_interface_resids)
print(len(non_interface_resids))

interface_resids = interface_resids - (first_resid - 1)
print(interface_resids)
print(len(interface_resids))

365
[770 775 778 782 786 792 793 794 795 796 797 798 800 801 802 803 804 805
 819 820 822 827 828 829 830 852 854 855 874 875 876 892]
697
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  75  76  77  78  80  81  83  84  85  87  88  89  91  92  93  94  95
 103 110 111 112 113 114 115 116 117 118 119 120 121 122 125 127 128 129
 130 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151
 152 153 154 155 157 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212
 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230
 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248
 249 250 251 252 253 254 255 256 257 258 259 260 261 262 272 273 274 275
 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293
 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311
 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329
 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347
 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365
 366 367 368 369 370 371 372 373 374]
333
[ 74  79  82  86  90  96  97  98  99 100 101 102 104 105 106 107 108 109
 123 124 126 131 132 133 134 156 158 159 178 179 180 196]
32

In [71]:
# # select residues in Chain A that are in 4A of Chain B and C
# import numpy as np
# selection_string = "protein and (segid A and around 3 (segid B or segid C))"

# interface = u.select_atoms(selection_string)
# interface_resids = interface.residues.resids  

# print(interface_resids)


# first_resid = chain_A.residues[0].resid
# print(first_resid)

# original_resids = u.select_atoms("protein and segid A").residues.resids

# non_interface_resids = np.setdiff1d(original_resids, interface_resids)
# non_interface_resids = non_interface_resids - (first_resid - 1)
# print(non_interface_resids)
# print(len(non_interface_resids))

# interface_resids = interface_resids - (first_resid - 1)
# print(interface_resids)
# print(len(interface_resids))

[793 796 802 803 805 819 827 829 874]
697
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  98  99 101 102 103 104 105 108 110 111 112 113
 114 115 116 117 118 119 120 121 122 124 125 126 127 128 129 130 132 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374]
356
[ 97 100 106 107 109 123 131 133 178]
9

In [81]:
raw_hdx_path = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_dab27_pepitde.csv"
raw_hdx = pd.read_csv(raw_hdx_path)
raw_hdx.tail()

,Unnamed: 0,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD
322,3554,RYLHVRPQPLAGEDPPAYQARL,17,3.920370,339,360,5.954507,0.001550
323,3555,RYLHVRPQPLAGEDPPAYQARL,17,4.449823,339,360,5.959930,0.003633
324,3586,LQKLTEEVPLGQSIPRRRK,16,0.000000,361,379,5.065956,0.000764
325,3587,LQKLTEEVPLGQSIPRRRK,16,4.779131,361,379,5.056829,0.000418
326,3588,LQKLTEEVPLGQSIPRRRK,16,5.703951,361,379,5.061204,0.004166

In [82]:
# drop Unnamed: 0	

raw_hdx = raw_hdx.drop(columns=['Unnamed: 0'])
raw_hdx.head()

        Sequence  MaxUptake    Uptake  Start  End        RT     RT.SD
0        GPGQECA          5  0.000000      1    7  3.009246  0.007705
1        GPGQECA          5  2.012346      1    7  3.009432  0.004473
2        GPGQECA          5  2.311637      1    7  3.005504  0.000807
3  CAVCGWALPHNRM         11  0.000000      6   18  7.340539  0.000927
4  CAVCGWALPHNRM         11  3.740321      6   18  7.336039  0.000096

In [83]:
# assign peptide number for each start and end residue using ngroup
raw_hdx['peptide'] = raw_hdx.groupby(['Start','End']).ngroup()

raw_hdx.head()

        Sequence  MaxUptake    Uptake  Start  End        RT     RT.SD  peptide
0        GPGQECA          5  0.000000      1    7  3.009246  0.007705        0
1        GPGQECA          5  2.012346      1    7  3.009432  0.004473        0
2        GPGQECA          5  2.311637      1    7  3.005504  0.000807        0
3  CAVCGWALPHNRM         11  0.000000      6   18  7.340539  0.000927        1
4  CAVCGWALPHNRM         11  3.740321      6   18  7.336039  0.000096        1

In [84]:

times = [0, 0.5, 5.0]

num_peptides = len(raw_hdx)//len(times)

exposure = times * num_peptides

raw_hdx['Exposure'] = exposure

raw_hdx.head()

,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD,peptide,Exposure
0,GPGQECA,5,0.000000,1,7,3.009246,0.007705,0,0.0
1,GPGQECA,5,2.012346,1,7,3.009432,0.004473,0,0.5
2,GPGQECA,5,2.311637,1,7,3.005504,0.000807,0,5.0
3,CAVCGWALPHNRM,11,0.000000,6,18,7.340539,0.000927,1,0.0
4,CAVCGWALPHNRM,11,3.740321,6,18,7.336039,0.000096,1,0.5

In [85]:
raw_hdx['UptakeFraction'] = raw_hdx['Uptake'] / raw_hdx['MaxUptake']

raw_hdx.head()

,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD,peptide,Exposure,UptakeFraction
0,GPGQECA,5,0.000000,1,7,3.009246,0.007705,0,0.0,0.000000
1,GPGQECA,5,2.012346,1,7,3.009432,0.004473,0,0.5,0.402469
2,GPGQECA,5,2.311637,1,7,3.005504,0.000807,0,5.0,0.462327
3,CAVCGWALPHNRM,11,0.000000,6,18,7.340539,0.000927,1,0.0,0.000000
4,CAVCGWALPHNRM,11,3.740321,6,18,7.336039,0.000096,1,0.5,0.340029

In [86]:
# clamp UptakeFraction to 1
raw_hdx['UptakeFraction'] = raw_hdx['UptakeFraction'].clip(upper=1)

In [87]:
# # print entire dataframe
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# print(raw_hdx)

In [88]:

# pivot exposure and uptake fraction
grouped = raw_hdx.pivot(index=['Start', 'End'], columns='Exposure', values='UptakeFraction').reset_index()

# drop 
grouped.head()

Exposure  Start  End  0.0       0.5       5.0
0             1    7  0.0  0.402469  0.462327
1             6   18  0.0  0.340029  0.427788
2             6   21  0.0  0.388407  0.441139
3             6   25  0.0  0.443811  0.504754
4             7   18  0.0  0.369763  0.445936

In [89]:

# print entire dataframe
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
print(grouped)

Exposure  Start  End  0.0       0.5       5.0
0             1    7  0.0  0.402469  0.462327
1             6   18  0.0  0.340029  0.427788
2             6   21  0.0  0.388407  0.441139
3             6   25  0.0  0.443811  0.504754
4             7   18  0.0  0.369763  0.445936
5             7   21  0.0  0.420648  0.493444
6             7   25  0.0  0.471674  0.521372
7             8   18  0.0  0.397925  0.464610
8             8   20  0.0  0.447318  0.493591
9             8   21  0.0  0.448424  0.498205
10            8   24  0.0  0.474742  0.515481
11            8   25  0.0  0.468641  0.515149
12           11   18  0.0  0.439051  0.472297
13           11   20  0.0  0.478321  0.507977
14           11   21  0.0  0.505550  0.528220
15           11   23  0.0  0.546336  0.568180
16           11   25  0.0  0.522284  0.543982
17           19   25  0.0  0.520757  0.532098
18           26   32  0.0  0.168114  0.273818
19           26   33  0.0  0.157410  0.282713
20           27   33  0.0  0.161139  0.261833
21           33   40  0.0  0.332209  0.425088
22           34   40  0.0  0.329676  0.411284
23           34   41  0.0  0.345943  0.427551
24           41   48  0.0  0.362567  0.357360
25           41   49  0.0  0.357264  0.352674
26           41   51  0.0  0.359544  0.396409
27           42   49  0.0  0.299268  0.297244
28           42   51  0.0  0.306369  0.348016
29           42   65  0.0  0.312953  0.387691
30           49   61  0.0  0.247578  0.354258
31           49   65  0.0  0.316002  0.387238
32           50   65  0.0  0.323162  0.385013
33           52   61  0.0  0.298809  0.388226
34           52   65  0.0  0.379119  0.441521
35           74   84  0.0  0.403449  0.482444
36           76   84  0.0  0.407739  0.464032
37           77   84  0.0  0.385902  0.438297
38           77   85  0.0  0.373938  0.441569
39           77   87  0.0  0.438380  0.503364
40           77   88  0.0  0.384152  0.475130
41           77   97  0.0  0.443793  0.517532
42           85   97  0.0  0.402665  0.463399
43           86   97  0.0  0.384971  0.446233
44           88   97  0.0  0.432701  0.472943
45           89   97  0.0  0.452550  0.494695
46           98  104  0.0  0.168177  0.254944
47           98  106  0.0  0.140735  0.218926
48           98  108  0.0  0.206598  0.298474
49          113  120  0.0  0.314966  0.402006
50          114  120  0.0  0.352676  0.433908
51          117  131  0.0  0.168166  0.211564
52          121  131  0.0  0.141708  0.169501
53          121  132  0.0  0.139717  0.165821
54          132  149  0.0  0.233802  0.266438
55          132  150  0.0  0.237353  0.273043
56          132  153  0.0  0.248378  0.308360
57          150  169  0.0  0.444379  0.524798
58          151  162  0.0  0.311726  0.429068
59          151  167  0.0  0.405558  0.474148
60          151  169  0.0  0.461316  0.523610
61          151  170  0.0  0.488147  0.558260
62          154  169  0.0  0.483451  0.499623
63          155  169  0.0  0.487028  0.486980
64          169  183  0.0  0.275488  0.347352
65          170  183  0.0  0.254951  0.315747
66          170  185  0.0  0.253713  0.332597
67          170  186  0.0  0.288587  0.357025
68          171  183  0.0  0.227104  0.291644
69          171  186  0.0  0.294224  0.366382
70          184  195  0.0  0.364250  0.417543
71          184  208  0.0  0.241067  0.295832
72          187  195  0.0  0.353873  0.357684
73          187  208  0.0  0.217111  0.249810
74          187  209  0.0  0.208684  0.242520
75          188  208  0.0  0.188048  0.218220
76          194  208  0.0  0.111068  0.144536
77          196  208  0.0  0.126156  0.170162
78          213  223  0.0  0.327099  0.389475
79          224  238  0.0  0.184719  0.194108
80          224  239  0.0  0.153845  0.162748
81          247  257  0.0  0.058057  0.070442
82          247  259  0.0  0.080272  0.114853
83          247  260  0.0  0.086146  0.139173
84          248  259  0.0  0.085093  0.129218
85          248  260  0.0  0.085446  0.142430
86          250  257  0.0  0.065256  0.079095
87          250  260  0.0  0.091618  0.154506
88          253  260  0.0  0.123225  0.211457
89          261  275  0.0  0.513374  0.482097
90          261  276  0.0  0.483490  0.455344
91          261  278  0.0  0.473550  0.466535
92          261  281  0.0  0.439776  0.467094
93          305  313  0.0  0.076182  0.113462
94          305  315  0.0  0.071047  0.108402
95          308  315  0.0  0.047073  0.048289
96          314  327  0.0  0.087681  0.111538
97          316  327  0.0  0.088448  0.117868
98          317  327  0.0  0.094098  0.124386
99          333  356  0.0  0.176701  0.211997
100         334  356  0.0  0.193607  0.227885
101         334  357  0.0  0.195659  0.222752
102         336  356  0.0  0.206997  0.229045
103         336  357  0.0  0.210657  0.237383
104         336  360  0.0  0.210770  0.234352
105         338  357  0.0  0.214084  0.237292
106         338  360  0.0  0.218291  0.245068
107         339  360  0.0  0.230610  0.261754
108         361  379  0.0  0.298696  0.356497

In [175]:
# conver to HDXer format ie start, end, exposure_1, exposure_2 

# change Start to ResStr and End to ResEnd
hdx = grouped.rename(columns={'Start': 'ResStr', 'End': 'ResEnd'})

# drop the exposure column
hdx.columns.name = None

hdx["Residues"] = hdx.apply(lambda x: list(range(int(x['ResStr']), int(x['ResEnd'])+1)), axis=1)

print(hdx)
print(len(hdx))

     ResStr  ResEnd  0.0       0.5       5.0  \
0         1       7  0.0  0.402469  0.462327
1         6      18  0.0  0.340029  0.427788
2         6      21  0.0  0.388407  0.441139
3         6      25  0.0  0.443811  0.504754
4         7      18  0.0  0.369763  0.445936
5         7      21  0.0  0.420648  0.493444
6         7      25  0.0  0.471674  0.521372
7         8      18  0.0  0.397925  0.464610
8         8      20  0.0  0.447318  0.493591
9         8      21  0.0  0.448424  0.498205
10        8      24  0.0  0.474742  0.515481
11        8      25  0.0  0.468641  0.515149
12       11      18  0.0  0.439051  0.472297
13       11      20  0.0  0.478321  0.507977
14       11      21  0.0  0.505550  0.528220
15       11      23  0.0  0.546336  0.568180
16       11      25  0.0  0.522284  0.543982
17       19      25  0.0  0.520757  0.532098
18       26      32  0.0  0.168114  0.273818
19       26      33  0.0  0.157410  0.282713
20       27      33  0.0  0.161139  0.261833
21       33      40  0.0  0.332209  0.425088
22       34      40  0.0  0.329676  0.411284
23       34      41  0.0  0.345943  0.427551
24       41      48  0.0  0.362567  0.357360
25       41      49  0.0  0.357264  0.352674
26       41      51  0.0  0.359544  0.396409
27       42      49  0.0  0.299268  0.297244
28       42      51  0.0  0.306369  0.348016
29       42      65  0.0  0.312953  0.387691
30       49      61  0.0  0.247578  0.354258
31       49      65  0.0  0.316002  0.387238
32       50      65  0.0  0.323162  0.385013
33       52      61  0.0  0.298809  0.388226
34       52      65  0.0  0.379119  0.441521
35       74      84  0.0  0.403449  0.482444
36       76      84  0.0  0.407739  0.464032
37       77      84  0.0  0.385902  0.438297
38       77      85  0.0  0.373938  0.441569
39       77      87  0.0  0.438380  0.503364
40       77      88  0.0  0.384152  0.475130
41       77      97  0.0  0.443793  0.517532
42       85      97  0.0  0.402665  0.463399
43       86      97  0.0  0.384971  0.446233
44       88      97  0.0  0.432701  0.472943
45       89      97  0.0  0.452550  0.494695
46       98     104  0.0  0.168177  0.254944
47       98     106  0.0  0.140735  0.218926
48       98     108  0.0  0.206598  0.298474
49      113     120  0.0  0.314966  0.402006
50      114     120  0.0  0.352676  0.433908
51      117     131  0.0  0.168166  0.211564
52      121     131  0.0  0.141708  0.169501
53      121     132  0.0  0.139717  0.165821
54      132     149  0.0  0.233802  0.266438
55      132     150  0.0  0.237353  0.273043
56      132     153  0.0  0.248378  0.308360
57      150     169  0.0  0.444379  0.524798
58      151     162  0.0  0.311726  0.429068
59      151     167  0.0  0.405558  0.474148
60      151     169  0.0  0.461316  0.523610
61      151     170  0.0  0.488147  0.558260
62      154     169  0.0  0.483451  0.499623
63      155     169  0.0  0.487028  0.486980
64      169     183  0.0  0.275488  0.347352
65      170     183  0.0  0.254951  0.315747
66      170     185  0.0  0.253713  0.332597
67      170     186  0.0  0.288587  0.357025
68      171     183  0.0  0.227104  0.291644
69      171     186  0.0  0.294224  0.366382
70      184     195  0.0  0.364250  0.417543
71      184     208  0.0  0.241067  0.295832
72      187     195  0.0  0.353873  0.357684
73      187     208  0.0  0.217111  0.249810
74      187     209  0.0  0.208684  0.242520
75      188     208  0.0  0.188048  0.218220
76      194     208  0.0  0.111068  0.144536
77      196     208  0.0  0.126156  0.170162
78      213     223  0.0  0.327099  0.389475
79      224     238  0.0  0.184719  0.194108
80      224     239  0.0  0.153845  0.162748
81      247     257  0.0  0.058057  0.070442
82      247     259  0.0  0.080272  0.114853
83      247     260  0.0  0.086146  0.139173
84      248     259  0.0  0.085093  0.129218
85      248     260  0.0  0.085446  0.142430
86      250     257  0.0  0.065256  0.079095
87      250     260  0.0  0.091618  0.154506
88      253     260  0.0  0.123225  0.211457
89      261     275  0.0  0.513374  0.482097
90      261     276  0.0  0.483490  0.455344
91      261     278  0.0  0.473550  0.466535
92      261     281  0.0  0.439776  0.467094
93      305     313  0.0  0.076182  0.113462
94      305     315  0.0  0.071047  0.108402
95      308     315  0.0  0.047073  0.048289
96      314     327  0.0  0.087681  0.111538
97      316     327  0.0  0.088448  0.117868
98      317     327  0.0  0.094098  0.124386
99      333     356  0.0  0.176701  0.211997
100     334     356  0.0  0.193607  0.227885
101     334     357  0.0  0.195659  0.222752
102     336     356  0.0  0.206997  0.229045
103     336     357  0.0  0.210657  0.237383
104     336     360  0.0  0.210770  0.234352
105     338     357  0.0  0.214084  0.237292
106     338     360  0.0  0.218291  0.245068
107     339     360  0.0  0.230610  0.261754
108     361     379  0.0  0.298696  0.356497

                                              Residues
0                                [1, 2, 3, 4, 5, 6, 7]
1     [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
2    [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1...
3    [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1...
4        [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
5    [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ...
6    [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ...
7           [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
8    [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...
9    [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...
10   [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...
11   [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...
12                    [11, 12, 13, 14, 15, 16, 17, 18]
13            [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
14        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
15   [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...
16   [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...
17                        [19, 20, 21, 22, 23, 24, 25]
18                        [26, 27, 28, 29, 30, 31, 32]
19                    [26, 27, 28, 29, 30, 31, 32, 33]
20                        [27, 28, 29, 30, 31, 32, 33]
21                    [33, 34, 35, 36, 37, 38, 39, 40]
22                        [34, 35, 36, 37, 38, 39, 40]
23                    [34, 35, 36, 37, 38, 39, 40, 41]
24                    [41, 42, 43, 44, 45, 46, 47, 48]
25                [41, 42, 43, 44, 45, 46, 47, 48, 49]
26        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
27                    [42, 43, 44, 45, 46, 47, 48, 49]
28            [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
29   [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 5...
30   [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6...
31   [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6...
32   [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 6...
33            [52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
34   [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 6...
35        [74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]
36                [76, 77, 78, 79, 80, 81, 82, 83, 84]
37                    [77, 78, 79, 80, 81, 82, 83, 84]
38                [77, 78, 79, 80, 81, 82, 83, 84, 85]
39        [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]
40    [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]
41   [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 8...
42   [85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 9...
43    [86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
44            [88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
45                [89, 90, 91, 92, 93, 94, 95, 96, 97]
46                   [98, 99, 100, 101, 102, 103, 104]
47         [98, 99, 100, 101, 102, 103, 104, 105, 106]
48   [98, 99, 100, 101, 102, 103, 104, 105, 106, 10...
49            [113, 114, 115, 116, 117, 118, 119, 120]
50                 [114, 115, 116, 117, 118, 119, 120]
51   [117, 118, 119, 120, 121, 122, 123, 124, 125, ...
52   [121, 122, 123, 124, 125, 126, 127, 128, 129, ...
53   [121, 122, 123, 124, 125, 126, 127, 128, 129, ...
54   [132, 133, 134, 135, 136, 137, 138, 139, 140, ...
55   [132, 133, 134, 135, 136, 137, 138, 139, 140, ...
56   [132, 133, 134, 135, 136, 137, 138, 139, 140, ...
57   [150, 151, 152, 153, 154, 155, 156, 157, 158, ...
58   [151, 152, 153, 154, 155, 156, 157, 158, 159, ...
59   [151, 152, 153, 154, 155, 156, 157, 158, 159, ...
60   [151, 152, 153, 154, 155, 156, 157, 158, 159, ...
61   [151, 152, 153, 154, 155, 156, 157, 158, 159, ...
62   [154, 155, 156, 157, 158, 159, 160, 161, 162, ...
63   [155, 156, 157, 158, 159, 160, 161, 162, 163, ...
64   [169, 170, 171, 172, 173, 174, 175, 176, 177, ...
65   [170, 171, 172, 173, 174, 175, 176, 177, 178, ...
66   [170, 171, 172, 173, 174, 175, 176, 177, 178, ...
67   [170, 171, 172, 173, 174, 175, 176, 177, 178, ...
68   [171, 172, 173, 174, 175, 176, 177, 178, 179, ...
69   [171, 172, 173, 174, 175, 176, 177, 178, 179, ...
70   [184, 185, 186, 187, 188, 189, 190, 191, 192, ...
71   [184, 185, 186, 187, 188, 189, 190, 191, 192, ...
72       [187, 188, 189, 190, 191, 192, 193, 194, 195]
73   [187, 188, 189, 190, 191, 192, 193, 194, 195, ...
74   [187, 188, 189, 190, 191, 192, 193, 194, 195, ...
75   [188, 189, 190, 191, 192, 193, 194, 195, 196, ...
76   [194, 195, 196, 197, 198, 199, 200, 201, 202, ...
77   [196, 197, 198, 199, 200, 201, 202, 203, 204, ...
78   [213, 214, 215, 216, 217, 218, 219, 220, 221, ...
79   [224, 225, 226, 227, 228, 229, 230, 231, 232, ...
80   [224, 225, 226, 227, 228, 229, 230, 231, 232, ...
81   [247, 248, 249, 250, 251, 252, 253, 254, 255, ...
82   [247, 248, 249, 250, 251, 252, 253, 254, 255, ...
83   [247, 248, 249, 250, 251, 252, 253, 254, 255, ...
84   [248, 249, 250, 251, 252, 253, 254, 255, 256, ...
85   [248, 249, 250, 251, 252, 253, 254, 255, 256, ...
86            [250, 251, 252, 253, 254, 255, 256, 257]
87   [250, 251, 252, 253, 254, 255, 256, 257, 258, ...
88            [253, 254, 255, 256, 257, 258, 259, 260]
89   [261, 262, 263, 264, 265, 266, 267, 268, 269, ...
90   [261, 262, 263, 264, 265, 266, 267, 268, 269, ...
91   [261, 262, 263, 264, 265, 266, 267, 268, 269, ...
92   [261, 262, 263, 264, 265, 266, 267, 268, 269, ...
93       [305, 306, 307, 308, 309, 310, 311, 312, 313]
94   [305, 306, 307, 308, 309, 310, 311, 312, 313, ...
95            [308, 309, 310, 311, 312, 313, 314, 315]
96   [314, 315, 316, 317, 318, 319, 320, 321, 322, ...
97   [316, 317, 318, 319, 320, 321, 322, 323, 324, ...
98   [317, 318, 319, 320, 321, 322, 323, 324, 325, ...
99   [333, 334, 335, 336, 337, 338, 339, 340, 341, ...
100  [334, 335, 336, 337, 338, 339, 340, 341, 342, ...
101  [334, 335, 336, 337, 338, 339, 340, 341, 342, ...
102  [336, 337, 338, 339, 340, 341, 342, 343, 344, ...
103  [336, 337, 338, 339, 340, 341, 342, 343, 344, ...
104  [336, 337, 338, 339, 340, 341, 342, 343, 344, ...
105  [338, 339, 340, 341, 342, 343, 344, 345, 346, ...
106  [338, 339, 340, 341, 342, 343, 344, 345, 346, ...
107  [339, 340, 341, 342, 343, 344, 345, 346, 347, ...
108  [361, 362, 363, 364, 365, 366, 367, 368, 369, ...
109

In [189]:
# conver to HDXer format ie start, end, exposure_1, exposure_2 

# change Start to ResStr and End to ResEnd
hdx = grouped.rename(columns={'Start': 'ResStr', 'End': 'ResEnd'})

# drop the exposure column
hdx.columns.name = None

hdx["Residues"] = hdx.apply(lambda x: list(range(int(x['ResStr']), int(x['ResEnd'])+1)), axis=1)

# print(hdx)

import MDAnalysis as mda

u = mda.Universe("6SC6.pdb")

chain_A = u.select_atoms("protein and segid A")

print(len(chain_A.residues.resids))
# select residues in Chain A that are in 4A of Chain B and C
import numpy as np
selection_string = "protein and (segid A and around 4 (segid B or segid C))"

interface = u.select_atoms(selection_string)
interface_resids = interface.residues.resids  

print(len(interface_resids))


first_resid = chain_A.residues[0].resid
print(first_resid)

original_resids = chain_A.residues.resids

non_interface_resids = np.setdiff1d(original_resids, interface_resids)
non_interface_resids = non_interface_resids - (first_resid - 1)
# print(non_interface_resids)
print(len(non_interface_resids))

interface_resids = interface_resids - (first_resid - 1)
# print(interface_resids)
print(len(interface_resids))
print(len(hdx))


clean_hdx = hdx.copy()
print(interface_resids)
print(len(hdx))
# interface_resids = [0]
# exclude residues in interface_resids
for idx, row in hdx.iterrows():
    row_resids = row['Residues']
    print(row_resids)
    # print(interface_resids)
    # if any residue in row_resids is in interface_resids, drop the row
    intersection = np.intersect1d(row_resids,interface_resids)
    print(intersection)

    if len(intersection) > 0:
        print("Dropping row")
        clean_hdx = clean_hdx.drop(idx)
        # print(clean_hdx)
    else:
        print("Keeping row")
        # print(clean_hdx)

# print(clean_hdx)
print(len(clean_hdx))


hdx = clean_hdx.copy()


# drop residues over 376
hdx = hdx[hdx['ResStr'] <= 376]
hdx = hdx[hdx['ResEnd'] <= 376]
print(len(clean_hdx))

print(len(hdx))

365
85
697
280
85
109
[ 70  71  74  75  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 121 122 123 124 125 126 128 129 130 131 132 133 134 135 145 149
 153 156 157 158 159 160 161 162 166 170 175 177 178 179 180 181 182 183
 184 194 195 196 197 198 199 278 283 284 285 286 287]
109
[1, 2, 3, 4, 5, 6, 7]
[]
Keeping row
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[]
Keeping row
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
[]
Keeping row
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[]
Keeping row
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[]
Keeping row
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
[]
Keeping row
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[]
Keeping row
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[]
Keeping row
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[]
Keeping row
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
[]
Keeping row
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[]
Keeping row
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[]
Keeping row
[11, 12, 13, 14, 15, 16, 17, 18]
[]
Keeping row
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[]
Keeping row
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
[]
Keeping row
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[]
Keeping row
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[]
Keeping row
[19, 20, 21, 22, 23, 24, 25]
[]
Keeping row
[26, 27, 28, 29, 30, 31, 32]
[]
Keeping row
[26, 27, 28, 29, 30, 31, 32, 33]
[]
Keeping row
[27, 28, 29, 30, 31, 32, 33]
[]
Keeping row
[33, 34, 35, 36, 37, 38, 39, 40]
[]
Keeping row
[34, 35, 36, 37, 38, 39, 40]
[]
Keeping row
[34, 35, 36, 37, 38, 39, 40, 41]
[]
Keeping row
[41, 42, 43, 44, 45, 46, 47, 48]
[]
Keeping row
[41, 42, 43, 44, 45, 46, 47, 48, 49]
[]
Keeping row
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
[]
Keeping row
[42, 43, 44, 45, 46, 47, 48, 49]
[]
Keeping row
[42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
[]
Keeping row
[42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
[]
Keeping row
[49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
[]
Keeping row
[49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
[]
Keeping row
[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
[]
Keeping row
[52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
[]
Keeping row
[52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
[]
Keeping row
[74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]
[74 75 78 79 80 81 82 83 84]
Dropping row
[76, 77, 78, 79, 80, 81, 82, 83, 84]
[78 79 80 81 82 83 84]
Dropping row
[77, 78, 79, 80, 81, 82, 83, 84]
[78 79 80 81 82 83 84]
Dropping row
[77, 78, 79, 80, 81, 82, 83, 84, 85]
[78 79 80 81 82 83 84 85]
Dropping row
[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]
[78 79 80 81 82 83 84 85 86 87]
Dropping row
[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]
[78 79 80 81 82 83 84 85 86 87 88]
Dropping row
[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
[78 79 80 81 82 83 84 85 86 87 88 89 90 91 94 95 96 97]
Dropping row
[85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
[85 86 87 88 89 90 91 94 95 96 97]
Dropping row
[86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
[86 87 88 89 90 91 94 95 96 97]
Dropping row
[88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
[88 89 90 91 94 95 96 97]
Dropping row
[89, 90, 91, 92, 93, 94, 95, 96, 97]
[89 90 91 94 95 96 97]
Dropping row
[98, 99, 100, 101, 102, 103, 104]
[ 98  99 100 101 102 103 104]
Dropping row
[98, 99, 100, 101, 102, 103, 104, 105, 106]
[ 98  99 100 101 102 103 104 105 106]
Dropping row
[98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108]
[ 98  99 100 101 102 103 104 105 106 107 108]
Dropping row
[113, 114, 115, 116, 117, 118, 119, 120]
[113]
Dropping row
[114, 115, 116, 117, 118, 119, 120]
[]
Keeping row
[117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]
[121 122 123 124 125 126 128 129 130 131]
Dropping row
[121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]
[121 122 123 124 125 126 128 129 130 131]
Dropping row
[121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]
[121 122 123 124 125 126 128 129 130 131 132]
Dropping row
[132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
[132 133 134 135 145 149]
Dropping row
[132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]
[132 133 134 135 145 149]
Dropping row
[132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153]
[132 133 134 135 145 149 153]
Dropping row
[150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169]
[153 156 157 158 159 160 161 162 166]
Dropping row
[151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162]
[153 156 157 158 159 160 161 162]
Dropping row
[151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167]
[153 156 157 158 159 160 161 162 166]
Dropping row
[151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169]
[153 156 157 158 159 160 161 162 166]
Dropping row
[151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170]
[153 156 157 158 159 160 161 162 166 170]
Dropping row
[154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169]
[156 157 158 159 160 161 162 166]
Dropping row
[155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169]
[156 157 158 159 160 161 162 166]
Dropping row
[169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
[170 175 177 178 179 180 181 182 183]
Dropping row
[170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
[170 175 177 178 179 180 181 182 183]
Dropping row
[170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185]
[170 175 177 178 179 180 181 182 183 184]
Dropping row
[170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186]
[170 175 177 178 179 180 181 182 183 184]
Dropping row
[171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
[175 177 178 179 180 181 182 183]
Dropping row
[171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186]
[175 177 178 179 180 181 182 183 184]
Dropping row
[184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195]
[184 194 195]
Dropping row
[184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208]
[184 194 195 196 197 198 199]
Dropping row
[187, 188, 189, 190, 191, 192, 193, 194, 195]
[194 195]
Dropping row
[187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208]
[194 195 196 197 198 199]
Dropping row
[187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209]
[194 195 196 197 198 199]
Dropping row
[188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208]
[194 195 196 197 198 199]
Dropping row
[194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208]
[194 195 196 197 198 199]
Dropping row
[196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208]
[196 197 198 199]
Dropping row
[213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223]
[]
Keeping row
[224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238]
[]
Keeping row
[224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239]
[]
Keeping row
[247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257]
[]
Keeping row
[247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259]
[]
Keeping row
[247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260]
[]
Keeping row
[248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259]
[]
Keeping row
[248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260]
[]
Keeping row
[250, 251, 252, 253, 254, 255, 256, 257]
[]
Keeping row
[250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260]
[]
Keeping row
[253, 254, 255, 256, 257, 258, 259, 260]
[]
Keeping row
[261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275]
[]
Keeping row
[261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276]
[]
Keeping row
[261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278]
[278]
Dropping row
[261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281]
[278]
Dropping row
[305, 306, 307, 308, 309, 310, 311, 312, 313]
[]
Keeping row
[305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315]
[]
Keeping row
[308, 309, 310, 311, 312, 313, 314, 315]
[]
Keeping row
[314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327]
[]
Keeping row
[316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327]
[]
Keeping row
[317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327]
[]
Keeping row
[333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356]
[]
Keeping row
[334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356]
[]
Keeping row
[334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357]
[]
Keeping row
[336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356]
[]
Keeping row
[336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357]
[]
Keeping row
[336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360]
[]
Keeping row
[338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357]
[]
Keeping row
[338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360]
[]
Keeping row
[339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360]
[]
Keeping row
[361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379]
[]
Keeping row
65
65
64

In [138]:

# clean_hdx = pd.DataFrame(columns=hdx.columns)
# print(interface_resids)
# print(len(hdx))
# # exclude residues in interface_resids
# for idx, row in hdx.iterrows():
#     row_resids = row['Residues']

#     # exclude any rows with residues in the interface
#     if not any(resid in interface_resids for resid in row_resids):
#         clean_hdx = pd.concat([clean_hdx, row], axis=1)

# # print(clean_hdx)
# print(len(clean_hdx))

[ 74  79  82  86  90  96  97  98  99 100 101 102 104 105 106 107 108 109
 123 124 126 131 132 133 134 156 158 159 178 179 180 196]
109
6

In [184]:

hdx = clean_hdx



# drop residues over 376
hdx = hdx[hdx['ResStr'] <= 376]
hdx = hdx[hdx['ResEnd'] <= 376]
print(len(hdx))




print(len(hdx))

69
69

In [25]:

hdx = hdx.round(5)
hdx.to_csv(os.path.join("raw_data", "HOIP", 'HOIP_dab27', 'HOIP_dab27.dat'), sep=' ', index=False)

In [26]:
segs = hdx[['ResStr', 'ResEnd']].drop_duplicates().sort_values(by=['ResStr', 'ResEnd']).reset_index(drop=True)

In [27]:

# convert to list of tuples
segs = [tuple(x) for x in segs.values]

print(segs)

[(1, 7), (6, 18), (6, 21), (6, 25), (7, 18), (7, 21), (7, 25), (8, 18), (8, 20), (8, 21), (8, 24), (8, 25), (11, 18), (11, 20), (11, 21), (11, 23), (11, 25), (19, 25), (26, 32), (26, 33), (27, 33), (33, 40), (34, 40), (34, 41), (41, 48), (41, 49), (41, 51), (42, 49), (42, 51), (42, 65), (49, 61), (49, 65), (50, 65), (52, 61), (52, 65), (74, 84), (76, 84), (77, 84), (77, 85), (77, 87), (77, 88), (77, 97), (85, 97), (86, 97), (88, 97), (89, 97), (98, 104), (98, 106), (98, 108), (113, 120), (114, 120), (117, 131), (121, 131), (121, 132), (132, 149), (132, 150), (132, 153), (150, 169), (151, 162), (151, 167), (151, 169), (151, 170), (154, 169), (155, 169), (169, 183), (170, 183), (170, 185), (170, 186), (171, 183), (171, 186), (184, 195), (184, 208), (187, 195), (187, 208), (187, 209), (188, 208), (194, 208), (196, 208), (213, 223), (224, 238), (224, 239), (247, 257), (247, 259), (247, 260), (248, 259), (248, 260), (250, 257), (250, 260), (253, 260), (261, 275), (261, 276), (261, 278), (261, 281), (305, 313), (305, 315), (308, 315), (314, 327), (316, 327), (317, 327), (333, 356), (334, 356), (334, 357), (336, 356), (336, 357), (336, 360), (338, 357), (338, 360), (339, 360), (361, 379)]

In [28]:


# write list as new lines with space delimiter
with open(os.path.join("raw_data", "HOIP", 'HOIP_dab27', 'HOIP_dab27.txt'), 'w') as f:
    for item in segs:
        f.write("%s\n" % ' '.join(map(str, item)))

In [22]:
# ### at the moment PDB fixer is adding different number of hydrogens to different structures... Need to change the code to use PROPKA to get H states and apply to all strucutres
# BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/"
# sim_dir = os.path.join(BPTI_dir, "alphafold_quick")

# pdb_list = [f for f in os.listdir(sim_dir) if f.endswith('.pdb')]

# print(pdb_list) 


# H_sim_dir = os.path.join(BPTI_dir, "alphafold_H")

# os.makedirs(H_sim_dir, exist_ok=True)

# for pdb in pdb_list:
#     continue
#     fixer = PDBFixer(os.path.join(sim_dir, pdb))
#     fixer.addMissingHydrogens(7.0)
#     H_pdb_name = pdb.replace('.pdb', '_H.pdb')
#     PDBFile.writeFile(fixer.topology, fixer.positions, open(os.path.join(H_sim_dir, H_pdb_name), 'w'), keepIds=True)

# pdb_list = [f for f in os.listdir(H_sim_dir) if f.endswith('.pdb')]



# top_path = os.path.join(H_sim_dir, pdb_list[0])
# pdb_paths = [os.path.join(H_sim_dir, i) for i in pdb_list]

# print(top_path)
# print(pdb_paths)


# small_traj_name = top_path.replace(".pdb","_small.xtc")
# small_traj_path = os.path.join(H_sim_dir, small_traj_name)

# u = mda.Universe(top_path)
    
# with XTCWriter(small_traj_path, n_atoms=u.atoms.n_atoms) as W:
#     for ts in u.trajectory:
#         W.write(u.atoms)
#         W.write(u.atoms)
#         break

Generate conformations with Alphafold

# need to find out how to generate a wide range of conformations

In [ ]:
def pre_process_main():
    # BPTI data
    # BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/"
    BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_dab27"
    # BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HDXer_tutorial/BPTI"

    sim_name = 'HOIP_apo_AF'
    os.listdir(BPTI_dir)

    segs_name = "HOIP_dab27.txt"
    segs_path = os.path.join(BPTI_dir, segs_name)

    hdx_name = "HOIP_dab27.dat"
    hdx_path = os.path.join(BPTI_dir, hdx_name)
    print(hdx_path)

    rates_name = "out__train_MD_Simulated_1Intrinsic_rates.dat"
    rates_path = os.path.join(BPTI_dir, rates_name)

    sim_dir = os.path.join(BPTI_dir, "alphafold_quick")

    pdb_list = [f for f in os.listdir(sim_dir) if f.endswith('.pdb')]

    print(pdb_list) 


    H_sim_dir = os.path.join(BPTI_dir, "alphafold_H")

    os.makedirs(H_sim_dir, exist_ok=True)

    for pdb in pdb_list:
        continue
        fixer = PDBFixer(os.path.join(H_sim_dir, pdb))
        fixer.addMissingHydrogens(7.0)
        H_pdb_name = pdb.replace('.pdb', '_H.pdb')
        PDBFile.writeFile(fixer.topology, fixer.positions, open(os.path.join(H_sim_dir, H_pdb_name), 'w'), keepIds=True)
        break
    pdb_list = [f for f in os.listdir(H_sim_dir) if f.endswith('.pdb')]


    top_path = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb"
    # pdb_paths = [os.path.join(H_sim_dir, i) for i in pdb_list]

    # print(top_path)
    # print(pdb_paths)


    # small_traj_name = top_path.replace(".pdb","_small.xtc")
    # small_traj_path = os.path.join(sim_dir, small_traj_name)

    # u = mda.Universe(top_path)
        
    # with XTCWriter(small_traj_path, n_atoms=u.atoms.n_atoms) as W:
    #     for ts in u.trajectory:
    #         W.write(u.atoms)
    #         W.write(u.atoms)
    #         break
    # # traj_paths = [os.path.join(sim_dir, i) for i in os.listdir(sim_dir) if i.endswith(".pdb")]
    
    traj_paths = ["/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.xtc"]

    print(traj_paths)
    return hdx_path, segs_path, rates_path, top_path, traj_paths, sim_name, expt_name, test_name

In [ ]:
hdx_path, segs_path, rates_path, top_path, traj_paths, sim_name, expt_name, test_name = pre_process_main()

In [ ]:
# # ic.disable()
# combined_analysis_dump, names, save_paths = VDX.run_benchmark_ensemble(system=test_name,
#                                                                     times=[0, 0.5, 5.0],
#                                                                     expt_name=expt_name,
#                                                                     n_reps=1,
#                                                                     optimise=False,
#                                                                     # split_modes=['r'],
#                                                                     hdx_path=hdx_path,
#                                                                     segs_path=segs_path,
#                                                                     traj_paths=traj_paths,
#                                                                     top_path=top_path)

In [ ]:
combined_analysis_dump, names, save_paths = VDX.run_refine_ensemble(system=test_name+"_modal1",
                                                                    times=[0, 0.5, 5.0],
                                                                    expt_name=expt_name,
                                                                    n_reps=1,
                                                                    split_mode='R3',
                                                                    hdx_path=hdx_path,
                                                                    segs_path=segs_path,
                                                                    traj_paths=traj_paths,
                                                                    top_path=top_path,
                                                                    modal_cluster=True)

In [ ]:

combined_analysis_dump, names, save_paths = VDX.run_refine_ensemble(system=test_name+"_mean1",
                                                                    times=[0, 0.5, 5.0],
                                                                    expt_name=expt_name,
                                                                    n_reps=1,
                                                                    split_mode='R3',
                                                                    hdx_path=hdx_path,
                                                                    segs_path=segs_path,
                                                                    traj_paths=traj_paths,
                                                                    top_path=top_path,
                                                                    modal_cluster=False)

In [ ]:
# # BPTI data
# BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HDXer_tutorial/BPTI"
# # BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HDXer_tutorial/BPTI"

In [ ]:
# expt_dir = os.path.join(BPTI_dir, "BPTI_expt_data")

# os.listdir(expt_dir)

# segs_name = "BPTI_residue_segs.txt"
# segs_path = os.path.join(expt_dir, segs_name)

# hdx_name = "BPTI_expt_dfracs.dat"
# hdx_path = os.path.join(expt_dir, hdx_name)
# print(hdx_path)

# rates_name = "BPTI_Intrinsic_rates.dat"
# rates_path = os.path.join(expt_dir, rates_name)

In [ ]:
# sim_name = 'BPTI_MD'

# sim_dir = os.path.join(BPTI_dir, "BPTI_simulations")

# os.listdir(sim_dir)

# md_reps = 1
# rep_dirs = ["Run_"+str(i+1) for i in range(md_reps)]

# top_name = "bpti_5pti_eq6_protonly.gro"

# top_path = os.path.join(sim_dir, rep_dirs[0], top_name)

# traj_name = "bpti_5pti_reimg_protonly.xtc"

# traj_paths = [os.path.join(sim_dir, rep_dir, traj_name) for rep_dir in rep_dirs]

# print(top_path)
# print(traj_paths)

In [ ]:
# def run_split_test(split_mode, name, system):

#     # settings.split_mode = 'R'
#     settings.split_mode = split_mode
#     settings.name = "_".join([name, split_mode])
#     settings.times = [0.0, 0.5, 5.0]
#     VDX = ValDXer(settings)

#     VDX.load_HDX_data(HDX_path=hdx_path, SEG_path=segs_path, calc_name=expt_name)
#     # VDX.load_intrinsic_rates(path=rates_path, calc_name=expt_name)

#     VDX.load_structures(top_path=top_path, traj_paths=traj_paths, calc_name=test_name)

#     run_outputs = VDX.run_VDX(calc_name=test_name, expt_name=expt_name)
#     analysis_dump, df, name = VDX.dump_analysis()
#     save_path = VDX.save_experiment()

#     return run_outputs, analysis_dump, df, name, save_path

In [ ]:

# splits = ['r', 'SR', 'R3']
# split_names = ['AvsB', 'LvsX', 'mixAandB']
# system = 'BPTITtut_test'

# raw_run_outputs = {}
# analysis_dumps = {}
# analysis_df = pd.DataFrame()
# names = []
# save_paths = []


# for split, split_name in zip(splits, split_names):
#     run_outputs, analysis_dump, df, name, save_path = run_split_test(split, split_name, system)
#     raw_run_outputs[name] = run_outputs
#     analysis_dumps.update(analysis_dump)
#     analysis_df = pd.concat([analysis_df, df])
#     names.append(name)
#     save_paths.append(save_path)

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named df
# Replace 'your_dataframe' with your actual DataFrame variable
df = analysis_df

# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('MSE over Time by Type for each Named Split Mode')

# Create boxplots
g = g.map(sns.boxplot, "time", "mse", "Type", palette="Set3")

# Adding some additional options for better visualization
g.add_legend(title='Type')
g.set_axis_labels("Time", "MSE")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named df
# Replace 'your_dataframe' with your actual DataFrame variable
df = analysis_df

# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('R over Time by Type for each Named Split Mode')

# Create boxplots
g = g.map(sns.boxplot, "time", "R", "Type", palette="Set3")

# Adding some additional options for better visualization
g.add_legend(title='Type')
g.set_axis_labels("Time", "R")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

In [ ]:
# plot LogPfs by Residues colour by calc_name facet wrap by name
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
LogPfs = pd.concat([analysis_dumps[i]["LogPfs"] for i in names])

print(LogPfs)

LogPfs_df = LogPfs.explode(['LogPf','Residues'])


# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(LogPfs_df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('LogPfs over Residues for each Named Split Mode')

# Create lineplots
g = g.map(sns.lineplot, "Residues", "LogPf", "calc_name", palette="Set2")

# Adding some additional options for better visualization
g.add_legend(title='calc_name')
g.set_axis_labels("Residues", "LogPf")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

In [ ]:
# from MDAnalysis.analysis.dssp import DSSP

In [ ]:
# VDX.paths.head()

In [ ]:
# print(top_path)

In [ ]:
# pdb_test = mda.Universe(top_path)

# # write out as a pdb and add header
# pdb_test.atoms.write('test.pdb')
# with open('test.pdb', 'r') as original: data = original.read()
# with open('test.pdb', 'w') as modified: modified.write('HEADER    '+sim_name+'\n'+data)

In [ ]:


# def PDB_to_DSSP(top_path: str, dssp_path: str=None, sim_name: str=None):
#     """
#     Run DSSP on a PDB file to generate a DSSP file. Reads the output and returns a list of secondary structure elements.
#     Secondary structure elements are reduced to a single character: H (alpha helix), S (beta sheet), or L (loop).
#     Args:
#     - top_path (str): The path to the topology file to create the PDB file from.
#     - dssp_path (str): The path to save the DSSP file.
#     - sim_name (str): Simulation name to be included in the HEADER of the PDB file.
#     Returns:
#     - List of tuples, each containing the residue number and its secondary structure element.
#     """
#     temp_pdb = "do_mkdssp.pdb"

#     if sim_name is None:
#         sim_name = "DSSP HEADER"
#     if dssp_path is None:
#         dssp_path = "dssp_file.dssp"
#     print(top_path)
#     pdb_test = mda.Universe(top_path)

#     # write out as a pdb and add header
#     pdb_test.atoms.write(temp_pdb)


#     with open(temp_pdb, 'r') as original: data = original.read()
#     with open(temp_pdb, 'w') as modified: modified.write('HEADER    '+sim_name+'\n'+data)

#     # Run mkdssp to generate DSSP file
#     try:
#         subprocess.run(['mkdssp', temp_pdb,  dssp_path], check=True)
#     except subprocess.CalledProcessError as e:
#         print(f"Error running DSSP: {e}")
#         return []

#     # Parse the DSSP file
#     secondary_structures = []
#     with open(dssp_path, 'r') as dssp_file:
#         # Skip header lines
#         for line in dssp_file:
#             if line.startswith('  #  RESIDUE AA'):
#                 break
#         # Read the secondary structure assignments
#         for line in dssp_file:
#             if len(line) > 13:  # Ensure line has enough data
#                 residue_num = line[5:10].strip()
#                 ss = line[16]
#                 # Simplify the secondary structure to H, S, or L
#                 if ss in 'GHI':
#                     ss = 'H'  # Helix
#                 elif ss in 'EB':
#                     ss = 'S'  # Sheet
#                 else:
#                     ss = 'L'  # Loop or other
#                 secondary_structures.append((residue_num, ss))

#     # Cleanup temp PDB file
#     os.remove(temp_pdb)
#     os.remove(dssp_path)
#     print(len(secondary_structures))
#     print(len(pdb_test.residues))
#     return secondary_structures