In [1]:
### ValDXer testing
import os
os.environ["HDXER_PATH"] = "/home/alexi/Documents/HDXer"

from ValDX.ValidationDX import ValDXer
from ValDX.VDX_Settings import Settings
import pandas as pd
import MDAnalysis as mda
from MDAnalysis.coordinates.XTC import XTCWriter

from pdbfixer import PDBFixer
from openmm.app import PDBFile

settings = Settings(name='testHOIP')
settings.replicates = 1
settings.gamma_range = (2,6)
settings.train_frac = 0.5
settings.RW_exponent = [0]
settings.split_mode = 'R3'
settings.stride = 1000
# settings.HDXer_stride = 10000

settings.RW_do_reweighting = True
settings.RW_do_params = False
import pickle

VDX = ValDXer(settings)
expt_name = 'Experimental'
test_name = "HOIPapo_test"
from icecream import ic
ic.disable()

/home/alexi/Documents/ValDX

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name testHOIP already exists. Attempting to change name to testHOIP0
Experiment name testHOIP already exists. Attempting to change name to testHOIP1
Experiment name testHOIP already exists. Attempting to change name to testHOIP2

In [2]:
# ### add code to read in sequence from CIF file instead of copying it manually

# cif_file = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/AF-Q96EP0-F1-model_v4.cif"

# sequence_header = "_entity_poly.pdbx_seq_one_letter_code"
# sequence = ""
# seq_head_idx = 0
# with open(cif_file, 'r') as f:
#     lines = f.readlines()
#     for idx, line in enumerate(lines):
#         if sequence_header in line:
#             seq_head_idx = idx+1
#             break
    
#     for idx, line in enumerate(lines[seq_head_idx:]):
#         if idx > 0 and line[0] == ";":
#             break
#         sequence += line.strip()


# # print(sequence)



# # strip sequence of non letters
# sequence = ''.join([i for i in sequence if i.isalpha()])

# print(sequence)

# print("Sequence length: ", len(sequence))


# # convert sequence to FASTA format
# def write_fasta(sequence, header, file_name):
#     """
#     Writes a single-letter amino acid sequence to a FASTA file.
    
#     Parameters:
#     - sequence: A string containing the amino acid sequence.
#     - header: A string to be used as the header in the FASTA file.
#     - file_name: The name of the FASTA file to be created.
#     """
#     print(f"Writing sequence to {file_name}")
#     with open(file_name, 'w') as fasta_file:
#         # Write the header with the '>' symbol
#         fasta_file.write(f">{header}\n")
        
#         # Write the sequence in lines of 80 characters
#         for i in range(0, len(sequence), 80):
#             fasta_file.write(sequence[i:i+80] + "\n")

In [3]:

# fasta_path = os.path.join("raw_data", "HOIP", 'HOIP_apo.fasta')
# write_fasta(sequence, 'HOIPapo', fasta_path)

In [4]:
raw_hdx_path = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo_peptide.csv"
raw_hdx = pd.read_csv(raw_hdx_path)
raw_hdx.tail()

,Unnamed: 0,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD
322,3536,RYLHVRPQPLAGEDPPAYQARL,17,4.065133,339,360,5.980509,0.004256
323,3537,RYLHVRPQPLAGEDPPAYQARL,17,4.601580,339,360,5.977207,0.004590
324,3568,LQKLTEEVPLGQSIPRRRK,16,0.000000,361,379,5.086766,0.002262
325,3569,LQKLTEEVPLGQSIPRRRK,16,4.921218,361,379,5.077346,0.001499
326,3570,LQKLTEEVPLGQSIPRRRK,16,5.863643,361,379,5.071376,0.005158

In [5]:
# drop Unnamed: 0	

raw_hdx = raw_hdx.drop(columns=['Unnamed: 0'])
raw_hdx.head()

        Sequence  MaxUptake    Uptake  Start  End        RT     RT.SD
0        GPGQECA          5  0.000000      1    7  3.019829  0.005348
1        GPGQECA          5  2.093943      1    7  3.014965  0.007647
2        GPGQECA          5  2.221890      1    7  3.013609  0.001502
3  CAVCGWALPHNRM         11  0.000000      6   18  7.366025  0.000841
4  CAVCGWALPHNRM         11  4.080613      6   18  7.359962  0.004124

In [6]:
# assign peptide number for each start and end residue using ngroup
raw_hdx['peptide'] = raw_hdx.groupby(['Start','End']).ngroup()

raw_hdx.head()

        Sequence  MaxUptake    Uptake  Start  End        RT     RT.SD  peptide
0        GPGQECA          5  0.000000      1    7  3.019829  0.005348        0
1        GPGQECA          5  2.093943      1    7  3.014965  0.007647        0
2        GPGQECA          5  2.221890      1    7  3.013609  0.001502        0
3  CAVCGWALPHNRM         11  0.000000      6   18  7.366025  0.000841        1
4  CAVCGWALPHNRM         11  4.080613      6   18  7.359962  0.004124        1

In [7]:

times = [0, 0.5, 5.0]

num_peptides = len(raw_hdx)//len(times)

exposure = times * num_peptides

raw_hdx['Exposure'] = exposure

raw_hdx.head()

,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD,peptide,Exposure
0,GPGQECA,5,0.000000,1,7,3.019829,0.005348,0,0.0
1,GPGQECA,5,2.093943,1,7,3.014965,0.007647,0,0.5
2,GPGQECA,5,2.221890,1,7,3.013609,0.001502,0,5.0
3,CAVCGWALPHNRM,11,0.000000,6,18,7.366025,0.000841,1,0.0
4,CAVCGWALPHNRM,11,4.080613,6,18,7.359962,0.004124,1,0.5

In [8]:
raw_hdx['UptakeFraction'] = raw_hdx['Uptake'] / raw_hdx['MaxUptake']

raw_hdx.head()

,Sequence,MaxUptake,Uptake,Start,End,RT,RT.SD,peptide,Exposure,UptakeFraction
0,GPGQECA,5,0.000000,1,7,3.019829,0.005348,0,0.0,0.000000
1,GPGQECA,5,2.093943,1,7,3.014965,0.007647,0,0.5,0.418789
2,GPGQECA,5,2.221890,1,7,3.013609,0.001502,0,5.0,0.444378
3,CAVCGWALPHNRM,11,0.000000,6,18,7.366025,0.000841,1,0.0,0.000000
4,CAVCGWALPHNRM,11,4.080613,6,18,7.359962,0.004124,1,0.5,0.370965

In [9]:
# clamp UptakeFraction to 1
raw_hdx['UptakeFraction'] = raw_hdx['UptakeFraction'].clip(upper=1)

In [10]:
# # print entire dataframe
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# print(raw_hdx)

In [11]:

# pivot exposure and uptake fraction
grouped = raw_hdx.pivot(index=['Start', 'End'], columns='Exposure', values='UptakeFraction').reset_index()

# drop 
grouped.head()

Exposure  Start  End  0.0       0.5       5.0
0             1    7  0.0  0.418789  0.444378
1             6   18  0.0  0.370965  0.452036
2             6   21  0.0  0.400400  0.485438
3             6   25  0.0  0.458750  0.515029
4             7   18  0.0  0.417256  0.495187

In [12]:

# print entire dataframe
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
print(grouped)

Exposure  Start  End  0.0       0.5       5.0
0             1    7  0.0  0.418789  0.444378
1             6   18  0.0  0.370965  0.452036
2             6   21  0.0  0.400400  0.485438
3             6   25  0.0  0.458750  0.515029
4             7   18  0.0  0.417256  0.495187
5             7   21  0.0  0.441761  0.509265
6             7   25  0.0  0.489870  0.540901
7             8   18  0.0  0.413157  0.482536
8             8   20  0.0  0.466166  0.510658
9             8   21  0.0  0.468247  0.520281
10            8   24  0.0  0.482729  0.531020
11            8   25  0.0  0.502576  0.539876
12           11   18  0.0  0.473734  0.501436
13           11   20  0.0  0.520572  0.541015
14           11   21  0.0  0.528228  0.556396
15           11   23  0.0  0.558020  0.575043
16           11   25  0.0  0.556407  0.571956
17           19   25  0.0  0.529281  0.548268
18           26   32  0.0  0.171628  0.278834
19           26   33  0.0  0.168832  0.286864
20           27   33  0.0  0.163408  0.273532
21           33   40  0.0  0.323093  0.412053
22           34   40  0.0  0.313553  0.399277
23           34   41  0.0  0.343919  0.422128
24           41   48  0.0  0.356035  0.356171
25           41   49  0.0  0.341051  0.351251
26           41   51  0.0  0.341353  0.388297
27           42   49  0.0  0.285116  0.296015
28           42   51  0.0  0.284389  0.331853
29           42   65  0.0  0.329544  0.390846
30           49   61  0.0  0.261915  0.346194
31           49   65  0.0  0.314207  0.378566
32           50   65  0.0  0.323136  0.385646
33           52   61  0.0  0.296657  0.378600
34           52   65  0.0  0.384396  0.447747
35           74   84  0.0  0.336329  0.463902
36           76   84  0.0  0.347162  0.458072
37           77   84  0.0  0.341649  0.443931
38           77   85  0.0  0.307247  0.435329
39           77   87  0.0  0.332518  0.489762
40           77   88  0.0  0.283693  0.429396
41           77   97  0.0  0.359056  0.502931
42           85   97  0.0  0.335752  0.451806
43           86   97  0.0  0.334431  0.436971
44           88   97  0.0  0.370824  0.472841
45           89   97  0.0  0.378474  0.488485
46           98  104  0.0  0.222184  0.310405
47           98  106  0.0  0.182171  0.283053
48           98  108  0.0  0.257190  0.370447
49          113  120  0.0  0.497561  0.508502
50          114  120  0.0  0.550238  0.543261
51          117  131  0.0  0.243104  0.292075
52          121  131  0.0  0.191728  0.239718
53          121  132  0.0  0.181047  0.230026
54          132  149  0.0  0.261401  0.302674
55          132  150  0.0  0.263925  0.306145
56          132  153  0.0  0.260611  0.328013
57          150  169  0.0  0.452972  0.539737
58          151  162  0.0  0.316216  0.453716
59          151  167  0.0  0.437109  0.529718
60          151  169  0.0  0.476280  0.547347
61          151  170  0.0  0.492489  0.571558
62          154  169  0.0  0.503408  0.532115
63          155  169  0.0  0.534998  0.538272
64          169  183  0.0  0.265241  0.353651
65          170  183  0.0  0.254539  0.325484
66          170  185  0.0  0.251521  0.357862
67          170  186  0.0  0.281644  0.365678
68          171  183  0.0  0.241772  0.301741
69          171  186  0.0  0.279695  0.365668
70          184  195  0.0  0.386327  0.448694
71          184  208  0.0  0.248715  0.312260
72          187  195  0.0  0.368200  0.378787
73          187  208  0.0  0.229030  0.268394
74          187  209  0.0  0.216867  0.259893
75          188  208  0.0  0.204792  0.235932
76          194  208  0.0  0.116843  0.151402
77          196  208  0.0  0.132671  0.181433
78          213  223  0.0  0.352027  0.426008
79          224  238  0.0  0.202486  0.214720
80          224  239  0.0  0.162602  0.174958
81          247  257  0.0  0.056878  0.072735
82          247  259  0.0  0.076002  0.114639
83          247  260  0.0  0.081465  0.135265
84          248  259  0.0  0.085270  0.132417
85          248  260  0.0  0.085689  0.143041
86          250  257  0.0  0.062907  0.078848
87          250  260  0.0  0.093933  0.162009
88          253  260  0.0  0.103850  0.196509
89          261  275  0.0  0.538767  0.499429
90          261  276  0.0  0.514169  0.478663
91          261  278  0.0  0.501067  0.490718
92          261  281  0.0  0.455513  0.472798
93          305  313  0.0  0.065001  0.106675
94          305  315  0.0  0.063618  0.105932
95          308  315  0.0  0.043579  0.043707
96          314  327  0.0  0.081513  0.106743
97          316  327  0.0  0.087946  0.115367
98          317  327  0.0  0.092608  0.122967
99          333  356  0.0  0.172982  0.202249
100         334  356  0.0  0.207287  0.230299
101         334  357  0.0  0.204014  0.234535
102         336  356  0.0  0.219425  0.234262
103         336  357  0.0  0.217314  0.244420
104         336  360  0.0  0.220285  0.251994
105         338  357  0.0  0.222167  0.241745
106         338  360  0.0  0.224541  0.249659
107         339  360  0.0  0.239125  0.270681
108         361  379  0.0  0.307576  0.366478

In [13]:
# conver to HDXer format ie start, end, exposure_1, exposure_2 

# change Start to ResStr and End to ResEnd
hdx = grouped.rename(columns={'Start': 'ResStr', 'End': 'ResEnd'})

# drop the exposure column
hdx.columns.name = None

print(hdx)

     ResStr  ResEnd  0.0       0.5       5.0
0         1       7  0.0  0.418789  0.444378
1         6      18  0.0  0.370965  0.452036
2         6      21  0.0  0.400400  0.485438
3         6      25  0.0  0.458750  0.515029
4         7      18  0.0  0.417256  0.495187
5         7      21  0.0  0.441761  0.509265
6         7      25  0.0  0.489870  0.540901
7         8      18  0.0  0.413157  0.482536
8         8      20  0.0  0.466166  0.510658
9         8      21  0.0  0.468247  0.520281
10        8      24  0.0  0.482729  0.531020
11        8      25  0.0  0.502576  0.539876
12       11      18  0.0  0.473734  0.501436
13       11      20  0.0  0.520572  0.541015
14       11      21  0.0  0.528228  0.556396
15       11      23  0.0  0.558020  0.575043
16       11      25  0.0  0.556407  0.571956
17       19      25  0.0  0.529281  0.548268
18       26      32  0.0  0.171628  0.278834
19       26      33  0.0  0.168832  0.286864
20       27      33  0.0  0.163408  0.273532
21       33      40  0.0  0.323093  0.412053
22       34      40  0.0  0.313553  0.399277
23       34      41  0.0  0.343919  0.422128
24       41      48  0.0  0.356035  0.356171
25       41      49  0.0  0.341051  0.351251
26       41      51  0.0  0.341353  0.388297
27       42      49  0.0  0.285116  0.296015
28       42      51  0.0  0.284389  0.331853
29       42      65  0.0  0.329544  0.390846
30       49      61  0.0  0.261915  0.346194
31       49      65  0.0  0.314207  0.378566
32       50      65  0.0  0.323136  0.385646
33       52      61  0.0  0.296657  0.378600
34       52      65  0.0  0.384396  0.447747
35       74      84  0.0  0.336329  0.463902
36       76      84  0.0  0.347162  0.458072
37       77      84  0.0  0.341649  0.443931
38       77      85  0.0  0.307247  0.435329
39       77      87  0.0  0.332518  0.489762
40       77      88  0.0  0.283693  0.429396
41       77      97  0.0  0.359056  0.502931
42       85      97  0.0  0.335752  0.451806
43       86      97  0.0  0.334431  0.436971
44       88      97  0.0  0.370824  0.472841
45       89      97  0.0  0.378474  0.488485
46       98     104  0.0  0.222184  0.310405
47       98     106  0.0  0.182171  0.283053
48       98     108  0.0  0.257190  0.370447
49      113     120  0.0  0.497561  0.508502
50      114     120  0.0  0.550238  0.543261
51      117     131  0.0  0.243104  0.292075
52      121     131  0.0  0.191728  0.239718
53      121     132  0.0  0.181047  0.230026
54      132     149  0.0  0.261401  0.302674
55      132     150  0.0  0.263925  0.306145
56      132     153  0.0  0.260611  0.328013
57      150     169  0.0  0.452972  0.539737
58      151     162  0.0  0.316216  0.453716
59      151     167  0.0  0.437109  0.529718
60      151     169  0.0  0.476280  0.547347
61      151     170  0.0  0.492489  0.571558
62      154     169  0.0  0.503408  0.532115
63      155     169  0.0  0.534998  0.538272
64      169     183  0.0  0.265241  0.353651
65      170     183  0.0  0.254539  0.325484
66      170     185  0.0  0.251521  0.357862
67      170     186  0.0  0.281644  0.365678
68      171     183  0.0  0.241772  0.301741
69      171     186  0.0  0.279695  0.365668
70      184     195  0.0  0.386327  0.448694
71      184     208  0.0  0.248715  0.312260
72      187     195  0.0  0.368200  0.378787
73      187     208  0.0  0.229030  0.268394
74      187     209  0.0  0.216867  0.259893
75      188     208  0.0  0.204792  0.235932
76      194     208  0.0  0.116843  0.151402
77      196     208  0.0  0.132671  0.181433
78      213     223  0.0  0.352027  0.426008
79      224     238  0.0  0.202486  0.214720
80      224     239  0.0  0.162602  0.174958
81      247     257  0.0  0.056878  0.072735
82      247     259  0.0  0.076002  0.114639
83      247     260  0.0  0.081465  0.135265
84      248     259  0.0  0.085270  0.132417
85      248     260  0.0  0.085689  0.143041
86      250     257  0.0  0.062907  0.078848
87      250     260  0.0  0.093933  0.162009
88      253     260  0.0  0.103850  0.196509
89      261     275  0.0  0.538767  0.499429
90      261     276  0.0  0.514169  0.478663
91      261     278  0.0  0.501067  0.490718
92      261     281  0.0  0.455513  0.472798
93      305     313  0.0  0.065001  0.106675
94      305     315  0.0  0.063618  0.105932
95      308     315  0.0  0.043579  0.043707
96      314     327  0.0  0.081513  0.106743
97      316     327  0.0  0.087946  0.115367
98      317     327  0.0  0.092608  0.122967
99      333     356  0.0  0.172982  0.202249
100     334     356  0.0  0.207287  0.230299
101     334     357  0.0  0.204014  0.234535
102     336     356  0.0  0.219425  0.234262
103     336     357  0.0  0.217314  0.244420
104     336     360  0.0  0.220285  0.251994
105     338     357  0.0  0.222167  0.241745
106     338     360  0.0  0.224541  0.249659
107     339     360  0.0  0.239125  0.270681
108     361     379  0.0  0.307576  0.366478

In [14]:

hdx = hdx.round(5)
hdx.to_csv(os.path.join("raw_data", "HOIP", 'HOIP_apo.dat'), sep=' ', index=False)

In [15]:
segs = hdx[['ResStr', 'ResEnd']].drop_duplicates().sort_values(by=['ResStr', 'ResEnd']).reset_index(drop=True)

In [16]:

# # convert to list of tuples
# segs = [tuple(x) for x in segs.values]

# print(segs)

In [17]:


# # write list as new lines with space delimiter
# with open(os.path.join("raw_data", "HOIP", 'HOIP_APO_segs.txt'), 'w') as f:
#     for item in segs:
#         f.write("%s\n" % ' '.join(map(str, item)))

In [18]:
# ### at the moment PDB fixer is adding different number of hydrogens to different structures... Need to change the code to use PROPKA to get H states and apply to all strucutres
# BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/"
# sim_dir = os.path.join(BPTI_dir, "alphafold_quick")

# pdb_list = [f for f in os.listdir(sim_dir) if f.endswith('.pdb')]

# print(pdb_list) 


# H_sim_dir = os.path.join(BPTI_dir, "alphafold_H")

# os.makedirs(H_sim_dir, exist_ok=True)

# for pdb in pdb_list:
#     continue
#     fixer = PDBFixer(os.path.join(sim_dir, pdb))
#     fixer.addMissingHydrogens(7.0)
#     H_pdb_name = pdb.replace('.pdb', '_H.pdb')
#     PDBFile.writeFile(fixer.topology, fixer.positions, open(os.path.join(H_sim_dir, H_pdb_name), 'w'), keepIds=True)

# pdb_list = [f for f in os.listdir(H_sim_dir) if f.endswith('.pdb')]



# top_path = os.path.join(H_sim_dir, pdb_list[0])
# pdb_paths = [os.path.join(H_sim_dir, i) for i in pdb_list]

# print(top_path)
# print(pdb_paths)


# small_traj_name = top_path.replace(".pdb","_small.xtc")
# small_traj_path = os.path.join(H_sim_dir, small_traj_name)

# u = mda.Universe(top_path)
    
# with XTCWriter(small_traj_path, n_atoms=u.atoms.n_atoms) as W:
#     for ts in u.trajectory:
#         W.write(u.atoms)
#         W.write(u.atoms)
#         break

Generate conformations with Alphafold

# need to find out how to generate a wide range of conformations

In [19]:
def pre_process_main():
    # BPTI data
    # BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HOIP/HOIP_apo/"
    BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo"
    # BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HDXer_tutorial/BPTI"

    sim_name = 'HOIP_apo_AF'
    os.listdir(BPTI_dir)

    segs_name = "HOIP_APO_segs.txt"
    segs_path = os.path.join(BPTI_dir, segs_name)

    hdx_name = "HOIP_apo.dat"
    hdx_path = os.path.join(BPTI_dir, hdx_name)
    print(hdx_path)

    rates_name = "out__train_MD_Simulated_1Intrinsic_rates.dat"
    rates_path = os.path.join(BPTI_dir, rates_name)

    sim_dir = os.path.join(BPTI_dir, "alphafold_quick")

    pdb_list = [f for f in os.listdir(sim_dir) if f.endswith('.pdb')]

    print(pdb_list) 


    H_sim_dir = os.path.join(BPTI_dir, "alphafold_H")

    os.makedirs(H_sim_dir, exist_ok=True)

    for pdb in pdb_list:
        continue
        fixer = PDBFixer(os.path.join(H_sim_dir, pdb))
        fixer.addMissingHydrogens(7.0)
        H_pdb_name = pdb.replace('.pdb', '_H.pdb')
        PDBFile.writeFile(fixer.topology, fixer.positions, open(os.path.join(H_sim_dir, H_pdb_name), 'w'), keepIds=True)
        break
    pdb_list = [f for f in os.listdir(H_sim_dir) if f.endswith('.pdb')]


    top_path = "/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb"
    # pdb_paths = [os.path.join(H_sim_dir, i) for i in pdb_list]

    # print(top_path)
    # print(pdb_paths)


    # small_traj_name = top_path.replace(".pdb","_small.xtc")
    # small_traj_path = os.path.join(sim_dir, small_traj_name)

    # u = mda.Universe(top_path)
        
    # with XTCWriter(small_traj_path, n_atoms=u.atoms.n_atoms) as W:
    #     for ts in u.trajectory:
    #         W.write(u.atoms)
    #         W.write(u.atoms)
    #         break
    # # traj_paths = [os.path.join(sim_dir, i) for i in os.listdir(sim_dir) if i.endswith(".pdb")]
    
    traj_paths = ["/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.xtc"]

    print(traj_paths)
    return hdx_path, segs_path, rates_path, top_path, traj_paths, sim_name, expt_name, test_name

In [20]:
hdx_path, segs_path, rates_path, top_path, traj_paths, sim_name, expt_name, test_name = pre_process_main()

/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
['HOIPapo_unrelaxed_rank_001_alphafold2_ptm_model_1_seed_000.pdb', 'HOIPapo_unrelaxed_rank_002_alphafold2_ptm_model_3_seed_000.pdb', 'HOIPapo_unrelaxed_rank_005_alphafold2_ptm_model_2_seed_000.pdb', 'HOIPapo_unrelaxed_rank_003_alphafold2_ptm_model_4_seed_000.pdb', 'HOIPapo_unrelaxed_rank_004_alphafold2_ptm_model_5_seed_000.pdb']
['/home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.xtc']

In [21]:
# # ic.disable()
# combined_analysis_dump, names, save_paths = VDX.run_benchmark_ensemble(system=test_name,
#                                                                     times=[0, 0.5, 5.0],
#                                                                     expt_name=expt_name,
#                                                                     n_reps=1,
#                                                                     optimise=False,
#                                                                     # split_modes=['r'],
#                                                                     hdx_path=hdx_path,
#                                                                     segs_path=segs_path,
#                                                                     traj_paths=traj_paths,
#                                                                     top_path=top_path)

In [22]:
# combined_analysis_dump, names, save_paths = VDX.run_refine_ensemble(system=test_name+"_modal1",
#                                                                     times=[0, 0.5, 5.0],
#                                                                     expt_name=expt_name,
#                                                                     n_reps=1,
#                                                                     split_mode='R3',
#                                                                     hdx_path=hdx_path,
#                                                                     segs_path=segs_path,
#                                                                     traj_paths=traj_paths,
#                                                                     top_path=top_path,
#                                                                     modal_cluster=True)

In [23]:
import cProfile
import pstats
import io

pr = cProfile.Profile()
pr.enable()
settings.cluster_frac1 = 0.5

combined_analysis_dump, names, save_paths = VDX.run_refine_ensemble(system=test_name+"_mean1",
                                                                    times=[0, 0.5, 5.0],
                                                                    expt_name=expt_name,
                                                                    n_reps=2,
                                                                    split_mode='R3',
                                                                    hdx_path=hdx_path,
                                                                    segs_path=segs_path,
                                                                    traj_paths=traj_paths,
                                                                    top_path=top_path,
                                                                    modal_cluster=False)




pr.disable()

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py

Experiment name HOIPapo_test_mean1 already exists. Attempting to change name to HOIPapo_test_mean10
Experiment name HOIPapo_test_mean1 already exists. Attempting to change name to HOIPapo_test_mean11
Experiment name HOIPapo_test_mean1 already exists. Attempting to change name to HOIPapo_test_mean12
Coords shape
(1100, 1128)
Performing PCA
Transformed data
(1100, 2)
Fitting KMeans

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

Getting cluster centers
(550, 2)
Getting cluster labels
(1100,)
Unique labels
(550,)
Cluster frames
[187, 424, 788, 763, 1080, 802, 148, 201, 234, 327, 27, 1066, 786, 196, 708, 643, 203, 396, 74, 876, 629, 800, 562, 546, 720, 1045, 383, 113, 887, 438, 908, 227, 439, 652, 152, 1067, 678, 367, 184, 582, 632, 316, 749, 735, 1034, 731, 376, 912, 795, 960, 598, 244, 1064, 1088, 977, 581, 175, 265, 72, 926, 494, 1058, 335, 516, 322, 706, 366, 96, 162, 486, 568, 650, 375, 906, 679, 261, 378, 480, 142, 565, 713, 271, 566, 475, 199, 826, 211, 29, 84, 515, 225, 1017, 726, 423, 88, 287, 1099, 319, 976, 1077, 698, 542, 792, 336, 980, 564, 659, 685, 71, 640, 1000, 709, 0, 251, 303, 6, 992, 663, 772, 673, 108, 925, 374, 1082, 973, 145, 1019, 18, 526, 764, 382, 860, 118, 325, 498, 982, 160, 657, 879, 216, 557, 351, 461, 301, 22, 645, 621, 57, 613, 835, 618, 676, 359, 92, 492, 939, 141, 94, 208, 440, 937, 324, 279, 1070, 456, 791, 149, 774, 1008, 462, 64, 1010, 99, 651, 737, 330, 264, 730, 210, 820, 104, 884, 1051, 1098, 272, 1095, 425, 474, 28, 647, 539, 281, 385, 93, 1012, 144, 573, 875, 1035, 748, 519, 675, 903, 171, 30, 363, 639, 1011, 129, 387, 169, 923, 861, 534, 215, 1085, 834, 429, 945, 16, 869, 1023, 115, 797, 863, 23, 406, 174, 789, 62, 550, 48, 40, 120, 488, 514, 339, 4, 1076, 994, 1063, 696, 766, 817, 41, 890, 680, 380, 371, 1013, 1071, 699, 465, 829, 877, 622, 125, 186, 293, 54, 771, 922, 517, 999, 451, 230, 967, 747, 955, 288, 1097, 849, 660, 1043, 76, 3, 694, 180, 719, 326, 529, 838, 15, 828, 506, 760, 966, 886, 68, 933, 81, 286, 536, 885, 642, 106, 364, 611, 1075, 204, 473, 864, 254, 1091, 1061, 80, 636, 625, 724, 270, 14, 956, 857, 466, 164, 245, 762, 588, 710, 705, 369, 683, 978, 606, 343, 472, 151, 896, 236, 1044, 258, 951, 784, 1020, 935, 497, 50, 593, 644, 158, 191, 314, 910, 454, 407, 331, 1024, 357, 195, 368, 867, 638, 604, 91, 579, 809, 448, 1093, 592, 95, 1046, 402, 53, 824, 616, 477, 1036, 576, 810, 101, 1094, 756, 969, 126, 711, 929, 403, 750, 450, 807, 112, 247, 859, 833, 1021, 489, 59, 891, 1060, 19, 757, 317, 962, 78, 1003, 574, 26, 1022, 51, 436, 633, 354, 608, 799, 949, 55, 878, 553, 61, 1084, 478, 69, 348, 283, 777, 524, 942, 1072, 1007, 43, 587, 586, 523, 1057, 778, 740, 200, 717, 919, 156, 411, 73, 1065, 677, 499, 437, 31, 971, 177, 830, 986, 340, 684, 585, 468, 140, 365, 853, 349, 567, 865, 619, 394, 463, 815, 355, 257, 972, 102, 356, 1009, 916, 297, 344, 624, 481, 805, 770, 217, 776, 260, 159, 851, 127, 957, 531, 1069, 467, 794, 690, 1002, 268, 320, 248, 990, 755, 121, 551, 107, 1056, 228, 10, 610, 952, 67, 742, 487, 543, 2, 173, 953, 844, 732, 397, 623, 299, 866, 597, 163, 804, 704, 181, 985, 207, 634, 178, 282, 1074, 913, 883, 449, 775, 464, 900, 427, 458, 9, 836, 500, 572, 868, 222, 979, 518, 825, 146, 432, 715, 612, 846, 249, 33, 485, 150, 415, 577, 1030, 787, 920, 252]
550
Cluster weights
[0.5 0.5 3.  1.5 2.  0.5 1.5 3.  1.  1.5 1.5 0.5 0.5 0.5 2.  0.5 1.  1.5
 0.5 0.5 0.5 1.  1.5 0.5 1.  0.5 1.  1.  1.  0.5 0.5 1.5 1.5 0.5 1.  0.5
 0.5 0.5 0.5 0.5 1.  0.5 0.5 0.5 3.  1.5 0.5 0.5 1.  1.5 0.5 0.5 3.  1.
 1.5 0.5 0.5 5.5 1.  1.5 2.  0.5 1.  0.5 1.5 1.  1.  2.  0.5 1.5 1.  0.5
 0.5 1.  1.  1.  0.5 2.  0.5 2.5 1.5 1.  0.5 2.5 1.5 0.5 0.5 0.5 2.  0.5
 0.5 2.  0.5 0.5 1.5 2.  0.5 1.  1.  0.5 1.5 0.5 3.5 1.  1.  0.5 1.  0.5
 1.  1.5 0.5 1.  1.5 1.  0.5 0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5 1.5 0.5 0.5
 1.5 2.  0.5 2.  2.5 0.5 2.5 0.5 2.  3.  0.5 0.5 0.5 1.5 0.5 0.5 1.  0.5
 1.  0.5 1.5 1.5 0.5 0.5 0.5 1.  0.5 0.5 0.5 1.  2.  1.  1.  1.  2.  1.5
 0.5 0.5 0.5 1.  0.5 1.  2.  0.5 0.5 0.5 0.5 0.5 2.  0.5 1.  0.5 1.  0.5
 2.5 2.  1.  1.5 1.5 0.5 1.  1.  0.5 1.  2.  0.5 1.  1.  1.  0.5 0.5 1.
 1.5 1.  1.  0.5 1.  2.  1.  1.  1.5 1.  1.  1.5 1.5 0.5 0.5 2.5 1.  0.5
 0.5 0.5 0.5 0.5 2.5 0.5 0.5 0.5 0.5 2.  0.5 1.  1.  1.  1.  1.  1.  0.5
 1.5 0.5 0.5 0.5 0.5 0.5 1.5 1.5 0.5 0.5 2.5 0.5 0.5 0.5 0.5 1.5 0.5 0.5
 0.5 0.5 0.5 1.  1.  0.5 0.5 1.  0.5 0.5 0.5 1.5 2.  0.5 1.  1.  0.5 3.
 0.5 0.5 2.5 0.5 1.5 1.  2.5 0.5 1.  0.5 0.5 0.5 0.5 1.  0.5 2.  1.  0.5
 1.5 1.5 0.5 0.5 1.  0.5 0.5 1.5 1.  2.  2.5 4.  1.  1.  0.5 0.5 1.  1.
 0.5 3.5 1.  1.  1.5 0.5 0.5 0.5 0.5 0.5 1.  2.  1.5 2.  1.  4.  3.5 1.
 0.5 1.  0.5 1.5 2.5 0.5 1.  1.  1.5 0.5 1.5 0.5 1.  1.  1.  0.5 0.5 1.
 1.  2.5 1.  1.  0.5 1.5 1.5 0.5 0.5 0.5 0.5 1.  0.5 0.5 1.  2.  0.5 2.
 0.5 0.5 0.5 0.5 1.  0.5 0.5 2.  0.5 1.5 2.5 2.5 2.5 1.5 0.5 1.  1.5 0.5
 0.5 0.5 1.5 0.5 0.5 0.5 2.  1.  0.5 0.5 1.  3.5 1.  0.5 0.5 1.  2.  1.
 1.  0.5 3.  0.5 0.5 0.5 0.5 1.5 1.5 0.5 1.  1.  0.5 0.5 2.  0.5 0.5 0.5
 0.5 1.5 2.  1.  0.5 0.5 0.5 1.  3.  1.  0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5
 1.5 0.5 0.5 2.  0.5 1.  0.5 0.5 0.5 0.5 0.5 1.  1.5 1.  1.5 0.5 0.5 3.5
 0.5 2.  0.5 0.5 3.  0.5 0.5 0.5 0.5 2.  1.5 0.5 0.5 1.  1.5 1.5 0.5 1.
 0.5 0.5 0.5 0.5 2.  0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5 1.  0.5 0.5 0.5 0.5
 1.5 1.  0.5 0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5 0.5 1.5 0.5 0.5 1.5 1.  0.5
 0.5 0.5 0.5 1.  2.  0.5 3.  1.5 0.5 0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5 0.5
 1.  0.5 0.5 0.5 1.  1.  2.5 1.  0.5 1.  0.5 1.  0.5 1.  1.  0.5 1.5 1.5
 1.  1.  1.  1.  1.  0.5 0.5 0.5 2.  0.5]
(550,)

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py:241: UserWarning: Reload offsets from trajectory
 ctime or size or n_atoms did not match
  warnings.warn("Reload offsets from trajectory\n "

(2, 6)
Running benchmark for cluster_1
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name cluster_1 already exists. Attempting to change name to cluster_10
Experiment name cluster_1 already exists. Attempting to change name to cluster_11
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN     cluster_1

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_1:
cluster_1 Topology: <Universe with 3369 atoms>
cluster_1 Trajectory: <Universe with 3369 atoms>
cluster_1 Traj: no frames 550
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
conda run -n HDXER_ENV python /home/alexi/Documents/HDXer/HDXer/calc_hdx.py -t /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1_clustered_cfrac1_0.5_.xtc -p /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb -m BestVendruscolo -log /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/calc_hdx_prep_cluster_11_0.log -out /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0 -seg /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_APO_segs.txt -mopt "{ 'save_detailed' : True }" --times 0 0.5 5.0 -str 1
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
Residue predictions complete

Running r split mode
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/mdtraj/formats/pdb/pdbfile.py:200: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
/home/alexi/Documents/HDXer/HDXer/dfpred.py:505: RuntimeWarning: divide by zero encountered in log
  logerr = logf + np.log(err) + np.log(time) # sd(e^Aa) = f * sd(A) * a
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

Experiment name cluster_1_r_naive_random already exists. Attempting to change name to cluster_1_r_naive_random0
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN     cluster_1

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_1:
cluster_1 Topology: <Universe with 3369 atoms>
cluster_1 Trajectory: <Universe with 3369 atoms>
cluster_1 Traj: no frames 550
Running VDX loop
Random seeds: [42]
Randomly splitting segments for cluster_1 with random seed 42 and train fraction 0.5
train_segs
    ResStr  ResEnd  peptide          calc_name
77     196     208       77  train_cluster_1_1
10       8      24       10  train_cluster_1_1
4        7      18        4  train_cluster_1_1
83     247     260       83  train_cluster_1_1
62     154     169       62  train_cluster_1_1
Saved train cluster_1_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/train_cluster_1_1/train_residue_segs__cluster_1_.txt
Train Peptide numbers: [  0   4   5   7   9  10  11  12  15  16  18  19  22  26  27  28  30  31
  33  34  35  36  39  40  42  43  44  45  47  53  55  56  62  64  65  66
  67  69  72  76  77  78  79  80  81  83  88  89  90  95 100 103 106 107]
Saved val cluster_1_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1/val_residue_segs__cluster_1_.txt
Val Peptide numbers: [  1   2   3   6   8  13  14  17  20  21  23  24  25  29  32  37  38  41
  46  48  49  50  51  52  54  57  58  59  60  61  63  68  70  71  73  74
  75  82  84  85  86  87  91  92  93  94  96  97  98  99 101 102 104 105]
train_HDX_data
    0.0      0.5      5.0  peptide          calc_name  \
0   0.0  0.13267  0.18143       77  train_cluster_1_1
1   0.0  0.48273  0.53102       10  train_cluster_1_1
2   0.0  0.41726  0.49519        4  train_cluster_1_1
3   0.0  0.08147  0.13526       83  train_cluster_1_1
4   0.0  0.50341  0.53212       62  train_cluster_1_1
5   0.0  0.28164  0.36568       67  train_cluster_1_1
6   0.0  0.26192  0.34619       30  train_cluster_1_1
7   0.0  0.37847  0.48848       45  train_cluster_1_1
8   0.0  0.04358  0.04371       95  train_cluster_1_1
9   0.0  0.50258  0.53988       11  train_cluster_1_1
10  0.0  0.05688  0.07274       81  train_cluster_1_1
11  0.0  0.20249  0.21472       79  train_cluster_1_1
12  0.0  0.41879  0.44438        0  train_cluster_1_1
13  0.0  0.16260  0.17496       80  train_cluster_1_1
14  0.0  0.17163  0.27883       18  train_cluster_1_1
15  0.0  0.27969  0.36567       69  train_cluster_1_1
16  0.0  0.26061  0.32801       56  train_cluster_1_1
17  0.0  0.11684  0.15140       76  train_cluster_1_1
18  0.0  0.22454  0.24966      106  train_cluster_1_1
19  0.0  0.33575  0.45181       42  train_cluster_1_1
20  0.0  0.47373  0.50144       12  train_cluster_1_1
21  0.0  0.34716  0.45807       36  train_cluster_1_1
22  0.0  0.26524  0.35365       64  train_cluster_1_1
23  0.0  0.34135  0.38830       26  train_cluster_1_1
24  0.0  0.31355  0.39928       22  train_cluster_1_1
25  0.0  0.31421  0.37857       31  train_cluster_1_1
26  0.0  0.18217  0.28305       47  train_cluster_1_1
27  0.0  0.20729  0.23030      100  train_cluster_1_1
28  0.0  0.55802  0.57504       15  train_cluster_1_1
29  0.0  0.37082  0.47284       44  train_cluster_1_1
30  0.0  0.10385  0.19651       88  train_cluster_1_1
31  0.0  0.53877  0.49943       89  train_cluster_1_1
32  0.0  0.46825  0.52028        9  train_cluster_1_1
33  0.0  0.29666  0.37860       33  train_cluster_1_1
34  0.0  0.26392  0.30614       55  train_cluster_1_1
35  0.0  0.21731  0.24442      103  train_cluster_1_1
36  0.0  0.28439  0.33185       28  train_cluster_1_1
37  0.0  0.28369  0.42940       40  train_cluster_1_1
38  0.0  0.44176  0.50927        5  train_cluster_1_1
39  0.0  0.18105  0.23003       53  train_cluster_1_1
40  0.0  0.23913  0.27068      107  train_cluster_1_1
41  0.0  0.33252  0.48976       39  train_cluster_1_1
42  0.0  0.33633  0.46390       35  train_cluster_1_1
43  0.0  0.55641  0.57196       16  train_cluster_1_1
44  0.0  0.35203  0.42601       78  train_cluster_1_1
45  0.0  0.38440  0.44775       34  train_cluster_1_1
46  0.0  0.25152  0.35786       66  train_cluster_1_1
47  0.0  0.41316  0.48254        7  train_cluster_1_1
48  0.0  0.33443  0.43697       43  train_cluster_1_1
49  0.0  0.25454  0.32548       65  train_cluster_1_1
50  0.0  0.36820  0.37879       72  train_cluster_1_1
51  0.0  0.28512  0.29602       27  train_cluster_1_1
52  0.0  0.16883  0.28686       19  train_cluster_1_1
53  0.0  0.51417  0.47866       90  train_cluster_1_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     196     208
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      24
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      18
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     260
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     154     169
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     186
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      61
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      89      97
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     308     315
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      25
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     257
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     238
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       1       7
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     239
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      32
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     186
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     153
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     194     208
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     360
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      85      97
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      18
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      76      84
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     169     183
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      51
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      34      40
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      65
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     106
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     356
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      23
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      88      97
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     253     260
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     275
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      21
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      61
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     150
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     357
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      51
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      88
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      21
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     121     132
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     339     360
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      87
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      74      84
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      25
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     213     223
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      65
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     185
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      18
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      86      97
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     183
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     195
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      49
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      33
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     276
    ResStr  ResEnd  0.0      0.5      5.0  peptide          calc_name  \
0      196     208  0.0  0.13267  0.18143       77  train_cluster_1_1
1        8      24  0.0  0.48273  0.53102       10  train_cluster_1_1
2        7      18  0.0  0.41726  0.49519        4  train_cluster_1_1
3      247     260  0.0  0.08147  0.13526       83  train_cluster_1_1
4      154     169  0.0  0.50341  0.53212       62  train_cluster_1_1
5      170     186  0.0  0.28164  0.36568       67  train_cluster_1_1
6       49      61  0.0  0.26192  0.34619       30  train_cluster_1_1
7       89      97  0.0  0.37847  0.48848       45  train_cluster_1_1
8      308     315  0.0  0.04358  0.04371       95  train_cluster_1_1
9        8      25  0.0  0.50258  0.53988       11  train_cluster_1_1
10     247     257  0.0  0.05688  0.07274       81  train_cluster_1_1
11     224     238  0.0  0.20249  0.21472       79  train_cluster_1_1
12       1       7  0.0  0.41879  0.44438        0  train_cluster_1_1
13     224     239  0.0  0.16260  0.17496       80  train_cluster_1_1
14      26      32  0.0  0.17163  0.27883       18  train_cluster_1_1
15     171     186  0.0  0.27969  0.36567       69  train_cluster_1_1
16     132     153  0.0  0.26061  0.32801       56  train_cluster_1_1
17     194     208  0.0  0.11684  0.15140       76  train_cluster_1_1
18     338     360  0.0  0.22454  0.24966      106  train_cluster_1_1
19      85      97  0.0  0.33575  0.45181       42  train_cluster_1_1
20      11      18  0.0  0.47373  0.50144       12  train_cluster_1_1
21      76      84  0.0  0.34716  0.45807       36  train_cluster_1_1
22     169     183  0.0  0.26524  0.35365       64  train_cluster_1_1
23      41      51  0.0  0.34135  0.38830       26  train_cluster_1_1
24      34      40  0.0  0.31355  0.39928       22  train_cluster_1_1
25      49      65  0.0  0.31421  0.37857       31  train_cluster_1_1
26      98     106  0.0  0.18217  0.28305       47  train_cluster_1_1
27     334     356  0.0  0.20729  0.23030      100  train_cluster_1_1
28      11      23  0.0  0.55802  0.57504       15  train_cluster_1_1
29      88      97  0.0  0.37082  0.47284       44  train_cluster_1_1
30     253     260  0.0  0.10385  0.19651       88  train_cluster_1_1
31     261     275  0.0  0.53877  0.49943       89  train_cluster_1_1
32       8      21  0.0  0.46825  0.52028        9  train_cluster_1_1
33      52      61  0.0  0.29666  0.37860       33  train_cluster_1_1
34     132     150  0.0  0.26392  0.30614       55  train_cluster_1_1
35     336     357  0.0  0.21731  0.24442      103  train_cluster_1_1
36      42      51  0.0  0.28439  0.33185       28  train_cluster_1_1
37      77      88  0.0  0.28369  0.42940       40  train_cluster_1_1
38       7      21  0.0  0.44176  0.50927        5  train_cluster_1_1
39     121     132  0.0  0.18105  0.23003       53  train_cluster_1_1
40     339     360  0.0  0.23913  0.27068      107  train_cluster_1_1
41      77      87  0.0  0.33252  0.48976       39  train_cluster_1_1
42      74      84  0.0  0.33633  0.46390       35  train_cluster_1_1
43      11      25  0.0  0.55641  0.57196       16  train_cluster_1_1
44     213     223  0.0  0.35203  0.42601       78  train_cluster_1_1
45      52      65  0.0  0.38440  0.44775       34  train_cluster_1_1
46     170     185  0.0  0.25152  0.35786       66  train_cluster_1_1
47       8      18  0.0  0.41316  0.48254        7  train_cluster_1_1
48      86      97  0.0  0.33443  0.43697       43  train_cluster_1_1
49     170     183  0.0  0.25454  0.32548       65  train_cluster_1_1
50     187     195  0.0  0.36820  0.37879       72  train_cluster_1_1
51      42      49  0.0  0.28512  0.29602       27  train_cluster_1_1
52      26      33  0.0  0.16883  0.28686       19  train_cluster_1_1
53     261     276  0.0  0.51417  0.47866       90  train_cluster_1_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train cluster_1 HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/train_cluster_1_1/train_cluster_1_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide        calc_name  \
0        6      18  0.0  0.37096  0.45204        1  val_cluster_1_1
1        6      21  0.0  0.40040  0.48544        2  val_cluster_1_1
2        6      25  0.0  0.45875  0.51503        3  val_cluster_1_1
3        7      25  0.0  0.48987  0.54090        6  val_cluster_1_1
4        8      20  0.0  0.46617  0.51066        8  val_cluster_1_1
5       11      20  0.0  0.52057  0.54102       13  val_cluster_1_1
6       11      21  0.0  0.52823  0.55640       14  val_cluster_1_1
7       19      25  0.0  0.52928  0.54827       17  val_cluster_1_1
8       27      33  0.0  0.16341  0.27353       20  val_cluster_1_1
9       33      40  0.0  0.32309  0.41205       21  val_cluster_1_1
10      34      41  0.0  0.34392  0.42213       23  val_cluster_1_1
11      41      48  0.0  0.35604  0.35617       24  val_cluster_1_1
12      41      49  0.0  0.34105  0.35125       25  val_cluster_1_1
13      42      65  0.0  0.32954  0.39085       29  val_cluster_1_1
14      50      65  0.0  0.32314  0.38565       32  val_cluster_1_1
15      77      84  0.0  0.34165  0.44393       37  val_cluster_1_1
16      77      85  0.0  0.30725  0.43533       38  val_cluster_1_1
17      77      97  0.0  0.35906  0.50293       41  val_cluster_1_1
18      98     104  0.0  0.22218  0.31040       46  val_cluster_1_1
19      98     108  0.0  0.25719  0.37045       48  val_cluster_1_1
20     113     120  0.0  0.49756  0.50850       49  val_cluster_1_1
21     114     120  0.0  0.55024  0.54326       50  val_cluster_1_1
22     117     131  0.0  0.24310  0.29208       51  val_cluster_1_1
23     121     131  0.0  0.19173  0.23972       52  val_cluster_1_1
24     132     149  0.0  0.26140  0.30267       54  val_cluster_1_1
25     150     169  0.0  0.45297  0.53974       57  val_cluster_1_1
26     151     162  0.0  0.31622  0.45372       58  val_cluster_1_1
27     151     167  0.0  0.43711  0.52972       59  val_cluster_1_1
28     151     169  0.0  0.47628  0.54735       60  val_cluster_1_1
29     151     170  0.0  0.49249  0.57156       61  val_cluster_1_1
30     155     169  0.0  0.53500  0.53827       63  val_cluster_1_1
31     171     183  0.0  0.24177  0.30174       68  val_cluster_1_1
32     184     195  0.0  0.38633  0.44869       70  val_cluster_1_1
33     184     208  0.0  0.24871  0.31226       71  val_cluster_1_1
34     187     208  0.0  0.22903  0.26839       73  val_cluster_1_1
35     187     209  0.0  0.21687  0.25989       74  val_cluster_1_1
36     188     208  0.0  0.20479  0.23593       75  val_cluster_1_1
37     247     259  0.0  0.07600  0.11464       82  val_cluster_1_1
38     248     259  0.0  0.08527  0.13242       84  val_cluster_1_1
39     248     260  0.0  0.08569  0.14304       85  val_cluster_1_1
40     250     257  0.0  0.06291  0.07885       86  val_cluster_1_1
41     250     260  0.0  0.09393  0.16201       87  val_cluster_1_1
42     261     278  0.0  0.50107  0.49072       91  val_cluster_1_1
43     261     281  0.0  0.45551  0.47280       92  val_cluster_1_1
44     305     313  0.0  0.06500  0.10668       93  val_cluster_1_1
45     305     315  0.0  0.06362  0.10593       94  val_cluster_1_1
46     314     327  0.0  0.08151  0.10674       96  val_cluster_1_1
47     316     327  0.0  0.08795  0.11537       97  val_cluster_1_1
48     317     327  0.0  0.09261  0.12297       98  val_cluster_1_1
49     333     356  0.0  0.17298  0.20225       99  val_cluster_1_1
50     334     357  0.0  0.20401  0.23454      101  val_cluster_1_1
51     336     356  0.0  0.21943  0.23426      102  val_cluster_1_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/train_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00181818, 0.00181818, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/train_cluster_1_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00000  0.00000        0
1  0.0  0.06670  0.06697        1
2  0.0  0.10000  0.10000        2
3  0.0  0.00000  0.00003        3
4  0.0  0.00001  0.00009        4
Experimental cluster_1 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat
REWIGHTING val_cluster_1_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([0.5, 0.5, 3. , 1.5, 2. , 0.5, 1.5, 3. , 1. , 1.5, 1.5, 0.5, 0.5,
       0.5, 2. , 0.5, 1. , 1.5, 0.5, 0.5, 0.5, 1. , 1.5, 0.5, 1. , 0.5,
       1. , 1. , 1. , 0.5, 0.5, 1.5, 1.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 0.5, 0.5, 0.5, 3. , 1.5, 0.5, 0.5, 1. , 1.5, 0.5, 0.5,
       3. , 1. , 1.5, 0.5, 0.5, 5.5, 1. , 1.5, 2. , 0.5, 1. , 0.5, 1.5,
       1. , 1. , 2. , 0.5, 1.5, 1. , 0.5, 0.5, 1. , 1. , 1. , 0.5, 2. ,
       0.5, 2.5, 1.5, 1. , 0.5, 2.5, 1.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5,
       2. , 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 1.5, 0.5, 3.5, 1. ,
       1. , 0.5, 1. , 0.5, 1. , 1.5, 0.5, 1. , 1.5, 1. , 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 2. , 0.5, 2. ,
       2.5, 0.5, 2.5, 0.5, 2. , 3. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1. ,
       0.5, 1. , 0.5, 1.5, 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. ,
       2. , 1. , 1. , 1. , 2. , 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 1. , 2. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 1. , 0.5, 2.5, 2. ,
       1. , 1.5, 1.5, 0.5, 1. , 1. , 0.5, 1. , 2. , 0.5, 1. , 1. , 1. ,
       0.5, 0.5, 1. , 1.5, 1. , 1. , 0.5, 1. , 2. , 1. , 1. , 1.5, 1. ,
       1. , 1.5, 1.5, 0.5, 0.5, 2.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 2.5,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 0.5,
       1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5, 1.5, 0.5, 0.5, 2.5, 0.5, 0.5,
       0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 0.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 3. , 0.5, 0.5, 2.5,
       0.5, 1.5, 1. , 2.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 2. ,
       1. , 0.5, 1.5, 1.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 1. , 2. , 2.5,
       4. , 1. , 1. , 0.5, 0.5, 1. , 1. , 0.5, 3.5, 1. , 1. , 1.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 1. , 2. , 1.5, 2. , 1. , 4. , 3.5, 1. , 0.5,
       1. , 0.5, 1.5, 2.5, 0.5, 1. , 1. , 1.5, 0.5, 1.5, 0.5, 1. , 1. ,
       1. , 0.5, 0.5, 1. , 1. , 2.5, 1. , 1. , 0.5, 1.5, 1.5, 0.5, 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 1. , 2. , 0.5, 2. , 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 2. , 0.5, 1.5, 2.5, 2.5, 2.5, 1.5, 0.5, 1. , 1.5,
       0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 2. , 1. , 0.5, 0.5, 1. , 3.5,
       1. , 0.5, 0.5, 1. , 2. , 1. , 1. , 0.5, 3. , 0.5, 0.5, 0.5, 0.5,
       1.5, 1.5, 0.5, 1. , 1. , 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 1.5,
       2. , 1. , 0.5, 0.5, 0.5, 1. , 3. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 1.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 1.5, 1. , 1.5, 0.5, 0.5, 3.5, 0.5, 2. , 0.5, 0.5, 3. ,
       0.5, 0.5, 0.5, 0.5, 2. , 1.5, 0.5, 0.5, 1. , 1.5, 1.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5,
       1. , 2. , 0.5, 3. , 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. , 1. , 2.5, 1. , 0.5, 1. , 0.5,
       1. , 0.5, 1. , 1. , 0.5, 1.5, 1.5, 1. , 1. , 1. , 1. , 1. , 0.5,
       0.5, 0.5, 2. , 0.5]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random0/val_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
LogPf_by_res [35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
Pf_by_res [3.79601138e+15 2.58787960e+27 2.46018177e+17 1.99893642e+12
 3.49715508e+07 3.46468273e+13 5.41893666e+14 2.21488468e+11
 1.18581871e+12 1.12331646e+10 5.77638782e+01 5.65169568e+08
 2.26149345e+20 2.44085750e+21 9.79081853e+14 7.93471050e+19
 3.00768675e+06 3.25319450e+08 5.31764297e+13 5.19321558e+06
 2.53970143e+08 2.38766169e+15 3.38116006e+22 3.54592556e+28
 1.82191469e+12 7.41839339e+17 2.15381810e+26 3.69558767e+24
 4.24345339e+18 1.04106170e+18 3.54640532e+20 1.03580533e+23
 8.13372987e+19 2.02796394e+29 2.05192002e+24 6.07584048e+16
 1.64428047e+13 1.18213288e+16 4.22526265e+14 2.23410907e+12
 4.91756476e+07 9.04376536e+13 1.17029810e+21 1.40534351e+25
 4.52831762e+29 1.96856112e+13 2.23385400e+08 3.06498228e+15
 1.63438904e+15 4.44648623e+04 1.50831820e+07 3.08522876e+06
 2.90199841e+14 7.98449131e+08 1.67917367e+05 8.58892058e+11
 3.50958363e+23 1.65647157e+17 7.25878147e+13 1.13248150e+16
 3.12028376e+26 4.52537452e+11 3.99419685e+12 1.84896857e+22
 2.11166954e+12 9.46002036e+05 1.32061676e+17 5.25738508e+23
 2.80387433e+16 1.82313808e+18 1.52827491e+24 1.87923891e+24
 9.43110983e+18 4.05645635e+22 3.20764507e+22 4.30347515e+18
 6.96118286e+21 2.28701362e+19 8.00926402e+17 2.18627988e+19
 1.34375553e+18 1.63065029e+12 8.81120616e+12 1.11738961e+07
 1.29274793e+23 2.20158868e+23 4.38415249e+15 3.00709717e+27
 2.56171806e+15 5.34584303e+08 1.84001514e+08 2.61272514e+13
 1.17621086e+20 1.16935206e+07 9.31811506e+01 1.71232668e+06
 6.70347337e+06 1.07030028e+13 1.04663735e+22 1.50296023e+36
 6.36782840e+21 2.39403693e+28 4.78814587e+09 2.08655151e+10
 6.22306931e+14 2.57409067e+15 2.17231262e+19 4.96423683e+29
 8.80808228e+37 3.43436840e+26 3.08952860e+11 1.26533474e+11
 4.40495226e+16 1.29376092e+17 5.80393404e+14 1.24977372e+17
 1.35373276e+16 1.97824660e+05 9.75671357e+08 8.74096566e+27
 7.68752491e+17 8.90258288e+04 6.59366561e+11 1.21828613e+14
 2.33010013e+16 7.60415284e+10 1.50005556e+16 5.23535983e+28
 1.85821495e+20 4.51351705e+21 2.09579824e+20 2.43778128e+23
 6.10418220e+19 4.22574509e+18 7.32649630e+23 6.78503101e+22
 1.65915365e+06 1.28636490e+16 5.74005232e+18 8.92416926e+14
 3.56650898e+15 4.90314785e+18 9.25045125e+14 1.93621539e+17
 1.67395616e+17 3.29163115e+19 1.14222711e+20 2.35543072e+15
 9.32173096e+13 5.73297869e+17 9.47596414e+21 4.89908610e+24
 5.00185965e+22 5.81328884e+33 1.65760923e+10 1.32761242e+11
 7.88271458e+14 3.15676448e+16 4.58526700e+13 8.59937721e+17
 4.64083261e+13 3.82895936e+16 1.60558876e+14 2.95976369e+11
 1.39866544e+11 5.10852220e+08 5.10942139e+07 7.65239387e+11
 2.45270080e+17 1.42519814e+30 2.61375140e+18 7.70415332e+29
 1.43444884e+17 7.10692594e+12 1.41233702e+11 3.47627914e+17
 6.25074974e+19 2.85232306e+23 4.94096859e+34 2.94800922e+38
 2.50723436e+31 7.40020694e+17 5.42719742e+18 6.77262701e+20
 9.46197081e+17 1.47913387e+16 6.83358490e+21 1.70734451e+13
 4.13477713e+12 1.18495099e+19 3.22714485e+09 6.80656032e+04
 6.52053674e+16 2.86059338e+05 5.51613303e+07 9.08976513e+10
 8.09756968e+11 3.32971920e+12 2.11625723e+10 7.88338537e+13
 7.00283113e+15 3.87738401e+12 2.49359041e+15 9.43952276e+15
 4.02461272e+19 2.42423220e+26 4.19479132e+20 3.79137754e+16
 8.20772357e+13 1.19503253e+22 4.95329702e+17 1.90742423e+28
 1.10895500e+25 6.94763061e+22 3.18044356e+27 1.29251291e+23
 5.26015610e+12 2.67933812e+12 2.44914744e+10 2.00908250e+15
 1.12263982e+08 1.41275361e+07 6.76607935e+10 1.46725571e+13
 4.69811189e+12 2.47005126e+02 3.20348380e+02 2.04617678e+11
 9.68534747e+04 2.07947233e+04 1.08649359e+08 7.98784270e+02
 3.95798146e+09 7.90402087e+17 1.57528401e+28 3.80143040e+18
 2.63271012e+18 4.66611186e+17 1.52209597e+23 1.38898167e+20
 1.13876042e+21 5.22079177e+10 9.86211196e+11 5.64153370e+19
 2.85018615e+27 2.43823874e+24 7.69080464e+20 9.87878027e+20
 2.91128374e+24 3.55439562e+24 1.83107034e+22 1.43467784e+21
 4.39957981e+25 2.10052023e+24 6.66372176e+15 6.03582153e+13
 1.87180915e+15 3.84068273e+18 2.80283862e+15 1.26639389e+22
 1.71169601e+13 2.79250557e+13 3.12729243e+21 6.62397471e+18
 3.26970688e+11 4.20632067e+23 4.70509236e+25 2.32666422e+28
 5.86399999e+18 1.20102137e+14 3.35450052e+13 5.27695030e+13
 1.12513115e+14 1.20309065e+13 7.84312567e+08 8.25346157e+15
 1.94891484e+00 6.13357970e+01 2.61324301e+08 6.57103438e+06
 8.21192398e+15 1.50944514e+26 3.50243264e+24 1.00156045e+18
 2.19425722e+20 2.11480706e+25 2.05713778e+23 1.08301289e+19
 1.29685269e+21]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  2970.25801533   664.95794074  5926.44387531
  3332.68430264   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  6649.57939778  1962.4300073
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
  9392.7805534   4393.33353926   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.08010673e-11 1.44494098e-24 1.82737206e-14 1.26472236e-10
 1.09415610e-04 1.21096253e-10 1.34548885e-12 4.44061434e-09
 2.81045011e-10 5.15575245e-08 9.35702591e+01 5.63138744e-06
 9.08654626e-18 7.67806441e-19 2.05104494e-12 4.20013348e-18
 2.21086169e-04 1.44705203e-05 1.98186926e-10 6.71982285e-04
 1.47235153e-05 1.60258615e-12 1.10593206e-20 8.77131205e-26
 5.03809270e-10 4.70418418e-15 1.20111656e-23 4.73271842e-22
 5.68950836e-16 1.53220794e-15 2.83795698e-18 1.19540766e-20
 4.59731679e-18 3.67903525e-27 1.62417847e-22 1.17270240e-14
 7.88530105e-11 6.92034716e-14 3.14007822e-12 1.45777268e-10
 1.29135036e-05 2.79540600e-11 6.99033001e-19 2.31745699e-23
 8.45001139e-27 3.70378078e-11 2.36450039e-05 1.36888262e-12
 1.37860146e-12 2.06432104e-02 1.45982641e-05 2.15529542e-04
 8.71158159e-12 1.31991816e-06 4.24324945e-03 2.68445167e-09
 1.50500721e-21 1.24053834e-15 2.52307671e-11 1.19884507e-13
 3.01023282e-24 3.60694607e-09 5.26459191e-10 3.59637233e-20
 2.87189278e-10 9.70291263e-04 6.33895082e-15 1.29426852e-21
 5.07032307e-14 1.82799337e-16 2.94166149e-22 6.14910885e-22
 1.69134177e-16 3.75532362e-20 1.36964454e-20 1.54516505e-16
 2.23929409e-19 3.66037373e-17 4.66876020e-16 1.10430343e-17
 5.68164262e-16 1.20346467e-09 3.00440736e-10 5.95099449e-05
 7.43498889e-21 1.73803290e-21 6.93279769e-14 1.36347354e-24
 1.75494232e-12 2.72130973e-06 4.54959543e-05 4.03367081e-10
 1.23682709e-17 9.43732453e-05 1.15735371e+01 9.53251620e-04
 1.53636459e-04 4.93501568e-11 5.79425959e-20 5.96824568e-34
 1.69356872e-19 3.49673991e-25 1.74834366e-07 4.01203826e-07
 5.73838309e-12 7.80136031e-13 7.86813586e-17 2.32777867e-27
 6.88514059e-35 2.61184438e-24 3.57192192e-09 6.92769476e-08
 9.30792703e-14 1.55217308e-14 4.15979288e-12 6.25119129e-15
 5.63976797e-14 3.51976565e-03 1.05557871e-06 1.82488190e-25
 2.73531685e-15 2.20433781e-02 3.41717530e-09 4.04617698e-11
 4.52292715e-13 4.58926714e-08 7.52812586e-14 9.20126727e-27
 8.98872775e-18 1.37492525e-18 4.91410809e-18 3.67959007e-21
 3.28977873e-17 4.86285007e-16 6.88490325e-21 4.91181888e-20
 3.41120303e-04 3.74481184e-14 2.84366429e-16 2.25022724e-12
 4.07897322e-13 3.82225086e-16 5.32882256e-13 4.03497187e-15
 7.39690595e-15 2.66307264e-17 3.27372138e-18 3.80823590e-13
 1.67223617e-11 4.83519339e-15 2.60717851e-19 7.12326507e-23
 1.87785771e-20 5.10942789e-31 4.01154825e-08 4.46398645e-08
 4.22783835e-12 3.04475250e-14 7.43754398e-11 1.57880021e-15
 3.06336166e-11 8.70389056e-15 4.86586281e-12 5.14679817e-09
 1.40307321e-08 3.42372514e-06 1.52905270e-04 5.74112313e-09
 5.28627321e-15 7.06185720e-28 4.42109552e-16 9.46388074e-27
 2.66752877e-14 3.24423560e-10 5.92728530e-08 1.55481790e-14
 2.67215758e-17 7.04036967e-21 2.33874075e-32 2.05714705e-35
 4.20338572e-28 3.18823490e-15 1.22523264e-15 2.89759056e-18
 4.64314848e-15 1.78972661e-13 1.06695372e-19 3.02324270e-10
 5.83904833e-10 5.87616237e-16 1.75378244e-07 3.31029332e-02
 1.44049193e-13 1.53581196e-02 7.60605472e-06 9.20961583e-09
 1.88121955e-09 1.17594380e-09 3.14214138e-08 7.87193360e-12
 2.33088326e-13 3.83932931e-10 5.57146053e-13 9.28633055e-14
 6.57763976e-17 1.43952749e-23 2.81892691e-18 1.18576095e-14
 9.51856446e-12 3.12906402e-20 1.89626839e-15 4.70269575e-26
 1.65150637e-22 6.32349904e-21 6.46110034e-26 6.93999707e-21
 4.80613039e-10 9.65531961e-10 3.34025210e-07 2.62903523e-13
 7.99012796e-06 6.64856244e-05 6.64442019e-08 1.53563629e-10
 3.31795751e-10 2.95180872e+00 3.69123458e+00 9.15906257e-09
 1.57281981e-02 1.01120924e-01 2.32684262e-06 8.51853032e-01
 4.41896358e-07 2.21282006e-15 4.95947051e-25 1.42182823e-15
 1.59364334e-16 3.66301782e-16 3.80497790e-21 7.41476964e-18
 1.60828056e-18 2.48346363e-08 1.81478112e-10 1.78400880e-17
 3.29549724e-25 5.31762796e-22 1.68586345e-18 4.87630492e-19
 1.28442764e-22 4.38559389e-23 1.17513875e-19 4.63489380e-19
 3.30661002e-24 1.09765866e-21 3.97262272e-13 1.66746908e-11
 2.19044630e-12 1.73135348e-16 3.50910287e-13 5.75738630e-20
 6.30039150e-11 1.89147292e-11 1.34160814e-19 1.66600197e-16
 5.47375508e-10 4.77410315e-21 2.29206022e-23 6.69977880e-26

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_1_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_r_naive_random/20240402-191427_analysis.csv
dict_keys(['cluster_1_r_naive_random'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_r_naive_random to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_1_r_naive_random/cluster_1_r_naive_random0_1712081668.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_1_r_naive_random': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00000  0.00000       77  train_cluster_1_1
1   0.0  0.06670  0.06697       10  train_cluster_1_1
2   0.0  0.10000  0.10000        4  train_cluster_1_1
3   0.0  0.00000  0.00003       83  train_cluster_1_1
4   0.0  0.00001  0.00009       62  train_cluster_1_1
5   0.0  0.00000  0.00000       67  train_cluster_1_1
6   0.0  0.00107  0.01031       30  train_cluster_1_1
7   0.0  0.00000  0.00000       45  train_cluster_1_1
8   0.0  0.00000  0.00000       95  train_cluster_1_1
9   0.0  0.06253  0.06279       11  train_cluster_1_1
10  0.0  0.00000  0.00004       81  train_cluster_1_1
11  0.0  0.00000  0.00000       79  train_cluster_1_1
12  0.0  0.00001  0.00009        0  train_cluster_1_1
13  0.0  0.00000  0.00000       80  train_cluster_1_1
14  0.0  0.00000  0.00000       18  train_cluster_1_1
15  0.0  0.00000  0.00000       69  train_cluster_1_1
16  0.0  0.00060  0.00579       56  train_cluster_1_1
17  0.0  0.00000  0.00000       76  train_cluster_1_1
18  0.0  0.11111  0.11116      106  train_cluster_1_1
19  0.0  0.00000  0.00000       42  train_cluster_1_1
20  0.0  0.14286  0.14286       12  train_cluster_1_1
21  0.0  0.00007  0.00069       36  train_cluster_1_1
22  0.0  0.00000  0.00000       64  train_cluster_1_1
23  0.0  0.00000  0.00002       26  train_cluster_1_1
24  0.0  0.00000  0.00000       22  train_cluster_1_1
25  0.0  0.00079  0.00756       31  train_cluster_1_1
26  0.0  0.00001  0.00006       47  train_cluster_1_1
27  0.0  0.11111  0.11116      100  train_cluster_1_1
28  0.0  0.08337  0.08371       15  train_cluster_1_1
29  0.0  0.00000  0.00000       44  train_cluster_1_1
30  0.0  0.00001  0.00005       88  train_cluster_1_1
31  0.0  0.16216  0.28406       89  train_cluster_1_1
32  0.0  0.08334  0.08343        9  train_cluster_1_1
33  0.0  0.00147  0.01417       33  train_cluster_1_1
34  0.0  0.00071  0.00675       55  train_cluster_1_1
35  0.0  0.11765  0.11770      103  train_cluster_1_1
36  0.0  0.00000  0.00002       28  train_cluster_1_1
37  0.0  0.00005  0.00048       40  train_cluster_1_1
38  0.0  0.07693  0.07701        5  train_cluster_1_1
39  0.0  0.00000  0.00000       53  train_cluster_1_1
40  0.0  0.11765  0.11770      107  train_cluster_1_1
41  0.0  0.00005  0.00054       39  train_cluster_1_1
42  0.0  0.00005  0.00054       35  train_cluster_1_1
43  0.0  0.07146  0.07175       16  train_cluster_1_1
44  0.0  0.00291  0.02741       78  train_cluster_1_1
45  0.0  0.00098  0.00944       34  train_cluster_1_1
46  0.0  0.00000  0.00000       66  train_cluster_1_1
47  0.0  0.11111  0.11111        7  train_cluster_1_1
48  0.0  0.00000  0.00000       43  train_cluster_1_1
49  0.0  0.00000  0.00000       65  train_cluster_1_1
50  0.0  0.00001  0.00009       72  train_cluster_1_1
51  0.0  0.00000  0.00001       27  train_cluster_1_1
52  0.0  0.00000  0.00000       19  train_cluster_1_1
53  0.0  0.14968  0.26221       90  train_cluster_1_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.09091  0.09091        1  val_cluster_1_1
1   0.0  0.07144  0.07151        2  val_cluster_1_1
2   0.0  0.05558  0.05581        3  val_cluster_1_1
3   0.0  0.05885  0.05909        6  val_cluster_1_1
4   0.0  0.09092  0.09102        8  val_cluster_1_1
5   0.0  0.11112  0.11124       13  val_cluster_1_1
6   0.0  0.10001  0.10012       14  val_cluster_1_1
7   0.0  0.00006  0.00058       17  val_cluster_1_1
8   0.0  0.00000  0.00000       20  val_cluster_1_1
9   0.0  0.00000  0.00000       21  val_cluster_1_1
10  0.0  0.00000  0.00000       23  val_cluster_1_1
11  0.0  0.00000  0.00001       24  val_cluster_1_1
12  0.0  0.00000  0.00001       25  val_cluster_1_1
13  0.0  0.00056  0.00541       29  val_cluster_1_1
14  0.0  0.00084  0.00810       32  val_cluster_1_1
15  0.0  0.00008  0.00081       37  val_cluster_1_1
16  0.0  0.00007  0.00069       38  val_cluster_1_1
17  0.0  0.00003  0.00025       41  val_cluster_1_1
18  0.0  0.00000  0.00003       46  val_cluster_1_1
19  0.0  0.00000  0.00004       48  val_cluster_1_1
20  0.0  0.14248  0.14363       49  val_cluster_1_1
21  0.0  0.00009  0.00090       50  val_cluster_1_1
22  0.0  0.00000  0.00000       51  val_cluster_1_1
23  0.0  0.00000  0.00000       52  val_cluster_1_1
24  0.0  0.00075  0.00715       54  val_cluster_1_1
25  0.0  0.00001  0.00007       57  val_cluster_1_1
26  0.0  0.00001  0.00012       58  val_cluster_1_1
27  0.0  0.00001  0.00008       59  val_cluster_1_1
28  0.0  0.00001  0.00007       60  val_cluster_1_1
29  0.0  0.00001  0.00007       61  val_cluster_1_1
30  0.0  0.00001  0.00010       63  val_cluster_1_1
31  0.0  0.00000  0.00000       68  val_cluster_1_1
32  0.0  0.00001  0.00007       70  val_cluster_1_1
33  0.0  0.00000  0.00003       71  val_cluster_1_1
34  0.0  0.00000  0.00004       73  val_cluster_1_1
35  0.0  0.00000  0.00003       74  val_cluster_1_1
36  0.0  0.00000  0.00004       75  val_cluster_1_1
37  0.0  0.00000  0.00003       82  val_cluster_1_1
38  0.0  0.00000  0.00003       84  val_cluster_1_1
39  0.0  0.00000  0.00003       85  val_cluster_1_1
40  0.0  0.00001  0.00005       86  val_cluster_1_1
41  0.0  0.00000  0.00004       87  val_cluster_1_1
42  0.0  0.12972  0.22725       91  val_cluster_1_1
43  0.0  0.10810  0.18937       92  val_cluster_1_1
44  0.0  0.00000  0.00000       93  val_cluster_1_1
45  0.0  0.00000  0.00000       94  val_cluster_1_1
46  0.0  0.00000  0.00000       96  val_cluster_1_1
47  0.0  0.00000  0.00000       97  val_cluster_1_1
48  0.0  0.00000  0.00000       98  val_cluster_1_1
49  0.0  0.10526  0.10531       99  val_cluster_1_1
50  0.0  0.10526  0.10531      101  val_cluster_1_1
51  0.0  0.12500  0.12506      102  val_cluster_1_1
52  0.0  0.10000  0.10004      104  val_cluster_1_1
53  0.0  0.13333  0.13339      105  val_cluster_1_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name                      name  \
0    0.0  0.41879  0.44438        0  Experimental  cluster_1_r_naive_random
1    0.0  0.37096  0.45204        1  Experimental  cluster_1_r_naive_random
2    0.0  0.40040  0.48544        2  Experimental  cluster_1_r_naive_random
3    0.0  0.45875  0.51503        3  Experimental  cluster_1_r_naive_random
4    0.0  0.41726  0.49519        4  Experimental  cluster_1_r_naive_random
5    0.0  0.44176  0.50927        5  Experimental  cluster_1_r_naive_random
6    0.0  0.48987  0.54090        6  Experimental  cluster_1_r_naive_random
7    0.0  0.41316  0.48254        7  Experimental  cluster_1_r_naive_random
8    0.0  0.46617  0.51066        8  Experimental  cluster_1_r_naive_random
9    0.0  0.46825  0.52028        9  Experimental  cluster_1_r_naive_random
10   0.0  0.48273  0.53102       10  Experimental  cluster_1_r_naive_random
11   0.0  0.50258  0.53988       11  Experimental  cluster_1_r_naive_random
12   0.0  0.47373  0.50144       12  Experimental  cluster_1_r_naive_random
13   0.0  0.52057  0.54102       13  Experimental  cluster_1_r_naive_random
14   0.0  0.52823  0.55640       14  Experimental  cluster_1_r_naive_random
15   0.0  0.55802  0.57504       15  Experimental  cluster_1_r_naive_random
16   0.0  0.55641  0.57196       16  Experimental  cluster_1_r_naive_random
17   0.0  0.52928  0.54827       17  Experimental  cluster_1_r_naive_random
18   0.0  0.17163  0.27883       18  Experimental  cluster_1_r_naive_random
19   0.0  0.16883  0.28686       19  Experimental  cluster_1_r_naive_random
20   0.0  0.16341  0.27353       20  Experimental  cluster_1_r_naive_random
21   0.0  0.32309  0.41205       21  Experimental  cluster_1_r_naive_random
22   0.0  0.31355  0.39928       22  Experimental  cluster_1_r_naive_random
23   0.0  0.34392  0.42213       23  Experimental  cluster_1_r_naive_random
24   0.0  0.35604  0.35617       24  Experimental  cluster_1_r_naive_random
25   0.0  0.34105  0.35125       25  Experimental  cluster_1_r_naive_random
26   0.0  0.34135  0.38830       26  Experimental  cluster_1_r_naive_random
27   0.0  0.28512  0.29602       27  Experimental  cluster_1_r_naive_random
28   0.0  0.28439  0.33185       28  Experimental  cluster_1_r_naive_random
29   0.0  0.32954  0.39085       29  Experimental  cluster_1_r_naive_random
30   0.0  0.26192  0.34619       30  Experimental  cluster_1_r_naive_random
31   0.0  0.31421  0.37857       31  Experimental  cluster_1_r_naive_random
32   0.0  0.32314  0.38565       32  Experimental  cluster_1_r_naive_random
33   0.0  0.29666  0.37860       33  Experimental  cluster_1_r_naive_random
34   0.0  0.38440  0.44775       34  Experimental  cluster_1_r_naive_random
35   0.0  0.33633  0.46390       35  Experimental  cluster_1_r_naive_random
36   0.0  0.34716  0.45807       36  Experimental  cluster_1_r_naive_random
37   0.0  0.34165  0.44393       37  Experimental  cluster_1_r_naive_random
38   0.0  0.30725  0.43533       38  Experimental  cluster_1_r_naive_random
39   0.0  0.33252  0.48976       39  Experimental  cluster_1_r_naive_random
40   0.0  0.28369  0.42940       40  Experimental  cluster_1_r_naive_random
41   0.0  0.35906  0.50293       41  Experimental  cluster_1_r_naive_random
42   0.0  0.33575  0.45181       42  Experimental  cluster_1_r_naive_random
43   0.0  0.33443  0.43697       43  Experimental  cluster_1_r_naive_random
44   0.0  0.37082  0.47284       44  Experimental  cluster_1_r_naive_random
45   0.0  0.37847  0.48848       45  Experimental  cluster_1_r_naive_random
46   0.0  0.22218  0.31040       46  Experimental  cluster_1_r_naive_random
47   0.0  0.18217  0.28305       47  Experimental  cluster_1_r_naive_random
48   0.0  0.25719  0.37045       48  Experimental  cluster_1_r_naive_random
49   0.0  0.49756  0.50850       49  Experimental  cluster_1_r_naive_random
50   0.0  0.55024  0.54326       50  Experimental  cluster_1_r_naive_random
51   0.0  0.24310  0.29208       51  Experimental  cluster_1_r_naive_random
52   0.0  0.19173  0.23972       52  Experimental  cluster_1_r_naive_random
53   0.0  0.18105  0.23003       53  Experimental  cluster_1_r_naive_random
54   0.0  0.26140  0.30267       54  Experimental  cluster_1_r_naive_random
55   0.0  0.26392  0.30614       55  Experimental  cluster_1_r_naive_random
56   0.0  0.26061  0.32801       56  Experimental  cluster_1_r_naive_random
57   0.0  0.45297  0.53974       57  Experimental  cluster_1_r_naive_random
58   0.0  0.31622  0.45372       58  Experimental  cluster_1_r_naive_random
59   0.0  0.43711  0.52972       59  Experimental  cluster_1_r_naive_random
60   0.0  0.47628  0.54735       60  Experimental  cluster_1_r_naive_random
61   0.0  0.49249  0.57156       61  Experimental  cluster_1_r_naive_random
62   0.0  0.50341  0.53212       62  Experimental  cluster_1_r_naive_random
63   0.0  0.53500  0.53827       63  Experimental  cluster_1_r_naive_random
64   0.0  0.26524  0.35365       64  Experimental  cluster_1_r_naive_random
65   0.0  0.25454  0.32548       65  Experimental  cluster_1_r_naive_random
66   0.0  0.25152  0.35786       66  Experimental  cluster_1_r_naive_random
67   0.0  0.28164  0.36568       67  Experimental  cluster_1_r_naive_random
68   0.0  0.24177  0.30174       68  Experimental  cluster_1_r_naive_random
69   0.0  0.27969  0.36567       69  Experimental  cluster_1_r_naive_random
70   0.0  0.38633  0.44869       70  Experimental  cluster_1_r_naive_random
71   0.0  0.24871  0.31226       71  Experimental  cluster_1_r_naive_random
72   0.0  0.36820  0.37879       72  Experimental  cluster_1_r_naive_random
73   0.0  0.22903  0.26839       73  Experimental  cluster_1_r_naive_random
74   0.0  0.21687  0.25989       74  Experimental  cluster_1_r_naive_random
75   0.0  0.20479  0.23593       75  Experimental  cluster_1_r_naive_random
76   0.0  0.11684  0.15140       76  Experimental  cluster_1_r_naive_random
77   0.0  0.13267  0.18143       77  Experimental  cluster_1_r_naive_random
78   0.0  0.35203  0.42601       78  Experimental  cluster_1_r_naive_random
79   0.0  0.20249  0.21472       79  Experimental  cluster_1_r_naive_random
80   0.0  0.16260  0.17496       80  Experimental  cluster_1_r_naive_random
81   0.0  0.05688  0.07274       81  Experimental  cluster_1_r_naive_random
82   0.0  0.07600  0.11464       82  Experimental  cluster_1_r_naive_random
83   0.0  0.08147  0.13526       83  Experimental  cluster_1_r_naive_random
84   0.0  0.08527  0.13242       84  Experimental  cluster_1_r_naive_random
85   0.0  0.08569  0.14304       85  Experimental  cluster_1_r_naive_random
86   0.0  0.06291  0.07885       86  Experimental  cluster_1_r_naive_random
87   0.0  0.09393  0.16201       87  Experimental  cluster_1_r_naive_random
88   0.0  0.10385  0.19651       88  Experimental  cluster_1_r_naive_random
89   0.0  0.53877  0.49943       89  Experimental  cluster_1_r_naive_random
90   0.0  0.51417  0.47866       90  Experimental  cluster_1_r_naive_random
91   0.0  0.50107  0.49072       91  Experimental  cluster_1_r_naive_random
92   0.0  0.45551  0.47280       92  Experimental  cluster_1_r_naive_random
93   0.0  0.06500  0.10668       93  Experimental  cluster_1_r_naive_random
94   0.0  0.06362  0.10593       94  Experimental  cluster_1_r_naive_random
95   0.0  0.04358  0.04371       95  Experimental  cluster_1_r_naive_random
96   0.0  0.08151  0.10674       96  Experimental  cluster_1_r_naive_random
97   0.0  0.08795  0.11537       97  Experimental  cluster_1_r_naive_random
98   0.0  0.09261  0.12297       98  Experimental  cluster_1_r_naive_random
99   0.0  0.17298  0.20225       99  Experimental  cluster_1_r_naive_random
100  0.0  0.20729  0.23030      100  Experimental  cluster_1_r_naive_random
101  0.0  0.20401  0.23454      101  Experimental  cluster_1_r_naive_random
102  0.0  0.21943  0.23426      102  Experimental  cluster_1_r_naive_random
103  0.0  0.21731  0.24442      103  Experimental  cluster_1_r_naive_random
104  0.0  0.22028  0.25199      104  Experimental  cluster_1_r_naive_random
105  0.0  0.22217  0.24175      105  Experimental  cluster_1_r_naive_random
106  0.0  0.22454  0.24966      106  Experimental  cluster_1_r_naive_random
107  0.0  0.23913  0.27068      107  Experimental  cluster_1_r_naive_random

    split_type
0            r
1            r
2            r
3            r
4            r
5            r
6            r
7            r
8            r
9            r
10           r
11           r
12           r
13           r
14           r
15           r
16           r
17           r
18           r
19           r
20           r
21           r
22           r
23           r
24           r
25           r
26           r
27           r
28           r
29           r
30           r
31           r
32           r
33           r
34           r
35           r
36           r
37           r
38           r
39           r
40           r
41           r
42           r
43           r
44           r
45           r
46           r
47           r
48           r
49           r
50           r
51           r
52           r
53           r
54           r
55           r
56           r
57           r
58           r
59           r
60           r
61           r
62           r
63           r
64           r
65           r
66           r
67           r
68           r
69           r
70           r
71           r
72           r
73           r
74           r
75           r
76           r
77           r
78           r
79           r
80           r
81           r
82           r
83           r
84           r
85           r
86           r
87           r
88           r
89           r
90           r
91           r
92           r
93           r
94           r
95           r
96           r
97           r
98           r
99           r
100          r
101          r
102          r
103          r
104          r
105          r
106          r
107          r  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental
69   0.0  0.27969  0.36567       69       Experimental
70   0.0  0.38633  0.44869       70       Experimental
71   0.0  0.24871  0.31226       71       Experimental
72   0.0  0.36820  0.37879       72       Experimental
73   0.0  0.22903  0.26839       73       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/train_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00181818, 0.00181818, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/train_cluster_1_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00001  0.00009        0
1  0.0  0.09091  0.09091        1
2  0.0  0.07144  0.07151        2
3  0.0  0.05558  0.05581        3
4  0.0  0.10000  0.10000        4
Experimental cluster_1 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/val_cluster_1_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat
REWIGHTING val_cluster_1_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/val_cluster_1_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([0.5, 0.5, 3. , 1.5, 2. , 0.5, 1.5, 3. , 1. , 1.5, 1.5, 0.5, 0.5,
       0.5, 2. , 0.5, 1. , 1.5, 0.5, 0.5, 0.5, 1. , 1.5, 0.5, 1. , 0.5,
       1. , 1. , 1. , 0.5, 0.5, 1.5, 1.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 0.5, 0.5, 0.5, 3. , 1.5, 0.5, 0.5, 1. , 1.5, 0.5, 0.5,
       3. , 1. , 1.5, 0.5, 0.5, 5.5, 1. , 1.5, 2. , 0.5, 1. , 0.5, 1.5,
       1. , 1. , 2. , 0.5, 1.5, 1. , 0.5, 0.5, 1. , 1. , 1. , 0.5, 2. ,
       0.5, 2.5, 1.5, 1. , 0.5, 2.5, 1.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5,
       2. , 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 1.5, 0.5, 3.5, 1. ,
       1. , 0.5, 1. , 0.5, 1. , 1.5, 0.5, 1. , 1.5, 1. , 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 2. , 0.5, 2. ,
       2.5, 0.5, 2.5, 0.5, 2. , 3. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1. ,
       0.5, 1. , 0.5, 1.5, 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. ,
       2. , 1. , 1. , 1. , 2. , 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 1. , 2. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 1. , 0.5, 2.5, 2. ,
       1. , 1.5, 1.5, 0.5, 1. , 1. , 0.5, 1. , 2. , 0.5, 1. , 1. , 1. ,
       0.5, 0.5, 1. , 1.5, 1. , 1. , 0.5, 1. , 2. , 1. , 1. , 1.5, 1. ,
       1. , 1.5, 1.5, 0.5, 0.5, 2.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 2.5,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 0.5,
       1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5, 1.5, 0.5, 0.5, 2.5, 0.5, 0.5,
       0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 0.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 3. , 0.5, 0.5, 2.5,
       0.5, 1.5, 1. , 2.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 2. ,
       1. , 0.5, 1.5, 1.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 1. , 2. , 2.5,
       4. , 1. , 1. , 0.5, 0.5, 1. , 1. , 0.5, 3.5, 1. , 1. , 1.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 1. , 2. , 1.5, 2. , 1. , 4. , 3.5, 1. , 0.5,
       1. , 0.5, 1.5, 2.5, 0.5, 1. , 1. , 1.5, 0.5, 1.5, 0.5, 1. , 1. ,
       1. , 0.5, 0.5, 1. , 1. , 2.5, 1. , 1. , 0.5, 1.5, 1.5, 0.5, 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 1. , 2. , 0.5, 2. , 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 2. , 0.5, 1.5, 2.5, 2.5, 2.5, 1.5, 0.5, 1. , 1.5,
       0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 2. , 1. , 0.5, 0.5, 1. , 3.5,
       1. , 0.5, 0.5, 1. , 2. , 1. , 1. , 0.5, 3. , 0.5, 0.5, 0.5, 0.5,
       1.5, 1.5, 0.5, 1. , 1. , 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 1.5,
       2. , 1. , 0.5, 0.5, 0.5, 1. , 3. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 1.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 1.5, 1. , 1.5, 0.5, 0.5, 3.5, 0.5, 2. , 0.5, 0.5, 3. ,
       0.5, 0.5, 0.5, 0.5, 2. , 1.5, 0.5, 0.5, 1. , 1.5, 1.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5,
       1. , 2. , 0.5, 3. , 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. , 1. , 2.5, 1. , 0.5, 1. , 0.5,
       1. , 0.5, 1. , 1. , 0.5, 1.5, 1.5, 1. , 1. , 1. , 1. , 1. , 0.5,
       0.5, 0.5, 2. , 0.5]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential0/val_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
LogPf_by_res [35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
Pf_by_res [3.79601138e+15 2.58787960e+27 2.46018177e+17 1.99893642e+12
 3.49715508e+07 3.46468273e+13 5.41893666e+14 2.21488468e+11
 1.18581871e+12 1.12331646e+10 5.77638782e+01 5.65169568e+08
 2.26149345e+20 2.44085750e+21 9.79081853e+14 7.93471050e+19
 3.00768675e+06 3.25319450e+08 5.31764297e+13 5.19321558e+06
 2.53970143e+08 2.38766169e+15 3.38116006e+22 3.54592556e+28
 1.82191469e+12 7.41839339e+17 2.15381810e+26 3.69558767e+24
 4.24345339e+18 1.04106170e+18 3.54640532e+20 1.03580533e+23
 8.13372987e+19 2.02796394e+29 2.05192002e+24 6.07584048e+16
 1.64428047e+13 1.18213288e+16 4.22526265e+14 2.23410907e+12
 4.91756476e+07 9.04376536e+13 1.17029810e+21 1.40534351e+25
 4.52831762e+29 1.96856112e+13 2.23385400e+08 3.06498228e+15
 1.63438904e+15 4.44648623e+04 1.50831820e+07 3.08522876e+06
 2.90199841e+14 7.98449131e+08 1.67917367e+05 8.58892058e+11
 3.50958363e+23 1.65647157e+17 7.25878147e+13 1.13248150e+16
 3.12028376e+26 4.52537452e+11 3.99419685e+12 1.84896857e+22
 2.11166954e+12 9.46002036e+05 1.32061676e+17 5.25738508e+23
 2.80387433e+16 1.82313808e+18 1.52827491e+24 1.87923891e+24
 9.43110983e+18 4.05645635e+22 3.20764507e+22 4.30347515e+18
 6.96118286e+21 2.28701362e+19 8.00926402e+17 2.18627988e+19
 1.34375553e+18 1.63065029e+12 8.81120616e+12 1.11738961e+07
 1.29274793e+23 2.20158868e+23 4.38415249e+15 3.00709717e+27
 2.56171806e+15 5.34584303e+08 1.84001514e+08 2.61272514e+13
 1.17621086e+20 1.16935206e+07 9.31811506e+01 1.71232668e+06
 6.70347337e+06 1.07030028e+13 1.04663735e+22 1.50296023e+36
 6.36782840e+21 2.39403693e+28 4.78814587e+09 2.08655151e+10
 6.22306931e+14 2.57409067e+15 2.17231262e+19 4.96423683e+29
 8.80808228e+37 3.43436840e+26 3.08952860e+11 1.26533474e+11
 4.40495226e+16 1.29376092e+17 5.80393404e+14 1.24977372e+17
 1.35373276e+16 1.97824660e+05 9.75671357e+08 8.74096566e+27
 7.68752491e+17 8.90258288e+04 6.59366561e+11 1.21828613e+14
 2.33010013e+16 7.60415284e+10 1.50005556e+16 5.23535983e+28
 1.85821495e+20 4.51351705e+21 2.09579824e+20 2.43778128e+23
 6.10418220e+19 4.22574509e+18 7.32649630e+23 6.78503101e+22
 1.65915365e+06 1.28636490e+16 5.74005232e+18 8.92416926e+14
 3.56650898e+15 4.90314785e+18 9.25045125e+14 1.93621539e+17
 1.67395616e+17 3.29163115e+19 1.14222711e+20 2.35543072e+15
 9.32173096e+13 5.73297869e+17 9.47596414e+21 4.89908610e+24
 5.00185965e+22 5.81328884e+33 1.65760923e+10 1.32761242e+11
 7.88271458e+14 3.15676448e+16 4.58526700e+13 8.59937721e+17
 4.64083261e+13 3.82895936e+16 1.60558876e+14 2.95976369e+11
 1.39866544e+11 5.10852220e+08 5.10942139e+07 7.65239387e+11
 2.45270080e+17 1.42519814e+30 2.61375140e+18 7.70415332e+29
 1.43444884e+17 7.10692594e+12 1.41233702e+11 3.47627914e+17
 6.25074974e+19 2.85232306e+23 4.94096859e+34 2.94800922e+38
 2.50723436e+31 7.40020694e+17 5.42719742e+18 6.77262701e+20
 9.46197081e+17 1.47913387e+16 6.83358490e+21 1.70734451e+13
 4.13477713e+12 1.18495099e+19 3.22714485e+09 6.80656032e+04
 6.52053674e+16 2.86059338e+05 5.51613303e+07 9.08976513e+10
 8.09756968e+11 3.32971920e+12 2.11625723e+10 7.88338537e+13
 7.00283113e+15 3.87738401e+12 2.49359041e+15 9.43952276e+15
 4.02461272e+19 2.42423220e+26 4.19479132e+20 3.79137754e+16
 8.20772357e+13 1.19503253e+22 4.95329702e+17 1.90742423e+28
 1.10895500e+25 6.94763061e+22 3.18044356e+27 1.29251291e+23
 5.26015610e+12 2.67933812e+12 2.44914744e+10 2.00908250e+15
 1.12263982e+08 1.41275361e+07 6.76607935e+10 1.46725571e+13
 4.69811189e+12 2.47005126e+02 3.20348380e+02 2.04617678e+11
 9.68534747e+04 2.07947233e+04 1.08649359e+08 7.98784270e+02
 3.95798146e+09 7.90402087e+17 1.57528401e+28 3.80143040e+18
 2.63271012e+18 4.66611186e+17 1.52209597e+23 1.38898167e+20
 1.13876042e+21 5.22079177e+10 9.86211196e+11 5.64153370e+19
 2.85018615e+27 2.43823874e+24 7.69080464e+20 9.87878027e+20
 2.91128374e+24 3.55439562e+24 1.83107034e+22 1.43467784e+21
 4.39957981e+25 2.10052023e+24 6.66372176e+15 6.03582153e+13
 1.87180915e+15 3.84068273e+18 2.80283862e+15 1.26639389e+22
 1.71169601e+13 2.79250557e+13 3.12729243e+21 6.62397471e+18
 3.26970688e+11 4.20632067e+23 4.70509236e+25 2.32666422e+28
 5.86399999e+18 1.20102137e+14 3.35450052e+13 5.27695030e+13
 1.12513115e+14 1.20309065e+13 7.84312567e+08 8.25346157e+15
 1.94891484e+00 6.13357970e+01 2.61324301e+08 6.57103438e+06
 8.21192398e+15 1.50944514e+26 3.50243264e+24 1.00156045e+18
 2.19425722e+20 2.11480706e+25 2.05713778e+23 1.08301289e+19
 1.29685269e+21]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  2970.25801533   664.95794074  5926.44387531
  3332.68430264   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  6649.57939778  1962.4300073
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
  9392.7805534   4393.33353926   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.08010673e-11 1.44494098e-24 1.82737206e-14 1.26472236e-10
 1.09415610e-04 1.21096253e-10 1.34548885e-12 4.44061434e-09
 2.81045011e-10 5.15575245e-08 9.35702591e+01 5.63138744e-06
 9.08654626e-18 7.67806441e-19 2.05104494e-12 4.20013348e-18
 2.21086169e-04 1.44705203e-05 1.98186926e-10 6.71982285e-04
 1.47235153e-05 1.60258615e-12 1.10593206e-20 8.77131205e-26
 5.03809270e-10 4.70418418e-15 1.20111656e-23 4.73271842e-22
 5.68950836e-16 1.53220794e-15 2.83795698e-18 1.19540766e-20
 4.59731679e-18 3.67903525e-27 1.62417847e-22 1.17270240e-14
 7.88530105e-11 6.92034716e-14 3.14007822e-12 1.45777268e-10
 1.29135036e-05 2.79540600e-11 6.99033001e-19 2.31745699e-23
 8.45001139e-27 3.70378078e-11 2.36450039e-05 1.36888262e-12
 1.37860146e-12 2.06432104e-02 1.45982641e-05 2.15529542e-04
 8.71158159e-12 1.31991816e-06 4.24324945e-03 2.68445167e-09
 1.50500721e-21 1.24053834e-15 2.52307671e-11 1.19884507e-13
 3.01023282e-24 3.60694607e-09 5.26459191e-10 3.59637233e-20
 2.87189278e-10 9.70291263e-04 6.33895082e-15 1.29426852e-21
 5.07032307e-14 1.82799337e-16 2.94166149e-22 6.14910885e-22
 1.69134177e-16 3.75532362e-20 1.36964454e-20 1.54516505e-16
 2.23929409e-19 3.66037373e-17 4.66876020e-16 1.10430343e-17
 5.68164262e-16 1.20346467e-09 3.00440736e-10 5.95099449e-05
 7.43498889e-21 1.73803290e-21 6.93279769e-14 1.36347354e-24
 1.75494232e-12 2.72130973e-06 4.54959543e-05 4.03367081e-10
 1.23682709e-17 9.43732453e-05 1.15735371e+01 9.53251620e-04
 1.53636459e-04 4.93501568e-11 5.79425959e-20 5.96824568e-34
 1.69356872e-19 3.49673991e-25 1.74834366e-07 4.01203826e-07
 5.73838309e-12 7.80136031e-13 7.86813586e-17 2.32777867e-27
 6.88514059e-35 2.61184438e-24 3.57192192e-09 6.92769476e-08
 9.30792703e-14 1.55217308e-14 4.15979288e-12 6.25119129e-15
 5.63976797e-14 3.51976565e-03 1.05557871e-06 1.82488190e-25
 2.73531685e-15 2.20433781e-02 3.41717530e-09 4.04617698e-11
 4.52292715e-13 4.58926714e-08 7.52812586e-14 9.20126727e-27
 8.98872775e-18 1.37492525e-18 4.91410809e-18 3.67959007e-21
 3.28977873e-17 4.86285007e-16 6.88490325e-21 4.91181888e-20
 3.41120303e-04 3.74481184e-14 2.84366429e-16 2.25022724e-12
 4.07897322e-13 3.82225086e-16 5.32882256e-13 4.03497187e-15
 7.39690595e-15 2.66307264e-17 3.27372138e-18 3.80823590e-13
 1.67223617e-11 4.83519339e-15 2.60717851e-19 7.12326507e-23
 1.87785771e-20 5.10942789e-31 4.01154825e-08 4.46398645e-08
 4.22783835e-12 3.04475250e-14 7.43754398e-11 1.57880021e-15
 3.06336166e-11 8.70389056e-15 4.86586281e-12 5.14679817e-09
 1.40307321e-08 3.42372514e-06 1.52905270e-04 5.74112313e-09
 5.28627321e-15 7.06185720e-28 4.42109552e-16 9.46388074e-27
 2.66752877e-14 3.24423560e-10 5.92728530e-08 1.55481790e-14
 2.67215758e-17 7.04036967e-21 2.33874075e-32 2.05714705e-35
 4.20338572e-28 3.18823490e-15 1.22523264e-15 2.89759056e-18
 4.64314848e-15 1.78972661e-13 1.06695372e-19 3.02324270e-10
 5.83904833e-10 5.87616237e-16 1.75378244e-07 3.31029332e-02
 1.44049193e-13 1.53581196e-02 7.60605472e-06 9.20961583e-09
 1.88121955e-09 1.17594380e-09 3.14214138e-08 7.87193360e-12
 2.33088326e-13 3.83932931e-10 5.57146053e-13 9.28633055e-14
 6.57763976e-17 1.43952749e-23 2.81892691e-18 1.18576095e-14
 9.51856446e-12 3.12906402e-20 1.89626839e-15 4.70269575e-26
 1.65150637e-22 6.32349904e-21 6.46110034e-26 6.93999707e-21
 4.80613039e-10 9.65531961e-10 3.34025210e-07 2.62903523e-13
 7.99012796e-06 6.64856244e-05 6.64442019e-08 1.53563629e-10
 3.31795751e-10 2.95180872e+00 3.69123458e+00 9.15906257e-09
 1.57281981e-02 1.01120924e-01 2.32684262e-06 8.51853032e-01
 4.41896358e-07 2.21282006e-15 4.95947051e-25 1.42182823e-15
 1.59364334e-16 3.66301782e-16 3.80497790e-21 7.41476964e-18
 1.60828056e-18 2.48346363e-08 1.81478112e-10 1.78400880e-17
 3.29549724e-25 5.31762796e-22 1.68586345e-18 4.87630492e-19
 1.28442764e-22 4.38559389e-23 1.17513875e-19 4.63489380e-19
 3.30661002e-24 1.09765866e-21 3.97262272e-13 1.66746908e-11
 2.19044630e-12 1.73135348e-16 3.50910287e-13 5.75738630e-20
 6.30039150e-11 1.89147292e-11 1.34160814e-19 1.66600197e-16
 5.47375508e-10 4.77410315e-21 2.29206022e-23 6.69977880e-26

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_1_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_s_naive_sequential/20240402-191522_analysis.csv
dict_keys(['cluster_1_s_naive_sequential'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_s_naive_sequential to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_1_s_naive_sequential/cluster_1_s_naive_sequential0_1712081722.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_1_s_naive_sequential': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00001  0.00009        0  train_cluster_1_1
1   0.0  0.09091  0.09091        1  train_cluster_1_1
2   0.0  0.07144  0.07151        2  train_cluster_1_1
3   0.0  0.05558  0.05581        3  train_cluster_1_1
4   0.0  0.10000  0.10000        4  train_cluster_1_1
5   0.0  0.07693  0.07701        5  train_cluster_1_1
6   0.0  0.05885  0.05909        6  train_cluster_1_1
7   0.0  0.11111  0.11111        7  train_cluster_1_1
8   0.0  0.09092  0.09102        8  train_cluster_1_1
9   0.0  0.08334  0.08343        9  train_cluster_1_1
10  0.0  0.06670  0.06697       10  train_cluster_1_1
11  0.0  0.06253  0.06279       11  train_cluster_1_1
12  0.0  0.14286  0.14286       12  train_cluster_1_1
13  0.0  0.11112  0.11124       13  train_cluster_1_1
14  0.0  0.10001  0.10012       14  train_cluster_1_1
15  0.0  0.08337  0.08371       15  train_cluster_1_1
16  0.0  0.07146  0.07175       16  train_cluster_1_1
17  0.0  0.00006  0.00058       17  train_cluster_1_1
18  0.0  0.00000  0.00000       18  train_cluster_1_1
19  0.0  0.00000  0.00000       19  train_cluster_1_1
20  0.0  0.00000  0.00000       20  train_cluster_1_1
21  0.0  0.00000  0.00000       21  train_cluster_1_1
22  0.0  0.00000  0.00000       22  train_cluster_1_1
23  0.0  0.00000  0.00000       23  train_cluster_1_1
24  0.0  0.00000  0.00001       24  train_cluster_1_1
25  0.0  0.00000  0.00001       25  train_cluster_1_1
26  0.0  0.00000  0.00002       26  train_cluster_1_1
27  0.0  0.00000  0.00001       27  train_cluster_1_1
28  0.0  0.00000  0.00002       28  train_cluster_1_1
29  0.0  0.00056  0.00541       29  train_cluster_1_1
30  0.0  0.00107  0.01031       30  train_cluster_1_1
31  0.0  0.00079  0.00756       31  train_cluster_1_1
32  0.0  0.00084  0.00810       32  train_cluster_1_1
33  0.0  0.00147  0.01417       33  train_cluster_1_1
34  0.0  0.00098  0.00944       34  train_cluster_1_1
35  0.0  0.00005  0.00054       35  train_cluster_1_1
36  0.0  0.00007  0.00069       36  train_cluster_1_1
37  0.0  0.00008  0.00081       37  train_cluster_1_1
38  0.0  0.00007  0.00069       38  train_cluster_1_1
39  0.0  0.00005  0.00054       39  train_cluster_1_1
40  0.0  0.00005  0.00048       40  train_cluster_1_1
41  0.0  0.00003  0.00025       41  train_cluster_1_1
42  0.0  0.00000  0.00000       42  train_cluster_1_1
43  0.0  0.00000  0.00000       43  train_cluster_1_1
44  0.0  0.00000  0.00000       44  train_cluster_1_1
45  0.0  0.00000  0.00000       45  train_cluster_1_1
46  0.0  0.00000  0.00003       46  train_cluster_1_1
47  0.0  0.00001  0.00006       47  train_cluster_1_1
48  0.0  0.00000  0.00004       48  train_cluster_1_1
49  0.0  0.14248  0.14363       49  train_cluster_1_1
50  0.0  0.00009  0.00090       50  train_cluster_1_1
51  0.0  0.00000  0.00000       51  train_cluster_1_1
52  0.0  0.00000  0.00000       52  train_cluster_1_1
53  0.0  0.00000  0.00000       53  train_cluster_1_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00075  0.00715       54  val_cluster_1_1
1   0.0  0.00071  0.00675       55  val_cluster_1_1
2   0.0  0.00060  0.00579       56  val_cluster_1_1
3   0.0  0.00001  0.00007       57  val_cluster_1_1
4   0.0  0.00001  0.00012       58  val_cluster_1_1
5   0.0  0.00001  0.00008       59  val_cluster_1_1
6   0.0  0.00001  0.00007       60  val_cluster_1_1
7   0.0  0.00001  0.00007       61  val_cluster_1_1
8   0.0  0.00001  0.00009       62  val_cluster_1_1
9   0.0  0.00001  0.00010       63  val_cluster_1_1
10  0.0  0.00000  0.00000       64  val_cluster_1_1
11  0.0  0.00000  0.00000       65  val_cluster_1_1
12  0.0  0.00000  0.00000       66  val_cluster_1_1
13  0.0  0.00000  0.00000       67  val_cluster_1_1
14  0.0  0.00000  0.00000       68  val_cluster_1_1
15  0.0  0.00000  0.00000       69  val_cluster_1_1
16  0.0  0.00001  0.00007       70  val_cluster_1_1
17  0.0  0.00000  0.00003       71  val_cluster_1_1
18  0.0  0.00001  0.00009       72  val_cluster_1_1
19  0.0  0.00000  0.00004       73  val_cluster_1_1
20  0.0  0.00000  0.00003       74  val_cluster_1_1
21  0.0  0.00000  0.00004       75  val_cluster_1_1
22  0.0  0.00000  0.00000       76  val_cluster_1_1
23  0.0  0.00000  0.00000       77  val_cluster_1_1
24  0.0  0.00291  0.02741       78  val_cluster_1_1
25  0.0  0.00000  0.00000       79  val_cluster_1_1
26  0.0  0.00000  0.00000       80  val_cluster_1_1
27  0.0  0.00000  0.00004       81  val_cluster_1_1
28  0.0  0.00000  0.00003       82  val_cluster_1_1
29  0.0  0.00000  0.00003       83  val_cluster_1_1
30  0.0  0.00000  0.00003       84  val_cluster_1_1
31  0.0  0.00000  0.00003       85  val_cluster_1_1
32  0.0  0.00001  0.00005       86  val_cluster_1_1
33  0.0  0.00000  0.00004       87  val_cluster_1_1
34  0.0  0.00001  0.00005       88  val_cluster_1_1
35  0.0  0.16216  0.28406       89  val_cluster_1_1
36  0.0  0.14968  0.26221       90  val_cluster_1_1
37  0.0  0.12972  0.22725       91  val_cluster_1_1
38  0.0  0.10810  0.18937       92  val_cluster_1_1
39  0.0  0.00000  0.00000       93  val_cluster_1_1
40  0.0  0.00000  0.00000       94  val_cluster_1_1
41  0.0  0.00000  0.00000       95  val_cluster_1_1
42  0.0  0.00000  0.00000       96  val_cluster_1_1
43  0.0  0.00000  0.00000       97  val_cluster_1_1
44  0.0  0.00000  0.00000       98  val_cluster_1_1
45  0.0  0.10526  0.10531       99  val_cluster_1_1
46  0.0  0.11111  0.11116      100  val_cluster_1_1
47  0.0  0.10526  0.10531      101  val_cluster_1_1
48  0.0  0.12500  0.12506      102  val_cluster_1_1
49  0.0  0.11765  0.11770      103  val_cluster_1_1
50  0.0  0.10000  0.10004      104  val_cluster_1_1
51  0.0  0.13333  0.13339      105  val_cluster_1_1
52  0.0  0.11111  0.11116      106  val_cluster_1_1
53  0.0  0.11765  0.11770      107  val_cluster_1_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                             name split_type
0    cluster_1_s_naive_sequential          s
1    cluster_1_s_naive_sequential          s
2    cluster_1_s_naive_sequential          s
3    cluster_1_s_naive_sequential          s
4    cluster_1_s_naive_sequential          s
5    cluster_1_s_naive_sequential          s
6    cluster_1_s_naive_sequential          s
7    cluster_1_s_naive_sequential          s
8    cluster_1_s_naive_sequential          s
9    cluster_1_s_naive_sequential          s
10   cluster_1_s_naive_sequential          s
11   cluster_1_s_naive_sequential          s
12   cluster_1_s_naive_sequential          s
13   cluster_1_s_naive_sequential          s
14   cluster_1_s_naive_sequential          s
15   cluster_1_s_naive_sequential          s
16   cluster_1_s_naive_sequential          s
17   cluster_1_s_naive_sequential          s
18   cluster_1_s_naive_sequential          s
19   cluster_1_s_naive_sequential          s
20   cluster_1_s_naive_sequential          s
21   cluster_1_s_naive_sequential          s
22   cluster_1_s_naive_sequential          s
23   cluster_1_s_naive_sequential          s
24   cluster_1_s_naive_sequential          s
25   cluster_1_s_naive_sequential          s
26   cluster_1_s_naive_sequential          s
27   cluster_1_s_naive_sequential          s
28   cluster_1_s_naive_sequential          s
29   cluster_1_s_naive_sequential          s
30   cluster_1_s_naive_sequential          s
31   cluster_1_s_naive_sequential          s
32   cluster_1_s_naive_sequential          s
33   cluster_1_s_naive_sequential          s
34   cluster_1_s_naive_sequential          s
35   cluster_1_s_naive_sequential          s
36   cluster_1_s_naive_sequential          s
37   cluster_1_s_naive_sequential          s
38   cluster_1_s_naive_sequential          s
39   cluster_1_s_naive_sequential          s
40   cluster_1_s_naive_sequential          s
41   cluster_1_s_naive_sequential          s
42   cluster_1_s_naive_sequential          s
43   cluster_1_s_naive_sequential          s
44   cluster_1_s_naive_sequential          s
45   cluster_1_s_naive_sequential          s
46   cluster_1_s_naive_sequential          s
47   cluster_1_s_naive_sequential          s
48   cluster_1_s_naive_sequential          s
49   cluster_1_s_naive_sequential          s
50   cluster_1_s_naive_sequential          s
51   cluster_1_s_naive_sequential          s
52   cluster_1_s_naive_sequential          s
53   cluster_1_s_naive_sequential          s
54   cluster_1_s_naive_sequential          s
55   cluster_1_s_naive_sequential          s
56   cluster_1_s_naive_sequential          s
57   cluster_1_s_naive_sequential          s
58   cluster_1_s_naive_sequential          s
59   cluster_1_s_naive_sequential          s
60   cluster_1_s_naive_sequential          s
61   cluster_1_s_naive_sequential          s
62   cluster_1_s_naive_sequential          s
63   cluster_1_s_naive_sequential          s
64   cluster_1_s_naive_sequential          s
65   cluster_1_s_naive_sequential          s
66   cluster_1_s_naive_sequential          s
67   cluster_1_s_naive_sequential          s
68   cluster_1_s_naive_sequential          s
69   cluster_1_s_naive_sequential          s
70   cluster_1_s_naive_sequential          s
71   cluster_1_s_naive_sequential          s
72   cluster_1_s_naive_sequential          s
73   cluster_1_s_naive_sequential          s
74   cluster_1_s_naive_sequential          s
75   cluster_1_s_naive_sequential          s
76   cluster_1_s_naive_sequential          s
77   cluster_1_s_naive_sequential          s
78   cluster_1_s_naive_sequential          s
79   cluster_1_s_naive_sequential          s
80   cluster_1_s_naive_sequential          s
81   cluster_1_s_naive_sequential          s
82   cluster_1_s_naive_sequential          s
83   cluster_1_s_naive_sequential          s
84   cluster_1_s_naive_sequential          s
85   cluster_1_s_naive_sequential          s
86   cluster_1_s_naive_sequential          s
87   cluster_1_s_naive_sequential          s
88   cluster_1_s_naive_sequential          s
89   cluster_1_s_naive_sequential          s
90   cluster_1_s_naive_sequential          s
91   cluster_1_s_naive_sequential          s
92   cluster_1_s_naive_sequential          s
93   cluster_1_s_naive_sequential          s
94   cluster_1_s_naive_sequential          s
95   cluster_1_s_naive_sequential          s
96   cluster_1_s_naive_sequential          s
97   cluster_1_s_naive_sequential          s
98   cluster_1_s_naive_sequential          s
99   cluster_1_s_naive_sequential          s
100  cluster_1_s_naive_sequential          s
101  cluster_1_s_naive_sequential          s
102  cluster_1_s_naive_sequential          s
103  cluster_1_s_naive_sequential          s
104  cluster_1_s_naive_sequential          s
105  cluster_1_s_naive_sequential          s
106  cluster_1_s_naive_sequential          s
107  cluster_1_s_naive_sequential          s  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/train_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00181818, 0.00181818, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/train_cluster_1_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(46, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00005  0.00054        0
1  0.0  0.00007  0.00069        1
2  0.0  0.00008  0.00081        2
3  0.0  0.00007  0.00069        3
4  0.0  0.00005  0.00054        4
Experimental cluster_1 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/val_cluster_1_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat
REWIGHTING val_cluster_1_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/val_cluster_1_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([0.5, 0.5, 3. , 1.5, 2. , 0.5, 1.5, 3. , 1. , 1.5, 1.5, 0.5, 0.5,
       0.5, 2. , 0.5, 1. , 1.5, 0.5, 0.5, 0.5, 1. , 1.5, 0.5, 1. , 0.5,
       1. , 1. , 1. , 0.5, 0.5, 1.5, 1.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 0.5, 0.5, 0.5, 3. , 1.5, 0.5, 0.5, 1. , 1.5, 0.5, 0.5,
       3. , 1. , 1.5, 0.5, 0.5, 5.5, 1. , 1.5, 2. , 0.5, 1. , 0.5, 1.5,
       1. , 1. , 2. , 0.5, 1.5, 1. , 0.5, 0.5, 1. , 1. , 1. , 0.5, 2. ,
       0.5, 2.5, 1.5, 1. , 0.5, 2.5, 1.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5,
       2. , 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 1.5, 0.5, 3.5, 1. ,
       1. , 0.5, 1. , 0.5, 1. , 1.5, 0.5, 1. , 1.5, 1. , 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 2. , 0.5, 2. ,
       2.5, 0.5, 2.5, 0.5, 2. , 3. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1. ,
       0.5, 1. , 0.5, 1.5, 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. ,
       2. , 1. , 1. , 1. , 2. , 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 1. , 2. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 1. , 0.5, 2.5, 2. ,
       1. , 1.5, 1.5, 0.5, 1. , 1. , 0.5, 1. , 2. , 0.5, 1. , 1. , 1. ,
       0.5, 0.5, 1. , 1.5, 1. , 1. , 0.5, 1. , 2. , 1. , 1. , 1.5, 1. ,
       1. , 1.5, 1.5, 0.5, 0.5, 2.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 2.5,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 0.5,
       1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5, 1.5, 0.5, 0.5, 2.5, 0.5, 0.5,
       0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 0.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 3. , 0.5, 0.5, 2.5,
       0.5, 1.5, 1. , 2.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 2. ,
       1. , 0.5, 1.5, 1.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 1. , 2. , 2.5,
       4. , 1. , 1. , 0.5, 0.5, 1. , 1. , 0.5, 3.5, 1. , 1. , 1.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 1. , 2. , 1.5, 2. , 1. , 4. , 3.5, 1. , 0.5,
       1. , 0.5, 1.5, 2.5, 0.5, 1. , 1. , 1.5, 0.5, 1.5, 0.5, 1. , 1. ,
       1. , 0.5, 0.5, 1. , 1. , 2.5, 1. , 1. , 0.5, 1.5, 1.5, 0.5, 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 1. , 2. , 0.5, 2. , 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 2. , 0.5, 1.5, 2.5, 2.5, 2.5, 1.5, 0.5, 1. , 1.5,
       0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 2. , 1. , 0.5, 0.5, 1. , 3.5,
       1. , 0.5, 0.5, 1. , 2. , 1. , 1. , 0.5, 3. , 0.5, 0.5, 0.5, 0.5,
       1.5, 1.5, 0.5, 1. , 1. , 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 1.5,
       2. , 1. , 0.5, 0.5, 0.5, 1. , 3. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 1.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 1.5, 1. , 1.5, 0.5, 0.5, 3.5, 0.5, 2. , 0.5, 0.5, 3. ,
       0.5, 0.5, 0.5, 0.5, 2. , 1.5, 0.5, 0.5, 1. , 1.5, 1.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5,
       1. , 2. , 0.5, 3. , 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. , 1. , 2.5, 1. , 0.5, 1. , 0.5,
       1. , 0.5, 1. , 1. , 0.5, 1.5, 1.5, 1. , 1. , 1. , 1. , 1. , 0.5,
       0.5, 0.5, 2. , 0.5]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence0/val_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
LogPf_by_res [35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
Pf_by_res [3.79601138e+15 2.58787960e+27 2.46018177e+17 1.99893642e+12
 3.49715508e+07 3.46468273e+13 5.41893666e+14 2.21488468e+11
 1.18581871e+12 1.12331646e+10 5.77638782e+01 5.65169568e+08
 2.26149345e+20 2.44085750e+21 9.79081853e+14 7.93471050e+19
 3.00768675e+06 3.25319450e+08 5.31764297e+13 5.19321558e+06
 2.53970143e+08 2.38766169e+15 3.38116006e+22 3.54592556e+28
 1.82191469e+12 7.41839339e+17 2.15381810e+26 3.69558767e+24
 4.24345339e+18 1.04106170e+18 3.54640532e+20 1.03580533e+23
 8.13372987e+19 2.02796394e+29 2.05192002e+24 6.07584048e+16
 1.64428047e+13 1.18213288e+16 4.22526265e+14 2.23410907e+12
 4.91756476e+07 9.04376536e+13 1.17029810e+21 1.40534351e+25
 4.52831762e+29 1.96856112e+13 2.23385400e+08 3.06498228e+15
 1.63438904e+15 4.44648623e+04 1.50831820e+07 3.08522876e+06
 2.90199841e+14 7.98449131e+08 1.67917367e+05 8.58892058e+11
 3.50958363e+23 1.65647157e+17 7.25878147e+13 1.13248150e+16
 3.12028376e+26 4.52537452e+11 3.99419685e+12 1.84896857e+22
 2.11166954e+12 9.46002036e+05 1.32061676e+17 5.25738508e+23
 2.80387433e+16 1.82313808e+18 1.52827491e+24 1.87923891e+24
 9.43110983e+18 4.05645635e+22 3.20764507e+22 4.30347515e+18
 6.96118286e+21 2.28701362e+19 8.00926402e+17 2.18627988e+19
 1.34375553e+18 1.63065029e+12 8.81120616e+12 1.11738961e+07
 1.29274793e+23 2.20158868e+23 4.38415249e+15 3.00709717e+27
 2.56171806e+15 5.34584303e+08 1.84001514e+08 2.61272514e+13
 1.17621086e+20 1.16935206e+07 9.31811506e+01 1.71232668e+06
 6.70347337e+06 1.07030028e+13 1.04663735e+22 1.50296023e+36
 6.36782840e+21 2.39403693e+28 4.78814587e+09 2.08655151e+10
 6.22306931e+14 2.57409067e+15 2.17231262e+19 4.96423683e+29
 8.80808228e+37 3.43436840e+26 3.08952860e+11 1.26533474e+11
 4.40495226e+16 1.29376092e+17 5.80393404e+14 1.24977372e+17
 1.35373276e+16 1.97824660e+05 9.75671357e+08 8.74096566e+27
 7.68752491e+17 8.90258288e+04 6.59366561e+11 1.21828613e+14
 2.33010013e+16 7.60415284e+10 1.50005556e+16 5.23535983e+28
 1.85821495e+20 4.51351705e+21 2.09579824e+20 2.43778128e+23
 6.10418220e+19 4.22574509e+18 7.32649630e+23 6.78503101e+22
 1.65915365e+06 1.28636490e+16 5.74005232e+18 8.92416926e+14
 3.56650898e+15 4.90314785e+18 9.25045125e+14 1.93621539e+17
 1.67395616e+17 3.29163115e+19 1.14222711e+20 2.35543072e+15
 9.32173096e+13 5.73297869e+17 9.47596414e+21 4.89908610e+24
 5.00185965e+22 5.81328884e+33 1.65760923e+10 1.32761242e+11
 7.88271458e+14 3.15676448e+16 4.58526700e+13 8.59937721e+17
 4.64083261e+13 3.82895936e+16 1.60558876e+14 2.95976369e+11
 1.39866544e+11 5.10852220e+08 5.10942139e+07 7.65239387e+11
 2.45270080e+17 1.42519814e+30 2.61375140e+18 7.70415332e+29
 1.43444884e+17 7.10692594e+12 1.41233702e+11 3.47627914e+17
 6.25074974e+19 2.85232306e+23 4.94096859e+34 2.94800922e+38
 2.50723436e+31 7.40020694e+17 5.42719742e+18 6.77262701e+20
 9.46197081e+17 1.47913387e+16 6.83358490e+21 1.70734451e+13
 4.13477713e+12 1.18495099e+19 3.22714485e+09 6.80656032e+04
 6.52053674e+16 2.86059338e+05 5.51613303e+07 9.08976513e+10
 8.09756968e+11 3.32971920e+12 2.11625723e+10 7.88338537e+13
 7.00283113e+15 3.87738401e+12 2.49359041e+15 9.43952276e+15
 4.02461272e+19 2.42423220e+26 4.19479132e+20 3.79137754e+16
 8.20772357e+13 1.19503253e+22 4.95329702e+17 1.90742423e+28
 1.10895500e+25 6.94763061e+22 3.18044356e+27 1.29251291e+23
 5.26015610e+12 2.67933812e+12 2.44914744e+10 2.00908250e+15
 1.12263982e+08 1.41275361e+07 6.76607935e+10 1.46725571e+13
 4.69811189e+12 2.47005126e+02 3.20348380e+02 2.04617678e+11
 9.68534747e+04 2.07947233e+04 1.08649359e+08 7.98784270e+02
 3.95798146e+09 7.90402087e+17 1.57528401e+28 3.80143040e+18
 2.63271012e+18 4.66611186e+17 1.52209597e+23 1.38898167e+20
 1.13876042e+21 5.22079177e+10 9.86211196e+11 5.64153370e+19
 2.85018615e+27 2.43823874e+24 7.69080464e+20 9.87878027e+20
 2.91128374e+24 3.55439562e+24 1.83107034e+22 1.43467784e+21
 4.39957981e+25 2.10052023e+24 6.66372176e+15 6.03582153e+13
 1.87180915e+15 3.84068273e+18 2.80283862e+15 1.26639389e+22
 1.71169601e+13 2.79250557e+13 3.12729243e+21 6.62397471e+18
 3.26970688e+11 4.20632067e+23 4.70509236e+25 2.32666422e+28
 5.86399999e+18 1.20102137e+14 3.35450052e+13 5.27695030e+13
 1.12513115e+14 1.20309065e+13 7.84312567e+08 8.25346157e+15
 1.94891484e+00 6.13357970e+01 2.61324301e+08 6.57103438e+06
 8.21192398e+15 1.50944514e+26 3.50243264e+24 1.00156045e+18
 2.19425722e+20 2.11480706e+25 2.05713778e+23 1.08301289e+19
 1.29685269e+21]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  2970.25801533   664.95794074  5926.44387531
  3332.68430264   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  6649.57939778  1962.4300073
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
  9392.7805534   4393.33353926   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.08010673e-11 1.44494098e-24 1.82737206e-14 1.26472236e-10
 1.09415610e-04 1.21096253e-10 1.34548885e-12 4.44061434e-09
 2.81045011e-10 5.15575245e-08 9.35702591e+01 5.63138744e-06
 9.08654626e-18 7.67806441e-19 2.05104494e-12 4.20013348e-18
 2.21086169e-04 1.44705203e-05 1.98186926e-10 6.71982285e-04
 1.47235153e-05 1.60258615e-12 1.10593206e-20 8.77131205e-26
 5.03809270e-10 4.70418418e-15 1.20111656e-23 4.73271842e-22
 5.68950836e-16 1.53220794e-15 2.83795698e-18 1.19540766e-20
 4.59731679e-18 3.67903525e-27 1.62417847e-22 1.17270240e-14
 7.88530105e-11 6.92034716e-14 3.14007822e-12 1.45777268e-10
 1.29135036e-05 2.79540600e-11 6.99033001e-19 2.31745699e-23
 8.45001139e-27 3.70378078e-11 2.36450039e-05 1.36888262e-12
 1.37860146e-12 2.06432104e-02 1.45982641e-05 2.15529542e-04
 8.71158159e-12 1.31991816e-06 4.24324945e-03 2.68445167e-09
 1.50500721e-21 1.24053834e-15 2.52307671e-11 1.19884507e-13
 3.01023282e-24 3.60694607e-09 5.26459191e-10 3.59637233e-20
 2.87189278e-10 9.70291263e-04 6.33895082e-15 1.29426852e-21
 5.07032307e-14 1.82799337e-16 2.94166149e-22 6.14910885e-22
 1.69134177e-16 3.75532362e-20 1.36964454e-20 1.54516505e-16
 2.23929409e-19 3.66037373e-17 4.66876020e-16 1.10430343e-17
 5.68164262e-16 1.20346467e-09 3.00440736e-10 5.95099449e-05
 7.43498889e-21 1.73803290e-21 6.93279769e-14 1.36347354e-24
 1.75494232e-12 2.72130973e-06 4.54959543e-05 4.03367081e-10
 1.23682709e-17 9.43732453e-05 1.15735371e+01 9.53251620e-04
 1.53636459e-04 4.93501568e-11 5.79425959e-20 5.96824568e-34
 1.69356872e-19 3.49673991e-25 1.74834366e-07 4.01203826e-07
 5.73838309e-12 7.80136031e-13 7.86813586e-17 2.32777867e-27
 6.88514059e-35 2.61184438e-24 3.57192192e-09 6.92769476e-08
 9.30792703e-14 1.55217308e-14 4.15979288e-12 6.25119129e-15
 5.63976797e-14 3.51976565e-03 1.05557871e-06 1.82488190e-25
 2.73531685e-15 2.20433781e-02 3.41717530e-09 4.04617698e-11
 4.52292715e-13 4.58926714e-08 7.52812586e-14 9.20126727e-27
 8.98872775e-18 1.37492525e-18 4.91410809e-18 3.67959007e-21
 3.28977873e-17 4.86285007e-16 6.88490325e-21 4.91181888e-20
 3.41120303e-04 3.74481184e-14 2.84366429e-16 2.25022724e-12
 4.07897322e-13 3.82225086e-16 5.32882256e-13 4.03497187e-15
 7.39690595e-15 2.66307264e-17 3.27372138e-18 3.80823590e-13
 1.67223617e-11 4.83519339e-15 2.60717851e-19 7.12326507e-23
 1.87785771e-20 5.10942789e-31 4.01154825e-08 4.46398645e-08
 4.22783835e-12 3.04475250e-14 7.43754398e-11 1.57880021e-15
 3.06336166e-11 8.70389056e-15 4.86586281e-12 5.14679817e-09
 1.40307321e-08 3.42372514e-06 1.52905270e-04 5.74112313e-09
 5.28627321e-15 7.06185720e-28 4.42109552e-16 9.46388074e-27
 2.66752877e-14 3.24423560e-10 5.92728530e-08 1.55481790e-14
 2.67215758e-17 7.04036967e-21 2.33874075e-32 2.05714705e-35
 4.20338572e-28 3.18823490e-15 1.22523264e-15 2.89759056e-18
 4.64314848e-15 1.78972661e-13 1.06695372e-19 3.02324270e-10
 5.83904833e-10 5.87616237e-16 1.75378244e-07 3.31029332e-02
 1.44049193e-13 1.53581196e-02 7.60605472e-06 9.20961583e-09
 1.88121955e-09 1.17594380e-09 3.14214138e-08 7.87193360e-12
 2.33088326e-13 3.83932931e-10 5.57146053e-13 9.28633055e-14
 6.57763976e-17 1.43952749e-23 2.81892691e-18 1.18576095e-14
 9.51856446e-12 3.12906402e-20 1.89626839e-15 4.70269575e-26
 1.65150637e-22 6.32349904e-21 6.46110034e-26 6.93999707e-21
 4.80613039e-10 9.65531961e-10 3.34025210e-07 2.62903523e-13
 7.99012796e-06 6.64856244e-05 6.64442019e-08 1.53563629e-10
 3.31795751e-10 2.95180872e+00 3.69123458e+00 9.15906257e-09
 1.57281981e-02 1.01120924e-01 2.32684262e-06 8.51853032e-01
 4.41896358e-07 2.21282006e-15 4.95947051e-25 1.42182823e-15
 1.59364334e-16 3.66301782e-16 3.80497790e-21 7.41476964e-18
 1.60828056e-18 2.48346363e-08 1.81478112e-10 1.78400880e-17
 3.29549724e-25 5.31762796e-22 1.68586345e-18 4.87630492e-19
 1.28442764e-22 4.38559389e-23 1.17513875e-19 4.63489380e-19
 3.30661002e-24 1.09765866e-21 3.97262272e-13 1.66746908e-11
 2.19044630e-12 1.73135348e-16 3.50910287e-13 5.75738630e-20
 6.30039150e-11 1.89147292e-11 1.34160814e-19 1.66600197e-16
 5.47375508e-10 4.77410315e-21 2.29206022e-23 6.69977880e-26

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_1_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_R3_k_sequence/20240402-191619_analysis.csv
dict_keys(['cluster_1_R3_k_sequence'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_R3_k_sequence to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_1_R3_k_sequence/cluster_1_R3_k_sequence0_1712081779.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_1_R3_k_sequence': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00005  0.00054       35  train_cluster_1_1
1   0.0  0.00007  0.00069       36  train_cluster_1_1
2   0.0  0.00008  0.00081       37  train_cluster_1_1
3   0.0  0.00007  0.00069       38  train_cluster_1_1
4   0.0  0.00005  0.00054       39  train_cluster_1_1
5   0.0  0.00005  0.00048       40  train_cluster_1_1
6   0.0  0.00003  0.00025       41  train_cluster_1_1
7   0.0  0.00000  0.00000       42  train_cluster_1_1
8   0.0  0.00000  0.00000       43  train_cluster_1_1
9   0.0  0.00000  0.00000       44  train_cluster_1_1
10  0.0  0.00000  0.00000       45  train_cluster_1_1
11  0.0  0.00000  0.00003       46  train_cluster_1_1
12  0.0  0.00001  0.00006       47  train_cluster_1_1
13  0.0  0.00000  0.00004       48  train_cluster_1_1
14  0.0  0.00001  0.00009       62  train_cluster_1_1
15  0.0  0.00001  0.00010       63  train_cluster_1_1
16  0.0  0.00000  0.00000       64  train_cluster_1_1
17  0.0  0.00000  0.00000       65  train_cluster_1_1
18  0.0  0.00000  0.00000       68  train_cluster_1_1
19  0.0  0.00000  0.00004       81  train_cluster_1_1
20  0.0  0.00000  0.00003       82  train_cluster_1_1
21  0.0  0.00000  0.00003       83  train_cluster_1_1
22  0.0  0.00000  0.00003       84  train_cluster_1_1
23  0.0  0.00000  0.00003       85  train_cluster_1_1
24  0.0  0.00001  0.00005       86  train_cluster_1_1
25  0.0  0.00000  0.00004       87  train_cluster_1_1
26  0.0  0.00001  0.00005       88  train_cluster_1_1
27  0.0  0.16216  0.28406       89  train_cluster_1_1
28  0.0  0.14968  0.26221       90  train_cluster_1_1
29  0.0  0.12972  0.22725       91  train_cluster_1_1
30  0.0  0.10810  0.18937       92  train_cluster_1_1
31  0.0  0.00000  0.00000       93  train_cluster_1_1
32  0.0  0.00000  0.00000       94  train_cluster_1_1
33  0.0  0.00000  0.00000       95  train_cluster_1_1
34  0.0  0.00000  0.00000       96  train_cluster_1_1
35  0.0  0.00000  0.00000       97  train_cluster_1_1
36  0.0  0.00000  0.00000       98  train_cluster_1_1
37  0.0  0.10526  0.10531       99  train_cluster_1_1
38  0.0  0.11111  0.11116      100  train_cluster_1_1
39  0.0  0.10526  0.10531      101  train_cluster_1_1
40  0.0  0.12500  0.12506      102  train_cluster_1_1
41  0.0  0.11765  0.11770      103  train_cluster_1_1
42  0.0  0.10000  0.10004      104  train_cluster_1_1
43  0.0  0.13333  0.13339      105  train_cluster_1_1
44  0.0  0.11111  0.11116      106  train_cluster_1_1
45  0.0  0.11765  0.11770      107  train_cluster_1_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00001  0.00009        0  val_cluster_1_1
1   0.0  0.09091  0.09091        1  val_cluster_1_1
2   0.0  0.07144  0.07151        2  val_cluster_1_1
3   0.0  0.05558  0.05581        3  val_cluster_1_1
4   0.0  0.10000  0.10000        4  val_cluster_1_1
5   0.0  0.07693  0.07701        5  val_cluster_1_1
6   0.0  0.05885  0.05909        6  val_cluster_1_1
7   0.0  0.11111  0.11111        7  val_cluster_1_1
8   0.0  0.09092  0.09102        8  val_cluster_1_1
9   0.0  0.08334  0.08343        9  val_cluster_1_1
10  0.0  0.06670  0.06697       10  val_cluster_1_1
11  0.0  0.06253  0.06279       11  val_cluster_1_1
12  0.0  0.14286  0.14286       12  val_cluster_1_1
13  0.0  0.11112  0.11124       13  val_cluster_1_1
14  0.0  0.10001  0.10012       14  val_cluster_1_1
15  0.0  0.08337  0.08371       15  val_cluster_1_1
16  0.0  0.07146  0.07175       16  val_cluster_1_1
17  0.0  0.00006  0.00058       17  val_cluster_1_1
18  0.0  0.00000  0.00000       18  val_cluster_1_1
19  0.0  0.00000  0.00000       19  val_cluster_1_1
20  0.0  0.00000  0.00000       20  val_cluster_1_1
21  0.0  0.00000  0.00000       21  val_cluster_1_1
22  0.0  0.00000  0.00000       22  val_cluster_1_1
23  0.0  0.00000  0.00000       23  val_cluster_1_1
24  0.0  0.00000  0.00001       24  val_cluster_1_1
25  0.0  0.00000  0.00001       25  val_cluster_1_1
26  0.0  0.00000  0.00002       26  val_cluster_1_1
27  0.0  0.00000  0.00001       27  val_cluster_1_1
28  0.0  0.00000  0.00002       28  val_cluster_1_1
29  0.0  0.00056  0.00541       29  val_cluster_1_1
30  0.0  0.00107  0.01031       30  val_cluster_1_1
31  0.0  0.00079  0.00756       31  val_cluster_1_1
32  0.0  0.00084  0.00810       32  val_cluster_1_1
33  0.0  0.00147  0.01417       33  val_cluster_1_1
34  0.0  0.00098  0.00944       34  val_cluster_1_1
35  0.0  0.14248  0.14363       49  val_cluster_1_1
36  0.0  0.00009  0.00090       50  val_cluster_1_1
37  0.0  0.00000  0.00000       51  val_cluster_1_1
38  0.0  0.00000  0.00000       52  val_cluster_1_1
39  0.0  0.00000  0.00000       53  val_cluster_1_1
40  0.0  0.00075  0.00715       54  val_cluster_1_1
41  0.0  0.00001  0.00009       72  val_cluster_1_1
42  0.0  0.00000  0.00004       73  val_cluster_1_1
43  0.0  0.00000  0.00003       74  val_cluster_1_1
44  0.0  0.00000  0.00004       75  val_cluster_1_1
45  0.0  0.00000  0.00000       76  val_cluster_1_1
46  0.0  0.00000  0.00000       77  val_cluster_1_1
47  0.0  0.00291  0.02741       78  val_cluster_1_1
48  0.0  0.00000  0.00000       79  val_cluster_1_1
49  0.0  0.00000  0.00000       80  val_cluster_1_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name                     name  \
0    0.0  0.41879  0.44438        0  Experimental  cluster_1_R3_k_sequence
1    0.0  0.37096  0.45204        1  Experimental  cluster_1_R3_k_sequence
2    0.0  0.40040  0.48544        2  Experimental  cluster_1_R3_k_sequence
3    0.0  0.45875  0.51503        3  Experimental  cluster_1_R3_k_sequence
4    0.0  0.41726  0.49519        4  Experimental  cluster_1_R3_k_sequence
5    0.0  0.44176  0.50927        5  Experimental  cluster_1_R3_k_sequence
6    0.0  0.48987  0.54090        6  Experimental  cluster_1_R3_k_sequence
7    0.0  0.41316  0.48254        7  Experimental  cluster_1_R3_k_sequence
8    0.0  0.46617  0.51066        8  Experimental  cluster_1_R3_k_sequence
9    0.0  0.46825  0.52028        9  Experimental  cluster_1_R3_k_sequence
10   0.0  0.48273  0.53102       10  Experimental  cluster_1_R3_k_sequence
11   0.0  0.50258  0.53988       11  Experimental  cluster_1_R3_k_sequence
12   0.0  0.47373  0.50144       12  Experimental  cluster_1_R3_k_sequence
13   0.0  0.52057  0.54102       13  Experimental  cluster_1_R3_k_sequence
14   0.0  0.52823  0.55640       14  Experimental  cluster_1_R3_k_sequence
15   0.0  0.55802  0.57504       15  Experimental  cluster_1_R3_k_sequence
16   0.0  0.55641  0.57196       16  Experimental  cluster_1_R3_k_sequence
17   0.0  0.52928  0.54827       17  Experimental  cluster_1_R3_k_sequence
18   0.0  0.17163  0.27883       18  Experimental  cluster_1_R3_k_sequence
19   0.0  0.16883  0.28686       19  Experimental  cluster_1_R3_k_sequence
20   0.0  0.16341  0.27353       20  Experimental  cluster_1_R3_k_sequence
21   0.0  0.32309  0.41205       21  Experimental  cluster_1_R3_k_sequence
22   0.0  0.31355  0.39928       22  Experimental  cluster_1_R3_k_sequence
23   0.0  0.34392  0.42213       23  Experimental  cluster_1_R3_k_sequence
24   0.0  0.35604  0.35617       24  Experimental  cluster_1_R3_k_sequence
25   0.0  0.34105  0.35125       25  Experimental  cluster_1_R3_k_sequence
26   0.0  0.34135  0.38830       26  Experimental  cluster_1_R3_k_sequence
27   0.0  0.28512  0.29602       27  Experimental  cluster_1_R3_k_sequence
28   0.0  0.28439  0.33185       28  Experimental  cluster_1_R3_k_sequence
29   0.0  0.32954  0.39085       29  Experimental  cluster_1_R3_k_sequence
30   0.0  0.26192  0.34619       30  Experimental  cluster_1_R3_k_sequence
31   0.0  0.31421  0.37857       31  Experimental  cluster_1_R3_k_sequence
32   0.0  0.32314  0.38565       32  Experimental  cluster_1_R3_k_sequence
33   0.0  0.29666  0.37860       33  Experimental  cluster_1_R3_k_sequence
34   0.0  0.38440  0.44775       34  Experimental  cluster_1_R3_k_sequence
35   0.0  0.33633  0.46390       35  Experimental  cluster_1_R3_k_sequence
36   0.0  0.34716  0.45807       36  Experimental  cluster_1_R3_k_sequence
37   0.0  0.34165  0.44393       37  Experimental  cluster_1_R3_k_sequence
38   0.0  0.30725  0.43533       38  Experimental  cluster_1_R3_k_sequence
39   0.0  0.33252  0.48976       39  Experimental  cluster_1_R3_k_sequence
40   0.0  0.28369  0.42940       40  Experimental  cluster_1_R3_k_sequence
41   0.0  0.35906  0.50293       41  Experimental  cluster_1_R3_k_sequence
42   0.0  0.33575  0.45181       42  Experimental  cluster_1_R3_k_sequence
43   0.0  0.33443  0.43697       43  Experimental  cluster_1_R3_k_sequence
44   0.0  0.37082  0.47284       44  Experimental  cluster_1_R3_k_sequence
45   0.0  0.37847  0.48848       45  Experimental  cluster_1_R3_k_sequence
46   0.0  0.22218  0.31040       46  Experimental  cluster_1_R3_k_sequence
47   0.0  0.18217  0.28305       47  Experimental  cluster_1_R3_k_sequence
48   0.0  0.25719  0.37045       48  Experimental  cluster_1_R3_k_sequence
49   0.0  0.49756  0.50850       49  Experimental  cluster_1_R3_k_sequence
50   0.0  0.55024  0.54326       50  Experimental  cluster_1_R3_k_sequence
51   0.0  0.24310  0.29208       51  Experimental  cluster_1_R3_k_sequence
52   0.0  0.19173  0.23972       52  Experimental  cluster_1_R3_k_sequence
53   0.0  0.18105  0.23003       53  Experimental  cluster_1_R3_k_sequence
54   0.0  0.26140  0.30267       54  Experimental  cluster_1_R3_k_sequence
55   0.0  0.26392  0.30614       55  Experimental  cluster_1_R3_k_sequence
56   0.0  0.26061  0.32801       56  Experimental  cluster_1_R3_k_sequence
57   0.0  0.45297  0.53974       57  Experimental  cluster_1_R3_k_sequence
58   0.0  0.31622  0.45372       58  Experimental  cluster_1_R3_k_sequence
59   0.0  0.43711  0.52972       59  Experimental  cluster_1_R3_k_sequence
60   0.0  0.47628  0.54735       60  Experimental  cluster_1_R3_k_sequence
61   0.0  0.49249  0.57156       61  Experimental  cluster_1_R3_k_sequence
62   0.0  0.50341  0.53212       62  Experimental  cluster_1_R3_k_sequence
63   0.0  0.53500  0.53827       63  Experimental  cluster_1_R3_k_sequence
64   0.0  0.26524  0.35365       64  Experimental  cluster_1_R3_k_sequence
65   0.0  0.25454  0.32548       65  Experimental  cluster_1_R3_k_sequence
66   0.0  0.25152  0.35786       66  Experimental  cluster_1_R3_k_sequence
67   0.0  0.28164  0.36568       67  Experimental  cluster_1_R3_k_sequence
68   0.0  0.24177  0.30174       68  Experimental  cluster_1_R3_k_sequence
69   0.0  0.27969  0.36567       69  Experimental  cluster_1_R3_k_sequence
70   0.0  0.38633  0.44869       70  Experimental  cluster_1_R3_k_sequence
71   0.0  0.24871  0.31226       71  Experimental  cluster_1_R3_k_sequence
72   0.0  0.36820  0.37879       72  Experimental  cluster_1_R3_k_sequence
73   0.0  0.22903  0.26839       73  Experimental  cluster_1_R3_k_sequence
74   0.0  0.21687  0.25989       74  Experimental  cluster_1_R3_k_sequence
75   0.0  0.20479  0.23593       75  Experimental  cluster_1_R3_k_sequence
76   0.0  0.11684  0.15140       76  Experimental  cluster_1_R3_k_sequence
77   0.0  0.13267  0.18143       77  Experimental  cluster_1_R3_k_sequence
78   0.0  0.35203  0.42601       78  Experimental  cluster_1_R3_k_sequence
79   0.0  0.20249  0.21472       79  Experimental  cluster_1_R3_k_sequence
80   0.0  0.16260  0.17496       80  Experimental  cluster_1_R3_k_sequence
81   0.0  0.05688  0.07274       81  Experimental  cluster_1_R3_k_sequence
82   0.0  0.07600  0.11464       82  Experimental  cluster_1_R3_k_sequence
83   0.0  0.08147  0.13526       83  Experimental  cluster_1_R3_k_sequence
84   0.0  0.08527  0.13242       84  Experimental  cluster_1_R3_k_sequence
85   0.0  0.08569  0.14304       85  Experimental  cluster_1_R3_k_sequence
86   0.0  0.06291  0.07885       86  Experimental  cluster_1_R3_k_sequence
87   0.0  0.09393  0.16201       87  Experimental  cluster_1_R3_k_sequence
88   0.0  0.10385  0.19651       88  Experimental  cluster_1_R3_k_sequence
89   0.0  0.53877  0.49943       89  Experimental  cluster_1_R3_k_sequence
90   0.0  0.51417  0.47866       90  Experimental  cluster_1_R3_k_sequence
91   0.0  0.50107  0.49072       91  Experimental  cluster_1_R3_k_sequence
92   0.0  0.45551  0.47280       92  Experimental  cluster_1_R3_k_sequence
93   0.0  0.06500  0.10668       93  Experimental  cluster_1_R3_k_sequence
94   0.0  0.06362  0.10593       94  Experimental  cluster_1_R3_k_sequence
95   0.0  0.04358  0.04371       95  Experimental  cluster_1_R3_k_sequence
96   0.0  0.08151  0.10674       96  Experimental  cluster_1_R3_k_sequence
97   0.0  0.08795  0.11537       97  Experimental  cluster_1_R3_k_sequence
98   0.0  0.09261  0.12297       98  Experimental  cluster_1_R3_k_sequence
99   0.0  0.17298  0.20225       99  Experimental  cluster_1_R3_k_sequence
100  0.0  0.20729  0.23030      100  Experimental  cluster_1_R3_k_sequence
101  0.0  0.20401  0.23454      101  Experimental  cluster_1_R3_k_sequence
102  0.0  0.21943  0.23426      102  Experimental  cluster_1_R3_k_sequence
103  0.0  0.21731  0.24442      103  Experimental  cluster_1_R3_k_sequence
104  0.0  0.22028  0.25199      104  Experimental  cluster_1_R3_k_sequence
105  0.0  0.22217  0.24175      105  Experimental  cluster_1_R3_k_sequence
106  0.0  0.22454  0.24966      106  Experimental  cluster_1_R3_k_sequence
107  0.0  0.23913  0.27068      107  Experimental  cluster_1_R3_k_sequence

    split_type
0           R3
1           R3
2           R3
3           R3
4           R3
5           R3
6           R3
7           R3
8           R3
9           R3
10          R3
11          R3
12          R3
13          R3
14          R3
15          R3
16          R3
17          R3
18          R3
19          R3
20          R3
21          R3
22          R3
23          R3
24          R3
25          R3
26          R3
27          R3
28          R3
29          R3
30          R3
31          R3
32          R3
33          R3
34          R3
35          R3
36          R3
37          R3
38          R3
39          R3
40          R3
41          R3
42          R3
43          R3
44          R3
45          R3
46          R3
47          R3
48          R3
49          R3
50          R3
51          R3
52          R3
53          R3
54          R3
55          R3
56          R3
57          R3
58          R3
59          R3
60          R3
61          R3
62          R3
63          R3
64          R3
65          R3
66          R3
67          R3
68          R3
69          R3
70          R3
71          R3
72          R3
73          R3
74          R3
75          R3
76          R3
77          R3
78          R3
79          R3
80          R3
81          R3
82          R3
83          R3
84          R3
85          R3
86          R3
87          R3
88          R3
89          R3
90          R3
91          R3
92          R3
93          R3
94          R3
95          R3
96          R3
97          R3
98          R3
99          R3
100         R3
101         R3
102         R3
103         R3
104         R3
105         R3
106         R3
107         R3  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental
69   0.0  0.27969  0.36567       69       Experimental
70   0.0  0.38633  0.44869       70       Experimental
71   0.0  0.24871  0.31226       71       Experimental
72   0.0  0.36820  0.37879       72       Experimental
73   0.0  0.22903  0.26839       73       Experimental
74   0.0  0.21687  0.25989       74       Experimental
75   0.0  0.20479  0.23593       75       Experimental
76   0.0  0.11684  0.15140       76       Experimental
77   0.0  0.13267  0.18143       77       Experimental
78   0.0  0.35203  0.42601       78       Experimental
79   0.0  0.20249  0.21472       79       Experimental
80   0.0  0.16260  0.17496       80       Experimental
81   0.0  0.05688  0.07274       81       Experimental
82   0.0  0.07600  0.11464       82       Experimental
83   0.0  0.08147  0.13526       83       Experimental
84   0.0  0.08527  0.13242       84       Experimental
85   0.0  0.08569  0.14304       85       Experimental
86   0.0  0.06291  0.07885       86       Experimental
87   0.0  0.09393  0.16201       87       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/train_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00181818, 0.00181818, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/train_cluster_1_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(35, 4)
   0.0  0.5      5.0  peptide
0  0.0  0.0  0.00000        0
1  0.0  0.0  0.00000        1
2  0.0  0.0  0.00000        2
3  0.0  0.0  0.00001        3
4  0.0  0.0  0.00001        4
Experimental cluster_1 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/val_cluster_1_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat
REWIGHTING val_cluster_1_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_11/prep_cluster_11_0/out__prep_cluster_11_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/val_cluster_1_1/val_cluster_1_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/val_cluster_1_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([0.5, 0.5, 3. , 1.5, 2. , 0.5, 1.5, 3. , 1. , 1.5, 1.5, 0.5, 0.5,
       0.5, 2. , 0.5, 1. , 1.5, 0.5, 0.5, 0.5, 1. , 1.5, 0.5, 1. , 0.5,
       1. , 1. , 1. , 0.5, 0.5, 1.5, 1.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 0.5, 0.5, 0.5, 3. , 1.5, 0.5, 0.5, 1. , 1.5, 0.5, 0.5,
       3. , 1. , 1.5, 0.5, 0.5, 5.5, 1. , 1.5, 2. , 0.5, 1. , 0.5, 1.5,
       1. , 1. , 2. , 0.5, 1.5, 1. , 0.5, 0.5, 1. , 1. , 1. , 0.5, 2. ,
       0.5, 2.5, 1.5, 1. , 0.5, 2.5, 1.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5,
       2. , 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 1.5, 0.5, 3.5, 1. ,
       1. , 0.5, 1. , 0.5, 1. , 1.5, 0.5, 1. , 1.5, 1. , 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 2. , 0.5, 2. ,
       2.5, 0.5, 2.5, 0.5, 2. , 3. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1. ,
       0.5, 1. , 0.5, 1.5, 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. ,
       2. , 1. , 1. , 1. , 2. , 1.5, 0.5, 0.5, 0.5, 1. , 0.5, 1. , 2. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 1. , 0.5, 2.5, 2. ,
       1. , 1.5, 1.5, 0.5, 1. , 1. , 0.5, 1. , 2. , 0.5, 1. , 1. , 1. ,
       0.5, 0.5, 1. , 1.5, 1. , 1. , 0.5, 1. , 2. , 1. , 1. , 1.5, 1. ,
       1. , 1.5, 1.5, 0.5, 0.5, 2.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 2.5,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 0.5,
       1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5, 1.5, 0.5, 0.5, 2.5, 0.5, 0.5,
       0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 0.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 1.5, 2. , 0.5, 1. , 1. , 0.5, 3. , 0.5, 0.5, 2.5,
       0.5, 1.5, 1. , 2.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 2. ,
       1. , 0.5, 1.5, 1.5, 0.5, 0.5, 1. , 0.5, 0.5, 1.5, 1. , 2. , 2.5,
       4. , 1. , 1. , 0.5, 0.5, 1. , 1. , 0.5, 3.5, 1. , 1. , 1.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 1. , 2. , 1.5, 2. , 1. , 4. , 3.5, 1. , 0.5,
       1. , 0.5, 1.5, 2.5, 0.5, 1. , 1. , 1.5, 0.5, 1.5, 0.5, 1. , 1. ,
       1. , 0.5, 0.5, 1. , 1. , 2.5, 1. , 1. , 0.5, 1.5, 1.5, 0.5, 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 1. , 2. , 0.5, 2. , 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 2. , 0.5, 1.5, 2.5, 2.5, 2.5, 1.5, 0.5, 1. , 1.5,
       0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 2. , 1. , 0.5, 0.5, 1. , 3.5,
       1. , 0.5, 0.5, 1. , 2. , 1. , 1. , 0.5, 3. , 0.5, 0.5, 0.5, 0.5,
       1.5, 1.5, 0.5, 1. , 1. , 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 1.5,
       2. , 1. , 0.5, 0.5, 0.5, 1. , 3. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 1.5, 0.5, 0.5, 2. , 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 1. , 1.5, 1. , 1.5, 0.5, 0.5, 3.5, 0.5, 2. , 0.5, 0.5, 3. ,
       0.5, 0.5, 0.5, 0.5, 2. , 1.5, 0.5, 0.5, 1. , 1.5, 1.5, 0.5, 1. ,
       0.5, 0.5, 0.5, 0.5, 2. , 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       1. , 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 1.5, 1. , 0.5, 0.5, 0.5, 0.5,
       1. , 2. , 0.5, 3. , 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5,
       0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. , 1. , 2.5, 1. , 0.5, 1. , 0.5,
       1. , 0.5, 1. , 1. , 0.5, 1.5, 1.5, 1. , 1. , 1. , 1. , 1. , 0.5,
       0.5, 0.5, 2. , 0.5]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours0/val_cluster_1_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([0.00090909, 0.00090909, 0.00545455, 0.00272727, 0.00363636,
       0.00090909, 0.00272727, 0.00545455, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00090909, 0.00545455,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.00545455, 0.00181818, 0.00272727,
       0.00090909, 0.00090909, 0.01      , 0.00181818, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00272727,
       0.00181818, 0.00181818, 0.00363636, 0.00090909, 0.00272727,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00181818,
       0.00181818, 0.00090909, 0.00363636, 0.00090909, 0.00454545,
       0.00272727, 0.00181818, 0.00090909, 0.00454545, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00363636, 0.00090909,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00272727,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00090909,
       0.00272727, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00272727,
       0.00090909, 0.00181818, 0.00272727, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00363636, 0.00090909, 0.00363636,
       0.00454545, 0.00090909, 0.00454545, 0.00090909, 0.00363636,
       0.00545455, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00181818,
       0.00090909, 0.00272727, 0.00272727, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00363636, 0.00181818, 0.00181818, 0.00181818,
       0.00363636, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00090909, 0.00181818, 0.00090909, 0.00181818, 0.00090909,
       0.00454545, 0.00363636, 0.00181818, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00181818,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00090909, 0.00090909, 0.00181818, 0.00272727, 0.00181818,
       0.00181818, 0.00090909, 0.00181818, 0.00363636, 0.00181818,
       0.00181818, 0.00272727, 0.00181818, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00090909, 0.00454545, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00454545, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00181818, 0.00181818,
       0.00181818, 0.00181818, 0.00181818, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00272727, 0.00090909, 0.00090909, 0.00454545,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00272727,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00363636,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00454545, 0.00090909, 0.00272727,
       0.00181818, 0.00454545, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00363636, 0.00181818, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00272727, 0.00181818, 0.00363636, 0.00454545, 0.00727273,
       0.00181818, 0.00181818, 0.00090909, 0.00090909, 0.00181818,
       0.00181818, 0.00090909, 0.00636364, 0.00181818, 0.00181818,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00272727, 0.00363636,
       0.00181818, 0.00727273, 0.00636364, 0.00181818, 0.00090909,
       0.00181818, 0.00090909, 0.00272727, 0.00454545, 0.00090909,
       0.00181818, 0.00181818, 0.00272727, 0.00090909, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,
       0.00181818, 0.00090909, 0.00272727, 0.00272727, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00363636, 0.00090909, 0.00363636,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00272727,
       0.00454545, 0.00454545, 0.00454545, 0.00272727, 0.00090909,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00636364,
       0.00181818, 0.00090909, 0.00090909, 0.00181818, 0.00363636,
       0.00181818, 0.00181818, 0.00090909, 0.00545455, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00272727,
       0.00090909, 0.00181818, 0.00181818, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00090909, 0.00090909, 0.00090909,
       0.00272727, 0.00363636, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00545455, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00272727, 0.00090909, 0.00090909,
       0.00363636, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00181818, 0.00272727, 0.00090909, 0.00090909, 0.00636364,
       0.00090909, 0.00363636, 0.00090909, 0.00090909, 0.00545455,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00363636,
       0.00272727, 0.00090909, 0.00090909, 0.00181818, 0.00272727,
       0.00272727, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00363636, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00181818, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00090909, 0.00181818,
       0.00090909, 0.00090909, 0.00090909, 0.00272727, 0.00090909,
       0.00090909, 0.00272727, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00363636, 0.00090909,
       0.00545455, 0.00272727, 0.00090909, 0.00090909, 0.00090909,
       0.00090909, 0.00090909, 0.00090909, 0.00181818, 0.00090909,
       0.00090909, 0.00090909, 0.00181818, 0.00090909, 0.00090909,
       0.00090909, 0.00181818, 0.00181818, 0.00454545, 0.00181818,

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
LogPf_by_res [35.87272727 63.12063636 40.04418182 28.32363636 17.37004545 31.17622727
 33.92609091 26.12363636 27.80145455 23.14213636  4.05636364 20.15263636
 46.86772727 49.24663636 34.51763636 45.82036364 14.91668182 19.60031818
 31.60463636 15.46286364 19.35272727 35.40909091 51.87509091 65.73818182
 28.23090909 41.14790909 60.63445455 56.56918182 42.89190909 41.48677273
 47.31763636 52.99463636 45.84513636 67.482      55.98081818 38.64568182
 30.43090909 37.00868182 33.67727273 28.43486364 17.71090909 32.13568182
 48.51154545 57.90490909 68.28531818 30.61090909 19.22440909 35.65881818
 35.03004545 10.70245455 16.52909091 14.94213636 33.30159091 20.49818182
 12.03122727 27.47890909 54.21495455 39.64863636 31.91581818 36.96577273
 61.00513636 26.83813636 29.01586364 51.2715     28.3785     13.76
 39.42204545 54.61909091 37.87236364 42.04709091 55.68618182 55.89290909
 43.69054545 52.05718182 51.82240909 42.90595455 50.29463636 44.57636364
 41.22454545 44.53131818 41.742      28.12       29.80704545 16.22909091
 53.21622727 53.74863636 36.01677273 63.27077273 35.47945455 20.097
 19.03045455 30.894      46.214      16.27454545  4.53454545 14.35336364
 15.71813636 30.00154545 50.70245455 83.3005     50.20554545 65.34536364
 22.28940909 23.76136364 34.06445455 35.48427273 44.52490909 68.37722727
 87.37131818 61.10104545 26.45645455 25.56377273 38.32409091 39.4015
 33.99472727 39.36690909 37.14422727 12.19513636 20.69863636 64.33781818
 41.18354545 11.39668182 27.21454545 32.43363636 37.68727273 25.05454545
 37.24686364 66.12781818 46.67131818 49.86136364 46.79163636 53.85054545
 45.55809091 42.88772727 54.95095455 52.57159091 14.32181818 37.09318182
 43.194      34.42495455 35.81036364 43.03640909 34.46086364 39.80468182
 39.65913636 44.9405     46.18468182 35.3955     32.16595455 40.89018182
 50.60304545 56.85109091 52.26668182 77.74545455 23.53122727 25.61181818
 34.30086364 37.99090909 31.45645455 41.29563636 31.4685     38.18395455
 32.70968182 26.41354545 25.66395455 20.05159091 17.74918182 27.36345455
 40.04113636 69.43186364 42.40731818 68.81672727 39.50472727 29.59209091
 25.67368182 40.38990909 45.58181818 54.00759091 79.88545455 88.57936364
 72.29931818 41.14545455 43.13795455 47.96459091 41.39122727 37.23281818
 50.27613636 30.46854545 29.05045455 43.91881818 21.89486364 11.12822727
 38.71631818 12.56395455 17.82577273 25.233      27.42       28.83390909
 23.7755     31.99836364 36.48509091 28.98618182 35.4525     36.78368182
 45.14154545 60.75272727 47.48554545 38.17409091 32.03868182 50.83504545
 40.744      65.11813636 57.66804545 52.59527273 63.32681818 53.21604545
 29.29118182 28.61659091 23.92159091 35.23645455 18.53636364 16.46363636
 24.93777273 30.317      29.17818182  5.50940909  5.76940909 26.04440909
 11.48095455  9.94245455 18.50363636  6.68309091 22.099      41.21131818
 64.92681818 42.78190909 42.41454545 40.68427273 53.37954545 46.38027273
 48.48422727 24.6785     27.61713636 45.47927273 63.21718182 56.15331818
 48.09172727 48.34209091 56.33063636 56.53022727 51.26177273 48.71522727
 59.04613636 56.00422727 36.43545455 31.73131818 35.16568182 42.79218182
 35.56940909 50.89304545 30.47109091 30.96054545 49.49445455 43.33722727
 26.51313636 54.39604545 59.11327273 65.31681818 43.21536364 32.41936364
 31.14390909 31.59695455 32.35409091 30.1185     20.48031818 36.64940909
  0.66727273  4.11636364 19.38127273 15.69818182 36.64436364 60.27895455
 56.5155     41.44809091 46.83754545 58.31359091 53.68077273 43.82886364
 48.61422727]
Pf_by_res [3.79601138e+15 2.58787960e+27 2.46018177e+17 1.99893642e+12
 3.49715508e+07 3.46468273e+13 5.41893666e+14 2.21488468e+11
 1.18581871e+12 1.12331646e+10 5.77638782e+01 5.65169568e+08
 2.26149345e+20 2.44085750e+21 9.79081853e+14 7.93471050e+19
 3.00768675e+06 3.25319450e+08 5.31764297e+13 5.19321558e+06
 2.53970143e+08 2.38766169e+15 3.38116006e+22 3.54592556e+28
 1.82191469e+12 7.41839339e+17 2.15381810e+26 3.69558767e+24
 4.24345339e+18 1.04106170e+18 3.54640532e+20 1.03580533e+23
 8.13372987e+19 2.02796394e+29 2.05192002e+24 6.07584048e+16
 1.64428047e+13 1.18213288e+16 4.22526265e+14 2.23410907e+12
 4.91756476e+07 9.04376536e+13 1.17029810e+21 1.40534351e+25
 4.52831762e+29 1.96856112e+13 2.23385400e+08 3.06498228e+15
 1.63438904e+15 4.44648623e+04 1.50831820e+07 3.08522876e+06
 2.90199841e+14 7.98449131e+08 1.67917367e+05 8.58892058e+11
 3.50958363e+23 1.65647157e+17 7.25878147e+13 1.13248150e+16
 3.12028376e+26 4.52537452e+11 3.99419685e+12 1.84896857e+22
 2.11166954e+12 9.46002036e+05 1.32061676e+17 5.25738508e+23
 2.80387433e+16 1.82313808e+18 1.52827491e+24 1.87923891e+24
 9.43110983e+18 4.05645635e+22 3.20764507e+22 4.30347515e+18
 6.96118286e+21 2.28701362e+19 8.00926402e+17 2.18627988e+19
 1.34375553e+18 1.63065029e+12 8.81120616e+12 1.11738961e+07
 1.29274793e+23 2.20158868e+23 4.38415249e+15 3.00709717e+27
 2.56171806e+15 5.34584303e+08 1.84001514e+08 2.61272514e+13
 1.17621086e+20 1.16935206e+07 9.31811506e+01 1.71232668e+06
 6.70347337e+06 1.07030028e+13 1.04663735e+22 1.50296023e+36
 6.36782840e+21 2.39403693e+28 4.78814587e+09 2.08655151e+10
 6.22306931e+14 2.57409067e+15 2.17231262e+19 4.96423683e+29
 8.80808228e+37 3.43436840e+26 3.08952860e+11 1.26533474e+11
 4.40495226e+16 1.29376092e+17 5.80393404e+14 1.24977372e+17
 1.35373276e+16 1.97824660e+05 9.75671357e+08 8.74096566e+27
 7.68752491e+17 8.90258288e+04 6.59366561e+11 1.21828613e+14
 2.33010013e+16 7.60415284e+10 1.50005556e+16 5.23535983e+28
 1.85821495e+20 4.51351705e+21 2.09579824e+20 2.43778128e+23
 6.10418220e+19 4.22574509e+18 7.32649630e+23 6.78503101e+22
 1.65915365e+06 1.28636490e+16 5.74005232e+18 8.92416926e+14
 3.56650898e+15 4.90314785e+18 9.25045125e+14 1.93621539e+17
 1.67395616e+17 3.29163115e+19 1.14222711e+20 2.35543072e+15
 9.32173096e+13 5.73297869e+17 9.47596414e+21 4.89908610e+24
 5.00185965e+22 5.81328884e+33 1.65760923e+10 1.32761242e+11
 7.88271458e+14 3.15676448e+16 4.58526700e+13 8.59937721e+17
 4.64083261e+13 3.82895936e+16 1.60558876e+14 2.95976369e+11
 1.39866544e+11 5.10852220e+08 5.10942139e+07 7.65239387e+11
 2.45270080e+17 1.42519814e+30 2.61375140e+18 7.70415332e+29
 1.43444884e+17 7.10692594e+12 1.41233702e+11 3.47627914e+17
 6.25074974e+19 2.85232306e+23 4.94096859e+34 2.94800922e+38
 2.50723436e+31 7.40020694e+17 5.42719742e+18 6.77262701e+20
 9.46197081e+17 1.47913387e+16 6.83358490e+21 1.70734451e+13
 4.13477713e+12 1.18495099e+19 3.22714485e+09 6.80656032e+04
 6.52053674e+16 2.86059338e+05 5.51613303e+07 9.08976513e+10
 8.09756968e+11 3.32971920e+12 2.11625723e+10 7.88338537e+13
 7.00283113e+15 3.87738401e+12 2.49359041e+15 9.43952276e+15
 4.02461272e+19 2.42423220e+26 4.19479132e+20 3.79137754e+16
 8.20772357e+13 1.19503253e+22 4.95329702e+17 1.90742423e+28
 1.10895500e+25 6.94763061e+22 3.18044356e+27 1.29251291e+23
 5.26015610e+12 2.67933812e+12 2.44914744e+10 2.00908250e+15
 1.12263982e+08 1.41275361e+07 6.76607935e+10 1.46725571e+13
 4.69811189e+12 2.47005126e+02 3.20348380e+02 2.04617678e+11
 9.68534747e+04 2.07947233e+04 1.08649359e+08 7.98784270e+02
 3.95798146e+09 7.90402087e+17 1.57528401e+28 3.80143040e+18
 2.63271012e+18 4.66611186e+17 1.52209597e+23 1.38898167e+20
 1.13876042e+21 5.22079177e+10 9.86211196e+11 5.64153370e+19
 2.85018615e+27 2.43823874e+24 7.69080464e+20 9.87878027e+20
 2.91128374e+24 3.55439562e+24 1.83107034e+22 1.43467784e+21
 4.39957981e+25 2.10052023e+24 6.66372176e+15 6.03582153e+13
 1.87180915e+15 3.84068273e+18 2.80283862e+15 1.26639389e+22
 1.71169601e+13 2.79250557e+13 3.12729243e+21 6.62397471e+18
 3.26970688e+11 4.20632067e+23 4.70509236e+25 2.32666422e+28
 5.86399999e+18 1.20102137e+14 3.35450052e+13 5.27695030e+13
 1.12513115e+14 1.20309065e+13 7.84312567e+08 8.25346157e+15
 1.94891484e+00 6.13357970e+01 2.61324301e+08 6.57103438e+06
 8.21192398e+15 1.50944514e+26 3.50243264e+24 1.00156045e+18
 2.19425722e+20 2.11480706e+25 2.05713778e+23 1.08301289e+19
 1.29685269e+21]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  2970.25801533   664.95794074  5926.44387531
  3332.68430264   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  6649.57939778  1962.4300073
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
  9392.7805534   4393.33353926   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.08010673e-11 1.44494098e-24 1.82737206e-14 1.26472236e-10
 1.09415610e-04 1.21096253e-10 1.34548885e-12 4.44061434e-09
 2.81045011e-10 5.15575245e-08 9.35702591e+01 5.63138744e-06
 9.08654626e-18 7.67806441e-19 2.05104494e-12 4.20013348e-18
 2.21086169e-04 1.44705203e-05 1.98186926e-10 6.71982285e-04
 1.47235153e-05 1.60258615e-12 1.10593206e-20 8.77131205e-26
 5.03809270e-10 4.70418418e-15 1.20111656e-23 4.73271842e-22
 5.68950836e-16 1.53220794e-15 2.83795698e-18 1.19540766e-20
 4.59731679e-18 3.67903525e-27 1.62417847e-22 1.17270240e-14
 7.88530105e-11 6.92034716e-14 3.14007822e-12 1.45777268e-10
 1.29135036e-05 2.79540600e-11 6.99033001e-19 2.31745699e-23
 8.45001139e-27 3.70378078e-11 2.36450039e-05 1.36888262e-12
 1.37860146e-12 2.06432104e-02 1.45982641e-05 2.15529542e-04
 8.71158159e-12 1.31991816e-06 4.24324945e-03 2.68445167e-09
 1.50500721e-21 1.24053834e-15 2.52307671e-11 1.19884507e-13
 3.01023282e-24 3.60694607e-09 5.26459191e-10 3.59637233e-20
 2.87189278e-10 9.70291263e-04 6.33895082e-15 1.29426852e-21
 5.07032307e-14 1.82799337e-16 2.94166149e-22 6.14910885e-22
 1.69134177e-16 3.75532362e-20 1.36964454e-20 1.54516505e-16
 2.23929409e-19 3.66037373e-17 4.66876020e-16 1.10430343e-17
 5.68164262e-16 1.20346467e-09 3.00440736e-10 5.95099449e-05
 7.43498889e-21 1.73803290e-21 6.93279769e-14 1.36347354e-24
 1.75494232e-12 2.72130973e-06 4.54959543e-05 4.03367081e-10
 1.23682709e-17 9.43732453e-05 1.15735371e+01 9.53251620e-04
 1.53636459e-04 4.93501568e-11 5.79425959e-20 5.96824568e-34
 1.69356872e-19 3.49673991e-25 1.74834366e-07 4.01203826e-07
 5.73838309e-12 7.80136031e-13 7.86813586e-17 2.32777867e-27
 6.88514059e-35 2.61184438e-24 3.57192192e-09 6.92769476e-08
 9.30792703e-14 1.55217308e-14 4.15979288e-12 6.25119129e-15
 5.63976797e-14 3.51976565e-03 1.05557871e-06 1.82488190e-25
 2.73531685e-15 2.20433781e-02 3.41717530e-09 4.04617698e-11
 4.52292715e-13 4.58926714e-08 7.52812586e-14 9.20126727e-27
 8.98872775e-18 1.37492525e-18 4.91410809e-18 3.67959007e-21
 3.28977873e-17 4.86285007e-16 6.88490325e-21 4.91181888e-20
 3.41120303e-04 3.74481184e-14 2.84366429e-16 2.25022724e-12
 4.07897322e-13 3.82225086e-16 5.32882256e-13 4.03497187e-15
 7.39690595e-15 2.66307264e-17 3.27372138e-18 3.80823590e-13
 1.67223617e-11 4.83519339e-15 2.60717851e-19 7.12326507e-23
 1.87785771e-20 5.10942789e-31 4.01154825e-08 4.46398645e-08
 4.22783835e-12 3.04475250e-14 7.43754398e-11 1.57880021e-15
 3.06336166e-11 8.70389056e-15 4.86586281e-12 5.14679817e-09
 1.40307321e-08 3.42372514e-06 1.52905270e-04 5.74112313e-09
 5.28627321e-15 7.06185720e-28 4.42109552e-16 9.46388074e-27
 2.66752877e-14 3.24423560e-10 5.92728530e-08 1.55481790e-14
 2.67215758e-17 7.04036967e-21 2.33874075e-32 2.05714705e-35
 4.20338572e-28 3.18823490e-15 1.22523264e-15 2.89759056e-18
 4.64314848e-15 1.78972661e-13 1.06695372e-19 3.02324270e-10
 5.83904833e-10 5.87616237e-16 1.75378244e-07 3.31029332e-02
 1.44049193e-13 1.53581196e-02 7.60605472e-06 9.20961583e-09
 1.88121955e-09 1.17594380e-09 3.14214138e-08 7.87193360e-12
 2.33088326e-13 3.83932931e-10 5.57146053e-13 9.28633055e-14
 6.57763976e-17 1.43952749e-23 2.81892691e-18 1.18576095e-14
 9.51856446e-12 3.12906402e-20 1.89626839e-15 4.70269575e-26
 1.65150637e-22 6.32349904e-21 6.46110034e-26 6.93999707e-21
 4.80613039e-10 9.65531961e-10 3.34025210e-07 2.62903523e-13
 7.99012796e-06 6.64856244e-05 6.64442019e-08 1.53563629e-10
 3.31795751e-10 2.95180872e+00 3.69123458e+00 9.15906257e-09
 1.57281981e-02 1.01120924e-01 2.32684262e-06 8.51853032e-01
 4.41896358e-07 2.21282006e-15 4.95947051e-25 1.42182823e-15
 1.59364334e-16 3.66301782e-16 3.80497790e-21 7.41476964e-18
 1.60828056e-18 2.48346363e-08 1.81478112e-10 1.78400880e-17
 3.29549724e-25 5.31762796e-22 1.68586345e-18 4.87630492e-19
 1.28442764e-22 4.38559389e-23 1.17513875e-19 4.63489380e-19
 3.30661002e-24 1.09765866e-21 3.97262272e-13 1.66746908e-11
 2.19044630e-12 1.73135348e-16 3.50910287e-13 5.75738630e-20
 6.30039150e-11 1.89147292e-11 1.34160814e-19 1.66600197e-16
 5.47375508e-10 4.77410315e-21 2.29206022e-23 6.69977880e-26

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_1_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_1/Benchmark/cluster_1_Sp_res_neighbours/20240402-191715_analysis.csv
dict_keys(['cluster_1_Sp_res_neighbours'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_1_Sp_res_neighbours to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_1_Sp_res_neighbours/cluster_1_Sp_res_neighbours0_1712081835.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_1_Sp_res_neighbours': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00000  0.00000       21  train_cluster_1_1
1   0.0  0.00000  0.00000       22  train_cluster_1_1
2   0.0  0.00000  0.00000       23  train_cluster_1_1
3   0.0  0.00000  0.00001       24  train_cluster_1_1
4   0.0  0.00000  0.00001       25  train_cluster_1_1
5   0.0  0.00000  0.00001       27  train_cluster_1_1
6   0.0  0.00147  0.01417       33  train_cluster_1_1
7   0.0  0.00098  0.00944       34  train_cluster_1_1
8   0.0  0.00005  0.00054       35  train_cluster_1_1
9   0.0  0.00007  0.00069       36  train_cluster_1_1
10  0.0  0.00008  0.00081       37  train_cluster_1_1
11  0.0  0.00007  0.00069       38  train_cluster_1_1
12  0.0  0.00005  0.00054       39  train_cluster_1_1
13  0.0  0.00005  0.00048       40  train_cluster_1_1
14  0.0  0.00003  0.00025       41  train_cluster_1_1
15  0.0  0.00000  0.00000       42  train_cluster_1_1
16  0.0  0.00000  0.00000       43  train_cluster_1_1
17  0.0  0.00000  0.00000       44  train_cluster_1_1
18  0.0  0.00000  0.00000       45  train_cluster_1_1
19  0.0  0.00000  0.00003       46  train_cluster_1_1
20  0.0  0.00001  0.00006       47  train_cluster_1_1
21  0.0  0.00000  0.00004       48  train_cluster_1_1
22  0.0  0.14248  0.14363       49  train_cluster_1_1
23  0.0  0.00009  0.00090       50  train_cluster_1_1
24  0.0  0.00000  0.00000       51  train_cluster_1_1
25  0.0  0.00000  0.00000       52  train_cluster_1_1
26  0.0  0.00000  0.00000       53  train_cluster_1_1
27  0.0  0.00075  0.00715       54  train_cluster_1_1
28  0.0  0.00071  0.00675       55  train_cluster_1_1
29  0.0  0.00060  0.00579       56  train_cluster_1_1
30  0.0  0.00001  0.00012       58  train_cluster_1_1
31  0.0  0.00001  0.00008       59  train_cluster_1_1
32  0.0  0.16216  0.28406       89  train_cluster_1_1
33  0.0  0.14968  0.26221       90  train_cluster_1_1
34  0.0  0.12972  0.22725       91  train_cluster_1_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00001  0.00009        0  val_cluster_1_1
1   0.0  0.09091  0.09091        1  val_cluster_1_1
2   0.0  0.07144  0.07151        2  val_cluster_1_1
3   0.0  0.05558  0.05581        3  val_cluster_1_1
4   0.0  0.10000  0.10000        4  val_cluster_1_1
5   0.0  0.07693  0.07701        5  val_cluster_1_1
6   0.0  0.05885  0.05909        6  val_cluster_1_1
7   0.0  0.11111  0.11111        7  val_cluster_1_1
8   0.0  0.09092  0.09102        8  val_cluster_1_1
9   0.0  0.08334  0.08343        9  val_cluster_1_1
10  0.0  0.06670  0.06697       10  val_cluster_1_1
11  0.0  0.06253  0.06279       11  val_cluster_1_1
12  0.0  0.14286  0.14286       12  val_cluster_1_1
13  0.0  0.11112  0.11124       13  val_cluster_1_1
14  0.0  0.10001  0.10012       14  val_cluster_1_1
15  0.0  0.08337  0.08371       15  val_cluster_1_1
16  0.0  0.07146  0.07175       16  val_cluster_1_1
17  0.0  0.00006  0.00058       17  val_cluster_1_1
18  0.0  0.00000  0.00000       18  val_cluster_1_1
19  0.0  0.00000  0.00000       19  val_cluster_1_1
20  0.0  0.00000  0.00000       20  val_cluster_1_1
21  0.0  0.00000  0.00002       26  val_cluster_1_1
22  0.0  0.00000  0.00002       28  val_cluster_1_1
23  0.0  0.00056  0.00541       29  val_cluster_1_1
24  0.0  0.00107  0.01031       30  val_cluster_1_1
25  0.0  0.00079  0.00756       31  val_cluster_1_1
26  0.0  0.00084  0.00810       32  val_cluster_1_1
27  0.0  0.00001  0.00007       57  val_cluster_1_1
28  0.0  0.00001  0.00007       60  val_cluster_1_1
29  0.0  0.00001  0.00007       61  val_cluster_1_1
30  0.0  0.00001  0.00009       62  val_cluster_1_1
31  0.0  0.00001  0.00010       63  val_cluster_1_1
32  0.0  0.00000  0.00000       64  val_cluster_1_1
33  0.0  0.00000  0.00000       65  val_cluster_1_1
34  0.0  0.00000  0.00000       66  val_cluster_1_1
35  0.0  0.00000  0.00000       67  val_cluster_1_1
36  0.0  0.00000  0.00000       68  val_cluster_1_1
37  0.0  0.00000  0.00000       69  val_cluster_1_1
38  0.0  0.00001  0.00007       70  val_cluster_1_1
39  0.0  0.00000  0.00003       71  val_cluster_1_1
40  0.0  0.00001  0.00009       72  val_cluster_1_1
41  0.0  0.00000  0.00004       73  val_cluster_1_1
42  0.0  0.00000  0.00003       74  val_cluster_1_1
43  0.0  0.00000  0.00004       75  val_cluster_1_1
44  0.0  0.00000  0.00000       76  val_cluster_1_1
45  0.0  0.00000  0.00000       77  val_cluster_1_1
46  0.0  0.00291  0.02741       78  val_cluster_1_1
47  0.0  0.00000  0.00000       79  val_cluster_1_1
48  0.0  0.00000  0.00000       80  val_cluster_1_1
49  0.0  0.00000  0.00004       81  val_cluster_1_1
50  0.0  0.00000  0.00003       82  val_cluster_1_1
51  0.0  0.00000  0.00003       83  val_cluster_1_1
52  0.0  0.00000  0.00003       84  val_cluster_1_1
53  0.0  0.00000  0.00003       85  val_cluster_1_1
54  0.0  0.00001  0.00005       86  val_cluster_1_1
55  0.0  0.00000  0.00004       87  val_cluster_1_1
56  0.0  0.00001  0.00005       88  val_cluster_1_1
57  0.0  0.10810  0.18937       92  val_cluster_1_1
58  0.0  0.00000  0.00000       93  val_cluster_1_1
59  0.0  0.00000  0.00000       94  val_cluster_1_1
60  0.0  0.00000  0.00000       95  val_cluster_1_1
61  0.0  0.00000  0.00000       96  val_cluster_1_1
62  0.0  0.00000  0.00000       97  val_cluster_1_1
63  0.0  0.00000  0.00000       98  val_cluster_1_1
64  0.0  0.10526  0.10531       99  val_cluster_1_1
65  0.0  0.11111  0.11116      100  val_cluster_1_1
66  0.0  0.10526  0.10531      101  val_cluster_1_1
67  0.0  0.12500  0.12506      102  val_cluster_1_1
68  0.0  0.11765  0.11770      103  val_cluster_1_1
69  0.0  0.10000  0.10004      104  val_cluster_1_1
70  0.0  0.13333  0.13339      105  val_cluster_1_1
71  0.0  0.11111  0.11116      106  val_cluster_1_1
72  0.0  0.11765  0.11770      107  val_cluster_1_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                            name split_type
0    cluster_1_Sp_res_neighbours         Sp
1    cluster_1_Sp_res_neighbours         Sp
2    cluster_1_Sp_res_neighbours         Sp
3    cluster_1_Sp_res_neighbours         Sp
4    cluster_1_Sp_res_neighbours         Sp
5    cluster_1_Sp_res_neighbours         Sp
6    cluster_1_Sp_res_neighbours         Sp
7    cluster_1_Sp_res_neighbours         Sp
8    cluster_1_Sp_res_neighbours         Sp
9    cluster_1_Sp_res_neighbours         Sp
10   cluster_1_Sp_res_neighbours         Sp
11   cluster_1_Sp_res_neighbours         Sp
12   cluster_1_Sp_res_neighbours         Sp
13   cluster_1_Sp_res_neighbours         Sp
14   cluster_1_Sp_res_neighbours         Sp
15   cluster_1_Sp_res_neighbours         Sp
16   cluster_1_Sp_res_neighbours         Sp
17   cluster_1_Sp_res_neighbours         Sp
18   cluster_1_Sp_res_neighbours         Sp
19   cluster_1_Sp_res_neighbours         Sp
20   cluster_1_Sp_res_neighbours         Sp
21   cluster_1_Sp_res_neighbours         Sp
22   cluster_1_Sp_res_neighbours         Sp
23   cluster_1_Sp_res_neighbours         Sp
24   cluster_1_Sp_res_neighbours         Sp
25   cluster_1_Sp_res_neighbours         Sp
26   cluster_1_Sp_res_neighbours         Sp
27   cluster_1_Sp_res_neighbours         Sp
28   cluster_1_Sp_res_neighbours         Sp
29   cluster_1_Sp_res_neighbours         Sp
30   cluster_1_Sp_res_neighbours         Sp
31   cluster_1_Sp_res_neighbours         Sp
32   cluster_1_Sp_res_neighbours         Sp
33   cluster_1_Sp_res_neighbours         Sp
34   cluster_1_Sp_res_neighbours         Sp
35   cluster_1_Sp_res_neighbours         Sp
36   cluster_1_Sp_res_neighbours         Sp
37   cluster_1_Sp_res_neighbours         Sp
38   cluster_1_Sp_res_neighbours         Sp
39   cluster_1_Sp_res_neighbours         Sp
40   cluster_1_Sp_res_neighbours         Sp
41   cluster_1_Sp_res_neighbours         Sp
42   cluster_1_Sp_res_neighbours         Sp
43   cluster_1_Sp_res_neighbours         Sp
44   cluster_1_Sp_res_neighbours         Sp
45   cluster_1_Sp_res_neighbours         Sp
46   cluster_1_Sp_res_neighbours         Sp
47   cluster_1_Sp_res_neighbours         Sp
48   cluster_1_Sp_res_neighbours         Sp
49   cluster_1_Sp_res_neighbours         Sp
50   cluster_1_Sp_res_neighbours         Sp
51   cluster_1_Sp_res_neighbours         Sp
52   cluster_1_Sp_res_neighbours         Sp
53   cluster_1_Sp_res_neighbours         Sp
54   cluster_1_Sp_res_neighbours         Sp
55   cluster_1_Sp_res_neighbours         Sp
56   cluster_1_Sp_res_neighbours         Sp
57   cluster_1_Sp_res_neighbours         Sp
58   cluster_1_Sp_res_neighbours         Sp
59   cluster_1_Sp_res_neighbours         Sp
60   cluster_1_Sp_res_neighbours         Sp
61   cluster_1_Sp_res_neighbours         Sp
62   cluster_1_Sp_res_neighbours         Sp
63   cluster_1_Sp_res_neighbours         Sp
64   cluster_1_Sp_res_neighbours         Sp
65   cluster_1_Sp_res_neighbours         Sp
66   cluster_1_Sp_res_neighbours         Sp
67   cluster_1_Sp_res_neighbours         Sp
68   cluster_1_Sp_res_neighbours         Sp
69   cluster_1_Sp_res_neighbours         Sp
70   cluster_1_Sp_res_neighbours         Sp
71   cluster_1_Sp_res_neighbours         Sp
72   cluster_1_Sp_res_neighbours         Sp
73   cluster_1_Sp_res_neighbours         Sp
74   cluster_1_Sp_res_neighbours         Sp
75   cluster_1_Sp_res_neighbours         Sp
76   cluster_1_Sp_res_neighbours         Sp
77   cluster_1_Sp_res_neighbours         Sp
78   cluster_1_Sp_res_neighbours         Sp
79   cluster_1_Sp_res_neighbours         Sp
80   cluster_1_Sp_res_neighbours         Sp
81   cluster_1_Sp_res_neighbours         Sp
82   cluster_1_Sp_res_neighbours         Sp
83   cluster_1_Sp_res_neighbours         Sp
84   cluster_1_Sp_res_neighbours         Sp
85   cluster_1_Sp_res_neighbours         Sp
86   cluster_1_Sp_res_neighbours         Sp
87   cluster_1_Sp_res_neighbours         Sp
88   cluster_1_Sp_res_neighbours         Sp
89   cluster_1_Sp_res_neighbours         Sp
90   cluster_1_Sp_res_neighbours         Sp
91   cluster_1_Sp_res_neighbours         Sp
92   cluster_1_Sp_res_neighbours         Sp
93   cluster_1_Sp_res_neighbours         Sp
94   cluster_1_Sp_res_neighbours         Sp
95   cluster_1_Sp_res_neighbours         Sp
96   cluster_1_Sp_res_neighbours         Sp
97   cluster_1_Sp_res_neighbours         Sp
98   cluster_1_Sp_res_neighbours         Sp
99   cluster_1_Sp_res_neighbours         Sp
100  cluster_1_Sp_res_neighbours         Sp
101  cluster_1_Sp_res_neighbours         Sp
102  cluster_1_Sp_res_neighbours         Sp
103  cluster_1_Sp_res_neighbours         Sp
104  cluster_1_Sp_res_neighbours         Sp
105  cluster_1_Sp_res_neighbours         Sp
106  cluster_1_Sp_res_neighbours         Sp
107  cluster_1_Sp_res_neighbours         Sp  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
conda run -n HDXER_ENV python /home/alexi/Documents/HDXer/HDXer/calc_hdx.py -t /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1_clustered_cfrac1_0.5_.xtc -p /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb -m BestVendruscolo -log /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/prep_HOIPapo_test_mean13_0/calc_hdx_prep_HOIPapo_test_mean13_0.log -out /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/prep_HOIPapo_test_mean13_0/out__prep_HOIPapo_test_mean13_0 -seg /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_APO_segs.txt -mopt "{ 'save_detailed' : True }" --times 0 0.5 5.0 -str 1
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
Residue predictions complete

Splitting segments for HOIPapo_test_mean1_RW by redundancy mk III
centrality
1    1509
Name: count, dtype: int64
Residue intersection:  [150 151 152 153]
Intersection peptides:  [55 56 57 58 59 60 61]
0.06481481481481481
Train peptides:  [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107]
0.3148148148148148
Val peptides:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 81 82 83 84 85 86 87 88 89 90 91 92]
0.6203703703703703
train_segs
    ResStr  ResEnd  peptide                      calc_name
62     154     169       62  train_HOIPapo_test_mean1_RW_1
63     155     169       63  train_HOIPapo_test_mean1_RW_1
64     169     183       64  train_HOIPapo_test_mean1_RW_1
65     170     183       65  train_HOIPapo_test_mean1_RW_1
66     170     185       66  train_HOIPapo_test_mean1_RW_1
Saved train HOIPapo_test_mean1_RW_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/train_residue_segs__HOIPapo_test_mean1_RW_.txt
Train Peptide numbers: [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107]
Saved val HOIPapo_test_mean1_RW_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/val_HOIPapo_test_mean1_RW_1/val_residue_segs__HOIPapo_test_mean1_RW_.txt
Val Peptide numbers: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 81 82 83 84 85 86 87 88 89 90 91 92]
train_HDX_data
    0.0      0.5      5.0  peptide                      calc_name  \
0   0.0  0.50341  0.53212       62  train_HOIPapo_test_mean1_RW_1
1   0.0  0.53500  0.53827       63  train_HOIPapo_test_mean1_RW_1
2   0.0  0.26524  0.35365       64  train_HOIPapo_test_mean1_RW_1
3   0.0  0.25454  0.32548       65  train_HOIPapo_test_mean1_RW_1
4   0.0  0.25152  0.35786       66  train_HOIPapo_test_mean1_RW_1
5   0.0  0.28164  0.36568       67  train_HOIPapo_test_mean1_RW_1
6   0.0  0.24177  0.30174       68  train_HOIPapo_test_mean1_RW_1
7   0.0  0.27969  0.36567       69  train_HOIPapo_test_mean1_RW_1
8   0.0  0.38633  0.44869       70  train_HOIPapo_test_mean1_RW_1
9   0.0  0.24871  0.31226       71  train_HOIPapo_test_mean1_RW_1
10  0.0  0.36820  0.37879       72  train_HOIPapo_test_mean1_RW_1
11  0.0  0.22903  0.26839       73  train_HOIPapo_test_mean1_RW_1
12  0.0  0.21687  0.25989       74  train_HOIPapo_test_mean1_RW_1
13  0.0  0.20479  0.23593       75  train_HOIPapo_test_mean1_RW_1
14  0.0  0.11684  0.15140       76  train_HOIPapo_test_mean1_RW_1
15  0.0  0.13267  0.18143       77  train_HOIPapo_test_mean1_RW_1
16  0.0  0.35203  0.42601       78  train_HOIPapo_test_mean1_RW_1
17  0.0  0.20249  0.21472       79  train_HOIPapo_test_mean1_RW_1
18  0.0  0.16260  0.17496       80  train_HOIPapo_test_mean1_RW_1
19  0.0  0.06500  0.10668       93  train_HOIPapo_test_mean1_RW_1
20  0.0  0.06362  0.10593       94  train_HOIPapo_test_mean1_RW_1
21  0.0  0.04358  0.04371       95  train_HOIPapo_test_mean1_RW_1
22  0.0  0.08151  0.10674       96  train_HOIPapo_test_mean1_RW_1
23  0.0  0.08795  0.11537       97  train_HOIPapo_test_mean1_RW_1
24  0.0  0.09261  0.12297       98  train_HOIPapo_test_mean1_RW_1
25  0.0  0.17298  0.20225       99  train_HOIPapo_test_mean1_RW_1
26  0.0  0.20729  0.23030      100  train_HOIPapo_test_mean1_RW_1
27  0.0  0.20401  0.23454      101  train_HOIPapo_test_mean1_RW_1
28  0.0  0.21943  0.23426      102  train_HOIPapo_test_mean1_RW_1
29  0.0  0.21731  0.24442      103  train_HOIPapo_test_mean1_RW_1
30  0.0  0.22028  0.25199      104  train_HOIPapo_test_mean1_RW_1
31  0.0  0.22217  0.24175      105  train_HOIPapo_test_mean1_RW_1
32  0.0  0.22454  0.24966      106  train_HOIPapo_test_mean1_RW_1
33  0.0  0.23913  0.27068      107  train_HOIPapo_test_mean1_RW_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     154     169
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     155     169
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     169     183
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     183
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     185
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     186
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     183
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     186
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     184     195
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     184     208
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     195
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     208
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     209
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     188     208
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     194     208
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     196     208
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     213     223
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     238
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     239
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     305     313
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     305     315
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     308     315
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     314     327
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     316     327
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     317     327
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     333     356
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     356
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     357
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     356
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     357
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     360
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     357
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     360
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     339     360
    ResStr  ResEnd  0.0      0.5      5.0  peptide  \
0      154     169  0.0  0.50341  0.53212       62
1      155     169  0.0  0.53500  0.53827       63
2      169     183  0.0  0.26524  0.35365       64
3      170     183  0.0  0.25454  0.32548       65
4      170     185  0.0  0.25152  0.35786       66
5      170     186  0.0  0.28164  0.36568       67
6      171     183  0.0  0.24177  0.30174       68
7      171     186  0.0  0.27969  0.36567       69
8      184     195  0.0  0.38633  0.44869       70
9      184     208  0.0  0.24871  0.31226       71
10     187     195  0.0  0.36820  0.37879       72
11     187     208  0.0  0.22903  0.26839       73
12     187     209  0.0  0.21687  0.25989       74
13     188     208  0.0  0.20479  0.23593       75
14     194     208  0.0  0.11684  0.15140       76
15     196     208  0.0  0.13267  0.18143       77
16     213     223  0.0  0.35203  0.42601       78
17     224     238  0.0  0.20249  0.21472       79
18     224     239  0.0  0.16260  0.17496       80
19     305     313  0.0  0.06500  0.10668       93
20     305     315  0.0  0.06362  0.10593       94
21     308     315  0.0  0.04358  0.04371       95
22     314     327  0.0  0.08151  0.10674       96
23     316     327  0.0  0.08795  0.11537       97
24     317     327  0.0  0.09261  0.12297       98
25     333     356  0.0  0.17298  0.20225       99
26     334     356  0.0  0.20729  0.23030      100
27     334     357  0.0  0.20401  0.23454      101
28     336     356  0.0  0.21943  0.23426      102
29     336     357  0.0  0.21731  0.24442      103
30     336     360  0.0  0.22028  0.25199      104
31     338     357  0.0  0.22217  0.24175      105
32     338     360  0.0  0.22454  0.24966      106
33     339     360  0.0  0.23913  0.27068      107

                        calc_name  \
0   train_HOIPapo_test_mean1_RW_1
1   train_HOIPapo_test_mean1_RW_1
2   train_HOIPapo_test_mean1_RW_1
3   train_HOIPapo_test_mean1_RW_1
4   train_HOIPapo_test_mean1_RW_1
5   train_HOIPapo_test_mean1_RW_1
6   train_HOIPapo_test_mean1_RW_1
7   train_HOIPapo_test_mean1_RW_1
8   train_HOIPapo_test_mean1_RW_1
9   train_HOIPapo_test_mean1_RW_1
10  train_HOIPapo_test_mean1_RW_1
11  train_HOIPapo_test_mean1_RW_1
12  train_HOIPapo_test_mean1_RW_1
13  train_HOIPapo_test_mean1_RW_1
14  train_HOIPapo_test_mean1_RW_1
15  train_HOIPapo_test_mean1_RW_1
16  train_HOIPapo_test_mean1_RW_1
17  train_HOIPapo_test_mean1_RW_1
18  train_HOIPapo_test_mean1_RW_1
19  train_HOIPapo_test_mean1_RW_1
20  train_HOIPapo_test_mean1_RW_1
21  train_HOIPapo_test_mean1_RW_1
22  train_HOIPapo_test_mean1_RW_1
23  train_HOIPapo_test_mean1_RW_1
24  train_HOIPapo_test_mean1_RW_1
25  train_HOIPapo_test_mean1_RW_1
26  train_HOIPapo_test_mean1_RW_1
27  train_HOIPapo_test_mean1_RW_1
28  train_HOIPapo_test_mean1_RW_1
29  train_HOIPapo_test_mean1_RW_1
30  train_HOIPapo_test_mean1_RW_1
31  train_HOIPapo_test_mean1_RW_1
32  train_HOIPapo_test_mean1_RW_1
33  train_HOIPapo_test_mean1_RW_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train HOIPapo_test_mean1_RW HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/train_HOIPapo_test_mean1_RW_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide  \
0        1       7  0.0  0.41879  0.44438        0
1        6      18  0.0  0.37096  0.45204        1
2        6      21  0.0  0.40040  0.48544        2
3        6      25  0.0  0.45875  0.51503        3
4        7      18  0.0  0.41726  0.49519        4
5        7      21  0.0  0.44176  0.50927        5
6        7      25  0.0  0.48987  0.54090        6
7        8      18  0.0  0.41316  0.48254        7
8        8      20  0.0  0.46617  0.51066        8
9        8      21  0.0  0.46825  0.52028        9
10       8      24  0.0  0.48273  0.53102       10
11       8      25  0.0  0.50258  0.53988       11
12      11      18  0.0  0.47373  0.50144       12
13      11      20  0.0  0.52057  0.54102       13
14      11      21  0.0  0.52823  0.55640       14
15      11      23  0.0  0.55802  0.57504       15
16      11      25  0.0  0.55641  0.57196       16
17      19      25  0.0  0.52928  0.54827       17
18      26      32  0.0  0.17163  0.27883       18
19      26      33  0.0  0.16883  0.28686       19
20      27      33  0.0  0.16341  0.27353       20
21      33      40  0.0  0.32309  0.41205       21
22      34      40  0.0  0.31355  0.39928       22
23      34      41  0.0  0.34392  0.42213       23
24      41      48  0.0  0.35604  0.35617       24
25      41      49  0.0  0.34105  0.35125       25
26      41      51  0.0  0.34135  0.38830       26
27      42      49  0.0  0.28512  0.29602       27
28      42      51  0.0  0.28439  0.33185       28
29      42      65  0.0  0.32954  0.39085       29
30      49      61  0.0  0.26192  0.34619       30
31      49      65  0.0  0.31421  0.37857       31
32      50      65  0.0  0.32314  0.38565       32
33      52      61  0.0  0.29666  0.37860       33
34      52      65  0.0  0.38440  0.44775       34
35      74      84  0.0  0.33633  0.46390       35
36      76      84  0.0  0.34716  0.45807       36
37      77      84  0.0  0.34165  0.44393       37
38      77      85  0.0  0.30725  0.43533       38
39      77      87  0.0  0.33252  0.48976       39
40      77      88  0.0  0.28369  0.42940       40
41      77      97  0.0  0.35906  0.50293       41
42      85      97  0.0  0.33575  0.45181       42
43      86      97  0.0  0.33443  0.43697       43
44      88      97  0.0  0.37082  0.47284       44
45      89      97  0.0  0.37847  0.48848       45
46      98     104  0.0  0.22218  0.31040       46
47      98     106  0.0  0.18217  0.28305       47
48      98     108  0.0  0.25719  0.37045       48
49     113     120  0.0  0.49756  0.50850       49
50     114     120  0.0  0.55024  0.54326       50
51     117     131  0.0  0.24310  0.29208       51
52     121     131  0.0  0.19173  0.23972       52
53     121     132  0.0  0.18105  0.23003       53
54     132     149  0.0  0.26140  0.30267       54
55     247     257  0.0  0.05688  0.07274       81
56     247     259  0.0  0.07600  0.11464       82
57     247     260  0.0  0.08147  0.13526       83
58     248     259  0.0  0.08527  0.13242       84
59     248     260  0.0  0.08569  0.14304       85
60     250     257  0.0  0.06291  0.07885       86
61     250     260  0.0  0.09393  0.16201       87
62     253     260  0.0  0.10385  0.19651       88
63     261     275  0.0  0.53877  0.49943       89
64     261     276  0.0  0.51417  0.47866       90
65     261     278  0.0  0.50107  0.49072       91
66     261     281  0.0  0.45551  0.47280       92

                      calc_name  \
0   val_HOIPapo_test_mean1_RW_1
1   val_HOIPapo_test_mean1_RW_1
2   val_HOIPapo_test_mean1_RW_1
3   val_HOIPapo_test_mean1_RW_1
4   val_HOIPapo_test_mean1_RW_1
5   val_HOIPapo_test_mean1_RW_1
6   val_HOIPapo_test_mean1_RW_1
7   val_HOIPapo_test_mean1_RW_1
8   val_HOIPapo_test_mean1_RW_1
9   val_HOIPapo_test_mean1_RW_1
10  val_HOIPapo_test_mean1_RW_1
11  val_HOIPapo_test_mean1_RW_1
12  val_HOIPapo_test_mean1_RW_1
13  val_HOIPapo_test_mean1_RW_1
14  val_HOIPapo_test_mean1_RW_1
15  val_HOIPapo_test_mean1_RW_1
16  val_HOIPapo_test_mean1_RW_1
17  val_HOIPapo_test_mean1_RW_1
18  val_HOIPapo_test_mean1_RW_1
19  val_HOIPapo_test_mean1_RW_1
20  val_HOIPapo_test_mean1_RW_1
21  val_HOIPapo_test_mean1_RW_1
22  val_HOIPapo_test_mean1_RW_1
23  val_HOIPapo_test_mean1_RW_1
24  val_HOIPapo_test_mean1_RW_1
25  val_HOIPapo_test_mean1_RW_1
26  val_HOIPapo_test_mean1_RW_1
27  val_HOIPapo_test_mean1_RW_1
28  val_HOIPapo_test_mean1_RW_1
29  val_HOIPapo_test_mean1_RW_1
30  val_HOIPapo_test_mean1_RW_1
31  val_HOIPapo_test_mean1_RW_1
32  val_HOIPapo_test_mean1_RW_1
33  val_HOIPapo_test_mean1_RW_1
34  val_HOIPapo_test_mean1_RW_1
35  val_HOIPapo_test_mean1_RW_1
36  val_HOIPapo_test_mean1_RW_1
37  val_HOIPapo_test_mean1_RW_1
38  val_HOIPapo_test_mean1_RW_1
39  val_HOIPapo_test_mean1_RW_1
40  val_HOIPapo_test_mean1_RW_1
41  val_HOIPapo_test_mean1_RW_1
42  val_HOIPapo_test_mean1_RW_1
43  val_HOIPapo_test_mean1_RW_1
44  val_HOIPapo_test_mean1_RW_1
45  val_HOIPapo_test_mean1_RW_1
46  val_HOIPapo_test_mean1_RW_1
47  val_HOIPapo_test_mean1_RW_1
48  val_HOIPapo_test_mean1_RW_1
49  val_HOIPapo_test_mean1_RW_1
50  val_HOIPapo_test_mean1_RW_1
51  val_HOIPapo_test_mean1_RW_1
52  val_HOIPapo_test_mean1_RW_1
53  val_HOIPapo_test_mean1_RW_1
54  val_HOIPapo_test_mean1_RW_1
55  val_HOIPapo_test_mean1_RW_1
56  val_HOIPapo_test_mean1_RW_1
57  val_HOIPapo_test_mean1_RW_1
58  val_HOIPapo_test_mean1_RW_1
59  val_HOIPapo_test_mean1_RW_1
60  val_HOIPapo_test_mean1_RW_1
61  val_HOIPapo_test_mean1_RW_1
62  val_HOIPapo_test_mean1_RW_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/mdtraj/formats/pdb/pdbfile.py:200: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
/home/alexi/Documents/HDXer/HDXer/dfpred.py:505: RuntimeWarning: divide by zero encountered in log
  logerr = logf + np.log(err) + np.log(time) # sd(e^Aa) = f * sd(A) * a
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/reweighting_gamma_2x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/reweighting_gamma_3x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/reweighting_gamma_5x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/train_HOIPapo_test_mean1_RW_1/reweighting_gamma_4x10^0



Contacts readContacts read

Contacts read
Hbonds readHbonds read

Hbonds readContacts read

Hbonds readSegments and experimental dfracs read
Segments and experimental dfracs read

Segments and experimental dfracs read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Sum of Output Weights
1.0
Sum of Output Weights
1.0
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([1.51639262e-03, 1.69799397e-03, 1.66233318e-05, 1.30424020e-04,
       2.09492850e-03, 2.32423479e-03, 5.23669253e-04, 1.68778929e-03,
       2.78691687e-03, 2.99725623e-03, 9.63347256e-04, 1.36233472e-04,
       2.41077827e-03, 3.47768754e-03, 1.36214105e-03, 1.55810427e-03,
       1.34746328e-03, 9.70617843e-04, 1.14842883e-03, 9.88420425e-04,
       2.88674389e-03, 2.22820524e-03, 2.65615703e-03, 7.82310920e-04,
       3.73740631e-03, 1.02901458e-03, 1.55212676e-03, 4.38571901e-04,
       1.61960887e-03, 4.88786526e-03, 5.95263410e-04, 4.16531625e-03,
       1.09350141e-04, 6.67668604e-04, 1.04345791e-03, 1.48758090e-03,
       2.60722937e-03, 1.51515380e-03, 2.10205039e-03, 1.94600940e-03,
       1.24142520e-03, 3.54226424e-03, 1.84087344e-05, 1.74239823e-03,
       1.06894387e-03, 2.44608787e-03, 5.17732382e-04, 1.27540133e-05,
       1.29094640e-03, 3.33670485e-03, 9.08325519e-04, 1.55852819e-03,
       8.15211189e-04, 2.10794888e-03, 6.57454741e-04, 4.90712113e-03,
       2.10633415e-03, 2.47020421e-03, 4.48677996e-03, 2.28467713e-03,
       6.29764819e-04, 3.71414271e-03, 7.41187312e-04, 2.02549774e-03,
       5.12422200e-04, 1.77067055e-03, 1.23064922e-03, 2.27259920e-03,
       3.08745108e-03, 2.87949869e-03, 1.84660858e-03, 2.76072991e-03,
       1.85083504e-03, 1.86614867e-03, 2.76394063e-03, 2.51027703e-03,
       6.42250083e-04, 1.44111633e-03, 3.05571835e-04, 1.32683606e-03,
       2.70509956e-03, 1.97317895e-03, 4.46569476e-03, 3.07074479e-03,
       3.33474046e-04, 5.03863418e-04, 3.17116845e-03, 2.18929860e-03,
       1.14438391e-03, 3.30876248e-03, 2.08524976e-03, 2.45934030e-03,
       3.80026350e-03, 7.44610022e-04, 3.33464237e-04, 1.78993179e-03,
       5.86352021e-04, 1.40626756e-03, 1.50281035e-03, 2.00771668e-03,
       1.29516216e-03, 8.42697403e-04, 2.20863945e-03, 1.33720284e-03,
       2.71865971e-03, 2.41265231e-04, 7.88108369e-04, 8.80086004e-04,
       3.89974256e-03, 4.75675282e-03, 1.10182626e-03, 3.73713189e-03,
       1.91872714e-03, 2.09870021e-03, 1.48015717e-03, 2.33498667e-03,
       2.07281006e-03, 1.74706848e-03, 2.08768074e-03, 1.32634446e-03,
       3.11115465e-04, 2.01989244e-03, 5.05406817e-04, 3.12772964e-03,
       1.06965976e-03, 2.74041301e-03, 3.10586765e-04, 1.42284866e-03,
       3.47787865e-03, 1.77482883e-03, 3.76853158e-05, 1.52608957e-03,
       8.89009651e-04, 8.62094016e-04, 1.56740401e-03, 1.88385822e-03,
       1.54421398e-03, 4.49976023e-03, 2.38646003e-05, 2.26893143e-03,
       3.48577505e-04, 1.97196006e-03, 1.25558654e-03, 1.05135340e-03,
       2.81958744e-03, 1.21738918e-03, 2.48486858e-03, 1.90069510e-03,
       3.41683004e-03, 1.83114030e-03, 4.71257780e-04, 3.54555137e-03,
       3.09242560e-03, 2.35310714e-03, 7.20976547e-04, 2.10162044e-03,
       1.26472654e-03, 8.40961310e-04, 2.40666796e-03, 5.78441174e-03,
       3.50688011e-05, 2.57243707e-03, 2.39579251e-03, 2.82964994e-03,
       2.47117750e-03, 1.87061159e-03, 3.69033065e-04, 2.97885347e-03,
       9.27508002e-04, 3.77770928e-03, 1.43000391e-03, 3.29555237e-03,
       6.82322652e-04, 2.31795676e-03, 3.59500774e-03, 1.74618737e-03,
       2.59183396e-03, 6.37858485e-04, 1.29001147e-03, 1.80408674e-03,
       1.83311656e-03, 9.21157954e-04, 2.39483826e-03, 2.38215921e-03,
       1.40785778e-04, 1.33234849e-03, 1.82118314e-03, 1.54231828e-04,
       9.76221083e-04, 8.41350948e-04, 1.42416014e-03, 8.62727552e-04,
       6.65187928e-04, 2.10406178e-03, 2.55868151e-03, 1.47559764e-03,
       1.31794649e-03, 3.34676381e-03, 6.32109383e-05, 2.54938432e-03,
       3.13745081e-03, 5.16327006e-04, 5.95718954e-04, 2.12793875e-03,
       1.25132471e-03, 3.82065064e-03, 2.66131300e-03, 2.53823377e-03,
       1.10542378e-03, 4.25108767e-03, 9.65968333e-04, 1.59026284e-03,
       1.99628725e-03, 3.98397066e-04, 9.66568979e-05, 1.81473276e-03,
       2.44433742e-03, 1.83006393e-04, 3.49773559e-03, 6.44309161e-04,
       3.31662723e-03, 2.31517416e-03, 2.47832209e-03, 9.28231215e-04,
       3.36953381e-03, 4.89199430e-05, 2.68927166e-04, 1.01742844e-03,
       2.78363432e-03, 1.14149522e-03, 8.92734963e-04, 9.44123241e-04,
       5.08807714e-04, 6.37758369e-03, 5.67265926e-04, 4.14496392e-03,
       1.24101619e-03, 1.37381984e-03, 1.23701229e-03, 2.92422421e-03,
       7.92735928e-04, 7.65016195e-05, 1.65929123e-03, 2.83254038e-03,
       2.12166048e-03, 1.26669828e-04, 1.53393461e-03, 1.50762225e-03,
       4.16515412e-04, 2.32428547e-04, 4.55308413e-04, 3.82086624e-03,
       6.62473522e-04, 1.51979999e-03, 1.51311219e-03, 1.43624184e-03,
       2.10520803e-03, 4.85771444e-04, 4.77650593e-03, 1.36804660e-03,
       2.65323748e-03, 4.91482745e-03, 1.28042016e-03, 4.25466461e-04,
       1.34282837e-03, 6.22632020e-04, 1.83779096e-03, 1.72474187e-03,
       1.99622535e-03, 2.88050387e-03, 1.91429712e-04, 1.54547455e-05,
       1.31439138e-05, 1.06818601e-06, 1.08377728e-03, 2.93207396e-03,
       2.57182503e-03, 1.82215219e-03, 2.35819478e-03, 2.88083584e-03,
       3.61125008e-03, 3.33518501e-03, 4.57163103e-03, 1.93880502e-03,
       1.57261331e-03, 3.43266190e-03, 2.32976003e-03, 8.69135450e-04,
       2.15551246e-03, 4.12263897e-03, 1.86288211e-03, 1.25164537e-03,
       1.25672751e-03, 3.73145977e-05, 1.29768473e-03, 2.65625606e-03,
       8.62936318e-04, 1.57368249e-03, 1.32906137e-04, 1.63370732e-03,
       3.42130638e-03, 8.75004541e-04, 3.02183523e-03, 2.50359463e-03,
       5.60441644e-03, 2.88378609e-03, 3.22837524e-03, 2.92669801e-04,
       8.46436132e-05, 5.18524333e-03, 1.89677836e-03, 1.99381645e-03,
       2.82422644e-03, 4.02622283e-03, 1.28867813e-03, 1.59005539e-03,
       2.64551078e-03, 2.41990766e-03, 4.78237259e-04, 3.03312696e-03,
       3.92904335e-04, 8.32046506e-04, 2.30010463e-03, 3.43576428e-03,
       1.78420393e-04, 3.13649188e-05, 1.38507389e-03, 3.42728702e-03,
       1.27067694e-03, 2.50111335e-03, 2.15385821e-03, 1.53483503e-03,
       2.35610154e-03, 2.42901726e-03, 6.41230575e-04, 2.06201785e-03,
       1.13733146e-03, 8.49130569e-04, 8.16338736e-04, 3.09894707e-03,
       3.69617662e-03, 2.74838813e-03, 2.25696917e-03, 1.42881028e-03,
       2.42400422e-03, 6.21974639e-04, 5.00504612e-05, 1.26441222e-03,
       1.09736511e-03, 8.42181609e-04, 3.11160928e-03, 3.18832255e-04,
       1.51953594e-03, 3.39838216e-03, 5.67384167e-04, 2.46084226e-03,
       1.06108841e-03, 2.40210527e-03, 7.11099439e-04, 2.16409256e-03,
       2.77948987e-03, 5.53658679e-04, 2.62754551e-03, 4.36260689e-03,
       1.79248623e-03, 1.09771420e-03, 2.60661373e-04, 3.91783947e-03,
       7.23181779e-04, 8.07590221e-04, 2.91873193e-03, 3.50954264e-03,
       2.38076121e-04, 2.78825544e-03, 1.86272076e-03, 1.94690840e-04,
       1.42218217e-03, 2.62082447e-03, 1.66306793e-03, 2.09887836e-05,
       6.64724113e-04, 3.75097704e-04, 2.71088549e-03, 1.72673084e-03,
       2.99791357e-03, 6.72780629e-04, 1.29796375e-03, 7.12763918e-04,
       2.26786931e-03, 2.79775267e-03, 1.16962483e-03, 2.59014544e-03,
       8.51860831e-04, 2.32160696e-03, 9.87223001e-04, 7.56213616e-04,
       3.18485969e-03, 5.78946911e-03, 8.08043383e-04, 1.49992103e-03,
       6.26206903e-03, 3.90109182e-03, 1.46535027e-03, 1.13618086e-03,
       2.50413726e-03, 9.65827285e-04, 3.35559179e-03, 1.87464176e-03,
       2.42748590e-03, 7.11809936e-04, 2.05325808e-03, 1.72583808e-04,
       1.66841810e-03, 6.40865023e-04, 3.60225365e-04, 1.05314273e-03,
       1.81877902e-03, 1.08767273e-03, 2.74753373e-03, 5.51822034e-04,
       3.02643116e-03, 2.56322384e-03, 1.62889333e-03, 1.22180787e-03,
       4.79700320e-03, 3.33676578e-03, 2.55125568e-04, 3.03339499e-03,
       1.02018297e-03, 7.47413803e-04, 6.20177750e-05, 2.11832561e-03,
       8.32372103e-04, 1.12646086e-03, 1.43538961e-03, 1.67852045e-03,
       1.99069228e-03, 3.13453966e-04, 1.49114657e-03, 2.91324042e-03,
       3.32874905e-03, 3.86727436e-03, 2.07268529e-03, 1.15255865e-03,
       2.58022813e-03, 1.26593569e-03, 1.31737385e-03, 2.28329642e-04,
       2.27019182e-03, 1.58521868e-03, 2.70077791e-03, 2.35486289e-04,
       1.03637976e-03, 4.36007229e-03, 1.17448708e-03, 1.36406309e-03,
       2.33339518e-03, 2.00576954e-03, 9.96358142e-04, 8.33166455e-04,
       8.19451413e-04, 4.16780578e-03, 4.04888730e-04, 9.95675686e-04,
       2.50865319e-03, 1.57851335e-03, 3.11958846e-03, 1.72522449e-03,
       1.01486532e-03, 1.71564373e-04, 3.42139167e-03, 4.81726547e-04,
       2.90520385e-03, 7.07762373e-04, 2.45357220e-03, 1.32206160e-03,
       4.56929613e-03, 2.07874949e-03, 2.51871458e-03, 2.28707667e-03,
       6.14629007e-04, 4.24783234e-04, 8.45102269e-04, 8.95969870e-05,
       8.51856341e-04, 1.74531829e-04, 1.66109051e-03, 2.88236791e-04,
       2.58554939e-03, 1.92355510e-03, 2.30799381e-03, 1.23096480e-03,
       2.86073087e-03, 8.37058611e-04, 3.95280936e-03, 2.21387782e-03,
       9.07956729e-04, 8.15410046e-04, 5.29092081e-04, 3.74311095e-03,
       4.08596631e-04, 3.41753282e-03, 3.07012917e-03, 2.27855112e-03,
       2.10729557e-03, 4.63047205e-03, 4.59969482e-03, 2.91332672e-03,
       1.96941536e-03, 1.81634687e-03, 4.62407278e-04, 2.12769234e-03,
       8.86894406e-04, 1.31023117e-03, 2.99524967e-03, 2.79257758e-03,
       2.86462732e-03, 2.07430292e-03, 2.13362957e-03, 4.96351270e-04,
       1.92812459e-04, 1.61391193e-03, 2.29045718e-03, 2.60189116e-03,
       1.15648043e-03, 1.52575730e-03, 1.67948284e-03, 4.60065601e-03,
       2.14642904e-03, 5.89082209e-04, 2.74793870e-03, 3.13823302e-03,
       1.51665539e-03, 1.55389828e-03, 1.59839870e-03, 2.76543648e-03,
       2.57232367e-03, 7.22703937e-04, 3.45432616e-04, 2.27972968e-03,
       1.68443102e-03, 2.01216426e-03, 1.36034203e-04, 7.13421144e-04,
       3.32585080e-04, 2.02366716e-03, 1.47891869e-03, 2.44522467e-03,
       2.53225810e-04, 1.24614310e-03]), 2.0, 0.35), (array([1.74018661e-03, 8.03601335e-04, 8.24051158e-04, 2.76870366e-03,
       1.48038820e-03, 4.05998972e-04, 2.60310202e-03, 8.38307459e-05,
       4.23318684e-03, 3.40515952e-03, 8.75224044e-04, 4.85892302e-03,
       1.64335072e-03, 7.87229141e-03, 1.31855461e-03, 5.54382266e-05,
       3.33747198e-04, 2.63400734e-03, 1.39063660e-03, 1.83105520e-03,
       1.53443901e-03, 2.75378693e-03, 3.44617975e-03, 1.74400994e-03,
       1.02818059e-03, 2.04098908e-03, 1.64883680e-04, 1.54131241e-03,
       2.16734690e-03, 4.65533459e-03, 1.99754919e-03, 4.21060395e-03,
       1.31384177e-04, 3.37786513e-03, 2.73714332e-03, 1.19232663e-03,
       2.77040505e-04, 1.02659463e-03, 8.77817849e-04, 1.69636995e-03,
       4.18334194e-03, 1.80514551e-03, 3.44394487e-03, 2.45824060e-03,
       1.08249121e-04, 5.61490910e-04, 9.95929898e-04, 2.36969125e-03,
       1.57023485e-04, 1.83005768e-04, 7.07899108e-03, 2.12285906e-03,
       7.87207784e-04, 6.78989272e-04, 5.47155967e-03, 3.43618114e-03,
       2.52515490e-04, 1.28641809e-04, 6.41856702e-03, 2.83396484e-03,
       4.00458175e-03, 5.58478193e-04, 1.48049415e-03, 9.15583634e-04,
       1.78010510e-03, 1.35310541e-03, 1.98776959e-03, 7.27839000e-04,
       3.47372825e-03, 1.01776795e-03, 1.39875552e-03, 8.18669842e-04,
       1.36241457e-03, 1.59753099e-03, 3.92152678e-03, 2.29105457e-03,
       3.23009208e-04, 2.32303894e-04, 1.75751359e-03, 2.99428724e-03,
       5.00208524e-03, 1.59186278e-03, 2.23400845e-03, 1.73907756e-03,
       1.41541256e-03, 3.97276932e-03, 8.66105151e-04, 2.04960019e-03,
       1.82691092e-03, 1.04994290e-03, 1.09172994e-04, 1.76965266e-03,
       3.93324496e-03, 3.80855463e-03, 6.49425551e-05, 1.35247615e-03,
       1.02447714e-03, 8.20898533e-04, 1.17258578e-03, 1.50923008e-03,
       4.42386916e-04, 6.26627637e-03, 2.09835836e-03, 2.44311365e-03,
       7.17628120e-05, 9.09627332e-04, 1.29020456e-03, 2.00964745e-03,
       3.52353795e-03, 2.13800397e-03, 9.60029834e-04, 2.74200199e-03,
       1.89525269e-03, 2.80208270e-03, 1.99541914e-03, 2.68168105e-03,
       3.06079618e-03, 2.99980009e-03, 2.04698629e-03, 3.72164235e-04,
       8.95437874e-04, 1.74907316e-03, 8.10229603e-04, 7.29546623e-04,
       1.20044443e-04, 1.65183232e-03, 2.91527689e-03, 1.44911954e-03,
       3.10466656e-03, 1.25965134e-04, 2.48746644e-04, 1.60680802e-03,
       9.91967761e-04, 1.12424784e-03, 8.43613305e-04, 4.80124910e-04,
       4.72153299e-04, 1.49647817e-03, 9.31963843e-04, 4.37608311e-03,
       1.30613002e-03, 1.83476706e-03, 7.64596815e-04, 7.36187154e-04,
       1.14412518e-03, 1.08046523e-03, 1.52167136e-03, 1.24450900e-03,
       1.82688313e-03, 2.12747056e-03, 1.19814821e-04, 6.17822979e-04,
       2.19246351e-03, 4.36626684e-03, 4.26319204e-04, 1.41517114e-03,
       6.05791485e-03, 2.42871418e-03, 2.47872393e-03, 6.19088563e-03,
       2.08888441e-04, 1.86908422e-03, 2.64871804e-03, 8.88319066e-04,
       7.72531898e-04, 7.65161709e-04, 8.77194797e-04, 6.46542948e-04,
       2.07344959e-03, 5.88044416e-03, 2.17668288e-03, 2.22829407e-03,
       6.92445746e-04, 1.40121038e-03, 1.13450357e-03, 2.16703904e-03,
       6.42339536e-04, 8.08411669e-04, 1.61463172e-03, 4.40529307e-03,
       7.03414451e-04, 9.89862674e-04, 1.95274206e-03, 2.95423855e-05,
       1.00855258e-03, 1.92911589e-03, 4.79691456e-03, 7.44925466e-04,
       2.93004370e-03, 2.74748591e-03, 2.43096972e-03, 5.82780238e-04,
       2.51959162e-03, 2.47806088e-03, 2.89868405e-03, 3.43799980e-04,
       1.54737435e-04, 5.18918628e-05, 2.18776345e-04, 2.75119303e-03,
       1.42418291e-03, 5.73363254e-04, 3.33747433e-03, 1.64879366e-03,
       6.16186121e-04, 3.87932251e-03, 2.00842458e-03, 2.52249437e-03,
       2.17046031e-03, 2.48818575e-03, 1.03729147e-03, 3.08503659e-04,
       1.14902173e-03, 8.17320319e-04, 7.81692307e-04, 1.97176905e-03,
       1.37766942e-03, 4.95383522e-04, 1.56775171e-03, 1.31911891e-03,
       1.18431083e-03, 1.48364303e-03, 5.37201539e-03, 8.89008866e-04,
       2.19516103e-04, 3.52806081e-04, 1.74758368e-03, 3.51374255e-03,
       8.62668670e-04, 2.36406910e-03, 1.37597820e-03, 1.63140184e-03,
       2.71600127e-03, 8.41403985e-03, 4.40956356e-05, 6.98831822e-04,
       2.44851006e-03, 4.29704919e-03, 8.14758747e-04, 4.87087250e-03,
       2.82755583e-03, 2.37097726e-03, 1.27392110e-03, 3.92094831e-03,
       4.49319110e-03, 4.53811100e-04, 1.37400518e-03, 1.38299869e-03,
       1.34147795e-03, 1.08050864e-03, 5.79034496e-04, 1.37424233e-03,
       2.62764748e-06, 4.62817131e-05, 4.29485866e-03, 2.16080359e-03,
       1.22290368e-03, 5.47254628e-04, 1.61010116e-03, 2.54129615e-03,
       9.47619194e-04, 6.30041211e-03, 1.81791514e-03, 6.51264942e-04,
       1.27539673e-03, 8.78442404e-04, 1.14764764e-03, 7.07324458e-04,
       3.84262527e-03, 2.94046737e-03, 3.48381961e-04, 9.70552057e-04,
       2.38639807e-03, 1.74180000e-03, 1.15085030e-03, 2.47793522e-03,
       3.60515856e-04, 3.23664086e-03, 3.97387775e-05, 1.58650662e-03,
       3.98378928e-03, 2.79890472e-03, 1.58576549e-03, 1.12635843e-03,
       7.95461017e-04, 2.82740792e-03, 1.42417186e-03, 5.70846118e-04,
       5.87797637e-04, 1.25458512e-03, 3.18959241e-03, 2.34236802e-03,
       1.82094723e-03, 5.61239029e-04, 1.46758445e-03, 3.02231305e-03,
       9.43232230e-04, 2.17222322e-03, 7.70229875e-04, 1.72870491e-03,
       1.66534559e-03, 1.55644712e-03, 2.12194448e-04, 1.14827533e-03,
       4.09579922e-03, 3.15608487e-03, 2.75464556e-03, 2.58283093e-03,
       1.28195272e-03, 5.70478282e-03, 9.70428091e-04, 1.94175081e-03,
       1.35492666e-03, 3.91377806e-03, 1.65763348e-03, 2.10395014e-03,
       3.64473937e-03, 1.93025107e-03, 2.43505850e-03, 1.05443007e-03,
       2.40832762e-03, 1.67937158e-03, 8.18521998e-04, 2.40709054e-03,
       4.04315240e-03, 6.96857993e-04, 2.77943153e-03, 2.45630509e-03,
       1.90200723e-03, 2.30573120e-03, 2.04968985e-03, 2.37578650e-03,
       8.70575822e-04, 1.01224480e-03, 1.10041367e-03, 1.65306899e-03,
       4.01160903e-04, 2.58164597e-04, 7.50452884e-04, 1.81002600e-03,
       1.04997930e-03, 1.60936356e-04, 1.52430898e-03, 1.51999138e-03,
       4.38198328e-04, 5.74358786e-04, 1.99123487e-03, 1.83316456e-03,
       8.04321164e-04, 3.04423795e-03, 2.51728342e-03, 3.06760606e-04,
       4.98620781e-03, 1.41447390e-03, 5.66417660e-04, 2.40635707e-03,
       3.46722290e-05, 1.07322683e-04, 2.04111068e-03, 5.50746086e-05,
       7.69305842e-04, 1.85818797e-03, 4.79030232e-04, 2.64377269e-03,
       1.86145053e-03, 1.46090059e-03, 7.34246562e-04, 3.96630475e-04,
       1.23955301e-03, 1.47853520e-04, 5.12048487e-04, 6.53326461e-04,
       1.88585707e-03, 1.92091221e-03, 3.65383807e-03, 3.88412974e-03,
       2.46222711e-03, 6.73191589e-04, 9.17733098e-04, 2.94847517e-03,
       3.25061507e-03, 2.72190797e-05, 3.28860586e-03, 1.99011258e-03,
       7.29698986e-04, 9.13222323e-04, 1.42109594e-03, 4.11480543e-03,
       1.02658867e-03, 2.66357185e-03, 1.15958330e-04, 5.64782260e-03,
       1.31655494e-03, 2.00413366e-03, 1.19986526e-03, 6.09781434e-04,
       7.76055941e-04, 5.48922288e-03, 3.15652071e-05, 1.58855874e-03,
       8.17276026e-03, 5.95483115e-04, 1.88069971e-03, 4.84277525e-03,
       3.40433322e-03, 4.28776484e-04, 8.86230564e-04, 1.77478757e-03,
       1.40801257e-03, 1.83711887e-03, 1.95205505e-03, 2.20201833e-03,
       2.65645022e-03, 6.24115877e-04, 1.08911210e-03, 2.81283611e-03,
       3.23470084e-03, 1.84661027e-03, 9.36329540e-04, 4.55215243e-04,
       3.01102217e-03, 2.46878240e-03, 1.97559509e-03, 6.92475357e-04,
       3.06483831e-03, 2.80116442e-03, 1.05548796e-03, 2.81863524e-03,
       3.60963066e-05, 2.11445930e-04, 2.40493972e-06, 1.30346996e-03,
       1.36521722e-03, 1.75230387e-03, 5.27967234e-03, 1.85117687e-03,
       8.74068325e-05, 2.73318791e-03, 5.63625437e-05, 2.13426932e-04,
       2.37843857e-03, 2.54288125e-03, 8.47776091e-04, 3.54933247e-04,
       1.93264201e-03, 1.42185381e-03, 2.05847739e-04, 2.41973359e-04,
       6.22520000e-04, 1.40727567e-04, 1.57830743e-03, 6.70438447e-05,
       2.86831587e-03, 1.41680513e-03, 2.70816495e-03, 1.24372016e-03,
       3.21980548e-04, 2.76480919e-03, 2.09765410e-03, 6.48163310e-04,
       4.03583525e-04, 1.94379195e-03, 1.41251651e-03, 7.06636928e-04,
       2.27561541e-03, 1.60562145e-03, 5.80430546e-04, 1.23258483e-03,
       7.31069307e-04, 1.46856774e-04, 8.30490607e-04, 1.46234559e-03,
       5.84243961e-03, 1.90034559e-03, 3.25592077e-03, 2.12579961e-03,
       4.04575839e-04, 1.47260688e-03, 2.63431052e-03, 3.29809591e-05,
       1.58942214e-03, 4.31251294e-03, 1.10016479e-03, 2.09874082e-03,
       1.91866706e-03, 1.09070104e-03, 3.27970986e-03, 5.10811820e-04,
       1.80749666e-03, 5.85759271e-04, 1.19059103e-03, 2.31189386e-03,
       1.83536510e-03, 4.56565312e-04, 8.59568513e-05, 2.28878987e-03,
       3.54029079e-03, 1.65196925e-04, 6.33826679e-04, 1.16634495e-03,
       1.47745541e-03, 4.18716217e-03, 2.87387208e-03, 5.96918559e-03,
       1.23746841e-04, 2.04721866e-03, 5.28032761e-03, 1.43364923e-03,
       8.42543194e-04, 8.16897400e-04, 1.46606633e-03, 6.20566108e-04,
       1.59026828e-03, 2.55157391e-03, 1.94367057e-03, 2.42043163e-03,
       3.16855819e-03, 7.36815383e-04, 8.12097725e-04, 5.35105776e-03,

/home/alexi/Documents/ValDX/ValDX/HDX_plots.py:1201: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/val_HOIPapo_test_mean1_RW_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0
Finished reweighting
[(array([1.74018661e-03, 8.03601335e-04, 8.24051158e-04, 2.76870366e-03,
       1.48038820e-03, 4.05998972e-04, 2.60310202e-03, 8.38307459e-05,
       4.23318684e-03, 3.40515952e-03, 8.75224044e-04, 4.85892302e-03,
       1.64335072e-03, 7.87229141e-03, 1.31855461e-03, 5.54382266e-05,
       3.33747198e-04, 2.63400734e-03, 1.39063660e-03, 1.83105520e-03,
       1.53443901e-03, 2.75378693e-03, 3.44617975e-03, 1.74400994e-03,
       1.02818059e-03, 2.04098908e-03, 1.64883680e-04, 1.54131241e-03,
       2.16734690e-03, 4.65533459e-03, 1.99754919e-03, 4.21060395e-03,
       1.31384177e-04, 3.37786513e-03, 2.73714332e-03, 1.19232663e-03,
       2.77040505e-04, 1.02659463e-03, 8.77817849e-04, 1.69636995e-03,
       4.18334194e-03, 1.80514551e-03, 3.44394487e-03, 2.45824060e-03,
       1.08249121e-04, 5.61490910e-04, 9.95929898e-04, 2.36969125e-03,
       1.57023485e-04, 1.83005768e-04, 7.07899108e-03, 2.12285906e-03,
       7.87207784e-04, 6.78989272e-04, 5.47155967e-03, 3.43618114e-03,
       2.52515490e-04, 1.28641809e-04, 6.41856702e-03, 2.83396484e-03,
       4.00458175e-03, 5.58478193e-04, 1.48049415e-03, 9.15583634e-04,
       1.78010510e-03, 1.35310541e-03, 1.98776959e-03, 7.27839000e-04,
       3.47372825e-03, 1.01776795e-03, 1.39875552e-03, 8.18669842e-04,
       1.36241457e-03, 1.59753099e-03, 3.92152678e-03, 2.29105457e-03,
       3.23009208e-04, 2.32303894e-04, 1.75751359e-03, 2.99428724e-03,
       5.00208524e-03, 1.59186278e-03, 2.23400845e-03, 1.73907756e-03,
       1.41541256e-03, 3.97276932e-03, 8.66105151e-04, 2.04960019e-03,
       1.82691092e-03, 1.04994290e-03, 1.09172994e-04, 1.76965266e-03,
       3.93324496e-03, 3.80855463e-03, 6.49425551e-05, 1.35247615e-03,
       1.02447714e-03, 8.20898533e-04, 1.17258578e-03, 1.50923008e-03,
       4.42386916e-04, 6.26627637e-03, 2.09835836e-03, 2.44311365e-03,
       7.17628120e-05, 9.09627332e-04, 1.29020456e-03, 2.00964745e-03,
       3.52353795e-03, 2.13800397e-03, 9.60029834e-04, 2.74200199e-03,
       1.89525269e-03, 2.80208270e-03, 1.99541914e-03, 2.68168105e-03,
       3.06079618e-03, 2.99980009e-03, 2.04698629e-03, 3.72164235e-04,
       8.95437874e-04, 1.74907316e-03, 8.10229603e-04, 7.29546623e-04,
       1.20044443e-04, 1.65183232e-03, 2.91527689e-03, 1.44911954e-03,
       3.10466656e-03, 1.25965134e-04, 2.48746644e-04, 1.60680802e-03,
       9.91967761e-04, 1.12424784e-03, 8.43613305e-04, 4.80124910e-04,
       4.72153299e-04, 1.49647817e-03, 9.31963843e-04, 4.37608311e-03,
       1.30613002e-03, 1.83476706e-03, 7.64596815e-04, 7.36187154e-04,
       1.14412518e-03, 1.08046523e-03, 1.52167136e-03, 1.24450900e-03,
       1.82688313e-03, 2.12747056e-03, 1.19814821e-04, 6.17822979e-04,
       2.19246351e-03, 4.36626684e-03, 4.26319204e-04, 1.41517114e-03,
       6.05791485e-03, 2.42871418e-03, 2.47872393e-03, 6.19088563e-03,
       2.08888441e-04, 1.86908422e-03, 2.64871804e-03, 8.88319066e-04,
       7.72531898e-04, 7.65161709e-04, 8.77194797e-04, 6.46542948e-04,
       2.07344959e-03, 5.88044416e-03, 2.17668288e-03, 2.22829407e-03,
       6.92445746e-04, 1.40121038e-03, 1.13450357e-03, 2.16703904e-03,
       6.42339536e-04, 8.08411669e-04, 1.61463172e-03, 4.40529307e-03,
       7.03414451e-04, 9.89862674e-04, 1.95274206e-03, 2.95423855e-05,
       1.00855258e-03, 1.92911589e-03, 4.79691456e-03, 7.44925466e-04,
       2.93004370e-03, 2.74748591e-03, 2.43096972e-03, 5.82780238e-04,
       2.51959162e-03, 2.47806088e-03, 2.89868405e-03, 3.43799980e-04,
       1.54737435e-04, 5.18918628e-05, 2.18776345e-04, 2.75119303e-03,
       1.42418291e-03, 5.73363254e-04, 3.33747433e-03, 1.64879366e-03,
       6.16186121e-04, 3.87932251e-03, 2.00842458e-03, 2.52249437e-03,
       2.17046031e-03, 2.48818575e-03, 1.03729147e-03, 3.08503659e-04,
       1.14902173e-03, 8.17320319e-04, 7.81692307e-04, 1.97176905e-03,
       1.37766942e-03, 4.95383522e-04, 1.56775171e-03, 1.31911891e-03,
       1.18431083e-03, 1.48364303e-03, 5.37201539e-03, 8.89008866e-04,
       2.19516103e-04, 3.52806081e-04, 1.74758368e-03, 3.51374255e-03,
       8.62668670e-04, 2.36406910e-03, 1.37597820e-03, 1.63140184e-03,
       2.71600127e-03, 8.41403985e-03, 4.40956356e-05, 6.98831822e-04,
       2.44851006e-03, 4.29704919e-03, 8.14758747e-04, 4.87087250e-03,
       2.82755583e-03, 2.37097726e-03, 1.27392110e-03, 3.92094831e-03,
       4.49319110e-03, 4.53811100e-04, 1.37400518e-03, 1.38299869e-03,
       1.34147795e-03, 1.08050864e-03, 5.79034496e-04, 1.37424233e-03,
       2.62764748e-06, 4.62817131e-05, 4.29485866e-03, 2.16080359e-03,
       1.22290368e-03, 5.47254628e-04, 1.61010116e-03, 2.54129615e-03,
       9.47619194e-04, 6.30041211e-03, 1.81791514e-03, 6.51264942e-04,
       1.27539673e-03, 8.78442404e-04, 1.14764764e-03, 7.07324458e-04,
       3.84262527e-03, 2.94046737e-03, 3.48381961e-04, 9.70552057e-04,
       2.38639807e-03, 1.74180000e-03, 1.15085030e-03, 2.47793522e-03,
       3.60515856e-04, 3.23664086e-03, 3.97387775e-05, 1.58650662e-03,
       3.98378928e-03, 2.79890472e-03, 1.58576549e-03, 1.12635843e-03,
       7.95461017e-04, 2.82740792e-03, 1.42417186e-03, 5.70846118e-04,
       5.87797637e-04, 1.25458512e-03, 3.18959241e-03, 2.34236802e-03,
       1.82094723e-03, 5.61239029e-04, 1.46758445e-03, 3.02231305e-03,
       9.43232230e-04, 2.17222322e-03, 7.70229875e-04, 1.72870491e-03,
       1.66534559e-03, 1.55644712e-03, 2.12194448e-04, 1.14827533e-03,
       4.09579922e-03, 3.15608487e-03, 2.75464556e-03, 2.58283093e-03,
       1.28195272e-03, 5.70478282e-03, 9.70428091e-04, 1.94175081e-03,
       1.35492666e-03, 3.91377806e-03, 1.65763348e-03, 2.10395014e-03,
       3.64473937e-03, 1.93025107e-03, 2.43505850e-03, 1.05443007e-03,
       2.40832762e-03, 1.67937158e-03, 8.18521998e-04, 2.40709054e-03,
       4.04315240e-03, 6.96857993e-04, 2.77943153e-03, 2.45630509e-03,
       1.90200723e-03, 2.30573120e-03, 2.04968985e-03, 2.37578650e-03,
       8.70575822e-04, 1.01224480e-03, 1.10041367e-03, 1.65306899e-03,
       4.01160903e-04, 2.58164597e-04, 7.50452884e-04, 1.81002600e-03,
       1.04997930e-03, 1.60936356e-04, 1.52430898e-03, 1.51999138e-03,
       4.38198328e-04, 5.74358786e-04, 1.99123487e-03, 1.83316456e-03,
       8.04321164e-04, 3.04423795e-03, 2.51728342e-03, 3.06760606e-04,
       4.98620781e-03, 1.41447390e-03, 5.66417660e-04, 2.40635707e-03,
       3.46722290e-05, 1.07322683e-04, 2.04111068e-03, 5.50746086e-05,
       7.69305842e-04, 1.85818797e-03, 4.79030232e-04, 2.64377269e-03,
       1.86145053e-03, 1.46090059e-03, 7.34246562e-04, 3.96630475e-04,
       1.23955301e-03, 1.47853520e-04, 5.12048487e-04, 6.53326461e-04,
       1.88585707e-03, 1.92091221e-03, 3.65383807e-03, 3.88412974e-03,
       2.46222711e-03, 6.73191589e-04, 9.17733098e-04, 2.94847517e-03,
       3.25061507e-03, 2.72190797e-05, 3.28860586e-03, 1.99011258e-03,
       7.29698986e-04, 9.13222323e-04, 1.42109594e-03, 4.11480543e-03,
       1.02658867e-03, 2.66357185e-03, 1.15958330e-04, 5.64782260e-03,
       1.31655494e-03, 2.00413366e-03, 1.19986526e-03, 6.09781434e-04,
       7.76055941e-04, 5.48922288e-03, 3.15652071e-05, 1.58855874e-03,
       8.17276026e-03, 5.95483115e-04, 1.88069971e-03, 4.84277525e-03,
       3.40433322e-03, 4.28776484e-04, 8.86230564e-04, 1.77478757e-03,
       1.40801257e-03, 1.83711887e-03, 1.95205505e-03, 2.20201833e-03,
       2.65645022e-03, 6.24115877e-04, 1.08911210e-03, 2.81283611e-03,
       3.23470084e-03, 1.84661027e-03, 9.36329540e-04, 4.55215243e-04,
       3.01102217e-03, 2.46878240e-03, 1.97559509e-03, 6.92475357e-04,
       3.06483831e-03, 2.80116442e-03, 1.05548796e-03, 2.81863524e-03,
       3.60963066e-05, 2.11445930e-04, 2.40493972e-06, 1.30346996e-03,
       1.36521722e-03, 1.75230387e-03, 5.27967234e-03, 1.85117687e-03,
       8.74068325e-05, 2.73318791e-03, 5.63625437e-05, 2.13426932e-04,
       2.37843857e-03, 2.54288125e-03, 8.47776091e-04, 3.54933247e-04,
       1.93264201e-03, 1.42185381e-03, 2.05847739e-04, 2.41973359e-04,
       6.22520000e-04, 1.40727567e-04, 1.57830743e-03, 6.70438447e-05,
       2.86831587e-03, 1.41680513e-03, 2.70816495e-03, 1.24372016e-03,
       3.21980548e-04, 2.76480919e-03, 2.09765410e-03, 6.48163310e-04,
       4.03583525e-04, 1.94379195e-03, 1.41251651e-03, 7.06636928e-04,
       2.27561541e-03, 1.60562145e-03, 5.80430546e-04, 1.23258483e-03,
       7.31069307e-04, 1.46856774e-04, 8.30490607e-04, 1.46234559e-03,
       5.84243961e-03, 1.90034559e-03, 3.25592077e-03, 2.12579961e-03,
       4.04575839e-04, 1.47260688e-03, 2.63431052e-03, 3.29809591e-05,
       1.58942214e-03, 4.31251294e-03, 1.10016479e-03, 2.09874082e-03,
       1.91866706e-03, 1.09070104e-03, 3.27970986e-03, 5.10811820e-04,
       1.80749666e-03, 5.85759271e-04, 1.19059103e-03, 2.31189386e-03,
       1.83536510e-03, 4.56565312e-04, 8.59568513e-05, 2.28878987e-03,
       3.54029079e-03, 1.65196925e-04, 6.33826679e-04, 1.16634495e-03,
       1.47745541e-03, 4.18716217e-03, 2.87387208e-03, 5.96918559e-03,
       1.23746841e-04, 2.04721866e-03, 5.28032761e-03, 1.43364923e-03,
       8.42543194e-04, 8.16897400e-04, 1.46606633e-03, 6.20566108e-04,
       1.59026828e-03, 2.55157391e-03, 1.94367057e-03, 2.42043163e-03,
       3.16855819e-03, 7.36815383e-04, 8.12097725e-04, 5.35105776e-03,
       4.91036263e-03, 3.32368847e-03, 2.21924259e-03, 1.76313064e-03,
       1.65652817e-04, 1.71256690e-03, 3.75625764e-03, 3.08074402e-03,
       2.19213128e-03, 1.50748587e-03, 5.07305624e-04, 2.27127626e-03,
       1.86527351e-03, 2.12577050e-03, 1.14107930e-03, 1.23495754e-03,
       1.77332082e-03, 5.11529353e-03, 2.85152428e-03, 1.90453452e-03,
       7.29874793e-04, 1.90482157e-03, 2.27404564e-03, 2.26510773e-03,
       1.79459077e-03, 6.84455704e-06, 1.16491541e-04, 2.73181059e-04,
       3.58365789e-04, 5.37818501e-03]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean13/val_HOIPapo_test_mean1_RW_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(67, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00004  0.00037        0
1  0.0  0.09091  0.09093        1
2  0.0  0.07148  0.07191        2
3  0.0  0.05569  0.05694        3
4  0.0  0.10000  0.10003        4
Structures loaded HOIPapo_test_mean1_RW:
HOIPapo_test_mean1_RW Topology: <Universe with 3369 atoms>
HOIPapo_test_mean1_RW Trajectory: <Universe with 3369 atoms>
HOIPapo_test_mean1_RW Traj: no frames 550
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 2970.25801533, 177: 664.95794074, 178: 5926.44387531, 179: 3332.68430264, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 6649.57939778, 206: 1962.4300073, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 9392.7805534, 221: 4393.33353926, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[30.8666921  54.86299454 34.76128645 24.75698537 15.96761077 28.05906806
 29.98953008 22.97786972 24.2219119  19.89973038  3.92157858 17.93089536
 40.09261861 42.17942773 29.99382452 40.07233548 13.25491395 17.04754249
 27.95299694 13.76561565 17.54327053 30.9070238  44.80677429 58.33035449
 26.50904456 39.84598415 57.76676358 53.17178131 41.49937677 40.44348074
 45.82053617 49.9055989  43.85648308 62.25370592 53.07212986 36.40638149
 28.92191577 33.8059463  29.9951901  26.35451335 15.62988944 28.85047613
 43.79659929 51.42843443 61.8654552  27.41226688 19.18786338 34.44364624
 32.71809446 10.21285184 15.88579561 15.36926595 32.32801192 21.09073933
 13.25133609 29.29492291 54.59701805 41.58161475 34.03223584 37.72667268
 61.42574686 27.43842304 28.88799778 50.05689864 27.86786795 13.80784961
 39.45210869 54.54092516 37.99743565 41.54341195 54.45125285 56.08270505
 44.35317472 52.21975977 53.07659199 44.02983439 48.28325439 43.62182956
 41.11986327 42.97286978 39.17365801 26.71508991 28.7142009  15.26011053
 49.28051556 50.07960291 33.36645278 56.15949527 32.01426625 19.4020758
 18.80758368 29.26413333 41.50232785 15.61834702  5.59337859 13.80097556
 15.94259265 29.14479555 46.29260253 75.33523698 46.79041897 60.92974099
 19.82549783 22.65880466 32.61530665 33.66197989 40.97932508 61.97243518
 79.0631988  56.55004261 25.90226556 27.41540524 40.44747909 41.06660678
 35.915088   41.52006781 39.03206179 15.88862272 21.90520443 61.97345437
 38.65159977 10.84736444 26.66056129 31.17630166 35.23988411 24.35383876
 37.39766714 64.29183991 46.77677743 49.68560115 47.20808355 53.36788539
 44.91905272 42.6790517  54.6067611  53.23182968 14.44426493 37.13908024
 44.36642204 36.46861143 36.14860135 43.47198109 36.72383989 40.93858929
 40.01818617 45.7925065  47.99919191 36.77476813 32.26516364 40.34718058
 47.41407361 53.07357922 46.39394681 68.41994656 21.71190913 25.85603724
 33.46408652 34.90766863 31.35798877 38.86683958 32.72226053 35.92070217
 32.21315565 22.96501674 22.62281053 22.18972665 23.17830106 32.05348868
 41.26189403 66.22493973 44.340128   67.93718178 39.12666803 27.43433471
 23.62858167 37.44314666 42.96606474 49.97537252 72.00269131 79.39385104
 67.32352257 38.2152149  39.32217591 44.28632272 36.64506618 33.50251766
 43.6572374  25.53351743 24.51125727 35.74532967 18.79835413  9.02907519
 32.59153375  9.7051278  14.66390921 21.07669947 22.16127817 24.43393845
 19.8784887  25.99095255 30.27374212 24.95094452 31.2413164  32.02132254
 39.68083301 51.69363531 40.80104341 33.51027282 29.31578285 44.88254186
 36.52693237 61.49055044 55.67859711 51.25256349 59.91309191 50.23360864
 28.69295083 27.87346124 22.75902867 31.79400853 16.57239311 14.3652517
 21.41253325 25.82462683 25.35070423  4.800403    5.3663916  22.84015584
 10.00286969  8.84717999 16.35467446  5.79131873 19.32807357 35.91758848
 56.27573848 37.32795358 36.20337609 34.07318083 45.36007101 38.87182135
 41.68225752 21.41997282 24.05580219 43.38248866 58.80806245 52.88502075
 45.89261342 46.57172992 55.31117086 54.70373081 50.01881998 48.40558119
 57.43735888 53.2534972  34.78259281 31.14753903 33.44035534 39.82034572
 31.96466917 44.88837214 28.51405795 29.37468542 44.99167801 39.62749529
 25.12055262 49.94219184 53.40592175 58.1301027  38.73811239 29.90679408
 28.1739941  27.97226613 27.49961652 26.87803174 19.28565178 34.84058986
  1.25413115  4.34792784 18.72942076 15.31610367 35.32476845 58.35591713
 54.02394661 40.71327207 46.04525814 57.26659049 51.80967213 43.26734295
 48.06340789]
LogPf_by_res [30.8666921  54.86299454 34.76128645 24.75698537 15.96761077 28.05906806
 29.98953008 22.97786972 24.2219119  19.89973038  3.92157858 17.93089536
 40.09261861 42.17942773 29.99382452 40.07233548 13.25491395 17.04754249
 27.95299694 13.76561565 17.54327053 30.9070238  44.80677429 58.33035449
 26.50904456 39.84598415 57.76676358 53.17178131 41.49937677 40.44348074
 45.82053617 49.9055989  43.85648308 62.25370592 53.07212986 36.40638149
 28.92191577 33.8059463  29.9951901  26.35451335 15.62988944 28.85047613
 43.79659929 51.42843443 61.8654552  27.41226688 19.18786338 34.44364624
 32.71809446 10.21285184 15.88579561 15.36926595 32.32801192 21.09073933
 13.25133609 29.29492291 54.59701805 41.58161475 34.03223584 37.72667268
 61.42574686 27.43842304 28.88799778 50.05689864 27.86786795 13.80784961
 39.45210869 54.54092516 37.99743565 41.54341195 54.45125285 56.08270505
 44.35317472 52.21975977 53.07659199 44.02983439 48.28325439 43.62182956
 41.11986327 42.97286978 39.17365801 26.71508991 28.7142009  15.26011053
 49.28051556 50.07960291 33.36645278 56.15949527 32.01426625 19.4020758
 18.80758368 29.26413333 41.50232785 15.61834702  5.59337859 13.80097556
 15.94259265 29.14479555 46.29260253 75.33523698 46.79041897 60.92974099
 19.82549783 22.65880466 32.61530665 33.66197989 40.97932508 61.97243518
 79.0631988  56.55004261 25.90226556 27.41540524 40.44747909 41.06660678
 35.915088   41.52006781 39.03206179 15.88862272 21.90520443 61.97345437
 38.65159977 10.84736444 26.66056129 31.17630166 35.23988411 24.35383876
 37.39766714 64.29183991 46.77677743 49.68560115 47.20808355 53.36788539
 44.91905272 42.6790517  54.6067611  53.23182968 14.44426493 37.13908024
 44.36642204 36.46861143 36.14860135 43.47198109 36.72383989 40.93858929
 40.01818617 45.7925065  47.99919191 36.77476813 32.26516364 40.34718058
 47.41407361 53.07357922 46.39394681 68.41994656 21.71190913 25.85603724
 33.46408652 34.90766863 31.35798877 38.86683958 32.72226053 35.92070217
 32.21315565 22.96501674 22.62281053 22.18972665 23.17830106 32.05348868
 41.26189403 66.22493973 44.340128   67.93718178 39.12666803 27.43433471
 23.62858167 37.44314666 42.96606474 49.97537252 72.00269131 79.39385104
 67.32352257 38.2152149  39.32217591 44.28632272 36.64506618 33.50251766
 43.6572374  25.53351743 24.51125727 35.74532967 18.79835413  9.02907519
 32.59153375  9.7051278  14.66390921 21.07669947 22.16127817 24.43393845
 19.8784887  25.99095255 30.27374212 24.95094452 31.2413164  32.02132254
 39.68083301 51.69363531 40.80104341 33.51027282 29.31578285 44.88254186
 36.52693237 61.49055044 55.67859711 51.25256349 59.91309191 50.23360864
 28.69295083 27.87346124 22.75902867 31.79400853 16.57239311 14.3652517
 21.41253325 25.82462683 25.35070423  4.800403    5.3663916  22.84015584
 10.00286969  8.84717999 16.35467446  5.79131873 19.32807357 35.91758848
 56.27573848 37.32795358 36.20337609 34.07318083 45.36007101 38.87182135
 41.68225752 21.41997282 24.05580219 43.38248866 58.80806245 52.88502075
 45.89261342 46.57172992 55.31117086 54.70373081 50.01881998 48.40558119
 57.43735888 53.2534972  34.78259281 31.14753903 33.44035534 39.82034572
 31.96466917 44.88837214 28.51405795 29.37468542 44.99167801 39.62749529
 25.12055262 49.94219184 53.40592175 58.1301027  38.73811239 29.90679408
 28.1739941  27.97226613 27.49961652 26.87803174 19.28565178 34.84058986
  1.25413115  4.34792784 18.72942076 15.31610367 35.32476845 58.35591713
 54.02394661 40.71327207 46.04525814 57.26659049 51.80967213 43.26734295
 48.06340789]
Pf_by_res [2.54234248e+13 6.70958701e+23 1.24920838e+15 5.64705652e+10
 8.60290739e+06 1.53425811e+12 1.05751717e+13 9.53151699e+09
 3.30706461e+10 4.38877276e+08 5.04800687e+01 6.12757888e+07
 2.58227818e+17 2.08109888e+18 1.06206839e+13 2.53042912e+17
 5.70868377e+05 2.53310758e+07 1.37985141e+12 9.51329393e+05
 4.15858505e+07 2.64697531e+13 2.87961765e+19 2.15055761e+25
 3.25635522e+11 2.01786005e+17 1.22401477e+25 1.23654867e+23
 1.05426632e+18 3.66758776e+17 7.93607965e+19 4.71765543e+21
 1.11334201e+19 1.08752929e+27 1.11926556e+23 6.47277617e+15
 3.63603808e+12 4.80547068e+14 1.06351971e+13 2.79009969e+11
 6.13726301e+06 3.38534228e+12 1.04862788e+19 2.16314327e+22
 7.37608333e+26 8.03519171e+11 2.15368998e+08 9.09254585e+14
 1.61915298e+14 2.72511729e+04 7.92708241e+06 4.72919685e+06
 1.09616818e+14 1.44408151e+09 5.68829540e+05 5.27987166e+12
 5.14261092e+23 1.14463187e+18 6.02576555e+14 2.42373853e+16
 4.75185201e+26 8.24813419e+11 3.51477904e+12 5.48826232e+21
 1.26724700e+12 9.92368325e+05 1.36092159e+17 4.86208821e+23
 3.17743467e+16 1.10172846e+18 4.44507040e+23 2.27200526e+24
 1.82952790e+19 4.77258326e+22 1.12427103e+23 1.32407966e+19
 9.31431560e+20 8.80480757e+18 7.21322892e+17 4.60129647e+18
 1.03015722e+17 4.00143837e+11 2.95405789e+12 4.24015564e+06
 2.52496854e+21 5.61429461e+21 3.09646606e+14 2.45334657e+24
 8.00975396e+13 2.66817590e+08 1.47241357e+08 5.11978380e+12
 1.05738214e+18 6.06683143e+06 2.68641719e+02 9.85570121e+05
 8.39034883e+06 4.54384893e+12 1.27239464e+20 5.22008666e+32
 2.09324839e+20 2.89367862e+26 4.07478133e+08 6.92777592e+09
 1.46099155e+14 4.16113797e+14 6.26750597e+17 8.20893147e+26
 2.17125564e+34 3.62552960e+24 1.77505169e+11 8.06044860e+11
 3.68228143e+17 6.83912775e+17 3.96026762e+15 1.07630743e+18
 8.94147267e+16 7.94952489e+06 3.26068924e+09 8.21730219e+26
 6.11190362e+16 5.13985086e+04 3.78908765e+11 3.46494048e+13
 2.01598460e+15 3.77344294e+10 1.74421684e+16 8.34817040e+27
 2.06488713e+20 3.78601568e+21 3.17841195e+20 1.50445131e+23
 3.22178628e+19 3.42986199e+18 5.19296049e+23 1.31307608e+23
 1.87527323e+06 1.34678295e+16 1.85392548e+19 6.88837380e+15
 5.00193557e+15 7.57951651e+18 8.89121306e+15 6.01732443e+17
 2.39705185e+17 7.71672256e+19 7.01106803e+20 9.35575573e+15
 1.02939612e+14 3.33087156e+17 3.90544505e+20 1.12088896e+23
 1.40810517e+20 5.18090038e+29 2.68758574e+09 1.69486181e+11
 3.41403616e+14 1.44613176e+15 4.15529140e+13 7.57973391e+16
 1.62591256e+14 3.98256378e+15 9.77227641e+13 9.40979250e+09
 6.68285102e+09 4.33386961e+09 1.16468437e+10 8.33015842e+13
 8.31405490e+17 5.76933674e+28 1.80581359e+19 3.19700388e+29
 9.82869864e+16 8.21448197e+11 1.82710134e+10 1.82537450e+16
 4.57009077e+18 5.05857877e+21 1.86368075e+31 3.02211789e+34
 1.73075005e+29 3.95054446e+16 1.19509936e+17 1.71121895e+19
 8.21769522e+15 3.54779525e+14 9.12215185e+18 1.22762499e+11
 4.41675976e+10 3.34194601e+15 1.45888637e+08 8.34214110e+03
 1.42666913e+14 1.64014954e+04 2.33590326e+06 1.42394848e+09
 4.21231481e+09 4.08812944e+10 4.29653101e+08 1.93966743e+11
 1.40513855e+13 6.85579028e+10 3.69769698e+13 8.06647294e+13
 1.71067227e+17 2.82007440e+22 5.24406432e+17 3.57541595e+14
 5.39116625e+12 3.10627759e+19 7.30205613e+15 5.06998582e+26
 1.51672723e+24 1.81428498e+22 1.04694824e+26 6.54906101e+21
 2.89194624e+12 1.27435495e+12 7.65809176e+09 6.42632168e+13
 1.57506645e+07 1.73280441e+06 1.99225551e+09 1.64245292e+11
 1.02251800e+11 1.21559397e+02 2.14088955e+02 8.30526790e+09
 2.20897657e+04 6.95474880e+03 1.26690740e+07 3.27444551e+02
 2.47785391e+08 3.97018257e+15 2.75576821e+24 1.62676290e+16
 5.28355782e+15 6.27761120e+14 5.00758740e+19 7.61758860e+16
 1.26582723e+18 2.00713229e+09 2.80092933e+10 6.93067344e+18
 3.46750435e+25 9.28266524e+22 8.52920922e+19 1.68207484e+20
 1.05035544e+24 5.72174411e+23 5.28320556e+21 1.05263257e+21
 8.80497276e+24 1.34183766e+23 1.27611003e+15 3.36669929e+13
 3.33397085e+14 1.96678284e+17 7.62218413e+13 3.12444096e+19
 2.41823233e+12 5.71825853e+12 3.46447547e+19 1.62181957e+17
 8.12301740e+10 4.89348578e+21 1.56277738e+23 1.76028438e+25
 6.66420659e+16 9.73544123e+12 1.72111612e+12 1.40669787e+12
 8.76862929e+11 4.70956581e+11 2.37493730e+08 1.35230896e+15
 3.50479190e+00 7.73180811e+01 1.36170830e+08 4.48434800e+06
 2.19458301e+15 2.20624021e+25 2.89935839e+23 4.80340717e+17
 9.93576995e+19 7.42273994e+24 3.16704850e+22 6.17686754e+18
 7.47606083e+20]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  2970.25801533   664.95794074  5926.44387531
  3332.68430264   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  6649.57939778  1962.4300073
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
  9392.7805534   4393.33353926   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.61272427e-09 5.57311991e-21 3.59881306e-12 4.47684485e-09
 4.44783766e-04 2.73461222e-09 6.89456309e-11 1.03188702e-07
 1.00774696e-08 1.31962667e-06 1.07071587e+02 5.19403971e-05
 7.95776573e-15 9.00536792e-16 1.89078302e-10 1.31704314e-15
 1.16481831e-03 1.85840575e-04 7.63768695e-09 3.66828661e-03
 8.99184037e-05 1.44558717e-10 1.29855201e-17 1.44624908e-22
 2.81878803e-09 1.72943059e-14 2.11352562e-22 1.41443489e-20
 2.29004408e-15 4.34924289e-15 1.26820120e-17 2.62462921e-19
 3.35865643e-17 6.86045968e-25 2.97756354e-21 1.10078775e-13
 3.56587203e-10 1.70238681e-12 1.24752320e-10 1.16727842e-09
 1.03471189e-04 7.46778136e-10 7.80140419e-17 1.50559753e-20
 5.18762246e-24 9.07398245e-10 2.45251114e-05 4.61433028e-12
 1.39157396e-11 3.36828625e-02 2.77767107e-05 1.40606949e-04
 2.30630632e-11 7.29797798e-07 1.25259893e-03 4.36687549e-10
 1.02709475e-21 1.79526410e-16 3.03935862e-12 5.60155248e-14
 1.97665679e-24 1.97896657e-09 5.98268516e-10 1.21160014e-19
 4.78556152e-10 9.24956477e-04 6.15121753e-15 1.39949498e-21
 4.47422218e-14 3.02495982e-16 1.01138273e-21 5.08609941e-22
 8.71876836e-17 3.19183669e-20 3.90771749e-21 5.02203880e-17
 1.67356747e-18 9.50767463e-17 5.18399368e-16 5.24703500e-17
 7.41123640e-15 4.90431147e-09 8.96138588e-10 1.56823946e-04
 3.80660843e-19 6.81551971e-20 9.81584868e-13 1.67122634e-21
 5.61274098e-11 5.45229969e-06 5.68544372e-05 2.05846058e-09
 1.37582186e-15 1.81899811e-04 4.01440070e+00 1.65617661e-03
 1.22747925e-04 1.16243932e-10 4.76620092e-18 1.71836916e-30
 5.15197100e-18 2.89296967e-23 2.05442300e-06 1.20837114e-06
 2.44425477e-11 4.82594159e-12 2.72708968e-15 1.40769169e-24
 2.79307899e-31 2.47413117e-22 6.21703300e-09 1.08751427e-08
 1.11346661e-14 2.93625291e-15 6.09634647e-13 7.25868315e-16
 8.53856960e-15 8.75896929e-05 3.15852826e-07 1.94117602e-24
 3.44046924e-14 3.81806800e-02 5.94647401e-09 1.42265108e-10
 5.22765557e-12 9.24818244e-08 6.47431375e-14 5.77035959e-26
 8.08905632e-18 1.63912384e-18 3.24029083e-18 5.96233040e-21
 6.23300461e-17 5.99125123e-16 9.71357633e-21 2.53807406e-20
 3.01807219e-04 3.57681576e-14 8.80444336e-17 2.91526119e-13
 2.90841304e-13 2.47259321e-16 5.54412689e-14 1.29834692e-15
 5.16555212e-15 1.13595543e-17 5.33347171e-19 9.58771912e-14
 1.51429905e-11 8.32216438e-15 6.32591925e-18 3.11337609e-21
 6.67051075e-18 5.73309231e-27 2.47418317e-07 3.49671214e-08
 9.76171355e-12 6.64639752e-13 8.20715604e-11 1.79118406e-14
 8.74373509e-12 8.36818819e-14 7.99463123e-12 1.61887803e-07
 2.93651617e-07 4.03569500e-07 6.70788992e-07 5.27400959e-11
 1.55948531e-15 1.74448921e-26 6.39913480e-17 2.28060994e-26
 3.89312328e-14 2.80681634e-09 4.58175159e-07 2.96102583e-13
 3.65484826e-16 3.96977287e-19 6.20044212e-29 2.00670149e-31
 6.08919417e-26 5.97223959e-14 5.56403894e-14 1.14680240e-16
 5.34618700e-13 7.46166297e-12 7.99276197e-17 4.20463648e-08
 5.46626143e-08 2.08350596e-12 3.87947278e-06 2.70095062e-01
 6.58371334e-11 2.67861766e-01 1.79613644e-04 5.87895181e-07
 3.61637414e-07 9.57788323e-08 1.54766238e-06 3.19938796e-09
 1.16164928e-10 2.17138411e-08 3.75718741e-11 1.08670207e-11
 1.54748827e-14 1.23746696e-19 2.25489418e-15 1.25738306e-12
 1.44914370e-10 1.20379882e-17 1.28631996e-13 1.76924278e-24
 1.20749875e-21 2.42152341e-20 1.96276800e-24 1.36966747e-19
 8.74186237e-10 2.03003613e-09 1.06825174e-06 8.21924101e-12
 5.69502055e-05 5.42056594e-04 2.25657172e-06 1.37183300e-08
 1.52448521e-08 5.99798870e+00 5.52331632e+00 2.25652699e-07
 6.89609233e-02 3.02351918e-01 1.99548885e-05 2.07805200e+00
 7.05859850e-06 4.40538328e-13 2.83498973e-21 3.32253768e-13
 7.94086316e-14 2.72269982e-13 1.15655326e-17 1.35199991e-14
 1.44683745e-15 6.45978671e-07 6.38987012e-09 1.45217429e-16
 2.70880138e-23 1.39675903e-20 1.52014638e-17 2.86384076e-18
 3.56006466e-22 2.72436785e-22 4.07283361e-19 6.31709446e-19
 1.65221348e-23 1.71828105e-20 2.07446472e-12 2.98944007e-11
 1.22979402e-11 3.38094234e-15 1.29037148e-11 2.33357550e-17
 4.45960254e-10 9.23698822e-11 1.21103498e-17 6.80442825e-15
 2.20331605e-09 4.10370228e-19 6.90076217e-21 8.85546439e-23

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/core/universe.py:817: DeprecationWarning: The bfactor topology attribute is only provided as an alias to the tempfactor attribute. It will be removed in 3.0. Please use the tempfactor attribute instead.
  warnings.warn(BFACTOR_WARNING, DeprecationWarning)
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/core/topologyattrs.py:282: DeprecationWarning: The bfactor topology attribute is only provided as an alias to the tempfactor attribute. It will be removed in 3.0. Please use the tempfactor attribute instead.
  warnings.warn(BFACTOR_WARNING, DeprecationWarning)
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:753: UserWarning: Unit cell dimensions not found. CRYST1 record set to unitary values.
  warnings.warn("Unit cell dimensions not found. "
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:1129: UserWarning: Found no information for attr: 'formalcharges' Using default value of '0'
  warnings.warn("Found no information for attr: '{}'"

Writing train PDB to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1/train_1_HOIPapo_test_mean1_R3_20240402-191829.pdb
Writing val PDB to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1/val_1_HOIPapo_test_mean1_R3_20240402-191829.pdb
Writing RW representative PDBs
Structures loaded HOIPapo_test_mean1_RW:
HOIPapo_test_mean1_RW Topology: <Universe with 3369 atoms>
HOIPapo_test_mean1_RW Trajectory: <Universe with 3369 atoms>
HOIPapo_test_mean1_RW Traj: no frames 550
[1.  0.4 0.5 1.5 0.8 0.2 1.4 0.  2.3 1.9 0.5 2.7 0.9 4.3 0.7 0.  0.2 1.4
 0.8 1.  0.8 1.5 1.9 1.  0.6 1.1 0.1 0.8 1.2 2.6 1.1 2.3 0.1 1.9 1.5 0.7
 0.2 0.6 0.5 0.9 2.3 1.  1.9 1.4 0.1 0.3 0.5 1.3 0.1 0.1 3.9 1.2 0.4 0.4
 3.  1.9 0.1 0.1 3.5 1.6 2.2 0.3 0.8 0.5 1.  0.7 1.1 0.4 1.9 0.6 0.8 0.5
 0.7 0.9 2.2 1.3 0.2 0.1 1.  1.6 2.8 0.9 1.2 1.  0.8 2.2 0.5 1.1 1.  0.6
 0.1 1.  2.2 2.1 0.  0.7 0.6 0.5 0.6 0.8 0.2 3.4 1.2 1.3 0.  0.5 0.7 1.1
 1.9 1.2 0.5 1.5 1.  1.5 1.1 1.5 1.7 1.6 1.1 0.2 0.5 1.  0.4 0.4 0.1 0.9
 1.6 0.8 1.7 0.1 0.1 0.9 0.5 0.6 0.5 0.3 0.3 0.8 0.5 2.4 0.7 1.  0.4 0.4
 0.6 0.6 0.8 0.7 1.  1.2 0.1 0.3 1.2 2.4 0.2 0.8 3.3 1.3 1.4 3.4 0.1 1.
 1.5 0.5 0.4 0.4 0.5 0.4 1.1 3.2 1.2 1.2 0.4 0.8 0.6 1.2 0.4 0.4 0.9 2.4
 0.4 0.5 1.1 0.  0.6 1.1 2.6 0.4 1.6 1.5 1.3 0.3 1.4 1.4 1.6 0.2 0.1 0.
 0.1 1.5 0.8 0.3 1.8 0.9 0.3 2.1 1.1 1.4 1.2 1.4 0.6 0.2 0.6 0.4 0.4 1.1
 0.8 0.3 0.9 0.7 0.7 0.8 3.  0.5 0.1 0.2 1.  1.9 0.5 1.3 0.8 0.9 1.5 4.6
 0.  0.4 1.3 2.4 0.4 2.7 1.6 1.3 0.7 2.2 2.5 0.2 0.8 0.8 0.7 0.6 0.3 0.8
 0.  0.  2.4 1.2 0.7 0.3 0.9 1.4 0.5 3.5 1.  0.4 0.7 0.5 0.6 0.4 2.1 1.6
 0.2 0.5 1.3 1.  0.6 1.4 0.2 1.8 0.  0.9 2.2 1.5 0.9 0.6 0.4 1.6 0.8 0.3
 0.3 0.7 1.8 1.3 1.  0.3 0.8 1.7 0.5 1.2 0.4 1.  0.9 0.9 0.1 0.6 2.3 1.7
 1.5 1.4 0.7 3.1 0.5 1.1 0.7 2.2 0.9 1.2 2.  1.1 1.3 0.6 1.3 0.9 0.5 1.3
 2.2 0.4 1.5 1.4 1.  1.3 1.1 1.3 0.5 0.6 0.6 0.9 0.2 0.1 0.4 1.  0.6 0.1
 0.8 0.8 0.2 0.3 1.1 1.  0.4 1.7 1.4 0.2 2.7 0.8 0.3 1.3 0.  0.1 1.1 0.
 0.4 1.  0.3 1.5 1.  0.8 0.4 0.2 0.7 0.1 0.3 0.4 1.  1.1 2.  2.1 1.4 0.4
 0.5 1.6 1.8 0.  1.8 1.1 0.4 0.5 0.8 2.3 0.6 1.5 0.1 3.1 0.7 1.1 0.7 0.3
 0.4 3.  0.  0.9 4.5 0.3 1.  2.7 1.9 0.2 0.5 1.  0.8 1.  1.1 1.2 1.5 0.3
 0.6 1.5 1.8 1.  0.5 0.3 1.7 1.4 1.1 0.4 1.7 1.5 0.6 1.6 0.  0.1 0.  0.7
 0.8 1.  2.9 1.  0.  1.5 0.  0.1 1.3 1.4 0.5 0.2 1.1 0.8 0.1 0.1 0.3 0.1
 0.9 0.  1.6 0.8 1.5 0.7 0.2 1.5 1.2 0.4 0.2 1.1 0.8 0.4 1.3 0.9 0.3 0.7
 0.4 0.1 0.5 0.8 3.2 1.  1.8 1.2 0.2 0.8 1.4 0.  0.9 2.4 0.6 1.2 1.1 0.6
 1.8 0.3 1.  0.3 0.7 1.3 1.  0.3 0.  1.3 1.9 0.1 0.3 0.6 0.8 2.3 1.6 3.3
 0.1 1.1 2.9 0.8 0.5 0.4 0.8 0.3 0.9 1.4 1.1 1.3 1.7 0.4 0.4 2.9 2.7 1.8
 1.2 1.  0.1 0.9 2.1 1.7 1.2 0.8 0.3 1.2 1.  1.2 0.6 0.7 1.  2.8 1.6 1.
 0.4 1.  1.3 1.2 1.  0.  0.1 0.2 0.2 3. ]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549]
550
[233 400  13  50  58 261 101 159 156 503 169 472 309 391 397  54 549 222
 519 506 434 537  80 352 520 239  11 403 186  29 244 179 139 153 481 237
 254   8  31 501  40 387 304 324  60 280  85  92  74 243 313 375 205 268
  93 526 374 316 496 108 227  68  22  42  55   9 404  33 202 521 382 486
 474 380 277 416 290 516 305 128 527 424 116 349 295 420 117  79 379 269
 188 126 194 502 452 538  59 240 285 427 415 113 425 281 326   3 457 306
  21 199 189 111  34 437 232 454 115 389 412 162 363 478  17   6 307 513
 441 259 207 192 350 209 158 193 275 421 376  43 327 236 103 318 190 157
 515 320 323 355 272 440 331 241  47 229 291 491 329  75 495 464 542 531
 543  82 171 522 411 152 528 170 297 208  28 175 255 109 149 475 533  51
 315 483 102 458 168 330  87 505 118 358  25 107 206 393  30 114 346 383
  66 422 215 182 410 461 514 311 444 317 185 373 484 541 539 328 473 112
 372 402 161 532 364 361 435 417 409 492 141 347  19  88 148 292 262 339
 488  41 544  64 407 536  91 523  78 433 121 226  23 273   0  83 299 525
  39 321 300 314 335 125 203  12 231 178 258 131 465  73  81 512 480 399
 279 282 450 218 301  27  20 342 146 343  99 529 137 221  62   4 500 477
 294 510 471 365 127 507 200 286 445 386 453  84 155 353 462 408 173  70
  18 247 216 230 251 246 432  72 312  65  95 248 219  14 392 140 431 106
 308 264 242 289 147 455 368 535 467 256 394  35 490 220  98 499 274 212
 303 266 144 534 174 283 133 334 482 485 414 249 145 426 319 340  89 210
  24  37 388  96  69 333 184  46 132 181 271 310 110 260 296 418 138 378
  63 385 105 120 223 163 406 265  38 166  10 332  86 228 442 134 508 470
   2  97  71 322 213 509 238 518 122 177 348   1 284  52 214 396 164 298
 360 165 142 338 187 517 143 366 468 540 384 123  67 267 463 180 235 325
 423 172  53 377 371 263 459 167 176 498 413 448 511 151 204 395 401 288
 489 191 466 250 345 201 287 354  45 293  61 257 370 487 530 217 135 362
 136 493 419 245 100 344 405 154   5 476 460 336 367 119 276 548 443 225
 270 195  16  76 456 211 351  36 547 337  56 130 447  77 224 198 439 302
 429 160 446  49 524 497  26 341  48 196 369 469 449  32  57 129 504 124
 150 546 390  90  44 357 436 494   7 104 451  94 438  15 359 197 253 234
 278 428 356 479 398 183 381 545 252 430]
Recluster Frames
[233 233 233 233 233 400 400 400 400  13  13  13  13  50  50  50  50  58
  58  58  58 261 261 261 101 101 101 159 159 159 156 156 156 503 503 503
 169 169 169 472 472 472 309 309 309 391 391 391 397 397 397  54  54  54
 549 549 549 222 222 222 519 519 519 506 506 506 434 434 434 537 537 537
  80  80  80 352 352 352 520 520 520 239 239 239  11  11  11 403 403 403
 186 186 186  29  29  29 244 244 179 179 139 139 153 153 481 481 237 237
 254 254   8   8  31  31 501 501  40  40 387 387 304 304 324 324  60  60
 280 280  85  85  92  92  74  74 243 243 313 313 375 375 205 205 268 268
  93  93 526 526 374 374 316 316 496 496 108 108 227 227  68  68  22  22
  42  42  55  55   9   9 404 404  33  33 202 202 521 521 382 382 486 486
 474 474 380 380 277 277 416 416 290 290 516 516 305 305 128 128 527 527
 424 424 116 116 349 349 295 295 420 420 117 117  79  79 379 379 269 269
 188 188 126 126 194 194 502 502 452 452 538 538  59  59 240 240 285 285
 427 427 415 415 113 113 425 425 281 281 326 326   3   3 457 457 306 306
  21  21 199 199 189 189 111 111  34  34 437 437 232 454 115 389 412 162
 363 478  17   6 307 513 441 259 207 192 350 209 158 193 275 421 376  43
 327 236 103 318 190 157 515 320 323 355 272 440 331 241  47 229 291 491
 329  75 495 464 542 531 543  82 171 522 411 152 528 170 297 208  28 175
 255 109 149 475 533  51 315 483 102 458 168 330  87 505 118 358  25 107
 206 393  30 114 346 383  66 422 215 182 410 461 514 311 444 317 185 373
 484 541 539 328 473 112 372 402 161 532 364 361 435 417 409 492 141 347
  19  88 148 292 262 339 488  41 544  64 407 536  91 523  78 433 121 226
  23 273   0  83 299 525  39 321 300 314 335 125 203  12 231 178 258 131
 465  73  81 512 480 399 279 282 450 218 301  27  20 342 146 343  99 529
 137 221  62   4 500 477 294 510 471 365 127 507 200 286 445 386 453  84
 155 353 462 408 173  70  18 247 216 230 251 246 432  72 312  65  95 248
 219  14 392 140 431 106 308 264 242 289 147 455 368 535 467 256 394  35
 490 220  98 499 274 212 303 266 144 534 174 283 133 334 482 485 414 249
 145 426 319 340  89 210  24  37 388  96  69 333 184  46 132 181 271 310
 110 260 296 418 138 378  63 385 105]
531
Modal Cluster
[465 297  62  88 230 403  84 402 538  74] 10
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Writing RW representative PDB to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1/RW_1_HOIPapo_test_mean1_R3_20240402-191829.pdb

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

Finished running VDX loop
Evaluating HDX
plotting gamma distributions
['train_HOIPapo_test_mean1_RW_1']
['val_HOIPapo_test_mean1_RW_1']
Restoring trainval peptide numbers
train_rep_names ['train_HOIPapo_test_mean1_RW_1']
val_rep_names ['val_HOIPapo_test_mean1_RW_1']
test_rep_names ['test_HOIPapo_test_mean1_RW_1']
train_rep_peptides [62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107]
val_rep_peptides [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]
test_rep_peptides [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107]
manual merge df
     0.0      0.5      5.0  peptide                      calc_name
0    0.0  0.00001  0.00008       62  train_HOIPapo_test_mean1_RW_1
1    0.0  0.00001  0.00008       63  train_HOIPapo_test_mean1_RW_1
2    0.0  0.00000  0.00000       64  train_HOIPapo_test_mean1_RW_1
3    0.0  0.00000  0.00000       65  train_HOIPapo_test_mean1_RW_1
4    0.0  0.00000  0.00000       66  train_HOIPapo_test_mean1_RW_1
5    0.0  0.00000  0.00000       67  train_HOIPapo_test_mean1_RW_1
6    0.0  0.00000  0.00000       68  train_HOIPapo_test_mean1_RW_1
7    0.0  0.00000  0.00000       69  train_HOIPapo_test_mean1_RW_1
8    0.0  0.00000  0.00000       70  train_HOIPapo_test_mean1_RW_1
9    0.0  0.00000  0.00000       71  train_HOIPapo_test_mean1_RW_1
10   0.0  0.00000  0.00000       72  train_HOIPapo_test_mean1_RW_1
11   0.0  0.00000  0.00000       73  train_HOIPapo_test_mean1_RW_1
12   0.0  0.00000  0.00000       74  train_HOIPapo_test_mean1_RW_1
13   0.0  0.00000  0.00000       75  train_HOIPapo_test_mean1_RW_1
14   0.0  0.00000  0.00000       76  train_HOIPapo_test_mean1_RW_1
15   0.0  0.00000  0.00000       77  train_HOIPapo_test_mean1_RW_1
16   0.0  0.02994  0.18025       78  train_HOIPapo_test_mean1_RW_1
17   0.0  0.00000  0.00000       79  train_HOIPapo_test_mean1_RW_1
18   0.0  0.00000  0.00000       80  train_HOIPapo_test_mean1_RW_1
19   0.0  0.00000  0.00000       93  train_HOIPapo_test_mean1_RW_1
20   0.0  0.00000  0.00000       94  train_HOIPapo_test_mean1_RW_1
21   0.0  0.00000  0.00000       95  train_HOIPapo_test_mean1_RW_1
22   0.0  0.00000  0.00000       96  train_HOIPapo_test_mean1_RW_1
23   0.0  0.00000  0.00000       97  train_HOIPapo_test_mean1_RW_1
24   0.0  0.00000  0.00000       98  train_HOIPapo_test_mean1_RW_1
25   0.0  0.10524  0.10533       99  train_HOIPapo_test_mean1_RW_1
26   0.0  0.11109  0.11118      100  train_HOIPapo_test_mean1_RW_1
27   0.0  0.10524  0.10533      101  train_HOIPapo_test_mean1_RW_1
28   0.0  0.12497  0.12508      102  train_HOIPapo_test_mean1_RW_1
29   0.0  0.11762  0.11773      103  train_HOIPapo_test_mean1_RW_1
30   0.0  0.09998  0.10007      104  train_HOIPapo_test_mean1_RW_1
31   0.0  0.13331  0.13342      105  train_HOIPapo_test_mean1_RW_1
32   0.0  0.11109  0.11118      106  train_HOIPapo_test_mean1_RW_1
33   0.0  0.11762  0.11773      107  train_HOIPapo_test_mean1_RW_1
34   0.0  0.00004  0.00037        0    val_HOIPapo_test_mean1_RW_1
35   0.0  0.09091  0.09093        1    val_HOIPapo_test_mean1_RW_1
36   0.0  0.07148  0.07191        2    val_HOIPapo_test_mean1_RW_1
37   0.0  0.05569  0.05694        3    val_HOIPapo_test_mean1_RW_1
38   0.0  0.10000  0.10003        4    val_HOIPapo_test_mean1_RW_1
39   0.0  0.07697  0.07744        5    val_HOIPapo_test_mean1_RW_1
40   0.0  0.05897  0.06029        6    val_HOIPapo_test_mean1_RW_1
41   0.0  0.11111  0.11114        7    val_HOIPapo_test_mean1_RW_1
42   0.0  0.09097  0.09152        8    val_HOIPapo_test_mean1_RW_1
43   0.0  0.08339  0.08389        9    val_HOIPapo_test_mean1_RW_1
44   0.0  0.06683  0.06833       10    val_HOIPapo_test_mean1_RW_1
45   0.0  0.06266  0.06406       11    val_HOIPapo_test_mean1_RW_1
46   0.0  0.14286  0.14290       12    val_HOIPapo_test_mean1_RW_1
47   0.0  0.11119  0.11186       13    val_HOIPapo_test_mean1_RW_1
48   0.0  0.10007  0.10067       14    val_HOIPapo_test_mean1_RW_1
49   0.0  0.08354  0.08541       15    val_HOIPapo_test_mean1_RW_1
50   0.0  0.07161  0.07321       16    val_HOIPapo_test_mean1_RW_1
51   0.0  0.00032  0.00318       17    val_HOIPapo_test_mean1_RW_1
52   0.0  0.00000  0.00000       18    val_HOIPapo_test_mean1_RW_1
53   0.0  0.00000  0.00000       19    val_HOIPapo_test_mean1_RW_1
54   0.0  0.00000  0.00000       20    val_HOIPapo_test_mean1_RW_1
55   0.0  0.00000  0.00000       21    val_HOIPapo_test_mean1_RW_1
56   0.0  0.00000  0.00000       22    val_HOIPapo_test_mean1_RW_1
57   0.0  0.00000  0.00000       23    val_HOIPapo_test_mean1_RW_1
58   0.0  0.00001  0.00007       24    val_HOIPapo_test_mean1_RW_1
59   0.0  0.00001  0.00007       25    val_HOIPapo_test_mean1_RW_1
60   0.0  0.00001  0.00007       26    val_HOIPapo_test_mean1_RW_1
61   0.0  0.00001  0.00008       27    val_HOIPapo_test_mean1_RW_1
62   0.0  0.00001  0.00008       28    val_HOIPapo_test_mean1_RW_1
63   0.0  0.00081  0.00750       29    val_HOIPapo_test_mean1_RW_1
64   0.0  0.00153  0.01428       30    val_HOIPapo_test_mean1_RW_1
65   0.0  0.00112  0.01047       31    val_HOIPapo_test_mean1_RW_1
66   0.0  0.00120  0.01122       32    val_HOIPapo_test_mean1_RW_1
67   0.0  0.00211  0.01962       33    val_HOIPapo_test_mean1_RW_1
68   0.0  0.00140  0.01308       34    val_HOIPapo_test_mean1_RW_1
69   0.0  0.00005  0.00051       35    val_HOIPapo_test_mean1_RW_1
70   0.0  0.00007  0.00066       36    val_HOIPapo_test_mean1_RW_1
71   0.0  0.00008  0.00077       37    val_HOIPapo_test_mean1_RW_1
72   0.0  0.00007  0.00066       38    val_HOIPapo_test_mean1_RW_1
73   0.0  0.00005  0.00051       39    val_HOIPapo_test_mean1_RW_1
74   0.0  0.00005  0.00046       40    val_HOIPapo_test_mean1_RW_1
75   0.0  0.00002  0.00024       41    val_HOIPapo_test_mean1_RW_1
76   0.0  0.00000  0.00000       42    val_HOIPapo_test_mean1_RW_1
77   0.0  0.00000  0.00000       43    val_HOIPapo_test_mean1_RW_1
78   0.0  0.00000  0.00000       44    val_HOIPapo_test_mean1_RW_1
79   0.0  0.00000  0.00000       45    val_HOIPapo_test_mean1_RW_1
80   0.0  0.00001  0.00009       46    val_HOIPapo_test_mean1_RW_1
81   0.0  0.00001  0.00011       47    val_HOIPapo_test_mean1_RW_1
82   0.0  0.00001  0.00009       48    val_HOIPapo_test_mean1_RW_1
83   0.0  0.12321  0.14408       49    val_HOIPapo_test_mean1_RW_1
84   0.0  0.00014  0.00143       50    val_HOIPapo_test_mean1_RW_1
85   0.0  0.00000  0.00000       51    val_HOIPapo_test_mean1_RW_1
86   0.0  0.00000  0.00000       52    val_HOIPapo_test_mean1_RW_1
87   0.0  0.00000  0.00000       53    val_HOIPapo_test_mean1_RW_1
88   0.0  0.00111  0.01017       54    val_HOIPapo_test_mean1_RW_1
89   0.0  0.00003  0.00030       81    val_HOIPapo_test_mean1_RW_1
90   0.0  0.00002  0.00025       82    val_HOIPapo_test_mean1_RW_1
91   0.0  0.00002  0.00023       83    val_HOIPapo_test_mean1_RW_1
92   0.0  0.00003  0.00027       84    val_HOIPapo_test_mean1_RW_1
93   0.0  0.00002  0.00025       85    val_HOIPapo_test_mean1_RW_1
94   0.0  0.00004  0.00042       86    val_HOIPapo_test_mean1_RW_1
95   0.0  0.00003  0.00030       87    val_HOIPapo_test_mean1_RW_1
96   0.0  0.00004  0.00043       88    val_HOIPapo_test_mean1_RW_1
97   0.0  0.21760  0.33468       89    val_HOIPapo_test_mean1_RW_1
98   0.0  0.20086  0.30893       90    val_HOIPapo_test_mean1_RW_1
99   0.0  0.17408  0.26774       91    val_HOIPapo_test_mean1_RW_1
100  0.0  0.14506  0.22312       92    val_HOIPapo_test_mean1_RW_1
train segs [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107]
val segs [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 81 82 83 84 85 86 87 88 89 90 91 92]
Adding experimental data in to merge df
dumping data
dumped data
plotting dfracs compare for merge_df
plotting dfracs compare abs for merge_df

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

plotting R agreement
concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting abs error for nan_df
plotting MSE for nan_df
plotting AVG df
Train coverage: 31.48
Val coverage: 62.04
plotting dfracs compare for avg_df
plotting paired errors for avg_df

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

Finished evaluating HDX
    Bc    Bh                      calc_name
0  2.0  0.35  train_HOIPapo_test_mean1_RW_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/alexi/Documents/ValDX/ValDX/HDX_plots.py:2152: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, axs = plt.subplots(1, 2, figsize=(12, 6))  # Create a figure with 1 row and 2 columns for subplots

Transformed data
(550, 2)
Cluster Centers
[[-4.7269104e+02  1.5726756e+02]
 [ 5.7354956e+02  9.0724487e+01]
 [ 1.4136969e+02  4.4649982e+00]
 [-1.7372696e+02 -2.0836922e+02]
 [ 8.1659344e+02 -7.2083969e+01]
 [-1.7059448e+02  6.8604980e+01]
 [-6.8798828e-01  3.5248785e+02]
 [-4.3990067e+02 -1.0634476e+02]
 [ 3.0787463e+02  2.1390785e+02]
 [ 1.7203287e+02 -2.8865054e+02]]
Getting cluster labels
(550,)
Unique labels
Final Cluster Weights
[1.43524773 1.13784148 0.88859965 1.29105018 0.99098678 1.00513752
 0.55652092 1.17227849 0.82076138 0.70157588]
10.0
10
Final Cluster Weights
[1.43524773 1.13784148 0.88859965 1.29105018 0.99098678 1.00513752
 0.55652092 1.17227849 0.82076138 0.70157588]
(10,)
Mean Cluster
[379, 199, 89, 338, 484, 274, 5, 463, 506, 0]
[1.43524773 1.13784148 0.88859965 1.29105018 0.99098678 1.00513752
 0.55652092 1.17227849 0.82076138 0.70157588]

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py:241: UserWarning: Reload offsets from trajectory
 ctime or size or n_atoms did not match
  warnings.warn("Reload offsets from trajectory\n "
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:753: UserWarning: Unit cell dimensions not found. CRYST1 record set to unitary values.
  warnings.warn("Unit cell dimensions not found. "
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:1129: UserWarning: Found no information for attr: 'formalcharges' Using default value of '0'
  warnings.warn("Found no information for attr: '{}'"

(2, 6)
Running benchmark for cluster_2
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name cluster_2 already exists. Attempting to change name to cluster_20
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN     cluster_2

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
conda run -n HDXER_ENV python /home/alexi/Documents/HDXer/HDXer/calc_hdx.py -t /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1_reclustered_csize2_10_.xtc -p /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb -m BestVendruscolo -log /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/calc_hdx_prep_cluster_20_0.log -out /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0 -seg /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_APO_segs.txt -mopt "{ 'save_detailed' : True }" --times 0 0.5 5.0 -str 1
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/mdtraj/formats/pdb/pdbfile.py:200: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
/home/alexi/Documents/HDXer/HDXer/dfpred.py:505: RuntimeWarning: divide by zero encountered in log
  logerr = logf + np.log(err) + np.log(time) # sd(e^Aa) = f * sd(A) * a
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

Residue predictions complete

Running r split mode
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name cluster_2_r_naive_random already exists. Attempting to change name to cluster_2_r_naive_random0
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN     cluster_2

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
Running VDX loop
Random seeds: [42]
Randomly splitting segments for cluster_2 with random seed 42 and train fraction 0.5
train_segs
    ResStr  ResEnd  peptide          calc_name
77     196     208       77  train_cluster_2_1
10       8      24       10  train_cluster_2_1
4        7      18        4  train_cluster_2_1
83     247     260       83  train_cluster_2_1
62     154     169       62  train_cluster_2_1
Saved train cluster_2_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/train_cluster_2_1/train_residue_segs__cluster_2_.txt
Train Peptide numbers: [  0   4   5   7   9  10  11  12  15  16  18  19  22  26  27  28  30  31
  33  34  35  36  39  40  42  43  44  45  47  53  55  56  62  64  65  66
  67  69  72  76  77  78  79  80  81  83  88  89  90  95 100 103 106 107]
Saved val cluster_2_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/val_residue_segs__cluster_2_.txt
Val Peptide numbers: [  1   2   3   6   8  13  14  17  20  21  23  24  25  29  32  37  38  41
  46  48  49  50  51  52  54  57  58  59  60  61  63  68  70  71  73  74
  75  82  84  85  86  87  91  92  93  94  96  97  98  99 101 102 104 105]
train_HDX_data
    0.0      0.5      5.0  peptide          calc_name  \
0   0.0  0.13267  0.18143       77  train_cluster_2_1
1   0.0  0.48273  0.53102       10  train_cluster_2_1
2   0.0  0.41726  0.49519        4  train_cluster_2_1
3   0.0  0.08147  0.13526       83  train_cluster_2_1
4   0.0  0.50341  0.53212       62  train_cluster_2_1
5   0.0  0.28164  0.36568       67  train_cluster_2_1
6   0.0  0.26192  0.34619       30  train_cluster_2_1
7   0.0  0.37847  0.48848       45  train_cluster_2_1
8   0.0  0.04358  0.04371       95  train_cluster_2_1
9   0.0  0.50258  0.53988       11  train_cluster_2_1
10  0.0  0.05688  0.07274       81  train_cluster_2_1
11  0.0  0.20249  0.21472       79  train_cluster_2_1
12  0.0  0.41879  0.44438        0  train_cluster_2_1
13  0.0  0.16260  0.17496       80  train_cluster_2_1
14  0.0  0.17163  0.27883       18  train_cluster_2_1
15  0.0  0.27969  0.36567       69  train_cluster_2_1
16  0.0  0.26061  0.32801       56  train_cluster_2_1
17  0.0  0.11684  0.15140       76  train_cluster_2_1
18  0.0  0.22454  0.24966      106  train_cluster_2_1
19  0.0  0.33575  0.45181       42  train_cluster_2_1
20  0.0  0.47373  0.50144       12  train_cluster_2_1
21  0.0  0.34716  0.45807       36  train_cluster_2_1
22  0.0  0.26524  0.35365       64  train_cluster_2_1
23  0.0  0.34135  0.38830       26  train_cluster_2_1
24  0.0  0.31355  0.39928       22  train_cluster_2_1
25  0.0  0.31421  0.37857       31  train_cluster_2_1
26  0.0  0.18217  0.28305       47  train_cluster_2_1
27  0.0  0.20729  0.23030      100  train_cluster_2_1
28  0.0  0.55802  0.57504       15  train_cluster_2_1
29  0.0  0.37082  0.47284       44  train_cluster_2_1
30  0.0  0.10385  0.19651       88  train_cluster_2_1
31  0.0  0.53877  0.49943       89  train_cluster_2_1
32  0.0  0.46825  0.52028        9  train_cluster_2_1
33  0.0  0.29666  0.37860       33  train_cluster_2_1
34  0.0  0.26392  0.30614       55  train_cluster_2_1
35  0.0  0.21731  0.24442      103  train_cluster_2_1
36  0.0  0.28439  0.33185       28  train_cluster_2_1
37  0.0  0.28369  0.42940       40  train_cluster_2_1
38  0.0  0.44176  0.50927        5  train_cluster_2_1
39  0.0  0.18105  0.23003       53  train_cluster_2_1
40  0.0  0.23913  0.27068      107  train_cluster_2_1
41  0.0  0.33252  0.48976       39  train_cluster_2_1
42  0.0  0.33633  0.46390       35  train_cluster_2_1
43  0.0  0.55641  0.57196       16  train_cluster_2_1
44  0.0  0.35203  0.42601       78  train_cluster_2_1
45  0.0  0.38440  0.44775       34  train_cluster_2_1
46  0.0  0.25152  0.35786       66  train_cluster_2_1
47  0.0  0.41316  0.48254        7  train_cluster_2_1
48  0.0  0.33443  0.43697       43  train_cluster_2_1
49  0.0  0.25454  0.32548       65  train_cluster_2_1
50  0.0  0.36820  0.37879       72  train_cluster_2_1
51  0.0  0.28512  0.29602       27  train_cluster_2_1
52  0.0  0.16883  0.28686       19  train_cluster_2_1
53  0.0  0.51417  0.47866       90  train_cluster_2_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     196     208
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      24
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      18
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     260
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     154     169
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     186
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      61
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      89      97
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     308     315
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      25
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     257
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     238
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       1       7
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     239
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      32
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     186
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     153
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     194     208
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     360
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      85      97
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      18
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      76      84
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     169     183
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      51
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      34      40
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      65
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     106
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     356
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      23
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      88      97
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     253     260
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     275
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      21
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      61
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     150
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     357
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      51
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      88
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      21
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     121     132
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     339     360
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      87
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      74      84
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      25
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     213     223
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      65
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     185
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      18
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      86      97
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     183
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     195
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      49
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      33
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     276
    ResStr  ResEnd  0.0      0.5      5.0  peptide          calc_name  \
0      196     208  0.0  0.13267  0.18143       77  train_cluster_2_1
1        8      24  0.0  0.48273  0.53102       10  train_cluster_2_1
2        7      18  0.0  0.41726  0.49519        4  train_cluster_2_1
3      247     260  0.0  0.08147  0.13526       83  train_cluster_2_1
4      154     169  0.0  0.50341  0.53212       62  train_cluster_2_1
5      170     186  0.0  0.28164  0.36568       67  train_cluster_2_1
6       49      61  0.0  0.26192  0.34619       30  train_cluster_2_1
7       89      97  0.0  0.37847  0.48848       45  train_cluster_2_1
8      308     315  0.0  0.04358  0.04371       95  train_cluster_2_1
9        8      25  0.0  0.50258  0.53988       11  train_cluster_2_1
10     247     257  0.0  0.05688  0.07274       81  train_cluster_2_1
11     224     238  0.0  0.20249  0.21472       79  train_cluster_2_1
12       1       7  0.0  0.41879  0.44438        0  train_cluster_2_1
13     224     239  0.0  0.16260  0.17496       80  train_cluster_2_1
14      26      32  0.0  0.17163  0.27883       18  train_cluster_2_1
15     171     186  0.0  0.27969  0.36567       69  train_cluster_2_1
16     132     153  0.0  0.26061  0.32801       56  train_cluster_2_1
17     194     208  0.0  0.11684  0.15140       76  train_cluster_2_1
18     338     360  0.0  0.22454  0.24966      106  train_cluster_2_1
19      85      97  0.0  0.33575  0.45181       42  train_cluster_2_1
20      11      18  0.0  0.47373  0.50144       12  train_cluster_2_1
21      76      84  0.0  0.34716  0.45807       36  train_cluster_2_1
22     169     183  0.0  0.26524  0.35365       64  train_cluster_2_1
23      41      51  0.0  0.34135  0.38830       26  train_cluster_2_1
24      34      40  0.0  0.31355  0.39928       22  train_cluster_2_1
25      49      65  0.0  0.31421  0.37857       31  train_cluster_2_1
26      98     106  0.0  0.18217  0.28305       47  train_cluster_2_1
27     334     356  0.0  0.20729  0.23030      100  train_cluster_2_1
28      11      23  0.0  0.55802  0.57504       15  train_cluster_2_1
29      88      97  0.0  0.37082  0.47284       44  train_cluster_2_1
30     253     260  0.0  0.10385  0.19651       88  train_cluster_2_1
31     261     275  0.0  0.53877  0.49943       89  train_cluster_2_1
32       8      21  0.0  0.46825  0.52028        9  train_cluster_2_1
33      52      61  0.0  0.29666  0.37860       33  train_cluster_2_1
34     132     150  0.0  0.26392  0.30614       55  train_cluster_2_1
35     336     357  0.0  0.21731  0.24442      103  train_cluster_2_1
36      42      51  0.0  0.28439  0.33185       28  train_cluster_2_1
37      77      88  0.0  0.28369  0.42940       40  train_cluster_2_1
38       7      21  0.0  0.44176  0.50927        5  train_cluster_2_1
39     121     132  0.0  0.18105  0.23003       53  train_cluster_2_1
40     339     360  0.0  0.23913  0.27068      107  train_cluster_2_1
41      77      87  0.0  0.33252  0.48976       39  train_cluster_2_1
42      74      84  0.0  0.33633  0.46390       35  train_cluster_2_1
43      11      25  0.0  0.55641  0.57196       16  train_cluster_2_1
44     213     223  0.0  0.35203  0.42601       78  train_cluster_2_1
45      52      65  0.0  0.38440  0.44775       34  train_cluster_2_1
46     170     185  0.0  0.25152  0.35786       66  train_cluster_2_1
47       8      18  0.0  0.41316  0.48254        7  train_cluster_2_1
48      86      97  0.0  0.33443  0.43697       43  train_cluster_2_1
49     170     183  0.0  0.25454  0.32548       65  train_cluster_2_1
50     187     195  0.0  0.36820  0.37879       72  train_cluster_2_1
51      42      49  0.0  0.28512  0.29602       27  train_cluster_2_1
52      26      33  0.0  0.16883  0.28686       19  train_cluster_2_1
53     261     276  0.0  0.51417  0.47866       90  train_cluster_2_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train cluster_2 HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/train_cluster_2_1/train_cluster_2_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide        calc_name  \
0        6      18  0.0  0.37096  0.45204        1  val_cluster_2_1
1        6      21  0.0  0.40040  0.48544        2  val_cluster_2_1
2        6      25  0.0  0.45875  0.51503        3  val_cluster_2_1
3        7      25  0.0  0.48987  0.54090        6  val_cluster_2_1
4        8      20  0.0  0.46617  0.51066        8  val_cluster_2_1
5       11      20  0.0  0.52057  0.54102       13  val_cluster_2_1
6       11      21  0.0  0.52823  0.55640       14  val_cluster_2_1
7       19      25  0.0  0.52928  0.54827       17  val_cluster_2_1
8       27      33  0.0  0.16341  0.27353       20  val_cluster_2_1
9       33      40  0.0  0.32309  0.41205       21  val_cluster_2_1
10      34      41  0.0  0.34392  0.42213       23  val_cluster_2_1
11      41      48  0.0  0.35604  0.35617       24  val_cluster_2_1
12      41      49  0.0  0.34105  0.35125       25  val_cluster_2_1
13      42      65  0.0  0.32954  0.39085       29  val_cluster_2_1
14      50      65  0.0  0.32314  0.38565       32  val_cluster_2_1
15      77      84  0.0  0.34165  0.44393       37  val_cluster_2_1
16      77      85  0.0  0.30725  0.43533       38  val_cluster_2_1
17      77      97  0.0  0.35906  0.50293       41  val_cluster_2_1
18      98     104  0.0  0.22218  0.31040       46  val_cluster_2_1
19      98     108  0.0  0.25719  0.37045       48  val_cluster_2_1
20     113     120  0.0  0.49756  0.50850       49  val_cluster_2_1
21     114     120  0.0  0.55024  0.54326       50  val_cluster_2_1
22     117     131  0.0  0.24310  0.29208       51  val_cluster_2_1
23     121     131  0.0  0.19173  0.23972       52  val_cluster_2_1
24     132     149  0.0  0.26140  0.30267       54  val_cluster_2_1
25     150     169  0.0  0.45297  0.53974       57  val_cluster_2_1
26     151     162  0.0  0.31622  0.45372       58  val_cluster_2_1
27     151     167  0.0  0.43711  0.52972       59  val_cluster_2_1
28     151     169  0.0  0.47628  0.54735       60  val_cluster_2_1
29     151     170  0.0  0.49249  0.57156       61  val_cluster_2_1
30     155     169  0.0  0.53500  0.53827       63  val_cluster_2_1
31     171     183  0.0  0.24177  0.30174       68  val_cluster_2_1
32     184     195  0.0  0.38633  0.44869       70  val_cluster_2_1
33     184     208  0.0  0.24871  0.31226       71  val_cluster_2_1
34     187     208  0.0  0.22903  0.26839       73  val_cluster_2_1
35     187     209  0.0  0.21687  0.25989       74  val_cluster_2_1
36     188     208  0.0  0.20479  0.23593       75  val_cluster_2_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/train_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/train_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00000  0.00000        0
1  0.0  0.06673  0.06726        1
2  0.0  0.10000  0.10001        2
3  0.0  0.00000  0.00000        3
4  0.0  0.00001  0.00011        4
Experimental cluster_2 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat
REWIGHTING val_cluster_2_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random0/val_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.09091  0.09092        0
1  0.0  0.07145  0.07166        1
2  0.0  0.05561  0.05605        2
3  0.0  0.05888  0.05935        3
4  0.0  0.09094  0.09120        4
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45
46       98     104       46
47       98     106       47
48       98     108       48
49      113     120       49
50      114     120       50
51      117     131       51
52      121     131       52
53      121     132       53
54      132     149       54
55      132     150       55
56      132     153       56
57      150     169       57
58      151     162       58
59      151     167       59
60      151     169       60
61      151     170       61
62      154     169       62
63      155     169       63
64      169     183       64
65      170     183       65
66      170     185       66
67      170     186       67
68      171     183       68
69      171     186       69
70      184     195       70
71      184     208       71
72      187     195       72
73      187     208       73
74      187     209       74
75      188     208       75
76      194     208       76
77      196     208       77
78      213     223       78
79      224     238       79
80      224     239       80
81      247     257       81
82      247     259       82
83      247     260       83
84      248     259       84
85      248     260       85
86      250     257       86
87      250     260       87
88      253     260       88
89      261     275       89
90      261     276       90
91      261     278       91
92      261     281       92
93      305     313       93
94      305     315       94
95      308     315       95
96      314     327       96
97      316     327       97
98      317     327       98
99      333     356       99

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
LogPf_by_res [34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
Pf_by_res [1.54869129e+15 6.43841553e+26 2.15360553e+17 1.04980485e+12
 9.46574006e+06 6.79517751e+12 2.96876504e+14 7.98983831e+10
 8.04844774e+11 1.19657911e+10 7.27515016e+01 2.19784913e+08
 6.72439411e+19 2.00012787e+21 4.94039627e+14 7.00665325e+18
 1.02425136e+06 4.29010165e+08 4.33446277e+13 3.13143209e+06
 1.24298683e+08 2.02009409e+15 1.16307032e+22 2.19487354e+28
 5.54208220e+11 8.52689864e+16 2.16953109e+25 2.89117644e+23
 7.43957430e+17 6.08840486e+16 4.95817000e+18 1.49267298e+21
 1.20206031e+19 8.26873626e+27 2.40290426e+22 3.75796210e+15
 1.54709720e+12 2.49835152e+15 5.51831003e+13 1.10867521e+11
 3.41040848e+07 2.09551142e+13 3.59989917e+20 6.71916035e+25
 8.80915231e+30 1.22115019e+13 1.09831713e+08 1.38558819e+16
 1.72170324e+16 7.96218677e+04 3.43742959e+07 1.03301516e+07
 6.01215626e+13 4.20370772e+08 1.95855476e+05 7.26352827e+11
 1.26699828e+23 2.65053064e+17 6.64765336e+13 6.34588549e+15
 1.83214005e+26 1.14664444e+12 1.83827633e+13 7.98839904e+22
 6.63093150e+12 9.02523903e+05 9.63824855e+16 3.58580302e+23
 4.31404576e+16 1.32745388e+18 8.63748343e+23 5.56396988e+23
 3.69534744e+19 4.46051887e+22 5.15852843e+22 3.29303015e+18
 1.79147070e+22 5.78412017e+19 1.85293868e+18 1.67020125e+19
 9.57771044e+17 2.79034005e+12 2.75829360e+12 2.92079963e+07
 1.58893202e+24 5.10111943e+25 6.06159738e+18 6.58383735e+30
 2.49568819e+19 9.11410067e+10 1.50327558e+09 6.11249589e+13
 9.53093166e+19 3.80270177e+06 7.52665978e+01 3.16939408e+05
 1.45787529e+06 5.61741288e+12 1.54351546e+21 9.91504498e+34
 7.61219663e+20 5.51417615e+26 8.99566856e+09 2.29397145e+10
 8.14479325e+13 4.10200306e+14 2.81346704e+18 1.33940332e+28
 2.12471170e+36 8.07467372e+24 1.71063416e+11 8.01065627e+11
 1.44637252e+17 2.65346237e+17 4.01971241e+14 8.61419719e+16
 4.72101949e+15 2.08389495e+05 4.15393827e+09 1.24983528e+28
 1.59371193e+18 8.64346123e+04 8.90267835e+11 1.53496231e+14
 1.54244518e+16 3.75783305e+10 1.05537705e+16 1.75756379e+28
 9.90367012e+19 4.06571207e+21 3.47837470e+19 3.25608869e+23
 2.83060823e+19 9.52562903e+18 1.17232584e+24 5.21168031e+22
 1.27893257e+06 4.32615013e+15 4.09806721e+18 2.02265001e+16
 2.34886707e+15 4.59880112e+18 2.12912591e+17 8.59208803e+16
 5.63301492e+16 4.68717401e+19 5.84097122e+19 3.88789162e+13
 4.44729635e+12 1.51173405e+15 2.80547856e+21 9.67794188e+24
 1.04477166e+23 1.01475756e+33 9.41828310e+09 9.41098351e+10
 1.72948389e+15 1.23162478e+17 1.77987873e+14 1.38708659e+19
 1.51683855e+16 1.46415512e+17 1.74553204e+16 1.75198954e+11
 5.36934030e+11 8.91599723e+08 1.01729811e+08 7.14815200e+12
 2.24172666e+18 1.70879782e+30 2.25347011e+19 5.39348197e+30
 2.86340712e+19 2.01068514e+13 9.14523707e+10 1.41236626e+18
 2.13465609e+20 4.69727752e+23 3.85756411e+33 1.51975951e+37
 1.44359924e+29 3.69511359e+16 1.78139004e+18 3.71986125e+19
 2.84833290e+17 6.02440664e+15 2.84234046e+21 1.91605666e+11
 2.32701457e+11 1.81125658e+17 2.18316996e+09 4.35469143e+04
 4.44882994e+16 1.78989082e+05 1.83777460e+06 1.71933881e+10
 7.91583355e+09 3.63453448e+10 2.52333313e+09 2.18313360e+13
 4.76713533e+15 4.78771634e+11 2.14807479e+16 3.05202202e+16
 5.89528596e+19 3.55956313e+25 1.06710707e+20 3.48742248e+16
 1.60110915e+13 6.21156779e+21 2.16858834e+18 1.98385442e+28
 2.34581930e+25 6.12478258e+22 3.97663106e+27 1.25887423e+23
 7.34802701e+12 2.97278891e+12 1.17281337e+11 3.86649971e+15
 4.90560991e+08 8.52617289e+07 3.41701613e+11 6.81130237e+13
 9.50106851e+12 4.12986542e+02 1.15733426e+02 1.19193369e+11
 8.25664512e+03 8.96658265e+03 3.82227916e+08 3.68853164e+03
 5.34412934e+10 2.57180274e+19 4.38374966e+28 3.77537682e+19
 2.55525910e+18 9.98657895e+17 2.82512992e+23 3.10199054e+20
 4.52805578e+21 2.40956610e+10 5.08043878e+11 1.89167653e+19
 4.46287445e+28 6.92302411e+25 3.51928114e+23 2.79624889e+23
 1.30975508e+26 3.10476005e+24 9.00471221e+22 2.22526078e+20
 6.78711036e+24 1.82009040e+24 1.51973866e+16 7.20089551e+12
 6.94857726e+14 1.00906798e+18 4.77767296e+14 9.92356750e+21
 3.05880741e+12 9.29134415e+12 6.63736020e+20 1.02470234e+18
 1.45248372e+11 8.51252235e+22 2.35768589e+25 5.81588485e+27
 2.13975876e+18 4.49096741e+13 1.30404025e+12 4.88832578e+13
 1.33361204e+15 4.63166597e+13 1.52893265e+08 2.75817831e+14
 1.92983575e+00 5.45981500e+01 1.16347721e+08 1.43899231e+06
 1.76727706e+15 1.17158537e+24 1.28733897e+23 1.82850094e+17
 7.03460558e+19 1.31036587e+25 1.15090091e+23 5.22140269e+18
 2.91918632e+20]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [2.64745947e-11 5.80784710e-24 2.08750737e-14 2.40816146e-10
 4.04240295e-04 6.17438022e-10 2.45594339e-12 1.23099471e-08
 4.14077898e-10 4.84008246e-08 7.42937388e+01 1.44809248e-05
 3.05591322e-17 9.36993146e-19 4.06473645e-12 4.75645676e-17
 6.49213628e-04 1.09730307e-05 2.43141392e-10 1.11442585e-03
 3.00834506e-05 1.89418581e-12 3.21505350e-20 1.41704836e-25
 1.65623222e-09 4.09263559e-14 1.19241738e-22 6.04950137e-21
 3.24523455e-15 2.61993582e-14 2.02989121e-16 8.29525047e-19
 3.11077011e-17 9.02308476e-26 1.38694012e-20 1.89601505e-13
 8.38062823e-10 3.27446711e-13 2.40429681e-11 2.93758092e-09
 1.86203473e-05 1.20643561e-10 2.27249974e-18 4.84706865e-24
 4.34370234e-28 5.97069790e-11 4.80912892e-05 3.02802882e-13
 1.30868728e-13 1.15282087e-02 6.40560830e-06 6.43705889e-05
 4.20497985e-11 2.50704278e-06 3.63796453e-03 3.17428959e-09
 4.16886807e-21 7.75284944e-16 2.75502669e-11 2.13944903e-13
 5.12667171e-24 1.42352601e-09 1.14388768e-10 8.32404512e-21
 9.14575651e-11 1.01703402e-03 8.68552485e-15 1.89761345e-21
 3.29540981e-14 2.51058389e-16 5.20483480e-22 2.07687045e-21
 4.31657110e-17 3.41514223e-20 8.51664114e-21 2.01928895e-16
 8.70130650e-20 1.44729437e-17 2.01805562e-16 1.44552422e-17
 7.97136092e-16 7.03294212e-10 9.59740203e-10 2.27662977e-05
 6.04907348e-22 7.50116442e-24 5.01426281e-17 6.22751931e-28
 1.80137384e-16 1.59617445e-08 5.56872247e-06 1.72415218e-10
 1.52636648e-17 2.90203008e-04 1.43282085e+01 5.15012694e-03
 7.06437594e-04 9.40281369e-11 3.92901054e-19 9.04689383e-33
 1.41672050e-18 1.51814600e-23 9.30595034e-08 3.64927144e-07
 4.38443980e-11 4.89551286e-12 6.07508480e-16 8.62745702e-26
 2.85426418e-33 1.11088523e-22 6.45114845e-09 1.09427400e-08
 2.83474510e-14 7.56800208e-15 6.00619176e-12 9.06941694e-15
 1.61718008e-13 3.34132219e-03 2.47932888e-07 1.27626658e-25
 1.31942391e-15 2.27042148e-02 2.53089130e-09 3.21141520e-11
 6.83257546e-13 9.28659903e-08 1.07000688e-13 2.74083623e-26
 1.68654530e-17 1.52636204e-18 2.96085960e-17 2.75484996e-21
 7.09437940e-17 2.15725017e-16 4.30274726e-21 6.39464461e-20
 4.42533883e-04 1.11350608e-13 3.98304396e-16 9.92826672e-14
 6.19349424e-13 4.07520582e-16 2.31522303e-15 9.09275440e-15
 2.19812950e-14 1.87017867e-17 6.40190331e-18 2.30717229e-11
 3.50508138e-10 1.83365987e-12 8.80617320e-19 3.60587915e-23
 8.99027129e-21 3.43899765e-30 7.06028831e-08 7.39876381e-08
 2.37070575e-12 7.80397301e-15 1.91603643e-11 9.78792433e-17
 9.37248639e-14 2.27618255e-15 4.47575549e-14 8.69486150e-09
 3.65488104e-09 1.96166233e-06 7.67972976e-05 6.14611096e-10
 5.78377674e-16 5.88983996e-28 5.12793338e-17 1.35183892e-27
 1.33632187e-16 1.14670078e-10 9.15375339e-08 3.82689760e-15
 7.82467414e-18 4.27511653e-21 2.99558070e-31 3.99042642e-34
 7.30041469e-26 6.38508058e-14 4.38566198e-15 6.49033980e-17
 1.54242277e-14 4.39420080e-13 2.56518139e-19 2.69392703e-08
 1.03751665e-08 3.84427282e-14 2.59242755e-07 5.17412349e-02
 2.48055220e-13 3.01972668e-02 2.28297908e-04 4.86892078e-08
 1.92440964e-07 1.07732164e-07 2.63523643e-07 2.84258766e-11
 3.42402318e-13 3.10932248e-09 6.46762422e-14 2.87214600e-14
 4.49044420e-17 9.80386849e-23 1.10811843e-17 1.28910892e-14
 4.87947657e-11 6.01995088e-20 4.33128796e-16 4.52151917e-26
 7.80727758e-23 7.17304408e-21 5.16748089e-26 7.12544241e-21
 3.44051485e-10 8.70222094e-10 6.97533817e-08 1.36608019e-13
 1.82852611e-06 1.10164088e-05 1.31567053e-08 3.30798869e-11
 1.64067185e-10 1.76546161e+00 1.02172817e+01 1.57232414e-08
 1.84497531e-01 2.34513161e-01 6.61411551e-07 1.84476336e-01
 3.27278305e-08 6.80074549e-17 1.78216714e-25 1.43164015e-16
 1.64194737e-16 1.71150210e-16 2.05000892e-21 3.32011945e-18
 4.04466361e-19 5.38090509e-08 3.52284033e-10 5.32043697e-17
 2.10464818e-26 1.87282989e-23 3.68417468e-21 1.72273452e-21
 2.85498667e-24 5.02072156e-23 2.38959521e-20 2.98822478e-18
 2.14342981e-23 1.26678005e-21 1.74190821e-13 1.39767974e-10
 5.90062868e-12 6.58982299e-16 2.05862752e-12 7.34727593e-20
 3.52567311e-10 5.68480576e-11 6.32118923e-19 1.07695225e-15
 1.23220483e-09 2.35904329e-20 4.57412714e-23 2.68026896e-25

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_2_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_r_naive_random/20240402-191851_analysis.csv
dict_keys(['cluster_2_r_naive_random'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_r_naive_random to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2_r_naive_random/cluster_2_r_naive_random0_1712081931.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2_r_naive_random': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00000  0.00000       77  train_cluster_2_1
1   0.0  0.06673  0.06726       10  train_cluster_2_1
2   0.0  0.10000  0.10001        4  train_cluster_2_1
3   0.0  0.00000  0.00000       83  train_cluster_2_1
4   0.0  0.00001  0.00011       62  train_cluster_2_1
5   0.0  0.00000  0.00000       67  train_cluster_2_1
6   0.0  0.00063  0.00613       30  train_cluster_2_1
7   0.0  0.00000  0.00000       45  train_cluster_2_1
8   0.0  0.00000  0.00000       95  train_cluster_2_1
9   0.0  0.06256  0.06306       11  train_cluster_2_1
10  0.0  0.00000  0.00001       81  train_cluster_2_1
11  0.0  0.00000  0.00000       79  train_cluster_2_1
12  0.0  0.00003  0.00034        0  train_cluster_2_1
13  0.0  0.00000  0.00000       80  train_cluster_2_1
14  0.0  0.00000  0.00000       18  train_cluster_2_1
15  0.0  0.00000  0.00000       69  train_cluster_2_1
16  0.0  0.00062  0.00590       56  train_cluster_2_1
17  0.0  0.00000  0.00000       76  train_cluster_2_1
18  0.0  0.11113  0.11133      106  train_cluster_2_1
19  0.0  0.00000  0.00000       42  train_cluster_2_1
20  0.0  0.14286  0.14287       12  train_cluster_2_1
21  0.0  0.00007  0.00072       36  train_cluster_2_1
22  0.0  0.00000  0.00000       64  train_cluster_2_1
23  0.0  0.00000  0.00004       26  train_cluster_2_1
24  0.0  0.00000  0.00000       22  train_cluster_2_1
25  0.0  0.00046  0.00450       31  train_cluster_2_1
26  0.0  0.00000  0.00001       47  train_cluster_2_1
27  0.0  0.11113  0.11133      100  train_cluster_2_1
28  0.0  0.08341  0.08408       15  train_cluster_2_1
29  0.0  0.00000  0.00000       44  train_cluster_2_1
30  0.0  0.00000  0.00001       88  train_cluster_2_1
31  0.0  0.15105  0.31019       89  train_cluster_2_1
32  0.0  0.08336  0.08360        9  train_cluster_2_1
33  0.0  0.00086  0.00840       33  train_cluster_2_1
34  0.0  0.00072  0.00688       55  train_cluster_2_1
35  0.0  0.11767  0.11788      103  train_cluster_2_1
36  0.0  0.00000  0.00004       28  train_cluster_2_1
37  0.0  0.00005  0.00051       40  train_cluster_2_1
38  0.0  0.07695  0.07717        5  train_cluster_2_1
39  0.0  0.00000  0.00000       53  train_cluster_2_1
40  0.0  0.11767  0.11788      107  train_cluster_2_1
41  0.0  0.00006  0.00056       39  train_cluster_2_1
42  0.0  0.00006  0.00056       35  train_cluster_2_1
43  0.0  0.07149  0.07207       16  train_cluster_2_1
44  0.0  0.00472  0.04329       78  train_cluster_2_1
45  0.0  0.00057  0.00560       34  train_cluster_2_1
46  0.0  0.00000  0.00000       66  train_cluster_2_1
47  0.0  0.11111  0.11112        7  train_cluster_2_1
48  0.0  0.00000  0.00000       43  train_cluster_2_1
49  0.0  0.00000  0.00000       65  train_cluster_2_1
50  0.0  0.00000  0.00005       72  train_cluster_2_1
51  0.0  0.00000  0.00001       27  train_cluster_2_1
52  0.0  0.00000  0.00000       19  train_cluster_2_1
53  0.0  0.13943  0.28633       90  train_cluster_2_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.09091  0.09092        1  val_cluster_2_1
1   0.0  0.07145  0.07166        2  val_cluster_2_1
2   0.0  0.05561  0.05605        3  val_cluster_2_1
3   0.0  0.05888  0.05935        6  val_cluster_2_1
4   0.0  0.09094  0.09120        8  val_cluster_2_1
5   0.0  0.11115  0.11147       13  val_cluster_2_1
6   0.0  0.10003  0.10032       14  val_cluster_2_1
7   0.0  0.00010  0.00096       17  val_cluster_2_1
8   0.0  0.00000  0.00000       20  val_cluster_2_1
9   0.0  0.00000  0.00000       21  val_cluster_2_1
10  0.0  0.00000  0.00000       23  val_cluster_2_1
11  0.0  0.00000  0.00001       24  val_cluster_2_1
12  0.0  0.00000  0.00001       25  val_cluster_2_1
13  0.0  0.00033  0.00322       29  val_cluster_2_1
14  0.0  0.00049  0.00482       32  val_cluster_2_1
15  0.0  0.00008  0.00085       37  val_cluster_2_1
16  0.0  0.00007  0.00072       38  val_cluster_2_1
17  0.0  0.00003  0.00027       41  val_cluster_2_1
18  0.0  0.00000  0.00001       46  val_cluster_2_1
19  0.0  0.00000  0.00001       48  val_cluster_2_1
20  0.0  0.14313  0.14699       49  val_cluster_2_1
21  0.0  0.00049  0.00482       50  val_cluster_2_1
22  0.0  0.00000  0.00000       51  val_cluster_2_1
23  0.0  0.00000  0.00000       52  val_cluster_2_1
24  0.0  0.00076  0.00729       54  val_cluster_2_1
25  0.0  0.00001  0.00009       57  val_cluster_2_1
26  0.0  0.00002  0.00016       58  val_cluster_2_1
27  0.0  0.00001  0.00010       59  val_cluster_2_1
28  0.0  0.00001  0.00009       60  val_cluster_2_1
29  0.0  0.00001  0.00009       61  val_cluster_2_1
30  0.0  0.00001  0.00012       63  val_cluster_2_1
31  0.0  0.00000  0.00000       68  val_cluster_2_1
32  0.0  0.00000  0.00003       70  val_cluster_2_1
33  0.0  0.00000  0.00002       71  val_cluster_2_1
34  0.0  0.00000  0.00002       73  val_cluster_2_1
35  0.0  0.00000  0.00002       74  val_cluster_2_1
36  0.0  0.00000  0.00002       75  val_cluster_2_1
37  0.0  0.00000  0.00001       82  val_cluster_2_1
38  0.0  0.00000  0.00001       84  val_cluster_2_1
39  0.0  0.00000  0.00001       85  val_cluster_2_1
40  0.0  0.00000  0.00001       86  val_cluster_2_1
41  0.0  0.00000  0.00001       87  val_cluster_2_1
42  0.0  0.12084  0.24815       91  val_cluster_2_1
43  0.0  0.10070  0.20679       92  val_cluster_2_1
44  0.0  0.00000  0.00000       93  val_cluster_2_1
45  0.0  0.00000  0.00000       94  val_cluster_2_1
46  0.0  0.00000  0.00000       96  val_cluster_2_1
47  0.0  0.00000  0.00000       97  val_cluster_2_1
48  0.0  0.00000  0.00000       98  val_cluster_2_1
49  0.0  0.10528  0.10547       99  val_cluster_2_1
50  0.0  0.10528  0.10547      101  val_cluster_2_1
51  0.0  0.12502  0.12525      102  val_cluster_2_1
52  0.0  0.10002  0.10020      104  val_cluster_2_1
53  0.0  0.13336  0.13360      105  val_cluster_2_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name                      name  \
0    0.0  0.41879  0.44438        0  Experimental  cluster_2_r_naive_random
1    0.0  0.37096  0.45204        1  Experimental  cluster_2_r_naive_random
2    0.0  0.40040  0.48544        2  Experimental  cluster_2_r_naive_random
3    0.0  0.45875  0.51503        3  Experimental  cluster_2_r_naive_random
4    0.0  0.41726  0.49519        4  Experimental  cluster_2_r_naive_random
5    0.0  0.44176  0.50927        5  Experimental  cluster_2_r_naive_random
6    0.0  0.48987  0.54090        6  Experimental  cluster_2_r_naive_random
7    0.0  0.41316  0.48254        7  Experimental  cluster_2_r_naive_random
8    0.0  0.46617  0.51066        8  Experimental  cluster_2_r_naive_random
9    0.0  0.46825  0.52028        9  Experimental  cluster_2_r_naive_random
10   0.0  0.48273  0.53102       10  Experimental  cluster_2_r_naive_random
11   0.0  0.50258  0.53988       11  Experimental  cluster_2_r_naive_random
12   0.0  0.47373  0.50144       12  Experimental  cluster_2_r_naive_random
13   0.0  0.52057  0.54102       13  Experimental  cluster_2_r_naive_random
14   0.0  0.52823  0.55640       14  Experimental  cluster_2_r_naive_random
15   0.0  0.55802  0.57504       15  Experimental  cluster_2_r_naive_random
16   0.0  0.55641  0.57196       16  Experimental  cluster_2_r_naive_random
17   0.0  0.52928  0.54827       17  Experimental  cluster_2_r_naive_random
18   0.0  0.17163  0.27883       18  Experimental  cluster_2_r_naive_random
19   0.0  0.16883  0.28686       19  Experimental  cluster_2_r_naive_random
20   0.0  0.16341  0.27353       20  Experimental  cluster_2_r_naive_random
21   0.0  0.32309  0.41205       21  Experimental  cluster_2_r_naive_random
22   0.0  0.31355  0.39928       22  Experimental  cluster_2_r_naive_random
23   0.0  0.34392  0.42213       23  Experimental  cluster_2_r_naive_random
24   0.0  0.35604  0.35617       24  Experimental  cluster_2_r_naive_random
25   0.0  0.34105  0.35125       25  Experimental  cluster_2_r_naive_random
26   0.0  0.34135  0.38830       26  Experimental  cluster_2_r_naive_random
27   0.0  0.28512  0.29602       27  Experimental  cluster_2_r_naive_random
28   0.0  0.28439  0.33185       28  Experimental  cluster_2_r_naive_random
29   0.0  0.32954  0.39085       29  Experimental  cluster_2_r_naive_random
30   0.0  0.26192  0.34619       30  Experimental  cluster_2_r_naive_random
31   0.0  0.31421  0.37857       31  Experimental  cluster_2_r_naive_random
32   0.0  0.32314  0.38565       32  Experimental  cluster_2_r_naive_random
33   0.0  0.29666  0.37860       33  Experimental  cluster_2_r_naive_random
34   0.0  0.38440  0.44775       34  Experimental  cluster_2_r_naive_random
35   0.0  0.33633  0.46390       35  Experimental  cluster_2_r_naive_random
36   0.0  0.34716  0.45807       36  Experimental  cluster_2_r_naive_random
37   0.0  0.34165  0.44393       37  Experimental  cluster_2_r_naive_random
38   0.0  0.30725  0.43533       38  Experimental  cluster_2_r_naive_random
39   0.0  0.33252  0.48976       39  Experimental  cluster_2_r_naive_random
40   0.0  0.28369  0.42940       40  Experimental  cluster_2_r_naive_random
41   0.0  0.35906  0.50293       41  Experimental  cluster_2_r_naive_random
42   0.0  0.33575  0.45181       42  Experimental  cluster_2_r_naive_random
43   0.0  0.33443  0.43697       43  Experimental  cluster_2_r_naive_random
44   0.0  0.37082  0.47284       44  Experimental  cluster_2_r_naive_random
45   0.0  0.37847  0.48848       45  Experimental  cluster_2_r_naive_random
46   0.0  0.22218  0.31040       46  Experimental  cluster_2_r_naive_random
47   0.0  0.18217  0.28305       47  Experimental  cluster_2_r_naive_random
48   0.0  0.25719  0.37045       48  Experimental  cluster_2_r_naive_random
49   0.0  0.49756  0.50850       49  Experimental  cluster_2_r_naive_random
50   0.0  0.55024  0.54326       50  Experimental  cluster_2_r_naive_random
51   0.0  0.24310  0.29208       51  Experimental  cluster_2_r_naive_random
52   0.0  0.19173  0.23972       52  Experimental  cluster_2_r_naive_random
53   0.0  0.18105  0.23003       53  Experimental  cluster_2_r_naive_random
54   0.0  0.26140  0.30267       54  Experimental  cluster_2_r_naive_random
55   0.0  0.26392  0.30614       55  Experimental  cluster_2_r_naive_random
56   0.0  0.26061  0.32801       56  Experimental  cluster_2_r_naive_random
57   0.0  0.45297  0.53974       57  Experimental  cluster_2_r_naive_random
58   0.0  0.31622  0.45372       58  Experimental  cluster_2_r_naive_random
59   0.0  0.43711  0.52972       59  Experimental  cluster_2_r_naive_random
60   0.0  0.47628  0.54735       60  Experimental  cluster_2_r_naive_random
61   0.0  0.49249  0.57156       61  Experimental  cluster_2_r_naive_random
62   0.0  0.50341  0.53212       62  Experimental  cluster_2_r_naive_random
63   0.0  0.53500  0.53827       63  Experimental  cluster_2_r_naive_random
64   0.0  0.26524  0.35365       64  Experimental  cluster_2_r_naive_random
65   0.0  0.25454  0.32548       65  Experimental  cluster_2_r_naive_random
66   0.0  0.25152  0.35786       66  Experimental  cluster_2_r_naive_random
67   0.0  0.28164  0.36568       67  Experimental  cluster_2_r_naive_random
68   0.0  0.24177  0.30174       68  Experimental  cluster_2_r_naive_random
69   0.0  0.27969  0.36567       69  Experimental  cluster_2_r_naive_random
70   0.0  0.38633  0.44869       70  Experimental  cluster_2_r_naive_random
71   0.0  0.24871  0.31226       71  Experimental  cluster_2_r_naive_random
72   0.0  0.36820  0.37879       72  Experimental  cluster_2_r_naive_random
73   0.0  0.22903  0.26839       73  Experimental  cluster_2_r_naive_random
74   0.0  0.21687  0.25989       74  Experimental  cluster_2_r_naive_random
75   0.0  0.20479  0.23593       75  Experimental  cluster_2_r_naive_random
76   0.0  0.11684  0.15140       76  Experimental  cluster_2_r_naive_random
77   0.0  0.13267  0.18143       77  Experimental  cluster_2_r_naive_random
78   0.0  0.35203  0.42601       78  Experimental  cluster_2_r_naive_random
79   0.0  0.20249  0.21472       79  Experimental  cluster_2_r_naive_random
80   0.0  0.16260  0.17496       80  Experimental  cluster_2_r_naive_random
81   0.0  0.05688  0.07274       81  Experimental  cluster_2_r_naive_random
82   0.0  0.07600  0.11464       82  Experimental  cluster_2_r_naive_random
83   0.0  0.08147  0.13526       83  Experimental  cluster_2_r_naive_random
84   0.0  0.08527  0.13242       84  Experimental  cluster_2_r_naive_random
85   0.0  0.08569  0.14304       85  Experimental  cluster_2_r_naive_random
86   0.0  0.06291  0.07885       86  Experimental  cluster_2_r_naive_random
87   0.0  0.09393  0.16201       87  Experimental  cluster_2_r_naive_random
88   0.0  0.10385  0.19651       88  Experimental  cluster_2_r_naive_random
89   0.0  0.53877  0.49943       89  Experimental  cluster_2_r_naive_random
90   0.0  0.51417  0.47866       90  Experimental  cluster_2_r_naive_random
91   0.0  0.50107  0.49072       91  Experimental  cluster_2_r_naive_random
92   0.0  0.45551  0.47280       92  Experimental  cluster_2_r_naive_random
93   0.0  0.06500  0.10668       93  Experimental  cluster_2_r_naive_random
94   0.0  0.06362  0.10593       94  Experimental  cluster_2_r_naive_random
95   0.0  0.04358  0.04371       95  Experimental  cluster_2_r_naive_random
96   0.0  0.08151  0.10674       96  Experimental  cluster_2_r_naive_random
97   0.0  0.08795  0.11537       97  Experimental  cluster_2_r_naive_random
98   0.0  0.09261  0.12297       98  Experimental  cluster_2_r_naive_random
99   0.0  0.17298  0.20225       99  Experimental  cluster_2_r_naive_random
100  0.0  0.20729  0.23030      100  Experimental  cluster_2_r_naive_random
101  0.0  0.20401  0.23454      101  Experimental  cluster_2_r_naive_random
102  0.0  0.21943  0.23426      102  Experimental  cluster_2_r_naive_random
103  0.0  0.21731  0.24442      103  Experimental  cluster_2_r_naive_random
104  0.0  0.22028  0.25199      104  Experimental  cluster_2_r_naive_random
105  0.0  0.22217  0.24175      105  Experimental  cluster_2_r_naive_random
106  0.0  0.22454  0.24966      106  Experimental  cluster_2_r_naive_random
107  0.0  0.23913  0.27068      107  Experimental  cluster_2_r_naive_random

    split_type
0            r
1            r
2            r
3            r
4            r
5            r
6            r
7            r
8            r
9            r
10           r
11           r
12           r
13           r
14           r
15           r
16           r
17           r
18           r
19           r
20           r
21           r
22           r
23           r
24           r
25           r
26           r
27           r
28           r
29           r
30           r
31           r
32           r
33           r
34           r
35           r
36           r
37           r
38           r
39           r
40           r
41           r
42           r
43           r
44           r
45           r
46           r
47           r
48           r
49           r
50           r
51           r
52           r
53           r
54           r
55           r
56           r
57           r
58           r
59           r
60           r
61           r
62           r
63           r
64           r
65           r
66           r
67           r
68           r
69           r
70           r
71           r
72           r
73           r
74           r
75           r
76           r
77           r
78           r
79           r
80           r
81           r
82           r
83           r
84           r
85           r
86           r
87           r
88           r
89           r
90           r
91           r
92           r
93           r
94           r
95           r
96           r
97           r
98           r
99           r
100          r
101          r
102          r
103          r
104          r
105          r
106          r
107          r  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental
69   0.0  0.27969  0.36567       69       Experimental
70   0.0  0.38633  0.44869       70       Experimental
71   0.0  0.24871  0.31226       71       Experimental
72   0.0  0.36820  0.37879       72       Experimental
73   0.0  0.22903  0.26839       73       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/train_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/train_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00003  0.00034        0
1  0.0  0.09091  0.09092        1
2  0.0  0.07145  0.07166        2
3  0.0  0.05561  0.05605        3
4  0.0  0.10000  0.10001        4
Experimental cluster_2 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat
REWIGHTING val_cluster_2_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential0/val_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00076  0.00729        0
1  0.0  0.00072  0.00688        1
2  0.0  0.00062  0.00590        2
3  0.0  0.00001  0.00009        3
4  0.0  0.00002  0.00016        4
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45
46       98     104       46
47       98     106       47
48       98     108       48
49      113     120       49
50      114     120       50
51      117     131       51
52      121     131       52
53      121     132       53
54      132     149       54
55      132     150       55
56      132     153       56
57      150     169       57
58      151     162       58
59      151     167       59
60      151     169       60
61      151     170       61
62      154     169       62
63      155     169       63
64      169     183       64
65      170     183       65
66      170     185       66
67      170     186       67
68      171     183       68
69      171     186       69
70      184     195       70
71      184     208       71
72      187     195       72
73      187     208       73
74      187     209       74
75      188     208       75
76      194     208       76
77      196     208       77
78      213     223       78
79      224     238       79
80      224     239       80
81      247     257       81
82      247     259       82
83      247     260       83
84      248     259       84
85      248     260       85
86      250     257       86
87      250     260       87
88      253     260       88
89      261     275       89
90      261     276       90
91      261     278       91
92      261     281       92
93      305     313       93
94      305     315       94
95      308     315       95
96      314     327       96
97      316     327       97
98      317     327       98

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
LogPf_by_res [34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
Pf_by_res [1.54869129e+15 6.43841553e+26 2.15360553e+17 1.04980485e+12
 9.46574006e+06 6.79517751e+12 2.96876504e+14 7.98983831e+10
 8.04844774e+11 1.19657911e+10 7.27515016e+01 2.19784913e+08
 6.72439411e+19 2.00012787e+21 4.94039627e+14 7.00665325e+18
 1.02425136e+06 4.29010165e+08 4.33446277e+13 3.13143209e+06
 1.24298683e+08 2.02009409e+15 1.16307032e+22 2.19487354e+28
 5.54208220e+11 8.52689864e+16 2.16953109e+25 2.89117644e+23
 7.43957430e+17 6.08840486e+16 4.95817000e+18 1.49267298e+21
 1.20206031e+19 8.26873626e+27 2.40290426e+22 3.75796210e+15
 1.54709720e+12 2.49835152e+15 5.51831003e+13 1.10867521e+11
 3.41040848e+07 2.09551142e+13 3.59989917e+20 6.71916035e+25
 8.80915231e+30 1.22115019e+13 1.09831713e+08 1.38558819e+16
 1.72170324e+16 7.96218677e+04 3.43742959e+07 1.03301516e+07
 6.01215626e+13 4.20370772e+08 1.95855476e+05 7.26352827e+11
 1.26699828e+23 2.65053064e+17 6.64765336e+13 6.34588549e+15
 1.83214005e+26 1.14664444e+12 1.83827633e+13 7.98839904e+22
 6.63093150e+12 9.02523903e+05 9.63824855e+16 3.58580302e+23
 4.31404576e+16 1.32745388e+18 8.63748343e+23 5.56396988e+23
 3.69534744e+19 4.46051887e+22 5.15852843e+22 3.29303015e+18
 1.79147070e+22 5.78412017e+19 1.85293868e+18 1.67020125e+19
 9.57771044e+17 2.79034005e+12 2.75829360e+12 2.92079963e+07
 1.58893202e+24 5.10111943e+25 6.06159738e+18 6.58383735e+30
 2.49568819e+19 9.11410067e+10 1.50327558e+09 6.11249589e+13
 9.53093166e+19 3.80270177e+06 7.52665978e+01 3.16939408e+05
 1.45787529e+06 5.61741288e+12 1.54351546e+21 9.91504498e+34
 7.61219663e+20 5.51417615e+26 8.99566856e+09 2.29397145e+10
 8.14479325e+13 4.10200306e+14 2.81346704e+18 1.33940332e+28
 2.12471170e+36 8.07467372e+24 1.71063416e+11 8.01065627e+11
 1.44637252e+17 2.65346237e+17 4.01971241e+14 8.61419719e+16
 4.72101949e+15 2.08389495e+05 4.15393827e+09 1.24983528e+28
 1.59371193e+18 8.64346123e+04 8.90267835e+11 1.53496231e+14
 1.54244518e+16 3.75783305e+10 1.05537705e+16 1.75756379e+28
 9.90367012e+19 4.06571207e+21 3.47837470e+19 3.25608869e+23
 2.83060823e+19 9.52562903e+18 1.17232584e+24 5.21168031e+22
 1.27893257e+06 4.32615013e+15 4.09806721e+18 2.02265001e+16
 2.34886707e+15 4.59880112e+18 2.12912591e+17 8.59208803e+16
 5.63301492e+16 4.68717401e+19 5.84097122e+19 3.88789162e+13
 4.44729635e+12 1.51173405e+15 2.80547856e+21 9.67794188e+24
 1.04477166e+23 1.01475756e+33 9.41828310e+09 9.41098351e+10
 1.72948389e+15 1.23162478e+17 1.77987873e+14 1.38708659e+19
 1.51683855e+16 1.46415512e+17 1.74553204e+16 1.75198954e+11
 5.36934030e+11 8.91599723e+08 1.01729811e+08 7.14815200e+12
 2.24172666e+18 1.70879782e+30 2.25347011e+19 5.39348197e+30
 2.86340712e+19 2.01068514e+13 9.14523707e+10 1.41236626e+18
 2.13465609e+20 4.69727752e+23 3.85756411e+33 1.51975951e+37
 1.44359924e+29 3.69511359e+16 1.78139004e+18 3.71986125e+19
 2.84833290e+17 6.02440664e+15 2.84234046e+21 1.91605666e+11
 2.32701457e+11 1.81125658e+17 2.18316996e+09 4.35469143e+04
 4.44882994e+16 1.78989082e+05 1.83777460e+06 1.71933881e+10
 7.91583355e+09 3.63453448e+10 2.52333313e+09 2.18313360e+13
 4.76713533e+15 4.78771634e+11 2.14807479e+16 3.05202202e+16
 5.89528596e+19 3.55956313e+25 1.06710707e+20 3.48742248e+16
 1.60110915e+13 6.21156779e+21 2.16858834e+18 1.98385442e+28
 2.34581930e+25 6.12478258e+22 3.97663106e+27 1.25887423e+23
 7.34802701e+12 2.97278891e+12 1.17281337e+11 3.86649971e+15
 4.90560991e+08 8.52617289e+07 3.41701613e+11 6.81130237e+13
 9.50106851e+12 4.12986542e+02 1.15733426e+02 1.19193369e+11
 8.25664512e+03 8.96658265e+03 3.82227916e+08 3.68853164e+03
 5.34412934e+10 2.57180274e+19 4.38374966e+28 3.77537682e+19
 2.55525910e+18 9.98657895e+17 2.82512992e+23 3.10199054e+20
 4.52805578e+21 2.40956610e+10 5.08043878e+11 1.89167653e+19
 4.46287445e+28 6.92302411e+25 3.51928114e+23 2.79624889e+23
 1.30975508e+26 3.10476005e+24 9.00471221e+22 2.22526078e+20
 6.78711036e+24 1.82009040e+24 1.51973866e+16 7.20089551e+12
 6.94857726e+14 1.00906798e+18 4.77767296e+14 9.92356750e+21
 3.05880741e+12 9.29134415e+12 6.63736020e+20 1.02470234e+18
 1.45248372e+11 8.51252235e+22 2.35768589e+25 5.81588485e+27
 2.13975876e+18 4.49096741e+13 1.30404025e+12 4.88832578e+13
 1.33361204e+15 4.63166597e+13 1.52893265e+08 2.75817831e+14
 1.92983575e+00 5.45981500e+01 1.16347721e+08 1.43899231e+06
 1.76727706e+15 1.17158537e+24 1.28733897e+23 1.82850094e+17
 7.03460558e+19 1.31036587e+25 1.15090091e+23 5.22140269e+18
 2.91918632e+20]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [2.64745947e-11 5.80784710e-24 2.08750737e-14 2.40816146e-10
 4.04240295e-04 6.17438022e-10 2.45594339e-12 1.23099471e-08
 4.14077898e-10 4.84008246e-08 7.42937388e+01 1.44809248e-05
 3.05591322e-17 9.36993146e-19 4.06473645e-12 4.75645676e-17
 6.49213628e-04 1.09730307e-05 2.43141392e-10 1.11442585e-03
 3.00834506e-05 1.89418581e-12 3.21505350e-20 1.41704836e-25
 1.65623222e-09 4.09263559e-14 1.19241738e-22 6.04950137e-21
 3.24523455e-15 2.61993582e-14 2.02989121e-16 8.29525047e-19
 3.11077011e-17 9.02308476e-26 1.38694012e-20 1.89601505e-13
 8.38062823e-10 3.27446711e-13 2.40429681e-11 2.93758092e-09
 1.86203473e-05 1.20643561e-10 2.27249974e-18 4.84706865e-24
 4.34370234e-28 5.97069790e-11 4.80912892e-05 3.02802882e-13
 1.30868728e-13 1.15282087e-02 6.40560830e-06 6.43705889e-05
 4.20497985e-11 2.50704278e-06 3.63796453e-03 3.17428959e-09
 4.16886807e-21 7.75284944e-16 2.75502669e-11 2.13944903e-13
 5.12667171e-24 1.42352601e-09 1.14388768e-10 8.32404512e-21
 9.14575651e-11 1.01703402e-03 8.68552485e-15 1.89761345e-21
 3.29540981e-14 2.51058389e-16 5.20483480e-22 2.07687045e-21
 4.31657110e-17 3.41514223e-20 8.51664114e-21 2.01928895e-16
 8.70130650e-20 1.44729437e-17 2.01805562e-16 1.44552422e-17
 7.97136092e-16 7.03294212e-10 9.59740203e-10 2.27662977e-05
 6.04907348e-22 7.50116442e-24 5.01426281e-17 6.22751931e-28
 1.80137384e-16 1.59617445e-08 5.56872247e-06 1.72415218e-10
 1.52636648e-17 2.90203008e-04 1.43282085e+01 5.15012694e-03
 7.06437594e-04 9.40281369e-11 3.92901054e-19 9.04689383e-33
 1.41672050e-18 1.51814600e-23 9.30595034e-08 3.64927144e-07
 4.38443980e-11 4.89551286e-12 6.07508480e-16 8.62745702e-26
 2.85426418e-33 1.11088523e-22 6.45114845e-09 1.09427400e-08
 2.83474510e-14 7.56800208e-15 6.00619176e-12 9.06941694e-15
 1.61718008e-13 3.34132219e-03 2.47932888e-07 1.27626658e-25
 1.31942391e-15 2.27042148e-02 2.53089130e-09 3.21141520e-11
 6.83257546e-13 9.28659903e-08 1.07000688e-13 2.74083623e-26
 1.68654530e-17 1.52636204e-18 2.96085960e-17 2.75484996e-21
 7.09437940e-17 2.15725017e-16 4.30274726e-21 6.39464461e-20
 4.42533883e-04 1.11350608e-13 3.98304396e-16 9.92826672e-14
 6.19349424e-13 4.07520582e-16 2.31522303e-15 9.09275440e-15
 2.19812950e-14 1.87017867e-17 6.40190331e-18 2.30717229e-11
 3.50508138e-10 1.83365987e-12 8.80617320e-19 3.60587915e-23
 8.99027129e-21 3.43899765e-30 7.06028831e-08 7.39876381e-08
 2.37070575e-12 7.80397301e-15 1.91603643e-11 9.78792433e-17
 9.37248639e-14 2.27618255e-15 4.47575549e-14 8.69486150e-09
 3.65488104e-09 1.96166233e-06 7.67972976e-05 6.14611096e-10
 5.78377674e-16 5.88983996e-28 5.12793338e-17 1.35183892e-27
 1.33632187e-16 1.14670078e-10 9.15375339e-08 3.82689760e-15
 7.82467414e-18 4.27511653e-21 2.99558070e-31 3.99042642e-34
 7.30041469e-26 6.38508058e-14 4.38566198e-15 6.49033980e-17
 1.54242277e-14 4.39420080e-13 2.56518139e-19 2.69392703e-08
 1.03751665e-08 3.84427282e-14 2.59242755e-07 5.17412349e-02
 2.48055220e-13 3.01972668e-02 2.28297908e-04 4.86892078e-08
 1.92440964e-07 1.07732164e-07 2.63523643e-07 2.84258766e-11
 3.42402318e-13 3.10932248e-09 6.46762422e-14 2.87214600e-14
 4.49044420e-17 9.80386849e-23 1.10811843e-17 1.28910892e-14
 4.87947657e-11 6.01995088e-20 4.33128796e-16 4.52151917e-26
 7.80727758e-23 7.17304408e-21 5.16748089e-26 7.12544241e-21
 3.44051485e-10 8.70222094e-10 6.97533817e-08 1.36608019e-13
 1.82852611e-06 1.10164088e-05 1.31567053e-08 3.30798869e-11
 1.64067185e-10 1.76546161e+00 1.02172817e+01 1.57232414e-08
 1.84497531e-01 2.34513161e-01 6.61411551e-07 1.84476336e-01
 3.27278305e-08 6.80074549e-17 1.78216714e-25 1.43164015e-16
 1.64194737e-16 1.71150210e-16 2.05000892e-21 3.32011945e-18
 4.04466361e-19 5.38090509e-08 3.52284033e-10 5.32043697e-17
 2.10464818e-26 1.87282989e-23 3.68417468e-21 1.72273452e-21
 2.85498667e-24 5.02072156e-23 2.38959521e-20 2.98822478e-18
 2.14342981e-23 1.26678005e-21 1.74190821e-13 1.39767974e-10
 5.90062868e-12 6.58982299e-16 2.05862752e-12 7.34727593e-20
 3.52567311e-10 5.68480576e-11 6.32118923e-19 1.07695225e-15
 1.23220483e-09 2.35904329e-20 4.57412714e-23 2.68026896e-25

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_2_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_s_naive_sequential/20240402-191855_analysis.csv
dict_keys(['cluster_2_s_naive_sequential'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_s_naive_sequential to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2_s_naive_sequential/cluster_2_s_naive_sequential0_1712081935.pkl
Analysis Dump {'cluster_2_s_naive_sequential': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00003  0.00034        0  train_cluster_2_1
1   0.0  0.09091  0.09092        1  train_cluster_2_1
2   0.0  0.07145  0.07166        2  train_cluster_2_1
3   0.0  0.05561  0.05605        3  train_cluster_2_1
4   0.0  0.10000  0.10001        4  train_cluster_2_1
5   0.0  0.07695  0.07717        5  train_cluster_2_1
6   0.0  0.05888  0.05935        6  train_cluster_2_1
7   0.0  0.11111  0.11112        7  train_cluster_2_1
8   0.0  0.09094  0.09120        8  train_cluster_2_1
9   0.0  0.08336  0.08360        9  train_cluster_2_1
10  0.0  0.06673  0.06726       10  train_cluster_2_1
11  0.0  0.06256  0.06306       11  train_cluster_2_1
12  0.0  0.14286  0.14287       12  train_cluster_2_1
13  0.0  0.11115  0.11147       13  train_cluster_2_1
14  0.0  0.10003  0.10032       14  train_cluster_2_1
15  0.0  0.08341  0.08408       15  train_cluster_2_1
16  0.0  0.07149  0.07207       16  train_cluster_2_1
17  0.0  0.00010  0.00096       17  train_cluster_2_1
18  0.0  0.00000  0.00000       18  train_cluster_2_1
19  0.0  0.00000  0.00000       19  train_cluster_2_1
20  0.0  0.00000  0.00000       20  train_cluster_2_1
21  0.0  0.00000  0.00000       21  train_cluster_2_1
22  0.0  0.00000  0.00000       22  train_cluster_2_1
23  0.0  0.00000  0.00000       23  train_cluster_2_1
24  0.0  0.00000  0.00001       24  train_cluster_2_1
25  0.0  0.00000  0.00001       25  train_cluster_2_1
26  0.0  0.00000  0.00004       26  train_cluster_2_1
27  0.0  0.00000  0.00001       27  train_cluster_2_1
28  0.0  0.00000  0.00004       28  train_cluster_2_1
29  0.0  0.00033  0.00322       29  train_cluster_2_1
30  0.0  0.00063  0.00613       30  train_cluster_2_1
31  0.0  0.00046  0.00450       31  train_cluster_2_1
32  0.0  0.00049  0.00482       32  train_cluster_2_1
33  0.0  0.00086  0.00840       33  train_cluster_2_1
34  0.0  0.00057  0.00560       34  train_cluster_2_1
35  0.0  0.00006  0.00056       35  train_cluster_2_1
36  0.0  0.00007  0.00072       36  train_cluster_2_1
37  0.0  0.00008  0.00085       37  train_cluster_2_1
38  0.0  0.00007  0.00072       38  train_cluster_2_1
39  0.0  0.00006  0.00056       39  train_cluster_2_1
40  0.0  0.00005  0.00051       40  train_cluster_2_1
41  0.0  0.00003  0.00027       41  train_cluster_2_1
42  0.0  0.00000  0.00000       42  train_cluster_2_1
43  0.0  0.00000  0.00000       43  train_cluster_2_1
44  0.0  0.00000  0.00000       44  train_cluster_2_1
45  0.0  0.00000  0.00000       45  train_cluster_2_1
46  0.0  0.00000  0.00001       46  train_cluster_2_1
47  0.0  0.00000  0.00001       47  train_cluster_2_1
48  0.0  0.00000  0.00001       48  train_cluster_2_1
49  0.0  0.14313  0.14699       49  train_cluster_2_1
50  0.0  0.00049  0.00482       50  train_cluster_2_1
51  0.0  0.00000  0.00000       51  train_cluster_2_1
52  0.0  0.00000  0.00000       52  train_cluster_2_1
53  0.0  0.00000  0.00000       53  train_cluster_2_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00076  0.00729       54  val_cluster_2_1
1   0.0  0.00072  0.00688       55  val_cluster_2_1
2   0.0  0.00062  0.00590       56  val_cluster_2_1
3   0.0  0.00001  0.00009       57  val_cluster_2_1
4   0.0  0.00002  0.00016       58  val_cluster_2_1
5   0.0  0.00001  0.00010       59  val_cluster_2_1
6   0.0  0.00001  0.00009       60  val_cluster_2_1
7   0.0  0.00001  0.00009       61  val_cluster_2_1
8   0.0  0.00001  0.00011       62  val_cluster_2_1
9   0.0  0.00001  0.00012       63  val_cluster_2_1
10  0.0  0.00000  0.00000       64  val_cluster_2_1
11  0.0  0.00000  0.00000       65  val_cluster_2_1
12  0.0  0.00000  0.00000       66  val_cluster_2_1
13  0.0  0.00000  0.00000       67  val_cluster_2_1
14  0.0  0.00000  0.00000       68  val_cluster_2_1
15  0.0  0.00000  0.00000       69  val_cluster_2_1
16  0.0  0.00000  0.00003       70  val_cluster_2_1
17  0.0  0.00000  0.00002       71  val_cluster_2_1
18  0.0  0.00000  0.00005       72  val_cluster_2_1
19  0.0  0.00000  0.00002       73  val_cluster_2_1
20  0.0  0.00000  0.00002       74  val_cluster_2_1
21  0.0  0.00000  0.00002       75  val_cluster_2_1
22  0.0  0.00000  0.00000       76  val_cluster_2_1
23  0.0  0.00000  0.00000       77  val_cluster_2_1
24  0.0  0.00472  0.04329       78  val_cluster_2_1
25  0.0  0.00000  0.00000       79  val_cluster_2_1
26  0.0  0.00000  0.00000       80  val_cluster_2_1
27  0.0  0.00000  0.00001       81  val_cluster_2_1
28  0.0  0.00000  0.00001       82  val_cluster_2_1
29  0.0  0.00000  0.00000       83  val_cluster_2_1
30  0.0  0.00000  0.00001       84  val_cluster_2_1
31  0.0  0.00000  0.00001       85  val_cluster_2_1
32  0.0  0.00000  0.00001       86  val_cluster_2_1
33  0.0  0.00000  0.00001       87  val_cluster_2_1
34  0.0  0.00000  0.00001       88  val_cluster_2_1
35  0.0  0.15105  0.31019       89  val_cluster_2_1
36  0.0  0.13943  0.28633       90  val_cluster_2_1
37  0.0  0.12084  0.24815       91  val_cluster_2_1
38  0.0  0.10070  0.20679       92  val_cluster_2_1
39  0.0  0.00000  0.00000       93  val_cluster_2_1
40  0.0  0.00000  0.00000       94  val_cluster_2_1
41  0.0  0.00000  0.00000       95  val_cluster_2_1
42  0.0  0.00000  0.00000       96  val_cluster_2_1
43  0.0  0.00000  0.00000       97  val_cluster_2_1
44  0.0  0.00000  0.00000       98  val_cluster_2_1
45  0.0  0.10528  0.10547       99  val_cluster_2_1
46  0.0  0.11113  0.11133      100  val_cluster_2_1
47  0.0  0.10528  0.10547      101  val_cluster_2_1
48  0.0  0.12502  0.12525      102  val_cluster_2_1
49  0.0  0.11767  0.11788      103  val_cluster_2_1
50  0.0  0.10002  0.10020      104  val_cluster_2_1
51  0.0  0.13336  0.13360      105  val_cluster_2_1
52  0.0  0.11113  0.11133      106  val_cluster_2_1
53  0.0  0.11767  0.11788      107  val_cluster_2_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                             name split_type
0    cluster_2_s_naive_sequential          s
1    cluster_2_s_naive_sequential          s
2    cluster_2_s_naive_sequential          s
3    cluster_2_s_naive_sequential          s
4    cluster_2_s_naive_sequential          s
5    cluster_2_s_naive_sequential          s
6    cluster_2_s_naive_sequential          s
7    cluster_2_s_naive_sequential          s
8    cluster_2_s_naive_sequential          s
9    cluster_2_s_naive_sequential          s
10   cluster_2_s_naive_sequential          s
11   cluster_2_s_naive_sequential          s
12   cluster_2_s_naive_sequential          s
13   cluster_2_s_naive_sequential          s
14   cluster_2_s_naive_sequential          s
15   cluster_2_s_naive_sequential          s
16   cluster_2_s_naive_sequential          s
17   cluster_2_s_naive_sequential          s
18   cluster_2_s_naive_sequential          s
19   cluster_2_s_naive_sequential          s
20   cluster_2_s_naive_sequential          s
21   cluster_2_s_naive_sequential          s
22   cluster_2_s_naive_sequential          s
23   cluster_2_s_naive_sequential          s
24   cluster_2_s_naive_sequential          s
25   cluster_2_s_naive_sequential          s
26   cluster_2_s_naive_sequential          s
27   cluster_2_s_naive_sequential          s
28   cluster_2_s_naive_sequential          s
29   cluster_2_s_naive_sequential          s
30   cluster_2_s_naive_sequential          s
31   cluster_2_s_naive_sequential          s
32   cluster_2_s_naive_sequential          s
33   cluster_2_s_naive_sequential          s
34   cluster_2_s_naive_sequential          s
35   cluster_2_s_naive_sequential          s
36   cluster_2_s_naive_sequential          s
37   cluster_2_s_naive_sequential          s
38   cluster_2_s_naive_sequential          s
39   cluster_2_s_naive_sequential          s
40   cluster_2_s_naive_sequential          s
41   cluster_2_s_naive_sequential          s
42   cluster_2_s_naive_sequential          s
43   cluster_2_s_naive_sequential          s
44   cluster_2_s_naive_sequential          s
45   cluster_2_s_naive_sequential          s
46   cluster_2_s_naive_sequential          s
47   cluster_2_s_naive_sequential          s
48   cluster_2_s_naive_sequential          s
49   cluster_2_s_naive_sequential          s
50   cluster_2_s_naive_sequential          s
51   cluster_2_s_naive_sequential          s
52   cluster_2_s_naive_sequential          s
53   cluster_2_s_naive_sequential          s
54   cluster_2_s_naive_sequential          s
55   cluster_2_s_naive_sequential          s
56   cluster_2_s_naive_sequential          s
57   cluster_2_s_naive_sequential          s
58   cluster_2_s_naive_sequential          s
59   cluster_2_s_naive_sequential          s
60   cluster_2_s_naive_sequential          s
61   cluster_2_s_naive_sequential          s
62   cluster_2_s_naive_sequential          s
63   cluster_2_s_naive_sequential          s
64   cluster_2_s_naive_sequential          s
65   cluster_2_s_naive_sequential          s
66   cluster_2_s_naive_sequential          s
67   cluster_2_s_naive_sequential          s
68   cluster_2_s_naive_sequential          s
69   cluster_2_s_naive_sequential          s
70   cluster_2_s_naive_sequential          s
71   cluster_2_s_naive_sequential          s
72   cluster_2_s_naive_sequential          s
73   cluster_2_s_naive_sequential          s
74   cluster_2_s_naive_sequential          s
75   cluster_2_s_naive_sequential          s
76   cluster_2_s_naive_sequential          s
77   cluster_2_s_naive_sequential          s
78   cluster_2_s_naive_sequential          s
79   cluster_2_s_naive_sequential          s
80   cluster_2_s_naive_sequential          s
81   cluster_2_s_naive_sequential          s
82   cluster_2_s_naive_sequential          s
83   cluster_2_s_naive_sequential          s
84   cluster_2_s_naive_sequential          s
85   cluster_2_s_naive_sequential          s
86   cluster_2_s_naive_sequential          s
87   cluster_2_s_naive_sequential          s
88   cluster_2_s_naive_sequential          s
89   cluster_2_s_naive_sequential          s
90   cluster_2_s_naive_sequential          s
91   cluster_2_s_naive_sequential          s
92   cluster_2_s_naive_sequential          s
93   cluster_2_s_naive_sequential          s
94   cluster_2_s_naive_sequential          s
95   cluster_2_s_naive_sequential          s
96   cluster_2_s_naive_sequential          s
97   cluster_2_s_naive_sequential          s
98   cluster_2_s_naive_sequential          s
99   cluster_2_s_naive_sequential          s
100  cluster_2_s_naive_sequential          s
101  cluster_2_s_naive_sequential          s
102  cluster_2_s_naive_sequential          s
103  cluster_2_s_naive_sequential          s
104  cluster_2_s_naive_sequential          s
105  cluster_2_s_naive_sequential          s
106  cluster_2_s_naive_sequential          s
107  cluster_2_s_naive_sequential          s  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name cluster_2_R3_k_sequence already exists. Attempting to change name to cluster_2_R3_k_sequence0
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN     cluster_2

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
Running VDX loop
Random seeds: [42]
Splitting segments for cluster_2 by redundancy mk III
centrality
1    1509
Name: count, dtype: int64
Residue intersection:  [150 151 152 153 184 185 186]
Intersection peptides:  [55 56 57 58 59 60 61 66 67 69 70 71]
0.1111111111111111
Train peptides:  [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  62  63  64  65
  68  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107]
0.42592592592592593
Val peptides:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 49 50 51 52 53 54 72 73 74 75 76 77 78
 79 80]
0.46296296296296297
train_segs
    ResStr  ResEnd  peptide          calc_name
35      74      84       35  train_cluster_2_1
36      76      84       36  train_cluster_2_1
37      77      84       37  train_cluster_2_1
38      77      85       38  train_cluster_2_1
39      77      87       39  train_cluster_2_1
Saved train cluster_2_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/train_cluster_2_1/train_residue_segs__cluster_2_.txt
Train Peptide numbers: [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  62  63  64  65
  68  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107]
Saved val cluster_2_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/val_residue_segs__cluster_2_.txt
Val Peptide numbers: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 49 50 51 52 53 54 72 73 74 75 76 77 78
 79 80]
train_HDX_data
    0.0      0.5      5.0  peptide          calc_name  \
0   0.0  0.33633  0.46390       35  train_cluster_2_1
1   0.0  0.34716  0.45807       36  train_cluster_2_1
2   0.0  0.34165  0.44393       37  train_cluster_2_1
3   0.0  0.30725  0.43533       38  train_cluster_2_1
4   0.0  0.33252  0.48976       39  train_cluster_2_1
5   0.0  0.28369  0.42940       40  train_cluster_2_1
6   0.0  0.35906  0.50293       41  train_cluster_2_1
7   0.0  0.33575  0.45181       42  train_cluster_2_1
8   0.0  0.33443  0.43697       43  train_cluster_2_1
9   0.0  0.37082  0.47284       44  train_cluster_2_1
10  0.0  0.37847  0.48848       45  train_cluster_2_1
11  0.0  0.22218  0.31040       46  train_cluster_2_1
12  0.0  0.18217  0.28305       47  train_cluster_2_1
13  0.0  0.25719  0.37045       48  train_cluster_2_1
14  0.0  0.50341  0.53212       62  train_cluster_2_1
15  0.0  0.53500  0.53827       63  train_cluster_2_1
16  0.0  0.26524  0.35365       64  train_cluster_2_1
17  0.0  0.25454  0.32548       65  train_cluster_2_1
18  0.0  0.24177  0.30174       68  train_cluster_2_1
19  0.0  0.05688  0.07274       81  train_cluster_2_1
20  0.0  0.07600  0.11464       82  train_cluster_2_1
21  0.0  0.08147  0.13526       83  train_cluster_2_1
22  0.0  0.08527  0.13242       84  train_cluster_2_1
23  0.0  0.08569  0.14304       85  train_cluster_2_1
24  0.0  0.06291  0.07885       86  train_cluster_2_1
25  0.0  0.09393  0.16201       87  train_cluster_2_1
26  0.0  0.10385  0.19651       88  train_cluster_2_1
27  0.0  0.53877  0.49943       89  train_cluster_2_1
28  0.0  0.51417  0.47866       90  train_cluster_2_1
29  0.0  0.50107  0.49072       91  train_cluster_2_1
30  0.0  0.45551  0.47280       92  train_cluster_2_1
31  0.0  0.06500  0.10668       93  train_cluster_2_1
32  0.0  0.06362  0.10593       94  train_cluster_2_1
33  0.0  0.04358  0.04371       95  train_cluster_2_1
34  0.0  0.08151  0.10674       96  train_cluster_2_1
35  0.0  0.08795  0.11537       97  train_cluster_2_1
36  0.0  0.09261  0.12297       98  train_cluster_2_1
37  0.0  0.17298  0.20225       99  train_cluster_2_1
38  0.0  0.20729  0.23030      100  train_cluster_2_1
39  0.0  0.20401  0.23454      101  train_cluster_2_1
40  0.0  0.21943  0.23426      102  train_cluster_2_1
41  0.0  0.21731  0.24442      103  train_cluster_2_1
42  0.0  0.22028  0.25199      104  train_cluster_2_1
43  0.0  0.22217  0.24175      105  train_cluster_2_1
44  0.0  0.22454  0.24966      106  train_cluster_2_1
45  0.0  0.23913  0.27068      107  train_cluster_2_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      74      84
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      76      84
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      84
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      85
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      87
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      88
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      97
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      85      97
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      86      97
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      88      97
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      89      97
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     104
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     106
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     108
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     154     169
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     155     169
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     169     183
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     183
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     183
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     257
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     259
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     260
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     248     259
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     248     260
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     250     257
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     250     260
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     253     260
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     275
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     276
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     278
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     281
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     305     313
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     305     315
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     308     315
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     314     327
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     316     327
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     317     327
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     333     356
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     356
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     357
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     356
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     357
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     360
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     357
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     360
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     339     360
    ResStr  ResEnd  0.0      0.5      5.0  peptide          calc_name  \
0       74      84  0.0  0.33633  0.46390       35  train_cluster_2_1
1       76      84  0.0  0.34716  0.45807       36  train_cluster_2_1
2       77      84  0.0  0.34165  0.44393       37  train_cluster_2_1
3       77      85  0.0  0.30725  0.43533       38  train_cluster_2_1
4       77      87  0.0  0.33252  0.48976       39  train_cluster_2_1
5       77      88  0.0  0.28369  0.42940       40  train_cluster_2_1
6       77      97  0.0  0.35906  0.50293       41  train_cluster_2_1
7       85      97  0.0  0.33575  0.45181       42  train_cluster_2_1
8       86      97  0.0  0.33443  0.43697       43  train_cluster_2_1
9       88      97  0.0  0.37082  0.47284       44  train_cluster_2_1
10      89      97  0.0  0.37847  0.48848       45  train_cluster_2_1
11      98     104  0.0  0.22218  0.31040       46  train_cluster_2_1
12      98     106  0.0  0.18217  0.28305       47  train_cluster_2_1
13      98     108  0.0  0.25719  0.37045       48  train_cluster_2_1
14     154     169  0.0  0.50341  0.53212       62  train_cluster_2_1
15     155     169  0.0  0.53500  0.53827       63  train_cluster_2_1
16     169     183  0.0  0.26524  0.35365       64  train_cluster_2_1
17     170     183  0.0  0.25454  0.32548       65  train_cluster_2_1
18     171     183  0.0  0.24177  0.30174       68  train_cluster_2_1
19     247     257  0.0  0.05688  0.07274       81  train_cluster_2_1
20     247     259  0.0  0.07600  0.11464       82  train_cluster_2_1
21     247     260  0.0  0.08147  0.13526       83  train_cluster_2_1
22     248     259  0.0  0.08527  0.13242       84  train_cluster_2_1
23     248     260  0.0  0.08569  0.14304       85  train_cluster_2_1
24     250     257  0.0  0.06291  0.07885       86  train_cluster_2_1
25     250     260  0.0  0.09393  0.16201       87  train_cluster_2_1
26     253     260  0.0  0.10385  0.19651       88  train_cluster_2_1
27     261     275  0.0  0.53877  0.49943       89  train_cluster_2_1
28     261     276  0.0  0.51417  0.47866       90  train_cluster_2_1
29     261     278  0.0  0.50107  0.49072       91  train_cluster_2_1
30     261     281  0.0  0.45551  0.47280       92  train_cluster_2_1
31     305     313  0.0  0.06500  0.10668       93  train_cluster_2_1
32     305     315  0.0  0.06362  0.10593       94  train_cluster_2_1
33     308     315  0.0  0.04358  0.04371       95  train_cluster_2_1
34     314     327  0.0  0.08151  0.10674       96  train_cluster_2_1
35     316     327  0.0  0.08795  0.11537       97  train_cluster_2_1
36     317     327  0.0  0.09261  0.12297       98  train_cluster_2_1
37     333     356  0.0  0.17298  0.20225       99  train_cluster_2_1
38     334     356  0.0  0.20729  0.23030      100  train_cluster_2_1
39     334     357  0.0  0.20401  0.23454      101  train_cluster_2_1
40     336     356  0.0  0.21943  0.23426      102  train_cluster_2_1
41     336     357  0.0  0.21731  0.24442      103  train_cluster_2_1
42     336     360  0.0  0.22028  0.25199      104  train_cluster_2_1
43     338     357  0.0  0.22217  0.24175      105  train_cluster_2_1
44     338     360  0.0  0.22454  0.24966      106  train_cluster_2_1
45     339     360  0.0  0.23913  0.27068      107  train_cluster_2_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train cluster_2 HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/train_cluster_2_1/train_cluster_2_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide        calc_name  \
0        1       7  0.0  0.41879  0.44438        0  val_cluster_2_1
1        6      18  0.0  0.37096  0.45204        1  val_cluster_2_1
2        6      21  0.0  0.40040  0.48544        2  val_cluster_2_1
3        6      25  0.0  0.45875  0.51503        3  val_cluster_2_1
4        7      18  0.0  0.41726  0.49519        4  val_cluster_2_1
5        7      21  0.0  0.44176  0.50927        5  val_cluster_2_1
6        7      25  0.0  0.48987  0.54090        6  val_cluster_2_1
7        8      18  0.0  0.41316  0.48254        7  val_cluster_2_1
8        8      20  0.0  0.46617  0.51066        8  val_cluster_2_1
9        8      21  0.0  0.46825  0.52028        9  val_cluster_2_1
10       8      24  0.0  0.48273  0.53102       10  val_cluster_2_1
11       8      25  0.0  0.50258  0.53988       11  val_cluster_2_1
12      11      18  0.0  0.47373  0.50144       12  val_cluster_2_1
13      11      20  0.0  0.52057  0.54102       13  val_cluster_2_1
14      11      21  0.0  0.52823  0.55640       14  val_cluster_2_1
15      11      23  0.0  0.55802  0.57504       15  val_cluster_2_1
16      11      25  0.0  0.55641  0.57196       16  val_cluster_2_1
17      19      25  0.0  0.52928  0.54827       17  val_cluster_2_1
18      26      32  0.0  0.17163  0.27883       18  val_cluster_2_1
19      26      33  0.0  0.16883  0.28686       19  val_cluster_2_1
20      27      33  0.0  0.16341  0.27353       20  val_cluster_2_1
21      33      40  0.0  0.32309  0.41205       21  val_cluster_2_1
22      34      40  0.0  0.31355  0.39928       22  val_cluster_2_1
23      34      41  0.0  0.34392  0.42213       23  val_cluster_2_1
24      41      48  0.0  0.35604  0.35617       24  val_cluster_2_1
25      41      49  0.0  0.34105  0.35125       25  val_cluster_2_1
26      41      51  0.0  0.34135  0.38830       26  val_cluster_2_1
27      42      49  0.0  0.28512  0.29602       27  val_cluster_2_1
28      42      51  0.0  0.28439  0.33185       28  val_cluster_2_1
29      42      65  0.0  0.32954  0.39085       29  val_cluster_2_1
30      49      61  0.0  0.26192  0.34619       30  val_cluster_2_1
31      49      65  0.0  0.31421  0.37857       31  val_cluster_2_1
32      50      65  0.0  0.32314  0.38565       32  val_cluster_2_1
33      52      61  0.0  0.29666  0.37860       33  val_cluster_2_1
34      52      65  0.0  0.38440  0.44775       34  val_cluster_2_1
35     113     120  0.0  0.49756  0.50850       49  val_cluster_2_1
36     114     120  0.0  0.55024  0.54326       50  val_cluster_2_1
37     117     131  0.0  0.24310  0.29208       51  val_cluster_2_1
38     121     131  0.0  0.19173  0.23972       52  val_cluster_2_1
39     121     132  0.0  0.18105  0.23003       53  val_cluster_2_1
40     132     149  0.0  0.26140  0.30267       54  val_cluster_2_1
41     187     195  0.0  0.36820  0.37879       72  val_cluster_2_1
42     187     208  0.0  0.22903  0.26839       73  val_cluster_2_1
43     187     209  0.0  0.21687  0.25989       74  val_cluster_2_1
44     188     208  0.0  0.20479  0.23593       75  val_cluster_2_1
45     194     208  0.0  0.11684  0.15140       76  val_cluster_2_1
46     196     208  0.0  0.13267  0.18143       77  val_cluster_2_1
47     213     223  0.0  0.35203  0.42601       78  val_cluster_2_1
48     224     238  0.0  0.20249  0.21472       79  val_cluster_2_1
49     224     239  0.0  0.16260  0.17496       80  val_cluster_2_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/train_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/train_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(46, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00006  0.00056        0
1  0.0  0.00007  0.00072        1
2  0.0  0.00008  0.00085        2
3  0.0  0.00007  0.00072        3
4  0.0  0.00006  0.00056        4
Experimental cluster_2 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat
REWIGHTING val_cluster_2_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence0/val_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(50, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00003  0.00034        0
1  0.0  0.09091  0.09092        1
2  0.0  0.07145  0.07166        2
3  0.0  0.05561  0.05605        3
4  0.0  0.10000  0.10001        4
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45
46       98     104       46
47       98     106       47
48       98     108       48
49      113     120       49
50      114     120       50
51      117     131       51
52      121     131       52
53      121     132       53
54      132     149       54
55      132     150       55
56      132     153       56
57      150     169       57
58      151     162       58
59      151     167       59
60      151     169       60
61      151     170       61
62      154     169       62
63      155     169       63
64      169     183       64
65      170     183       65
66      170     185       66
67      170     186       67
68      171     183       68
69      171     186       69
70      184     195       70
71      184     208       71
72      187     195       72
73      187     208       73
74      187     209       74
75      188     208       75
76      194     208       76
77      196     208       77
78      213     223       78
79      224     238       79
80      224     239       80
81      247     257       81
82      247     259       82
83      247     260       83
84      248     259       84
85      248     260       85
86      250     257       86
87      250     260       87
88      253     260       88
89      261     275       89
90      261     276       90
91      261     278       91
92      261     281       92
93      305     313       93
94      305     315       94
95      308     315       95
96      314     327       96
97      316     327       97
98      317     327       98
99      333     356       99

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
LogPf_by_res [34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
Pf_by_res [1.54869129e+15 6.43841553e+26 2.15360553e+17 1.04980485e+12
 9.46574006e+06 6.79517751e+12 2.96876504e+14 7.98983831e+10
 8.04844774e+11 1.19657911e+10 7.27515016e+01 2.19784913e+08
 6.72439411e+19 2.00012787e+21 4.94039627e+14 7.00665325e+18
 1.02425136e+06 4.29010165e+08 4.33446277e+13 3.13143209e+06
 1.24298683e+08 2.02009409e+15 1.16307032e+22 2.19487354e+28
 5.54208220e+11 8.52689864e+16 2.16953109e+25 2.89117644e+23
 7.43957430e+17 6.08840486e+16 4.95817000e+18 1.49267298e+21
 1.20206031e+19 8.26873626e+27 2.40290426e+22 3.75796210e+15
 1.54709720e+12 2.49835152e+15 5.51831003e+13 1.10867521e+11
 3.41040848e+07 2.09551142e+13 3.59989917e+20 6.71916035e+25
 8.80915231e+30 1.22115019e+13 1.09831713e+08 1.38558819e+16
 1.72170324e+16 7.96218677e+04 3.43742959e+07 1.03301516e+07
 6.01215626e+13 4.20370772e+08 1.95855476e+05 7.26352827e+11
 1.26699828e+23 2.65053064e+17 6.64765336e+13 6.34588549e+15
 1.83214005e+26 1.14664444e+12 1.83827633e+13 7.98839904e+22
 6.63093150e+12 9.02523903e+05 9.63824855e+16 3.58580302e+23
 4.31404576e+16 1.32745388e+18 8.63748343e+23 5.56396988e+23
 3.69534744e+19 4.46051887e+22 5.15852843e+22 3.29303015e+18
 1.79147070e+22 5.78412017e+19 1.85293868e+18 1.67020125e+19
 9.57771044e+17 2.79034005e+12 2.75829360e+12 2.92079963e+07
 1.58893202e+24 5.10111943e+25 6.06159738e+18 6.58383735e+30
 2.49568819e+19 9.11410067e+10 1.50327558e+09 6.11249589e+13
 9.53093166e+19 3.80270177e+06 7.52665978e+01 3.16939408e+05
 1.45787529e+06 5.61741288e+12 1.54351546e+21 9.91504498e+34
 7.61219663e+20 5.51417615e+26 8.99566856e+09 2.29397145e+10
 8.14479325e+13 4.10200306e+14 2.81346704e+18 1.33940332e+28
 2.12471170e+36 8.07467372e+24 1.71063416e+11 8.01065627e+11
 1.44637252e+17 2.65346237e+17 4.01971241e+14 8.61419719e+16
 4.72101949e+15 2.08389495e+05 4.15393827e+09 1.24983528e+28
 1.59371193e+18 8.64346123e+04 8.90267835e+11 1.53496231e+14
 1.54244518e+16 3.75783305e+10 1.05537705e+16 1.75756379e+28
 9.90367012e+19 4.06571207e+21 3.47837470e+19 3.25608869e+23
 2.83060823e+19 9.52562903e+18 1.17232584e+24 5.21168031e+22
 1.27893257e+06 4.32615013e+15 4.09806721e+18 2.02265001e+16
 2.34886707e+15 4.59880112e+18 2.12912591e+17 8.59208803e+16
 5.63301492e+16 4.68717401e+19 5.84097122e+19 3.88789162e+13
 4.44729635e+12 1.51173405e+15 2.80547856e+21 9.67794188e+24
 1.04477166e+23 1.01475756e+33 9.41828310e+09 9.41098351e+10
 1.72948389e+15 1.23162478e+17 1.77987873e+14 1.38708659e+19
 1.51683855e+16 1.46415512e+17 1.74553204e+16 1.75198954e+11
 5.36934030e+11 8.91599723e+08 1.01729811e+08 7.14815200e+12
 2.24172666e+18 1.70879782e+30 2.25347011e+19 5.39348197e+30
 2.86340712e+19 2.01068514e+13 9.14523707e+10 1.41236626e+18
 2.13465609e+20 4.69727752e+23 3.85756411e+33 1.51975951e+37
 1.44359924e+29 3.69511359e+16 1.78139004e+18 3.71986125e+19
 2.84833290e+17 6.02440664e+15 2.84234046e+21 1.91605666e+11
 2.32701457e+11 1.81125658e+17 2.18316996e+09 4.35469143e+04
 4.44882994e+16 1.78989082e+05 1.83777460e+06 1.71933881e+10
 7.91583355e+09 3.63453448e+10 2.52333313e+09 2.18313360e+13
 4.76713533e+15 4.78771634e+11 2.14807479e+16 3.05202202e+16
 5.89528596e+19 3.55956313e+25 1.06710707e+20 3.48742248e+16
 1.60110915e+13 6.21156779e+21 2.16858834e+18 1.98385442e+28
 2.34581930e+25 6.12478258e+22 3.97663106e+27 1.25887423e+23
 7.34802701e+12 2.97278891e+12 1.17281337e+11 3.86649971e+15
 4.90560991e+08 8.52617289e+07 3.41701613e+11 6.81130237e+13
 9.50106851e+12 4.12986542e+02 1.15733426e+02 1.19193369e+11
 8.25664512e+03 8.96658265e+03 3.82227916e+08 3.68853164e+03
 5.34412934e+10 2.57180274e+19 4.38374966e+28 3.77537682e+19
 2.55525910e+18 9.98657895e+17 2.82512992e+23 3.10199054e+20
 4.52805578e+21 2.40956610e+10 5.08043878e+11 1.89167653e+19
 4.46287445e+28 6.92302411e+25 3.51928114e+23 2.79624889e+23
 1.30975508e+26 3.10476005e+24 9.00471221e+22 2.22526078e+20
 6.78711036e+24 1.82009040e+24 1.51973866e+16 7.20089551e+12
 6.94857726e+14 1.00906798e+18 4.77767296e+14 9.92356750e+21
 3.05880741e+12 9.29134415e+12 6.63736020e+20 1.02470234e+18
 1.45248372e+11 8.51252235e+22 2.35768589e+25 5.81588485e+27
 2.13975876e+18 4.49096741e+13 1.30404025e+12 4.88832578e+13
 1.33361204e+15 4.63166597e+13 1.52893265e+08 2.75817831e+14
 1.92983575e+00 5.45981500e+01 1.16347721e+08 1.43899231e+06
 1.76727706e+15 1.17158537e+24 1.28733897e+23 1.82850094e+17
 7.03460558e+19 1.31036587e+25 1.15090091e+23 5.22140269e+18
 2.91918632e+20]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [2.64745947e-11 5.80784710e-24 2.08750737e-14 2.40816146e-10
 4.04240295e-04 6.17438022e-10 2.45594339e-12 1.23099471e-08
 4.14077898e-10 4.84008246e-08 7.42937388e+01 1.44809248e-05
 3.05591322e-17 9.36993146e-19 4.06473645e-12 4.75645676e-17
 6.49213628e-04 1.09730307e-05 2.43141392e-10 1.11442585e-03
 3.00834506e-05 1.89418581e-12 3.21505350e-20 1.41704836e-25
 1.65623222e-09 4.09263559e-14 1.19241738e-22 6.04950137e-21
 3.24523455e-15 2.61993582e-14 2.02989121e-16 8.29525047e-19
 3.11077011e-17 9.02308476e-26 1.38694012e-20 1.89601505e-13
 8.38062823e-10 3.27446711e-13 2.40429681e-11 2.93758092e-09
 1.86203473e-05 1.20643561e-10 2.27249974e-18 4.84706865e-24
 4.34370234e-28 5.97069790e-11 4.80912892e-05 3.02802882e-13
 1.30868728e-13 1.15282087e-02 6.40560830e-06 6.43705889e-05
 4.20497985e-11 2.50704278e-06 3.63796453e-03 3.17428959e-09
 4.16886807e-21 7.75284944e-16 2.75502669e-11 2.13944903e-13
 5.12667171e-24 1.42352601e-09 1.14388768e-10 8.32404512e-21
 9.14575651e-11 1.01703402e-03 8.68552485e-15 1.89761345e-21
 3.29540981e-14 2.51058389e-16 5.20483480e-22 2.07687045e-21
 4.31657110e-17 3.41514223e-20 8.51664114e-21 2.01928895e-16
 8.70130650e-20 1.44729437e-17 2.01805562e-16 1.44552422e-17
 7.97136092e-16 7.03294212e-10 9.59740203e-10 2.27662977e-05
 6.04907348e-22 7.50116442e-24 5.01426281e-17 6.22751931e-28
 1.80137384e-16 1.59617445e-08 5.56872247e-06 1.72415218e-10
 1.52636648e-17 2.90203008e-04 1.43282085e+01 5.15012694e-03
 7.06437594e-04 9.40281369e-11 3.92901054e-19 9.04689383e-33
 1.41672050e-18 1.51814600e-23 9.30595034e-08 3.64927144e-07
 4.38443980e-11 4.89551286e-12 6.07508480e-16 8.62745702e-26
 2.85426418e-33 1.11088523e-22 6.45114845e-09 1.09427400e-08
 2.83474510e-14 7.56800208e-15 6.00619176e-12 9.06941694e-15
 1.61718008e-13 3.34132219e-03 2.47932888e-07 1.27626658e-25
 1.31942391e-15 2.27042148e-02 2.53089130e-09 3.21141520e-11
 6.83257546e-13 9.28659903e-08 1.07000688e-13 2.74083623e-26
 1.68654530e-17 1.52636204e-18 2.96085960e-17 2.75484996e-21
 7.09437940e-17 2.15725017e-16 4.30274726e-21 6.39464461e-20
 4.42533883e-04 1.11350608e-13 3.98304396e-16 9.92826672e-14
 6.19349424e-13 4.07520582e-16 2.31522303e-15 9.09275440e-15
 2.19812950e-14 1.87017867e-17 6.40190331e-18 2.30717229e-11
 3.50508138e-10 1.83365987e-12 8.80617320e-19 3.60587915e-23
 8.99027129e-21 3.43899765e-30 7.06028831e-08 7.39876381e-08
 2.37070575e-12 7.80397301e-15 1.91603643e-11 9.78792433e-17
 9.37248639e-14 2.27618255e-15 4.47575549e-14 8.69486150e-09
 3.65488104e-09 1.96166233e-06 7.67972976e-05 6.14611096e-10
 5.78377674e-16 5.88983996e-28 5.12793338e-17 1.35183892e-27
 1.33632187e-16 1.14670078e-10 9.15375339e-08 3.82689760e-15
 7.82467414e-18 4.27511653e-21 2.99558070e-31 3.99042642e-34
 7.30041469e-26 6.38508058e-14 4.38566198e-15 6.49033980e-17
 1.54242277e-14 4.39420080e-13 2.56518139e-19 2.69392703e-08
 1.03751665e-08 3.84427282e-14 2.59242755e-07 5.17412349e-02
 2.48055220e-13 3.01972668e-02 2.28297908e-04 4.86892078e-08
 1.92440964e-07 1.07732164e-07 2.63523643e-07 2.84258766e-11
 3.42402318e-13 3.10932248e-09 6.46762422e-14 2.87214600e-14
 4.49044420e-17 9.80386849e-23 1.10811843e-17 1.28910892e-14
 4.87947657e-11 6.01995088e-20 4.33128796e-16 4.52151917e-26
 7.80727758e-23 7.17304408e-21 5.16748089e-26 7.12544241e-21
 3.44051485e-10 8.70222094e-10 6.97533817e-08 1.36608019e-13
 1.82852611e-06 1.10164088e-05 1.31567053e-08 3.30798869e-11
 1.64067185e-10 1.76546161e+00 1.02172817e+01 1.57232414e-08
 1.84497531e-01 2.34513161e-01 6.61411551e-07 1.84476336e-01
 3.27278305e-08 6.80074549e-17 1.78216714e-25 1.43164015e-16
 1.64194737e-16 1.71150210e-16 2.05000892e-21 3.32011945e-18
 4.04466361e-19 5.38090509e-08 3.52284033e-10 5.32043697e-17
 2.10464818e-26 1.87282989e-23 3.68417468e-21 1.72273452e-21
 2.85498667e-24 5.02072156e-23 2.38959521e-20 2.98822478e-18
 2.14342981e-23 1.26678005e-21 1.74190821e-13 1.39767974e-10
 5.90062868e-12 6.58982299e-16 2.05862752e-12 7.34727593e-20
 3.52567311e-10 5.68480576e-11 6.32118923e-19 1.07695225e-15
 1.23220483e-09 2.35904329e-20 4.57412714e-23 2.68026896e-25

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_2_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_R3_k_sequence/20240402-191859_analysis.csv
dict_keys(['cluster_2_R3_k_sequence'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_R3_k_sequence to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2_R3_k_sequence/cluster_2_R3_k_sequence0_1712081939.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2_R3_k_sequence': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00006  0.00056       35  train_cluster_2_1
1   0.0  0.00007  0.00072       36  train_cluster_2_1
2   0.0  0.00008  0.00085       37  train_cluster_2_1
3   0.0  0.00007  0.00072       38  train_cluster_2_1
4   0.0  0.00006  0.00056       39  train_cluster_2_1
5   0.0  0.00005  0.00051       40  train_cluster_2_1
6   0.0  0.00003  0.00027       41  train_cluster_2_1
7   0.0  0.00000  0.00000       42  train_cluster_2_1
8   0.0  0.00000  0.00000       43  train_cluster_2_1
9   0.0  0.00000  0.00000       44  train_cluster_2_1
10  0.0  0.00000  0.00000       45  train_cluster_2_1
11  0.0  0.00000  0.00001       46  train_cluster_2_1
12  0.0  0.00000  0.00001       47  train_cluster_2_1
13  0.0  0.00000  0.00001       48  train_cluster_2_1
14  0.0  0.00001  0.00011       62  train_cluster_2_1
15  0.0  0.00001  0.00012       63  train_cluster_2_1
16  0.0  0.00000  0.00000       64  train_cluster_2_1
17  0.0  0.00000  0.00000       65  train_cluster_2_1
18  0.0  0.00000  0.00000       68  train_cluster_2_1
19  0.0  0.00000  0.00001       81  train_cluster_2_1
20  0.0  0.00000  0.00001       82  train_cluster_2_1
21  0.0  0.00000  0.00000       83  train_cluster_2_1
22  0.0  0.00000  0.00001       84  train_cluster_2_1
23  0.0  0.00000  0.00001       85  train_cluster_2_1
24  0.0  0.00000  0.00001       86  train_cluster_2_1
25  0.0  0.00000  0.00001       87  train_cluster_2_1
26  0.0  0.00000  0.00001       88  train_cluster_2_1
27  0.0  0.15105  0.31019       89  train_cluster_2_1
28  0.0  0.13943  0.28633       90  train_cluster_2_1
29  0.0  0.12084  0.24815       91  train_cluster_2_1
30  0.0  0.10070  0.20679       92  train_cluster_2_1
31  0.0  0.00000  0.00000       93  train_cluster_2_1
32  0.0  0.00000  0.00000       94  train_cluster_2_1
33  0.0  0.00000  0.00000       95  train_cluster_2_1
34  0.0  0.00000  0.00000       96  train_cluster_2_1
35  0.0  0.00000  0.00000       97  train_cluster_2_1
36  0.0  0.00000  0.00000       98  train_cluster_2_1
37  0.0  0.10528  0.10547       99  train_cluster_2_1
38  0.0  0.11113  0.11133      100  train_cluster_2_1
39  0.0  0.10528  0.10547      101  train_cluster_2_1
40  0.0  0.12502  0.12525      102  train_cluster_2_1
41  0.0  0.11767  0.11788      103  train_cluster_2_1
42  0.0  0.10002  0.10020      104  train_cluster_2_1
43  0.0  0.13336  0.13360      105  train_cluster_2_1
44  0.0  0.11113  0.11133      106  train_cluster_2_1
45  0.0  0.11767  0.11788      107  train_cluster_2_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00003  0.00034        0  val_cluster_2_1
1   0.0  0.09091  0.09092        1  val_cluster_2_1
2   0.0  0.07145  0.07166        2  val_cluster_2_1
3   0.0  0.05561  0.05605        3  val_cluster_2_1
4   0.0  0.10000  0.10001        4  val_cluster_2_1
5   0.0  0.07695  0.07717        5  val_cluster_2_1
6   0.0  0.05888  0.05935        6  val_cluster_2_1
7   0.0  0.11111  0.11112        7  val_cluster_2_1
8   0.0  0.09094  0.09120        8  val_cluster_2_1
9   0.0  0.08336  0.08360        9  val_cluster_2_1
10  0.0  0.06673  0.06726       10  val_cluster_2_1
11  0.0  0.06256  0.06306       11  val_cluster_2_1
12  0.0  0.14286  0.14287       12  val_cluster_2_1
13  0.0  0.11115  0.11147       13  val_cluster_2_1
14  0.0  0.10003  0.10032       14  val_cluster_2_1
15  0.0  0.08341  0.08408       15  val_cluster_2_1
16  0.0  0.07149  0.07207       16  val_cluster_2_1
17  0.0  0.00010  0.00096       17  val_cluster_2_1
18  0.0  0.00000  0.00000       18  val_cluster_2_1
19  0.0  0.00000  0.00000       19  val_cluster_2_1
20  0.0  0.00000  0.00000       20  val_cluster_2_1
21  0.0  0.00000  0.00000       21  val_cluster_2_1
22  0.0  0.00000  0.00000       22  val_cluster_2_1
23  0.0  0.00000  0.00000       23  val_cluster_2_1
24  0.0  0.00000  0.00001       24  val_cluster_2_1
25  0.0  0.00000  0.00001       25  val_cluster_2_1
26  0.0  0.00000  0.00004       26  val_cluster_2_1
27  0.0  0.00000  0.00001       27  val_cluster_2_1
28  0.0  0.00000  0.00004       28  val_cluster_2_1
29  0.0  0.00033  0.00322       29  val_cluster_2_1
30  0.0  0.00063  0.00613       30  val_cluster_2_1
31  0.0  0.00046  0.00450       31  val_cluster_2_1
32  0.0  0.00049  0.00482       32  val_cluster_2_1
33  0.0  0.00086  0.00840       33  val_cluster_2_1
34  0.0  0.00057  0.00560       34  val_cluster_2_1
35  0.0  0.14313  0.14699       49  val_cluster_2_1
36  0.0  0.00049  0.00482       50  val_cluster_2_1
37  0.0  0.00000  0.00000       51  val_cluster_2_1
38  0.0  0.00000  0.00000       52  val_cluster_2_1
39  0.0  0.00000  0.00000       53  val_cluster_2_1
40  0.0  0.00076  0.00729       54  val_cluster_2_1
41  0.0  0.00000  0.00005       72  val_cluster_2_1
42  0.0  0.00000  0.00002       73  val_cluster_2_1
43  0.0  0.00000  0.00002       74  val_cluster_2_1
44  0.0  0.00000  0.00002       75  val_cluster_2_1
45  0.0  0.00000  0.00000       76  val_cluster_2_1
46  0.0  0.00000  0.00000       77  val_cluster_2_1
47  0.0  0.00472  0.04329       78  val_cluster_2_1
48  0.0  0.00000  0.00000       79  val_cluster_2_1
49  0.0  0.00000  0.00000       80  val_cluster_2_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name                     name  \
0    0.0  0.41879  0.44438        0  Experimental  cluster_2_R3_k_sequence
1    0.0  0.37096  0.45204        1  Experimental  cluster_2_R3_k_sequence
2    0.0  0.40040  0.48544        2  Experimental  cluster_2_R3_k_sequence
3    0.0  0.45875  0.51503        3  Experimental  cluster_2_R3_k_sequence
4    0.0  0.41726  0.49519        4  Experimental  cluster_2_R3_k_sequence
5    0.0  0.44176  0.50927        5  Experimental  cluster_2_R3_k_sequence
6    0.0  0.48987  0.54090        6  Experimental  cluster_2_R3_k_sequence
7    0.0  0.41316  0.48254        7  Experimental  cluster_2_R3_k_sequence
8    0.0  0.46617  0.51066        8  Experimental  cluster_2_R3_k_sequence
9    0.0  0.46825  0.52028        9  Experimental  cluster_2_R3_k_sequence
10   0.0  0.48273  0.53102       10  Experimental  cluster_2_R3_k_sequence
11   0.0  0.50258  0.53988       11  Experimental  cluster_2_R3_k_sequence
12   0.0  0.47373  0.50144       12  Experimental  cluster_2_R3_k_sequence
13   0.0  0.52057  0.54102       13  Experimental  cluster_2_R3_k_sequence
14   0.0  0.52823  0.55640       14  Experimental  cluster_2_R3_k_sequence
15   0.0  0.55802  0.57504       15  Experimental  cluster_2_R3_k_sequence
16   0.0  0.55641  0.57196       16  Experimental  cluster_2_R3_k_sequence
17   0.0  0.52928  0.54827       17  Experimental  cluster_2_R3_k_sequence
18   0.0  0.17163  0.27883       18  Experimental  cluster_2_R3_k_sequence
19   0.0  0.16883  0.28686       19  Experimental  cluster_2_R3_k_sequence
20   0.0  0.16341  0.27353       20  Experimental  cluster_2_R3_k_sequence
21   0.0  0.32309  0.41205       21  Experimental  cluster_2_R3_k_sequence
22   0.0  0.31355  0.39928       22  Experimental  cluster_2_R3_k_sequence
23   0.0  0.34392  0.42213       23  Experimental  cluster_2_R3_k_sequence
24   0.0  0.35604  0.35617       24  Experimental  cluster_2_R3_k_sequence
25   0.0  0.34105  0.35125       25  Experimental  cluster_2_R3_k_sequence
26   0.0  0.34135  0.38830       26  Experimental  cluster_2_R3_k_sequence
27   0.0  0.28512  0.29602       27  Experimental  cluster_2_R3_k_sequence
28   0.0  0.28439  0.33185       28  Experimental  cluster_2_R3_k_sequence
29   0.0  0.32954  0.39085       29  Experimental  cluster_2_R3_k_sequence
30   0.0  0.26192  0.34619       30  Experimental  cluster_2_R3_k_sequence
31   0.0  0.31421  0.37857       31  Experimental  cluster_2_R3_k_sequence
32   0.0  0.32314  0.38565       32  Experimental  cluster_2_R3_k_sequence
33   0.0  0.29666  0.37860       33  Experimental  cluster_2_R3_k_sequence
34   0.0  0.38440  0.44775       34  Experimental  cluster_2_R3_k_sequence
35   0.0  0.33633  0.46390       35  Experimental  cluster_2_R3_k_sequence
36   0.0  0.34716  0.45807       36  Experimental  cluster_2_R3_k_sequence
37   0.0  0.34165  0.44393       37  Experimental  cluster_2_R3_k_sequence
38   0.0  0.30725  0.43533       38  Experimental  cluster_2_R3_k_sequence
39   0.0  0.33252  0.48976       39  Experimental  cluster_2_R3_k_sequence
40   0.0  0.28369  0.42940       40  Experimental  cluster_2_R3_k_sequence
41   0.0  0.35906  0.50293       41  Experimental  cluster_2_R3_k_sequence
42   0.0  0.33575  0.45181       42  Experimental  cluster_2_R3_k_sequence
43   0.0  0.33443  0.43697       43  Experimental  cluster_2_R3_k_sequence
44   0.0  0.37082  0.47284       44  Experimental  cluster_2_R3_k_sequence
45   0.0  0.37847  0.48848       45  Experimental  cluster_2_R3_k_sequence
46   0.0  0.22218  0.31040       46  Experimental  cluster_2_R3_k_sequence
47   0.0  0.18217  0.28305       47  Experimental  cluster_2_R3_k_sequence
48   0.0  0.25719  0.37045       48  Experimental  cluster_2_R3_k_sequence
49   0.0  0.49756  0.50850       49  Experimental  cluster_2_R3_k_sequence
50   0.0  0.55024  0.54326       50  Experimental  cluster_2_R3_k_sequence
51   0.0  0.24310  0.29208       51  Experimental  cluster_2_R3_k_sequence
52   0.0  0.19173  0.23972       52  Experimental  cluster_2_R3_k_sequence
53   0.0  0.18105  0.23003       53  Experimental  cluster_2_R3_k_sequence
54   0.0  0.26140  0.30267       54  Experimental  cluster_2_R3_k_sequence
55   0.0  0.26392  0.30614       55  Experimental  cluster_2_R3_k_sequence
56   0.0  0.26061  0.32801       56  Experimental  cluster_2_R3_k_sequence
57   0.0  0.45297  0.53974       57  Experimental  cluster_2_R3_k_sequence
58   0.0  0.31622  0.45372       58  Experimental  cluster_2_R3_k_sequence
59   0.0  0.43711  0.52972       59  Experimental  cluster_2_R3_k_sequence
60   0.0  0.47628  0.54735       60  Experimental  cluster_2_R3_k_sequence
61   0.0  0.49249  0.57156       61  Experimental  cluster_2_R3_k_sequence
62   0.0  0.50341  0.53212       62  Experimental  cluster_2_R3_k_sequence
63   0.0  0.53500  0.53827       63  Experimental  cluster_2_R3_k_sequence
64   0.0  0.26524  0.35365       64  Experimental  cluster_2_R3_k_sequence
65   0.0  0.25454  0.32548       65  Experimental  cluster_2_R3_k_sequence
66   0.0  0.25152  0.35786       66  Experimental  cluster_2_R3_k_sequence
67   0.0  0.28164  0.36568       67  Experimental  cluster_2_R3_k_sequence
68   0.0  0.24177  0.30174       68  Experimental  cluster_2_R3_k_sequence
69   0.0  0.27969  0.36567       69  Experimental  cluster_2_R3_k_sequence
70   0.0  0.38633  0.44869       70  Experimental  cluster_2_R3_k_sequence
71   0.0  0.24871  0.31226       71  Experimental  cluster_2_R3_k_sequence
72   0.0  0.36820  0.37879       72  Experimental  cluster_2_R3_k_sequence
73   0.0  0.22903  0.26839       73  Experimental  cluster_2_R3_k_sequence
74   0.0  0.21687  0.25989       74  Experimental  cluster_2_R3_k_sequence
75   0.0  0.20479  0.23593       75  Experimental  cluster_2_R3_k_sequence
76   0.0  0.11684  0.15140       76  Experimental  cluster_2_R3_k_sequence
77   0.0  0.13267  0.18143       77  Experimental  cluster_2_R3_k_sequence
78   0.0  0.35203  0.42601       78  Experimental  cluster_2_R3_k_sequence
79   0.0  0.20249  0.21472       79  Experimental  cluster_2_R3_k_sequence
80   0.0  0.16260  0.17496       80  Experimental  cluster_2_R3_k_sequence
81   0.0  0.05688  0.07274       81  Experimental  cluster_2_R3_k_sequence
82   0.0  0.07600  0.11464       82  Experimental  cluster_2_R3_k_sequence
83   0.0  0.08147  0.13526       83  Experimental  cluster_2_R3_k_sequence
84   0.0  0.08527  0.13242       84  Experimental  cluster_2_R3_k_sequence
85   0.0  0.08569  0.14304       85  Experimental  cluster_2_R3_k_sequence
86   0.0  0.06291  0.07885       86  Experimental  cluster_2_R3_k_sequence
87   0.0  0.09393  0.16201       87  Experimental  cluster_2_R3_k_sequence
88   0.0  0.10385  0.19651       88  Experimental  cluster_2_R3_k_sequence
89   0.0  0.53877  0.49943       89  Experimental  cluster_2_R3_k_sequence
90   0.0  0.51417  0.47866       90  Experimental  cluster_2_R3_k_sequence
91   0.0  0.50107  0.49072       91  Experimental  cluster_2_R3_k_sequence
92   0.0  0.45551  0.47280       92  Experimental  cluster_2_R3_k_sequence
93   0.0  0.06500  0.10668       93  Experimental  cluster_2_R3_k_sequence
94   0.0  0.06362  0.10593       94  Experimental  cluster_2_R3_k_sequence
95   0.0  0.04358  0.04371       95  Experimental  cluster_2_R3_k_sequence
96   0.0  0.08151  0.10674       96  Experimental  cluster_2_R3_k_sequence
97   0.0  0.08795  0.11537       97  Experimental  cluster_2_R3_k_sequence
98   0.0  0.09261  0.12297       98  Experimental  cluster_2_R3_k_sequence
99   0.0  0.17298  0.20225       99  Experimental  cluster_2_R3_k_sequence
100  0.0  0.20729  0.23030      100  Experimental  cluster_2_R3_k_sequence
101  0.0  0.20401  0.23454      101  Experimental  cluster_2_R3_k_sequence
102  0.0  0.21943  0.23426      102  Experimental  cluster_2_R3_k_sequence
103  0.0  0.21731  0.24442      103  Experimental  cluster_2_R3_k_sequence
104  0.0  0.22028  0.25199      104  Experimental  cluster_2_R3_k_sequence
105  0.0  0.22217  0.24175      105  Experimental  cluster_2_R3_k_sequence
106  0.0  0.22454  0.24966      106  Experimental  cluster_2_R3_k_sequence
107  0.0  0.23913  0.27068      107  Experimental  cluster_2_R3_k_sequence

    split_type
0           R3
1           R3
2           R3
3           R3
4           R3
5           R3
6           R3
7           R3
8           R3
9           R3
10          R3
11          R3
12          R3
13          R3
14          R3
15          R3
16          R3
17          R3
18          R3
19          R3
20          R3
21          R3
22          R3
23          R3
24          R3
25          R3
26          R3
27          R3
28          R3
29          R3
30          R3
31          R3
32          R3
33          R3
34          R3
35          R3
36          R3
37          R3
38          R3
39          R3
40          R3
41          R3
42          R3
43          R3
44          R3
45          R3
46          R3
47          R3
48          R3
49          R3
50          R3
51          R3
52          R3
53          R3
54          R3
55          R3
56          R3
57          R3
58          R3
59          R3
60          R3
61          R3
62          R3
63          R3
64          R3
65          R3
66          R3
67          R3
68          R3
69          R3
70          R3
71          R3
72          R3
73          R3
74          R3
75          R3
76          R3
77          R3
78          R3
79          R3
80          R3
81          R3
82          R3
83          R3
84          R3
85          R3
86          R3
87          R3
88          R3
89          R3
90          R3
91          R3
92          R3
93          R3
94          R3
95          R3
96          R3
97          R3
98          R3
99          R3
100         R3
101         R3
102         R3
103         R3
104         R3
105         R3
106         R3
107         R3  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental
69   0.0  0.27969  0.36567       69       Experimental
70   0.0  0.38633  0.44869       70       Experimental
71   0.0  0.24871  0.31226       71       Experimental
72   0.0  0.36820  0.37879       72       Experimental
73   0.0  0.22903  0.26839       73       Experimental
74   0.0  0.21687  0.25989       74       Experimental
75   0.0  0.20479  0.23593       75       Experimental
76   0.0  0.11684  0.15140       76       Experimental
77   0.0  0.13267  0.18143       77       Experimental
78   0.0  0.35203  0.42601       78       Experimental
79   0.0  0.20249  0.21472       79       Experimental
80   0.0  0.16260  0.17496       80       Experimental
81   0.0  0.05688  0.07274       81       Experimental
82   0.0  0.07600  0.11464       82       Experimental
83   0.0  0.08147  0.13526       83       Experimental
84   0.0  0.08527  0.13242       84       Experimental
85   0.0  0.08569  0.14304       85       Experimental
86   0.0  0.06291  0.07885       86       Experimental
87   0.0  0.09393  0.16201       87       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/train_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/train_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(35, 4)
   0.0  0.5      5.0  peptide
0  0.0  0.0  0.00000        0
1  0.0  0.0  0.00000        1
2  0.0  0.0  0.00000        2
3  0.0  0.0  0.00001        3
4  0.0  0.0  0.00001        4
Experimental cluster_2 False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat
REWIGHTING val_cluster_2_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_20/prep_cluster_20_0/out__prep_cluster_20_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1/val_cluster_2_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 2.0, 'bv_bh': 0.35}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 2.0, 0.35)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours0/val_cluster_2_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(73, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.00003  0.00034        0
1  0.0  0.09091  0.09092        1
2  0.0  0.07145  0.07166        2
3  0.0  0.05561  0.05605        3
4  0.0  0.10000  0.10001        4
Structures loaded cluster_2:
cluster_2 Topology: <Universe with 3369 atoms>
cluster_2 Trajectory: <Universe with 3369 atoms>
cluster_2 Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45
46       98     104       46
47       98     106       47
48       98     108       48
49      113     120       49
50      114     120       50
51      117     131       51
52      121     131       52
53      121     132       53
54      132     149       54
55      132     150       55
56      132     153       56
57      150     169       57
58      151     162       58
59      151     167       59
60      151     169       60
61      151     170       61
62      154     169       62
63      155     169       63
64      169     183       64
65      170     183       65
66      170     185       66
67      170     186       67
68      171     183       68
69      171     186       69
70      184     195       70
71      184     208       71
72      187     195       72
73      187     208       73
74      187     209       74
75      188     208       75
76      194     208       76
77      196     208       77
78      213     223       78
79      224     238       79
80      224     239       80
81      247     257       81
82      247     259       82
83      247     260       83
84      248     259       84
85      248     260       85
86      250     257       86
87      250     260       87
88      253     260       88
89      261     275       89
90      261     276       90
91      261     278       91
92      261     281       92
93      305     313       93
94      305     315       94
95      308     315       95
96      314     327       96
97      316     327       97
98      317     327       98
99      333     356       99

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
LogPf_by_res [34.97618664 61.72949489 39.91109001 27.67962541 16.06318953 29.54723429
 33.32433736 25.10402145 27.41391527 23.20531768  4.28704955 19.20815996
 45.65485859 49.04749807 33.83363685 43.39339184 13.83947252 19.87699117
 31.40020388 14.95700099 18.63819796 35.24192048 50.80793538 65.25850704
 27.0408063  38.9845872  58.33913838 54.02112063 41.15076021 38.64774761
 43.0475684  48.75485541 43.93315378 64.2822792  51.53355016 35.86265321
 28.06740152 35.45440752 31.64167787 25.43160182 17.34492772 30.67340385
 47.3326077  59.46959052 71.25334401 30.1333994  18.51445987 37.16748622
 37.38467554 11.28504405 17.35281963 16.15057751 31.72738967 19.85664767
 12.1851323  27.31130172 53.19610768 40.11870644 31.82787012 36.38658304
 60.47269713 27.76786091 30.54243457 52.73486241 29.52276641 13.71295045
 39.10710089 54.23643958 38.30323764 41.7297944  55.11556841 54.675769
 45.05619135 52.15213714 52.2975234  42.63833983 51.23990895 45.50423303
 42.06330453 44.26206089 41.40338515 28.65718459 28.64563334 17.18995308
 55.72510434 59.19408734 43.24850503 70.96217055 44.66368129 25.23567367
 21.13091228 31.74394139 46.00365924 15.15122236  4.32103645 12.66646589
 14.19249065 29.35689233 48.78834953 80.58194646 48.08145364 61.57453468
 22.92000903 23.8561355  32.03098507 33.64766671 42.48094922 64.76460684
 83.64669947 57.35077469 25.86530018 27.40920871 39.51300529 40.11981192
 33.62740166 38.99477317 36.09080116 12.24716418 22.1473227  64.69539437
 41.91259752 11.36714348 27.51478819 32.66469713 37.27473043 24.3496934
 36.89525958 65.03631124 46.04202217 49.75687585 44.99568191 54.13998382
 44.78960838 43.70051763 55.42103191 52.30777437 14.06153636 36.00345443
 42.85704712 37.54577003 35.39270951 42.97232732 39.89965811 38.99220327
 38.5700063  45.29394661 45.51401385 31.29147322 29.12331747 34.95203377
 49.38586109 57.53189149 53.0032555  75.9999578  22.96591865 25.2677284
 35.08659943 39.35228084 32.81273654 44.07632234 37.25798976 39.52522494
 37.39842089 25.88918804 27.00914107 20.60852785 18.43783095 29.59787498
 42.25377807 69.61334289 44.56158807 70.76274397 44.80112898 30.63208174
 25.23908413 41.79179817 46.81000741 54.50644023 77.33534399 85.61420054
 67.14210717 38.14837278 42.02392566 45.06280314 40.19068046 36.33459539
 49.39891477 25.97870528 26.17302217 39.73796743 21.50404377 10.68159413
 38.33400261 12.09508009 14.42406594 23.56779074 22.79213084 24.31633197
 21.64884654 30.71436748 36.10052196 26.89448957 37.60593348 37.95716582
 45.52326981 58.83426515 46.11665317 38.09052441 30.40430282 50.18070028
 42.2206081  65.15742423 58.41726205 52.46921531 63.5502325  53.18967499
 29.62545296 28.72052165 25.48784148 35.89112603 20.01106017 18.26123625
 26.55720372 31.85218956 29.88242538  6.02341501  4.7512895  25.50401296
  9.01877362  9.10125991 19.76152763  8.21298373 24.70184957 44.69372388
 65.95028705 45.07761697 42.3846853  41.44518867 53.99801149 47.18374587
 49.86457961 23.90529762 26.95383366 44.38658026 65.96817566 59.49948001
 54.21771389 53.98773597 60.13705258 56.39497867 52.85462007 46.85157597
 57.17706751 55.8609284  37.25989987 29.60522651 34.17472823 41.45555879
 33.8001449  50.64919944 28.74904622 29.86010435 47.94441618 41.47093385
 25.70171103 52.79841034 58.42230791 63.93039045 42.20722477 31.43567435
 27.89648844 31.52045608 34.82666748 31.46652283 18.84525062 33.25076173
  0.6574349   4.         18.57209386 14.17945364 35.10821637 55.42040008
 53.21203441 39.74744305 45.69995839 57.83493371 53.10000217 43.09929776
 47.12300678]
Pf_by_res [1.54869129e+15 6.43841553e+26 2.15360553e+17 1.04980485e+12
 9.46574006e+06 6.79517751e+12 2.96876504e+14 7.98983831e+10
 8.04844774e+11 1.19657911e+10 7.27515016e+01 2.19784913e+08
 6.72439411e+19 2.00012787e+21 4.94039627e+14 7.00665325e+18
 1.02425136e+06 4.29010165e+08 4.33446277e+13 3.13143209e+06
 1.24298683e+08 2.02009409e+15 1.16307032e+22 2.19487354e+28
 5.54208220e+11 8.52689864e+16 2.16953109e+25 2.89117644e+23
 7.43957430e+17 6.08840486e+16 4.95817000e+18 1.49267298e+21
 1.20206031e+19 8.26873626e+27 2.40290426e+22 3.75796210e+15
 1.54709720e+12 2.49835152e+15 5.51831003e+13 1.10867521e+11
 3.41040848e+07 2.09551142e+13 3.59989917e+20 6.71916035e+25
 8.80915231e+30 1.22115019e+13 1.09831713e+08 1.38558819e+16
 1.72170324e+16 7.96218677e+04 3.43742959e+07 1.03301516e+07
 6.01215626e+13 4.20370772e+08 1.95855476e+05 7.26352827e+11
 1.26699828e+23 2.65053064e+17 6.64765336e+13 6.34588549e+15
 1.83214005e+26 1.14664444e+12 1.83827633e+13 7.98839904e+22
 6.63093150e+12 9.02523903e+05 9.63824855e+16 3.58580302e+23
 4.31404576e+16 1.32745388e+18 8.63748343e+23 5.56396988e+23
 3.69534744e+19 4.46051887e+22 5.15852843e+22 3.29303015e+18
 1.79147070e+22 5.78412017e+19 1.85293868e+18 1.67020125e+19
 9.57771044e+17 2.79034005e+12 2.75829360e+12 2.92079963e+07
 1.58893202e+24 5.10111943e+25 6.06159738e+18 6.58383735e+30
 2.49568819e+19 9.11410067e+10 1.50327558e+09 6.11249589e+13
 9.53093166e+19 3.80270177e+06 7.52665978e+01 3.16939408e+05
 1.45787529e+06 5.61741288e+12 1.54351546e+21 9.91504498e+34
 7.61219663e+20 5.51417615e+26 8.99566856e+09 2.29397145e+10
 8.14479325e+13 4.10200306e+14 2.81346704e+18 1.33940332e+28
 2.12471170e+36 8.07467372e+24 1.71063416e+11 8.01065627e+11
 1.44637252e+17 2.65346237e+17 4.01971241e+14 8.61419719e+16
 4.72101949e+15 2.08389495e+05 4.15393827e+09 1.24983528e+28
 1.59371193e+18 8.64346123e+04 8.90267835e+11 1.53496231e+14
 1.54244518e+16 3.75783305e+10 1.05537705e+16 1.75756379e+28
 9.90367012e+19 4.06571207e+21 3.47837470e+19 3.25608869e+23
 2.83060823e+19 9.52562903e+18 1.17232584e+24 5.21168031e+22
 1.27893257e+06 4.32615013e+15 4.09806721e+18 2.02265001e+16
 2.34886707e+15 4.59880112e+18 2.12912591e+17 8.59208803e+16
 5.63301492e+16 4.68717401e+19 5.84097122e+19 3.88789162e+13
 4.44729635e+12 1.51173405e+15 2.80547856e+21 9.67794188e+24
 1.04477166e+23 1.01475756e+33 9.41828310e+09 9.41098351e+10
 1.72948389e+15 1.23162478e+17 1.77987873e+14 1.38708659e+19
 1.51683855e+16 1.46415512e+17 1.74553204e+16 1.75198954e+11
 5.36934030e+11 8.91599723e+08 1.01729811e+08 7.14815200e+12
 2.24172666e+18 1.70879782e+30 2.25347011e+19 5.39348197e+30
 2.86340712e+19 2.01068514e+13 9.14523707e+10 1.41236626e+18
 2.13465609e+20 4.69727752e+23 3.85756411e+33 1.51975951e+37
 1.44359924e+29 3.69511359e+16 1.78139004e+18 3.71986125e+19
 2.84833290e+17 6.02440664e+15 2.84234046e+21 1.91605666e+11
 2.32701457e+11 1.81125658e+17 2.18316996e+09 4.35469143e+04
 4.44882994e+16 1.78989082e+05 1.83777460e+06 1.71933881e+10
 7.91583355e+09 3.63453448e+10 2.52333313e+09 2.18313360e+13
 4.76713533e+15 4.78771634e+11 2.14807479e+16 3.05202202e+16
 5.89528596e+19 3.55956313e+25 1.06710707e+20 3.48742248e+16
 1.60110915e+13 6.21156779e+21 2.16858834e+18 1.98385442e+28
 2.34581930e+25 6.12478258e+22 3.97663106e+27 1.25887423e+23
 7.34802701e+12 2.97278891e+12 1.17281337e+11 3.86649971e+15
 4.90560991e+08 8.52617289e+07 3.41701613e+11 6.81130237e+13
 9.50106851e+12 4.12986542e+02 1.15733426e+02 1.19193369e+11
 8.25664512e+03 8.96658265e+03 3.82227916e+08 3.68853164e+03
 5.34412934e+10 2.57180274e+19 4.38374966e+28 3.77537682e+19
 2.55525910e+18 9.98657895e+17 2.82512992e+23 3.10199054e+20
 4.52805578e+21 2.40956610e+10 5.08043878e+11 1.89167653e+19
 4.46287445e+28 6.92302411e+25 3.51928114e+23 2.79624889e+23
 1.30975508e+26 3.10476005e+24 9.00471221e+22 2.22526078e+20
 6.78711036e+24 1.82009040e+24 1.51973866e+16 7.20089551e+12
 6.94857726e+14 1.00906798e+18 4.77767296e+14 9.92356750e+21
 3.05880741e+12 9.29134415e+12 6.63736020e+20 1.02470234e+18
 1.45248372e+11 8.51252235e+22 2.35768589e+25 5.81588485e+27
 2.13975876e+18 4.49096741e+13 1.30404025e+12 4.88832578e+13
 1.33361204e+15 4.63166597e+13 1.52893265e+08 2.75817831e+14
 1.92983575e+00 5.45981500e+01 1.16347721e+08 1.43899231e+06
 1.76727706e+15 1.17158537e+24 1.28733897e+23 1.82850094e+17
 7.03460558e+19 1.31036587e+25 1.15090091e+23 5.22140269e+18
 2.91918632e+20]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [2.64745947e-11 5.80784710e-24 2.08750737e-14 2.40816146e-10
 4.04240295e-04 6.17438022e-10 2.45594339e-12 1.23099471e-08
 4.14077898e-10 4.84008246e-08 7.42937388e+01 1.44809248e-05
 3.05591322e-17 9.36993146e-19 4.06473645e-12 4.75645676e-17
 6.49213628e-04 1.09730307e-05 2.43141392e-10 1.11442585e-03
 3.00834506e-05 1.89418581e-12 3.21505350e-20 1.41704836e-25
 1.65623222e-09 4.09263559e-14 1.19241738e-22 6.04950137e-21
 3.24523455e-15 2.61993582e-14 2.02989121e-16 8.29525047e-19
 3.11077011e-17 9.02308476e-26 1.38694012e-20 1.89601505e-13
 8.38062823e-10 3.27446711e-13 2.40429681e-11 2.93758092e-09
 1.86203473e-05 1.20643561e-10 2.27249974e-18 4.84706865e-24
 4.34370234e-28 5.97069790e-11 4.80912892e-05 3.02802882e-13
 1.30868728e-13 1.15282087e-02 6.40560830e-06 6.43705889e-05
 4.20497985e-11 2.50704278e-06 3.63796453e-03 3.17428959e-09
 4.16886807e-21 7.75284944e-16 2.75502669e-11 2.13944903e-13
 5.12667171e-24 1.42352601e-09 1.14388768e-10 8.32404512e-21
 9.14575651e-11 1.01703402e-03 8.68552485e-15 1.89761345e-21
 3.29540981e-14 2.51058389e-16 5.20483480e-22 2.07687045e-21
 4.31657110e-17 3.41514223e-20 8.51664114e-21 2.01928895e-16
 8.70130650e-20 1.44729437e-17 2.01805562e-16 1.44552422e-17
 7.97136092e-16 7.03294212e-10 9.59740203e-10 2.27662977e-05
 6.04907348e-22 7.50116442e-24 5.01426281e-17 6.22751931e-28
 1.80137384e-16 1.59617445e-08 5.56872247e-06 1.72415218e-10
 1.52636648e-17 2.90203008e-04 1.43282085e+01 5.15012694e-03
 7.06437594e-04 9.40281369e-11 3.92901054e-19 9.04689383e-33
 1.41672050e-18 1.51814600e-23 9.30595034e-08 3.64927144e-07
 4.38443980e-11 4.89551286e-12 6.07508480e-16 8.62745702e-26
 2.85426418e-33 1.11088523e-22 6.45114845e-09 1.09427400e-08
 2.83474510e-14 7.56800208e-15 6.00619176e-12 9.06941694e-15
 1.61718008e-13 3.34132219e-03 2.47932888e-07 1.27626658e-25
 1.31942391e-15 2.27042148e-02 2.53089130e-09 3.21141520e-11
 6.83257546e-13 9.28659903e-08 1.07000688e-13 2.74083623e-26
 1.68654530e-17 1.52636204e-18 2.96085960e-17 2.75484996e-21
 7.09437940e-17 2.15725017e-16 4.30274726e-21 6.39464461e-20
 4.42533883e-04 1.11350608e-13 3.98304396e-16 9.92826672e-14
 6.19349424e-13 4.07520582e-16 2.31522303e-15 9.09275440e-15
 2.19812950e-14 1.87017867e-17 6.40190331e-18 2.30717229e-11
 3.50508138e-10 1.83365987e-12 8.80617320e-19 3.60587915e-23
 8.99027129e-21 3.43899765e-30 7.06028831e-08 7.39876381e-08
 2.37070575e-12 7.80397301e-15 1.91603643e-11 9.78792433e-17
 9.37248639e-14 2.27618255e-15 4.47575549e-14 8.69486150e-09
 3.65488104e-09 1.96166233e-06 7.67972976e-05 6.14611096e-10
 5.78377674e-16 5.88983996e-28 5.12793338e-17 1.35183892e-27
 1.33632187e-16 1.14670078e-10 9.15375339e-08 3.82689760e-15
 7.82467414e-18 4.27511653e-21 2.99558070e-31 3.99042642e-34
 7.30041469e-26 6.38508058e-14 4.38566198e-15 6.49033980e-17
 1.54242277e-14 4.39420080e-13 2.56518139e-19 2.69392703e-08
 1.03751665e-08 3.84427282e-14 2.59242755e-07 5.17412349e-02
 2.48055220e-13 3.01972668e-02 2.28297908e-04 4.86892078e-08
 1.92440964e-07 1.07732164e-07 2.63523643e-07 2.84258766e-11
 3.42402318e-13 3.10932248e-09 6.46762422e-14 2.87214600e-14
 4.49044420e-17 9.80386849e-23 1.10811843e-17 1.28910892e-14
 4.87947657e-11 6.01995088e-20 4.33128796e-16 4.52151917e-26
 7.80727758e-23 7.17304408e-21 5.16748089e-26 7.12544241e-21
 3.44051485e-10 8.70222094e-10 6.97533817e-08 1.36608019e-13
 1.82852611e-06 1.10164088e-05 1.31567053e-08 3.30798869e-11
 1.64067185e-10 1.76546161e+00 1.02172817e+01 1.57232414e-08
 1.84497531e-01 2.34513161e-01 6.61411551e-07 1.84476336e-01
 3.27278305e-08 6.80074549e-17 1.78216714e-25 1.43164015e-16
 1.64194737e-16 1.71150210e-16 2.05000892e-21 3.32011945e-18
 4.04466361e-19 5.38090509e-08 3.52284033e-10 5.32043697e-17
 2.10464818e-26 1.87282989e-23 3.68417468e-21 1.72273452e-21
 2.85498667e-24 5.02072156e-23 2.38959521e-20 2.98822478e-18
 2.14342981e-23 1.26678005e-21 1.74190821e-13 1.39767974e-10
 5.90062868e-12 6.58982299e-16 2.05862752e-12 7.34727593e-20
 3.52567311e-10 5.68480576e-11 6.32118923e-19 1.07695225e-15
 1.23220483e-09 2.35904329e-20 4.57412714e-23 2.68026896e-25

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
    Bc    Bh          calc_name
0  2.0  0.35  train_cluster_2_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2/Benchmark/cluster_2_Sp_res_neighbours/20240402-191902_analysis.csv
dict_keys(['cluster_2_Sp_res_neighbours'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2_Sp_res_neighbours to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2_Sp_res_neighbours/cluster_2_Sp_res_neighbours0_1712081942.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2_Sp_res_neighbours': {'train_dfs': [    0.0      0.5      5.0  peptide          calc_name
0   0.0  0.00000  0.00000       21  train_cluster_2_1
1   0.0  0.00000  0.00000       22  train_cluster_2_1
2   0.0  0.00000  0.00000       23  train_cluster_2_1
3   0.0  0.00000  0.00001       24  train_cluster_2_1
4   0.0  0.00000  0.00001       25  train_cluster_2_1
5   0.0  0.00000  0.00001       27  train_cluster_2_1
6   0.0  0.00086  0.00840       33  train_cluster_2_1
7   0.0  0.00057  0.00560       34  train_cluster_2_1
8   0.0  0.00006  0.00056       35  train_cluster_2_1
9   0.0  0.00007  0.00072       36  train_cluster_2_1
10  0.0  0.00008  0.00085       37  train_cluster_2_1
11  0.0  0.00007  0.00072       38  train_cluster_2_1
12  0.0  0.00006  0.00056       39  train_cluster_2_1
13  0.0  0.00005  0.00051       40  train_cluster_2_1
14  0.0  0.00003  0.00027       41  train_cluster_2_1
15  0.0  0.00000  0.00000       42  train_cluster_2_1
16  0.0  0.00000  0.00000       43  train_cluster_2_1
17  0.0  0.00000  0.00000       44  train_cluster_2_1
18  0.0  0.00000  0.00000       45  train_cluster_2_1
19  0.0  0.00000  0.00001       46  train_cluster_2_1
20  0.0  0.00000  0.00001       47  train_cluster_2_1
21  0.0  0.00000  0.00001       48  train_cluster_2_1
22  0.0  0.14313  0.14699       49  train_cluster_2_1
23  0.0  0.00049  0.00482       50  train_cluster_2_1
24  0.0  0.00000  0.00000       51  train_cluster_2_1
25  0.0  0.00000  0.00000       52  train_cluster_2_1
26  0.0  0.00000  0.00000       53  train_cluster_2_1
27  0.0  0.00076  0.00729       54  train_cluster_2_1
28  0.0  0.00072  0.00688       55  train_cluster_2_1
29  0.0  0.00062  0.00590       56  train_cluster_2_1
30  0.0  0.00002  0.00016       58  train_cluster_2_1
31  0.0  0.00001  0.00010       59  train_cluster_2_1
32  0.0  0.15105  0.31019       89  train_cluster_2_1
33  0.0  0.13943  0.28633       90  train_cluster_2_1
34  0.0  0.12084  0.24815       91  train_cluster_2_1], 'val_dfs': [    0.0      0.5      5.0  peptide        calc_name
0   0.0  0.00003  0.00034        0  val_cluster_2_1
1   0.0  0.09091  0.09092        1  val_cluster_2_1
2   0.0  0.07145  0.07166        2  val_cluster_2_1
3   0.0  0.05561  0.05605        3  val_cluster_2_1
4   0.0  0.10000  0.10001        4  val_cluster_2_1
5   0.0  0.07695  0.07717        5  val_cluster_2_1
6   0.0  0.05888  0.05935        6  val_cluster_2_1
7   0.0  0.11111  0.11112        7  val_cluster_2_1
8   0.0  0.09094  0.09120        8  val_cluster_2_1
9   0.0  0.08336  0.08360        9  val_cluster_2_1
10  0.0  0.06673  0.06726       10  val_cluster_2_1
11  0.0  0.06256  0.06306       11  val_cluster_2_1
12  0.0  0.14286  0.14287       12  val_cluster_2_1
13  0.0  0.11115  0.11147       13  val_cluster_2_1
14  0.0  0.10003  0.10032       14  val_cluster_2_1
15  0.0  0.08341  0.08408       15  val_cluster_2_1
16  0.0  0.07149  0.07207       16  val_cluster_2_1
17  0.0  0.00010  0.00096       17  val_cluster_2_1
18  0.0  0.00000  0.00000       18  val_cluster_2_1
19  0.0  0.00000  0.00000       19  val_cluster_2_1
20  0.0  0.00000  0.00000       20  val_cluster_2_1
21  0.0  0.00000  0.00004       26  val_cluster_2_1
22  0.0  0.00000  0.00004       28  val_cluster_2_1
23  0.0  0.00033  0.00322       29  val_cluster_2_1
24  0.0  0.00063  0.00613       30  val_cluster_2_1
25  0.0  0.00046  0.00450       31  val_cluster_2_1
26  0.0  0.00049  0.00482       32  val_cluster_2_1
27  0.0  0.00001  0.00009       57  val_cluster_2_1
28  0.0  0.00001  0.00009       60  val_cluster_2_1
29  0.0  0.00001  0.00009       61  val_cluster_2_1
30  0.0  0.00001  0.00011       62  val_cluster_2_1
31  0.0  0.00001  0.00012       63  val_cluster_2_1
32  0.0  0.00000  0.00000       64  val_cluster_2_1
33  0.0  0.00000  0.00000       65  val_cluster_2_1
34  0.0  0.00000  0.00000       66  val_cluster_2_1
35  0.0  0.00000  0.00000       67  val_cluster_2_1
36  0.0  0.00000  0.00000       68  val_cluster_2_1
37  0.0  0.00000  0.00000       69  val_cluster_2_1
38  0.0  0.00000  0.00003       70  val_cluster_2_1
39  0.0  0.00000  0.00002       71  val_cluster_2_1
40  0.0  0.00000  0.00005       72  val_cluster_2_1
41  0.0  0.00000  0.00002       73  val_cluster_2_1
42  0.0  0.00000  0.00002       74  val_cluster_2_1
43  0.0  0.00000  0.00002       75  val_cluster_2_1
44  0.0  0.00000  0.00000       76  val_cluster_2_1
45  0.0  0.00000  0.00000       77  val_cluster_2_1
46  0.0  0.00472  0.04329       78  val_cluster_2_1
47  0.0  0.00000  0.00000       79  val_cluster_2_1
48  0.0  0.00000  0.00000       80  val_cluster_2_1
49  0.0  0.00000  0.00001       81  val_cluster_2_1
50  0.0  0.00000  0.00001       82  val_cluster_2_1
51  0.0  0.00000  0.00000       83  val_cluster_2_1
52  0.0  0.00000  0.00001       84  val_cluster_2_1
53  0.0  0.00000  0.00001       85  val_cluster_2_1
54  0.0  0.00000  0.00001       86  val_cluster_2_1
55  0.0  0.00000  0.00001       87  val_cluster_2_1
56  0.0  0.00000  0.00001       88  val_cluster_2_1
57  0.0  0.10070  0.20679       92  val_cluster_2_1
58  0.0  0.00000  0.00000       93  val_cluster_2_1
59  0.0  0.00000  0.00000       94  val_cluster_2_1
60  0.0  0.00000  0.00000       95  val_cluster_2_1
61  0.0  0.00000  0.00000       96  val_cluster_2_1
62  0.0  0.00000  0.00000       97  val_cluster_2_1
63  0.0  0.00000  0.00000       98  val_cluster_2_1
64  0.0  0.10528  0.10547       99  val_cluster_2_1
65  0.0  0.11113  0.11133      100  val_cluster_2_1
66  0.0  0.10528  0.10547      101  val_cluster_2_1
67  0.0  0.12502  0.12525      102  val_cluster_2_1
68  0.0  0.11767  0.11788      103  val_cluster_2_1
69  0.0  0.10002  0.10020      104  val_cluster_2_1
70  0.0  0.13336  0.13360      105  val_cluster_2_1
71  0.0  0.11113  0.11133      106  val_cluster_2_1
72  0.0  0.11767  0.11788      107  val_cluster_2_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                            name split_type
0    cluster_2_Sp_res_neighbours         Sp
1    cluster_2_Sp_res_neighbours         Sp
2    cluster_2_Sp_res_neighbours         Sp
3    cluster_2_Sp_res_neighbours         Sp
4    cluster_2_Sp_res_neighbours         Sp
5    cluster_2_Sp_res_neighbours         Sp
6    cluster_2_Sp_res_neighbours         Sp
7    cluster_2_Sp_res_neighbours         Sp
8    cluster_2_Sp_res_neighbours         Sp
9    cluster_2_Sp_res_neighbours         Sp
10   cluster_2_Sp_res_neighbours         Sp
11   cluster_2_Sp_res_neighbours         Sp
12   cluster_2_Sp_res_neighbours         Sp
13   cluster_2_Sp_res_neighbours         Sp
14   cluster_2_Sp_res_neighbours         Sp
15   cluster_2_Sp_res_neighbours         Sp
16   cluster_2_Sp_res_neighbours         Sp
17   cluster_2_Sp_res_neighbours         Sp
18   cluster_2_Sp_res_neighbours         Sp
19   cluster_2_Sp_res_neighbours         Sp
20   cluster_2_Sp_res_neighbours         Sp
21   cluster_2_Sp_res_neighbours         Sp
22   cluster_2_Sp_res_neighbours         Sp
23   cluster_2_Sp_res_neighbours         Sp
24   cluster_2_Sp_res_neighbours         Sp
25   cluster_2_Sp_res_neighbours         Sp
26   cluster_2_Sp_res_neighbours         Sp
27   cluster_2_Sp_res_neighbours         Sp
28   cluster_2_Sp_res_neighbours         Sp
29   cluster_2_Sp_res_neighbours         Sp
30   cluster_2_Sp_res_neighbours         Sp
31   cluster_2_Sp_res_neighbours         Sp
32   cluster_2_Sp_res_neighbours         Sp
33   cluster_2_Sp_res_neighbours         Sp
34   cluster_2_Sp_res_neighbours         Sp
35   cluster_2_Sp_res_neighbours         Sp
36   cluster_2_Sp_res_neighbours         Sp
37   cluster_2_Sp_res_neighbours         Sp
38   cluster_2_Sp_res_neighbours         Sp
39   cluster_2_Sp_res_neighbours         Sp
40   cluster_2_Sp_res_neighbours         Sp
41   cluster_2_Sp_res_neighbours         Sp
42   cluster_2_Sp_res_neighbours         Sp
43   cluster_2_Sp_res_neighbours         Sp
44   cluster_2_Sp_res_neighbours         Sp
45   cluster_2_Sp_res_neighbours         Sp
46   cluster_2_Sp_res_neighbours         Sp
47   cluster_2_Sp_res_neighbours         Sp
48   cluster_2_Sp_res_neighbours         Sp
49   cluster_2_Sp_res_neighbours         Sp
50   cluster_2_Sp_res_neighbours         Sp
51   cluster_2_Sp_res_neighbours         Sp
52   cluster_2_Sp_res_neighbours         Sp
53   cluster_2_Sp_res_neighbours         Sp
54   cluster_2_Sp_res_neighbours         Sp
55   cluster_2_Sp_res_neighbours         Sp
56   cluster_2_Sp_res_neighbours         Sp
57   cluster_2_Sp_res_neighbours         Sp
58   cluster_2_Sp_res_neighbours         Sp
59   cluster_2_Sp_res_neighbours         Sp
60   cluster_2_Sp_res_neighbours         Sp
61   cluster_2_Sp_res_neighbours         Sp
62   cluster_2_Sp_res_neighbours         Sp
63   cluster_2_Sp_res_neighbours         Sp
64   cluster_2_Sp_res_neighbours         Sp
65   cluster_2_Sp_res_neighbours         Sp
66   cluster_2_Sp_res_neighbours         Sp
67   cluster_2_Sp_res_neighbours         Sp
68   cluster_2_Sp_res_neighbours         Sp
69   cluster_2_Sp_res_neighbours         Sp
70   cluster_2_Sp_res_neighbours         Sp
71   cluster_2_Sp_res_neighbours         Sp
72   cluster_2_Sp_res_neighbours         Sp
73   cluster_2_Sp_res_neighbours         Sp
74   cluster_2_Sp_res_neighbours         Sp
75   cluster_2_Sp_res_neighbours         Sp
76   cluster_2_Sp_res_neighbours         Sp
77   cluster_2_Sp_res_neighbours         Sp
78   cluster_2_Sp_res_neighbours         Sp
79   cluster_2_Sp_res_neighbours         Sp
80   cluster_2_Sp_res_neighbours         Sp
81   cluster_2_Sp_res_neighbours         Sp
82   cluster_2_Sp_res_neighbours         Sp
83   cluster_2_Sp_res_neighbours         Sp
84   cluster_2_Sp_res_neighbours         Sp
85   cluster_2_Sp_res_neighbours         Sp
86   cluster_2_Sp_res_neighbours         Sp
87   cluster_2_Sp_res_neighbours         Sp
88   cluster_2_Sp_res_neighbours         Sp
89   cluster_2_Sp_res_neighbours         Sp
90   cluster_2_Sp_res_neighbours         Sp
91   cluster_2_Sp_res_neighbours         Sp
92   cluster_2_Sp_res_neighbours         Sp
93   cluster_2_Sp_res_neighbours         Sp
94   cluster_2_Sp_res_neighbours         Sp
95   cluster_2_Sp_res_neighbours         Sp
96   cluster_2_Sp_res_neighbours         Sp
97   cluster_2_Sp_res_neighbours         Sp
98   cluster_2_Sp_res_neighbours         Sp
99   cluster_2_Sp_res_neighbours         Sp
100  cluster_2_Sp_res_neighbours         Sp
101  cluster_2_Sp_res_neighbours         Sp
102  cluster_2_Sp_res_neighbours         Sp
103  cluster_2_Sp_res_neighbours         Sp
104  cluster_2_Sp_res_neighbours         Sp
105  cluster_2_Sp_res_neighbours         Sp
106  cluster_2_Sp_res_neighbours         Sp
107  cluster_2_Sp_res_neighbours         Sp  , 'merge_df':      0.0      0.5      5.0  peptide          calc_name  \
0    0.0  0.41879  0.44438        0       Experimental
1    0.0  0.37096  0.45204        1       Experimental
2    0.0  0.40040  0.48544        2       Experimental
3    0.0  0.45875  0.51503        3       Experimental
4    0.0  0.41726  0.49519        4       Experimental
5    0.0  0.44176  0.50927        5       Experimental
6    0.0  0.48987  0.54090        6       Experimental
7    0.0  0.41316  0.48254        7       Experimental
8    0.0  0.46617  0.51066        8       Experimental
9    0.0  0.46825  0.52028        9       Experimental
10   0.0  0.48273  0.53102       10       Experimental
11   0.0  0.50258  0.53988       11       Experimental
12   0.0  0.47373  0.50144       12       Experimental
13   0.0  0.52057  0.54102       13       Experimental
14   0.0  0.52823  0.55640       14       Experimental
15   0.0  0.55802  0.57504       15       Experimental
16   0.0  0.55641  0.57196       16       Experimental
17   0.0  0.52928  0.54827       17       Experimental
18   0.0  0.17163  0.27883       18       Experimental
19   0.0  0.16883  0.28686       19       Experimental
20   0.0  0.16341  0.27353       20       Experimental
21   0.0  0.32309  0.41205       21       Experimental
22   0.0  0.31355  0.39928       22       Experimental
23   0.0  0.34392  0.42213       23       Experimental
24   0.0  0.35604  0.35617       24       Experimental
25   0.0  0.34105  0.35125       25       Experimental
26   0.0  0.34135  0.38830       26       Experimental
27   0.0  0.28512  0.29602       27       Experimental
28   0.0  0.28439  0.33185       28       Experimental
29   0.0  0.32954  0.39085       29       Experimental
30   0.0  0.26192  0.34619       30       Experimental
31   0.0  0.31421  0.37857       31       Experimental
32   0.0  0.32314  0.38565       32       Experimental
33   0.0  0.29666  0.37860       33       Experimental
34   0.0  0.38440  0.44775       34       Experimental
35   0.0  0.33633  0.46390       35       Experimental
36   0.0  0.34716  0.45807       36       Experimental
37   0.0  0.34165  0.44393       37       Experimental
38   0.0  0.30725  0.43533       38       Experimental
39   0.0  0.33252  0.48976       39       Experimental
40   0.0  0.28369  0.42940       40       Experimental
41   0.0  0.35906  0.50293       41       Experimental
42   0.0  0.33575  0.45181       42       Experimental
43   0.0  0.33443  0.43697       43       Experimental
44   0.0  0.37082  0.47284       44       Experimental
45   0.0  0.37847  0.48848       45       Experimental
46   0.0  0.22218  0.31040       46       Experimental
47   0.0  0.18217  0.28305       47       Experimental
48   0.0  0.25719  0.37045       48       Experimental
49   0.0  0.49756  0.50850       49       Experimental
50   0.0  0.55024  0.54326       50       Experimental
51   0.0  0.24310  0.29208       51       Experimental
52   0.0  0.19173  0.23972       52       Experimental
53   0.0  0.18105  0.23003       53       Experimental
54   0.0  0.26140  0.30267       54       Experimental
55   0.0  0.26392  0.30614       55       Experimental
56   0.0  0.26061  0.32801       56       Experimental
57   0.0  0.45297  0.53974       57       Experimental
58   0.0  0.31622  0.45372       58       Experimental
59   0.0  0.43711  0.52972       59       Experimental
60   0.0  0.47628  0.54735       60       Experimental
61   0.0  0.49249  0.57156       61       Experimental
62   0.0  0.50341  0.53212       62       Experimental
63   0.0  0.53500  0.53827       63       Experimental
64   0.0  0.26524  0.35365       64       Experimental
65   0.0  0.25454  0.32548       65       Experimental
66   0.0  0.25152  0.35786       66       Experimental
67   0.0  0.28164  0.36568       67       Experimental
68   0.0  0.24177  0.30174       68       Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
conda run -n HDXER_ENV python /home/alexi/Documents/HDXer/HDXer/calc_hdx.py -t /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/HOIPapo_test_mean1_reclustered_csize2_10_.xtc -p /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo697_af_sample_1000_protonated.pdb -m BestVendruscolo -log /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/calc_hdx_prep_cluster_2+BV0_0.log -out /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0 -seg /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_APO_segs.txt -mopt "{ 'save_detailed' : True }" --times 0 0.5 5.0 -str 1
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
Residue predictions complete

Running r split mode
envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/mdtraj/formats/pdb/pdbfile.py:200: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
/home/alexi/Documents/HDXer/HDXer/dfpred.py:505: RuntimeWarning: divide by zero encountered in log
  logerr = logf + np.log(err) + np.log(time) # sd(e^Aa) = f * sd(A) * a
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

Experiment name cluster_2+BV_r_naive_random already exists. Attempting to change name to cluster_2+BV_r_naive_random0
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN  cluster_2+BV

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
Running VDX loop
Random seeds: [42]
Randomly splitting segments for cluster_2+BV with random seed 42 and train fraction 0.5
train_segs
    ResStr  ResEnd  peptide             calc_name
77     196     208       77  train_cluster_2+BV_1
10       8      24       10  train_cluster_2+BV_1
4        7      18        4  train_cluster_2+BV_1
83     247     260       83  train_cluster_2+BV_1
62     154     169       62  train_cluster_2+BV_1
Saved train cluster_2+BV_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/train_residue_segs__cluster_2+BV_.txt
Train Peptide numbers: [  0   4   5   7   9  10  11  12  15  16  18  19  22  26  27  28  30  31
  33  34  35  36  39  40  42  43  44  45  47  53  55  56  62  64  65  66
  67  69  72  76  77  78  79  80  81  83  88  89  90  95 100 103 106 107]
Saved val cluster_2+BV_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/val_residue_segs__cluster_2+BV_.txt
Val Peptide numbers: [  1   2   3   6   8  13  14  17  20  21  23  24  25  29  32  37  38  41
  46  48  49  50  51  52  54  57  58  59  60  61  63  68  70  71  73  74
  75  82  84  85  86  87  91  92  93  94  96  97  98  99 101 102 104 105]
train_HDX_data
    0.0      0.5      5.0  peptide             calc_name  \
0   0.0  0.13267  0.18143       77  train_cluster_2+BV_1
1   0.0  0.48273  0.53102       10  train_cluster_2+BV_1
2   0.0  0.41726  0.49519        4  train_cluster_2+BV_1
3   0.0  0.08147  0.13526       83  train_cluster_2+BV_1
4   0.0  0.50341  0.53212       62  train_cluster_2+BV_1
5   0.0  0.28164  0.36568       67  train_cluster_2+BV_1
6   0.0  0.26192  0.34619       30  train_cluster_2+BV_1
7   0.0  0.37847  0.48848       45  train_cluster_2+BV_1
8   0.0  0.04358  0.04371       95  train_cluster_2+BV_1
9   0.0  0.50258  0.53988       11  train_cluster_2+BV_1
10  0.0  0.05688  0.07274       81  train_cluster_2+BV_1
11  0.0  0.20249  0.21472       79  train_cluster_2+BV_1
12  0.0  0.41879  0.44438        0  train_cluster_2+BV_1
13  0.0  0.16260  0.17496       80  train_cluster_2+BV_1
14  0.0  0.17163  0.27883       18  train_cluster_2+BV_1
15  0.0  0.27969  0.36567       69  train_cluster_2+BV_1
16  0.0  0.26061  0.32801       56  train_cluster_2+BV_1
17  0.0  0.11684  0.15140       76  train_cluster_2+BV_1
18  0.0  0.22454  0.24966      106  train_cluster_2+BV_1
19  0.0  0.33575  0.45181       42  train_cluster_2+BV_1
20  0.0  0.47373  0.50144       12  train_cluster_2+BV_1
21  0.0  0.34716  0.45807       36  train_cluster_2+BV_1
22  0.0  0.26524  0.35365       64  train_cluster_2+BV_1
23  0.0  0.34135  0.38830       26  train_cluster_2+BV_1
24  0.0  0.31355  0.39928       22  train_cluster_2+BV_1
25  0.0  0.31421  0.37857       31  train_cluster_2+BV_1
26  0.0  0.18217  0.28305       47  train_cluster_2+BV_1
27  0.0  0.20729  0.23030      100  train_cluster_2+BV_1
28  0.0  0.55802  0.57504       15  train_cluster_2+BV_1
29  0.0  0.37082  0.47284       44  train_cluster_2+BV_1
30  0.0  0.10385  0.19651       88  train_cluster_2+BV_1
31  0.0  0.53877  0.49943       89  train_cluster_2+BV_1
32  0.0  0.46825  0.52028        9  train_cluster_2+BV_1
33  0.0  0.29666  0.37860       33  train_cluster_2+BV_1
34  0.0  0.26392  0.30614       55  train_cluster_2+BV_1
35  0.0  0.21731  0.24442      103  train_cluster_2+BV_1
36  0.0  0.28439  0.33185       28  train_cluster_2+BV_1
37  0.0  0.28369  0.42940       40  train_cluster_2+BV_1
38  0.0  0.44176  0.50927        5  train_cluster_2+BV_1
39  0.0  0.18105  0.23003       53  train_cluster_2+BV_1
40  0.0  0.23913  0.27068      107  train_cluster_2+BV_1
41  0.0  0.33252  0.48976       39  train_cluster_2+BV_1
42  0.0  0.33633  0.46390       35  train_cluster_2+BV_1
43  0.0  0.55641  0.57196       16  train_cluster_2+BV_1
44  0.0  0.35203  0.42601       78  train_cluster_2+BV_1
45  0.0  0.38440  0.44775       34  train_cluster_2+BV_1
46  0.0  0.25152  0.35786       66  train_cluster_2+BV_1
47  0.0  0.41316  0.48254        7  train_cluster_2+BV_1
48  0.0  0.33443  0.43697       43  train_cluster_2+BV_1
49  0.0  0.25454  0.32548       65  train_cluster_2+BV_1
50  0.0  0.36820  0.37879       72  train_cluster_2+BV_1
51  0.0  0.28512  0.29602       27  train_cluster_2+BV_1
52  0.0  0.16883  0.28686       19  train_cluster_2+BV_1
53  0.0  0.51417  0.47866       90  train_cluster_2+BV_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     196     208
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      24
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      18
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     260
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     154     169
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     186
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      61
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...      89      97
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...     308     315
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      25
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     247     257
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     238
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       1       7
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     224     239
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      32
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     171     186
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     153
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     194     208
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     338     360
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      85      97
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      18
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      76      84
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     169     183
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      51
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      34      40
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      65
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     106
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     334     356
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      23
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      88      97
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     253     260
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     275
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      21
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      61
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     132     150
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     336     357
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      51
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      88
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      21
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     121     132
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     339     360
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      87
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      74      84
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      25
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     213     223
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      65
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     185
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      18
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      86      97
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     170     183
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     187     195
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      49
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      33
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     261     276
    ResStr  ResEnd  0.0      0.5      5.0  peptide             calc_name  \
0      196     208  0.0  0.13267  0.18143       77  train_cluster_2+BV_1
1        8      24  0.0  0.48273  0.53102       10  train_cluster_2+BV_1
2        7      18  0.0  0.41726  0.49519        4  train_cluster_2+BV_1
3      247     260  0.0  0.08147  0.13526       83  train_cluster_2+BV_1
4      154     169  0.0  0.50341  0.53212       62  train_cluster_2+BV_1
5      170     186  0.0  0.28164  0.36568       67  train_cluster_2+BV_1
6       49      61  0.0  0.26192  0.34619       30  train_cluster_2+BV_1
7       89      97  0.0  0.37847  0.48848       45  train_cluster_2+BV_1
8      308     315  0.0  0.04358  0.04371       95  train_cluster_2+BV_1
9        8      25  0.0  0.50258  0.53988       11  train_cluster_2+BV_1
10     247     257  0.0  0.05688  0.07274       81  train_cluster_2+BV_1
11     224     238  0.0  0.20249  0.21472       79  train_cluster_2+BV_1
12       1       7  0.0  0.41879  0.44438        0  train_cluster_2+BV_1
13     224     239  0.0  0.16260  0.17496       80  train_cluster_2+BV_1
14      26      32  0.0  0.17163  0.27883       18  train_cluster_2+BV_1
15     171     186  0.0  0.27969  0.36567       69  train_cluster_2+BV_1
16     132     153  0.0  0.26061  0.32801       56  train_cluster_2+BV_1
17     194     208  0.0  0.11684  0.15140       76  train_cluster_2+BV_1
18     338     360  0.0  0.22454  0.24966      106  train_cluster_2+BV_1
19      85      97  0.0  0.33575  0.45181       42  train_cluster_2+BV_1
20      11      18  0.0  0.47373  0.50144       12  train_cluster_2+BV_1
21      76      84  0.0  0.34716  0.45807       36  train_cluster_2+BV_1
22     169     183  0.0  0.26524  0.35365       64  train_cluster_2+BV_1
23      41      51  0.0  0.34135  0.38830       26  train_cluster_2+BV_1
24      34      40  0.0  0.31355  0.39928       22  train_cluster_2+BV_1
25      49      65  0.0  0.31421  0.37857       31  train_cluster_2+BV_1
26      98     106  0.0  0.18217  0.28305       47  train_cluster_2+BV_1
27     334     356  0.0  0.20729  0.23030      100  train_cluster_2+BV_1
28      11      23  0.0  0.55802  0.57504       15  train_cluster_2+BV_1
29      88      97  0.0  0.37082  0.47284       44  train_cluster_2+BV_1
30     253     260  0.0  0.10385  0.19651       88  train_cluster_2+BV_1
31     261     275  0.0  0.53877  0.49943       89  train_cluster_2+BV_1
32       8      21  0.0  0.46825  0.52028        9  train_cluster_2+BV_1
33      52      61  0.0  0.29666  0.37860       33  train_cluster_2+BV_1
34     132     150  0.0  0.26392  0.30614       55  train_cluster_2+BV_1
35     336     357  0.0  0.21731  0.24442      103  train_cluster_2+BV_1
36      42      51  0.0  0.28439  0.33185       28  train_cluster_2+BV_1
37      77      88  0.0  0.28369  0.42940       40  train_cluster_2+BV_1
38       7      21  0.0  0.44176  0.50927        5  train_cluster_2+BV_1
39     121     132  0.0  0.18105  0.23003       53  train_cluster_2+BV_1
40     339     360  0.0  0.23913  0.27068      107  train_cluster_2+BV_1
41      77      87  0.0  0.33252  0.48976       39  train_cluster_2+BV_1
42      74      84  0.0  0.33633  0.46390       35  train_cluster_2+BV_1
43      11      25  0.0  0.55641  0.57196       16  train_cluster_2+BV_1
44     213     223  0.0  0.35203  0.42601       78  train_cluster_2+BV_1
45      52      65  0.0  0.38440  0.44775       34  train_cluster_2+BV_1
46     170     185  0.0  0.25152  0.35786       66  train_cluster_2+BV_1
47       8      18  0.0  0.41316  0.48254        7  train_cluster_2+BV_1
48      86      97  0.0  0.33443  0.43697       43  train_cluster_2+BV_1
49     170     183  0.0  0.25454  0.32548       65  train_cluster_2+BV_1
50     187     195  0.0  0.36820  0.37879       72  train_cluster_2+BV_1
51      42      49  0.0  0.28512  0.29602       27  train_cluster_2+BV_1
52      26      33  0.0  0.16883  0.28686       19  train_cluster_2+BV_1
53     261     276  0.0  0.51417  0.47866       90  train_cluster_2+BV_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train cluster_2+BV HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/train_cluster_2+BV_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide           calc_name  \
0        6      18  0.0  0.37096  0.45204        1  val_cluster_2+BV_1
1        6      21  0.0  0.40040  0.48544        2  val_cluster_2+BV_1
2        6      25  0.0  0.45875  0.51503        3  val_cluster_2+BV_1
3        7      25  0.0  0.48987  0.54090        6  val_cluster_2+BV_1
4        8      20  0.0  0.46617  0.51066        8  val_cluster_2+BV_1
5       11      20  0.0  0.52057  0.54102       13  val_cluster_2+BV_1
6       11      21  0.0  0.52823  0.55640       14  val_cluster_2+BV_1
7       19      25  0.0  0.52928  0.54827       17  val_cluster_2+BV_1
8       27      33  0.0  0.16341  0.27353       20  val_cluster_2+BV_1
9       33      40  0.0  0.32309  0.41205       21  val_cluster_2+BV_1
10      34      41  0.0  0.34392  0.42213       23  val_cluster_2+BV_1
11      41      48  0.0  0.35604  0.35617       24  val_cluster_2+BV_1
12      41      49  0.0  0.34105  0.35125       25  val_cluster_2+BV_1
13      42      65  0.0  0.32954  0.39085       29  val_cluster_2+BV_1
14      50      65  0.0  0.32314  0.38565       32  val_cluster_2+BV_1
15      77      84  0.0  0.34165  0.44393       37  val_cluster_2+BV_1
16      77      85  0.0  0.30725  0.43533       38  val_cluster_2+BV_1
17      77      97  0.0  0.35906  0.50293       41  val_cluster_2+BV_1
18      98     104  0.0  0.22218  0.31040       46  val_cluster_2+BV_1
19      98     108  0.0  0.25719  0.37045       48  val_cluster_2+BV_1
20     113     120  0.0  0.49756  0.50850       49  val_cluster_2+BV_1
21     114     120  0.0  0.55024  0.54326       50  val_cluster_2+BV_1
22     117     131  0.0  0.24310  0.29208       51  val_cluster_2+BV_1
23     121     131  0.0  0.19173  0.23972       52  val_cluster_2+BV_1
24     132     149  0.0  0.26140  0.30267       54  val_cluster_2+BV_1
25     150     169  0.0  0.45297  0.53974       57  val_cluster_2+BV_1
26     151     162  0.0  0.31622  0.45372       58  val_cluster_2+BV_1
27     151     167  0.0  0.43711  0.52972       59  val_cluster_2+BV_1
28     151     169  0.0  0.47628  0.54735       60  val_cluster_2+BV_1
29     151     170  0.0  0.49249  0.57156       61  val_cluster_2+BV_1
30     155     169  0.0  0.53500  0.53827       63  val_cluster_2+BV_1
31     171     183  0.0  0.24177  0.30174       68  val_cluster_2+BV_1
32     184     195  0.0  0.38633  0.44869       70  val_cluster_2+BV_1
33     184     208  0.0  0.24871  0.31226       71  val_cluster_2+BV_1
34     187     208  0.0  0.22903  0.26839       73  val_cluster_2+BV_1
35     187     209  0.0  0.21687  0.25989       74  val_cluster_2+BV_1
36     188     208  0.0  0.20479  0.23593       75  val_cluster_2+BV_1
37     247     259  0.0  0.07600  0.11464       82  val_cluster_2+BV_1
38     248     259  0.0  0.08527  0.13242       84  val_cluster_2+BV_1
39     248     260  0.0  0.08569  0.14304       85  val_cluster_2+BV_1
40     250     257  0.0  0.06291  0.07885       86  val_cluster_2+BV_1
41     250     260  0.0  0.09393  0.16201       87  val_cluster_2+BV_1
42     261     278  0.0  0.50107  0.49072       91  val_cluster_2+BV_1
43     261     281  0.0  0.45551  0.47280       92  val_cluster_2+BV_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/reweighting_gamma_2x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/reweighting_gamma_3x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/reweighting_gamma_4x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/reweighting_gamma_5x10^0



Contacts readContacts read
Contacts read
Hbonds read

Hbonds readHbonds read

Contacts read
Hbonds read
Segments and experimental dfracs read
Segments and experimental dfracs read
Segments and experimental dfracs read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002Sum of Output Weights

1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.5030264685184154, 6.612844249743728), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.5030264685184154, 6.612844249743728), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.5030264685184154, 6.612844249743728), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.5030264685184154, 6.612844249743728)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/train_cluster_2+BV_1/reweighting_gamma_2x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.10968  0.27760        0
1  0.0  0.42124  0.57346        1
2  0.0  0.22849  0.44235        2
3  0.0  0.20112  0.35374        3
4  0.0  0.00143  0.01381        4
Experimental cluster_2+BV False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat
REWIGHTING val_cluster_2+BV_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 0.5030264685184154, 'bv_bh': 6.612844249743728}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.5030264685184154, 6.612844249743728)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random0/val_cluster_2+BV_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.20788  0.40376        0
1  0.0  0.30579  0.46181        1
2  0.0  0.35558  0.51033        2
3  0.0  0.37639  0.53929        3
4  0.0  0.38152  0.53248        4
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2+BV_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[ 8.79697382 21.30817906 15.82056148  6.96179211  4.04010475 13.21391461
  8.38151187  6.31399363 12.09756184  5.8364445   1.0782497  10.61350058
 16.90207571 18.11848902  8.50960743 10.91401233  3.48081049  4.99932634
 13.67996098  3.76188369  4.68775345  8.8638094  18.5612623  16.41337817
  6.80112065 10.54756008 20.45545953 19.36942092 16.13235494 15.50281415
 16.07389572 18.04488552 16.83216375 21.9502381  18.74376402 14.80232605
 12.84171708 14.69964685  8.60490124  6.39638443  4.36247887 13.49716116
 13.58893781 14.95738905 24.44597362  7.57894874  4.65663168 15.87292929
  9.40274066  2.83833793  4.36446379  4.06208399  7.97985839  4.99420968
  3.06472203  8.51022546 16.9974713  12.67077176 10.58551671 14.74004927
 20.89211195  7.72640498 13.84352153 19.78833042  7.42536646  3.44898852
 10.5783739  20.16599695 16.1585858  16.08393764 19.45063695 19.34002158
 17.85704303 19.6417673  19.67833387 17.24892137 19.41232984 17.96973144
 17.10429238 16.91488824 16.19589346 10.95630384 12.98715004  4.32350069
 19.79799537 20.6704905  11.61999185 24.37273964 11.9759274   6.3471059
  5.31470409 11.70193341 11.57052912  3.81073294  1.08679785  3.1857838
  4.21619973  7.38364694 12.27091558 26.04982013 12.09312191 21.26920451
  5.7646856   6.0001338  13.8386108   8.46283348 10.68452093 22.07154988
 26.82064607 20.20687298  6.5054653   6.89377873 15.35731832 10.83308412
  9.20015702 16.33251614  9.8197346   3.82274434  7.0551857  22.7965625
 16.32396711  2.85898702 12.70272752  8.95802409  9.37508801  6.12427014
 15.80446068 22.13988713 18.10499253 19.03932739 17.09940363 20.14173705
 17.78999388 16.9415459  20.76309346 16.6456027   3.53666249 12.49443763
 16.36745661 13.19591699 12.10775911 14.75655377 13.98373679 14.85986565
 14.75367753 16.4448375  16.3891184  12.92303013 12.91324185 13.27487538
 15.71380879 20.99484672 13.33102022 24.89738934  5.77623248  7.09758856
 14.60713825  9.89761943  8.99525796 16.86817253 10.11329797 12.00559927
 10.14861826  6.51147342  6.79315643  5.18331749  4.63735849  7.44425726
 11.36980485 24.03349163 11.95024961 24.32258122 17.050471    7.70437395
  7.09038415 17.03600494 11.77333636 13.70909107 25.97567711 27.31549863
 22.13399109  9.59482062 10.56957346 17.11628551 10.10848803  9.1386316
 18.20687497  8.11976301  9.75170932  9.99462471  5.4085516   2.68656229
 14.3142172   3.04207271  3.62784348  6.46314286  5.73252254  9.07957201
  5.44497141  9.02466203  9.07975904  6.76432005  9.45838996  9.54672954
 13.48345631 19.08177056 11.59894859  9.58027099 12.23811351 17.01635339
 14.56347016 22.17034865 21.21752913 19.18598508 22.50853913 19.9027218
 13.97600811 10.21657706 12.93534406 14.80948734  5.03304647  4.59294259
 11.80604875  8.01124721  7.51582546  1.51496859  1.19501219 10.72498682
  2.26834092  2.28908732  4.97028573  2.0656741  11.33940263 11.24106304
 22.36976414 11.33761724 10.66030928 10.42401345 19.36360866 13.21202131
 18.32399584  6.01249872 12.56164003 11.16381236 22.37426337 20.7473008
 19.41886672 20.1034447  20.90765874 19.96647763 19.07603059 17.56618555
 20.16318332 19.83215692 15.15375207 12.69296884 14.37779058 16.20901582
  8.50118376 12.73894396 11.72182873 14.03502604 17.84104933 16.21288285
  6.46432047 19.0618931  20.47637776 21.86173342 16.39806976 13.68888227
 12.79873018  9.15420716  8.75936778  7.91424693  4.73982993 14.14540077
  0.16535358  1.00605294 10.45352154  3.56632025 14.6125752  19.72135822
 19.16592503 15.7794021  18.01895896 20.32864538 19.13774743 17.36485839
 17.63445399]
LogPf_by_res [ 8.79697382 21.30817906 15.82056148  6.96179211  4.04010475 13.21391461
  8.38151187  6.31399363 12.09756184  5.8364445   1.0782497  10.61350058
 16.90207571 18.11848902  8.50960743 10.91401233  3.48081049  4.99932634
 13.67996098  3.76188369  4.68775345  8.8638094  18.5612623  16.41337817
  6.80112065 10.54756008 20.45545953 19.36942092 16.13235494 15.50281415
 16.07389572 18.04488552 16.83216375 21.9502381  18.74376402 14.80232605
 12.84171708 14.69964685  8.60490124  6.39638443  4.36247887 13.49716116
 13.58893781 14.95738905 24.44597362  7.57894874  4.65663168 15.87292929
  9.40274066  2.83833793  4.36446379  4.06208399  7.97985839  4.99420968
  3.06472203  8.51022546 16.9974713  12.67077176 10.58551671 14.74004927
 20.89211195  7.72640498 13.84352153 19.78833042  7.42536646  3.44898852
 10.5783739  20.16599695 16.1585858  16.08393764 19.45063695 19.34002158
 17.85704303 19.6417673  19.67833387 17.24892137 19.41232984 17.96973144
 17.10429238 16.91488824 16.19589346 10.95630384 12.98715004  4.32350069
 19.79799537 20.6704905  11.61999185 24.37273964 11.9759274   6.3471059
  5.31470409 11.70193341 11.57052912  3.81073294  1.08679785  3.1857838
  4.21619973  7.38364694 12.27091558 26.04982013 12.09312191 21.26920451
  5.7646856   6.0001338  13.8386108   8.46283348 10.68452093 22.07154988
 26.82064607 20.20687298  6.5054653   6.89377873 15.35731832 10.83308412
  9.20015702 16.33251614  9.8197346   3.82274434  7.0551857  22.7965625
 16.32396711  2.85898702 12.70272752  8.95802409  9.37508801  6.12427014
 15.80446068 22.13988713 18.10499253 19.03932739 17.09940363 20.14173705
 17.78999388 16.9415459  20.76309346 16.6456027   3.53666249 12.49443763
 16.36745661 13.19591699 12.10775911 14.75655377 13.98373679 14.85986565
 14.75367753 16.4448375  16.3891184  12.92303013 12.91324185 13.27487538
 15.71380879 20.99484672 13.33102022 24.89738934  5.77623248  7.09758856
 14.60713825  9.89761943  8.99525796 16.86817253 10.11329797 12.00559927
 10.14861826  6.51147342  6.79315643  5.18331749  4.63735849  7.44425726
 11.36980485 24.03349163 11.95024961 24.32258122 17.050471    7.70437395
  7.09038415 17.03600494 11.77333636 13.70909107 25.97567711 27.31549863
 22.13399109  9.59482062 10.56957346 17.11628551 10.10848803  9.1386316
 18.20687497  8.11976301  9.75170932  9.99462471  5.4085516   2.68656229
 14.3142172   3.04207271  3.62784348  6.46314286  5.73252254  9.07957201
  5.44497141  9.02466203  9.07975904  6.76432005  9.45838996  9.54672954
 13.48345631 19.08177056 11.59894859  9.58027099 12.23811351 17.01635339
 14.56347016 22.17034865 21.21752913 19.18598508 22.50853913 19.9027218
 13.97600811 10.21657706 12.93534406 14.80948734  5.03304647  4.59294259
 11.80604875  8.01124721  7.51582546  1.51496859  1.19501219 10.72498682
  2.26834092  2.28908732  4.97028573  2.0656741  11.33940263 11.24106304
 22.36976414 11.33761724 10.66030928 10.42401345 19.36360866 13.21202131
 18.32399584  6.01249872 12.56164003 11.16381236 22.37426337 20.7473008
 19.41886672 20.1034447  20.90765874 19.96647763 19.07603059 17.56618555
 20.16318332 19.83215692 15.15375207 12.69296884 14.37779058 16.20901582
  8.50118376 12.73894396 11.72182873 14.03502604 17.84104933 16.21288285
  6.46432047 19.0618931  20.47637776 21.86173342 16.39806976 13.68888227
 12.79873018  9.15420716  8.75936778  7.91424693  4.73982993 14.14540077
  0.16535358  1.00605294 10.45352154  3.56632025 14.6125752  19.72135822
 19.16592503 15.7794021  18.01895896 20.32864538 19.13774743 17.36485839
 17.63445399]
Pf_by_res [6.61419796e+03 1.79483523e+09 7.42647206e+06 1.05552348e+03
 5.68322957e+01 5.47936459e+05 4.36560416e+03 5.52246016e+02
 1.79433841e+05 3.42559204e+02 2.93952998e+00 4.06803553e+04
 2.19017195e+07 7.39196330e+07 4.96221469e+03 5.49408442e+04
 3.24860412e+01 1.48313212e+02 8.73235872e+05 4.30294040e+01
 1.08608910e+02 7.07136919e+03 1.15094294e+08 1.34350587e+07
 8.98854028e+02 3.80844020e+04 7.65055951e+08 2.58245416e+08
 1.01436144e+07 5.40488724e+06 9.56762652e+06 6.86742947e+07
 2.04228258e+07 3.41088660e+09 1.38138039e+08 2.68267784e+06
 3.77647720e+05 2.42089255e+06 5.45834682e+03 5.99672952e+02
 7.84513643e+01 7.27348607e+05 7.97261337e+05 3.13264750e+06
 4.13762806e+10 1.95657102e+03 1.05280865e+02 7.82574335e+06
 1.21215563e+04 1.70873415e+01 7.86072385e+01 5.80952547e+01
 2.92151732e+03 1.47556282e+02 2.14285048e+01 4.96528245e+03
 2.40939493e+07 3.18307051e+05 3.95577420e+04 2.52070521e+06
 1.18393793e+09 2.26743604e+03 1.02840697e+06 3.92611222e+08
 1.67801439e+03 3.14685464e+01 3.92761953e+04 5.72771233e+08
 1.04132105e+07 9.66418783e+06 2.80094316e+08 2.50763689e+08
 5.69134942e+07 3.39087012e+08 3.51715747e+08 3.09821371e+07
 2.69567624e+08 6.37023135e+07 2.68101843e+07 2.21841414e+07
 1.08090408e+07 5.73142087e+04 4.36764767e+05 7.54523020e+01
 3.96424185e+08 9.48593106e+08 1.11300814e+05 3.84544262e+10
 1.58883642e+05 5.70838255e+02 2.03304345e+02 1.20805055e+05
 1.05929507e+05 4.51835435e+01 2.96476524e+00 2.41862382e+01
 6.77754294e+01 1.60944864e+03 2.13398286e+05 2.05727873e+11
 1.78638933e+05 1.72622799e+09 3.18838785e+02 4.03482775e+02
 1.02336912e+06 4.73545682e+03 4.36745544e+04 3.85081203e+09
 4.44691254e+11 5.96668941e+08 6.68786786e+02 9.86120671e+02
 4.67303037e+06 5.06697378e+04 9.89868323e+03 1.23914359e+07
 1.83931685e+04 4.57295338e+01 1.15885265e+03 7.95099167e+09
 1.22859527e+07 1.74438477e+01 3.28643060e+05 7.76998949e+03
 1.17909552e+04 4.56811184e+02 7.30785740e+06 4.12316592e+09
 7.29286794e+07 1.85641396e+08 2.66794359e+07 5.59043056e+08
 5.32226110e+07 2.27834716e+07 1.04063137e+09 1.69470222e+07
 3.43520772e+01 2.66848839e+05 1.28320514e+07 5.38163119e+05
 1.81272936e+05 2.56265340e+06 1.18320426e+06 2.84156539e+06
 2.55529319e+06 1.38644352e+07 1.31130491e+07 4.09638414e+05
 4.05648317e+05 5.82378219e+05 6.67452627e+06 1.31203699e+09
 6.16011072e+05 6.49828573e+10 3.22541715e+02 1.20904801e+03
 2.20698580e+06 1.98829812e+04 8.06474974e+03 2.11716278e+07
 2.46688841e+04 1.63668655e+05 2.55557665e+04 6.72817028e+02
 8.91723785e+02 1.78273251e+02 1.03271195e+02 1.71001473e+03
 8.66649533e+04 2.73913097e+10 1.54855795e+05 3.65731872e+10
 2.54053667e+07 2.21802835e+03 1.20036883e+03 2.50404967e+07
 1.29746310e+05 8.99047429e+05 1.91026330e+11 7.29407667e+11
 4.09892710e+09 1.46885069e+04 3.89320640e+04 2.71336581e+07
 2.45505130e+04 9.30801933e+03 8.07505210e+07 3.36022431e+03
 1.71835760e+04 2.19083848e+04 2.23307914e+02 1.46811196e+01
 1.64659027e+06 2.09486187e+01 3.76315756e+01 6.41072692e+02
 3.08747115e+02 8.77420995e+03 2.31590658e+02 8.30540699e+03
 8.77585111e+03 8.66376918e+02 1.28152348e+04 1.39988371e+04
 7.17448401e+05 1.93690205e+08 1.08983153e+05 1.44763417e+04
 2.06511939e+05 2.45532158e+07 2.11268490e+06 4.25069635e+09
 1.63929012e+09 2.14964848e+08 5.96120890e+09 4.40192110e+08
 1.17409490e+06 2.73528789e+04 4.14713858e+05 2.70195823e+06
 1.53399628e+02 9.87846857e+01 1.34060806e+05 3.01467471e+03
 1.83688312e+03 4.54927823e+00 3.30359804e+00 4.54781293e+04
 9.66335526e+00 9.86592909e+00 1.44068046e+02 7.89061517e+00
 8.40697953e+04 7.61959083e+04 5.18877847e+09 8.39198315e+04
 4.26298198e+04 3.36582490e+04 2.56748782e+08 5.46900034e+05
 9.07842020e+07 4.08502780e+02 2.85398015e+05 7.05313350e+04
 5.21217654e+09 1.02432613e+09 2.71335528e+08 5.38040666e+08
 1.20248819e+09 4.69170889e+08 1.92581613e+08 4.25497932e+07
 5.71161933e+08 4.10200622e+08 3.81233368e+06 3.25451535e+05
 1.75466862e+06 1.09518157e+07 4.92059020e+03 3.40763498e+05
 1.23232578e+05 1.24547313e+06 5.60104774e+07 1.09942487e+07
 6.41828071e+02 1.89878148e+08 7.81228129e+08 3.12198052e+09
 1.32309556e+07 8.81061117e+05 3.61757791e+05 9.45413183e+03
 6.37008299e+03 2.73598536e+03 1.14414742e+02 1.39081543e+06
 1.17981020e+00 2.73478531e+00 3.46662387e+04 3.53861410e+01
 2.21901774e+06 3.67178336e+08 2.10695606e+08 7.12700825e+06
 6.69166891e+07 6.73935779e+08 2.04841575e+08 3.47906208e+07
 4.55560499e+07]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [6.19893363e+00 2.08338528e-06 6.05357078e-04 2.39511450e-01
 6.73285058e+01 7.65709398e-03 1.67012826e-01 1.78099043e+00
 1.85733321e-03 1.69066880e+00 1.83872289e+03 7.82365046e-02
 9.38244361e-05 2.53532929e-05 4.04686416e-01 6.06595033e-03
 2.04690358e+01 3.17405417e+01 1.20687588e-02 8.11014923e+01
 3.44293418e+01 5.41116359e-01 3.24893020e-06 2.31501926e-04
 1.02118640e+00 9.16319725e-02 3.38143449e-06 6.77269556e-06
 2.38013420e-04 2.95126046e-04 1.05193756e-04 1.80301761e-05
 1.83095783e-05 2.18739339e-07 2.41257539e-06 2.65598523e-04
 3.43326487e-03 3.37923709e-04 2.43070945e-01 5.43099891e-01
 8.09456799e+00 3.47577430e-03 1.02610895e-03 1.03963920e-04
 9.24789154e-08 3.72647799e-01 5.01700729e+01 5.36128106e-04
 1.85881340e-01 5.37179823e+01 2.80111958e+00 1.14459941e+01
 8.65337876e-01 7.14227475e+00 3.32508162e+01 4.64355098e-01
 2.19223035e-05 6.45576808e-04 4.62980481e-02 5.38607154e-04
 7.93350758e-07 7.19878379e-01 2.04469796e-03 1.69368042e-06
 3.61408610e-01 2.91687293e+01 2.13139910e-02 1.18799053e-06
 1.36524165e-04 3.44848877e-05 1.60505486e-06 4.60818097e-06
 2.80271493e-05 4.49244761e-06 1.24911483e-06 2.14626234e-05
 5.78264385e-06 1.31413195e-05 1.39474361e-05 1.08830733e-05
 7.06328969e-05 3.42398517e-02 6.06103208e-03 8.81295763e+00
 2.42456613e-06 4.03379861e-07 2.73083739e-03 1.06622249e-07
 2.82953447e-02 2.54847928e+00 4.11763187e+01 8.72386764e-02
 1.37333733e-02 2.44238367e+01 3.63750724e+02 6.74878899e+01
 1.51957416e+01 3.28183736e-01 2.84186373e-03 4.36014615e-09
 6.03695669e-03 4.84948948e-06 2.62556655e+00 2.07476626e+01
 3.48948928e-03 4.24064869e-01 3.91350320e-02 3.00083320e-07
 1.36375259e-08 1.50335222e-06 1.65008567e+00 8.88922938e+00
 8.77395842e-04 3.96319571e-02 2.43902779e-01 6.30481784e-05
 4.15085561e-02 1.52264059e+01 8.88722058e-01 2.00619377e-07
 1.71153324e-04 1.12499836e+02 6.85598266e-03 6.34415441e-01
 8.93809955e-01 7.63936829e+00 1.54526921e-04 1.16832419e-07
 2.29031821e-05 3.34286895e-05 3.86026869e-05 1.60453398e-06
 3.77309726e-05 9.01933000e-05 4.84727055e-06 1.96653093e-04
 1.64755975e+01 1.80521471e-03 1.27203214e-04 3.73147250e-03
 8.02529875e-03 7.31314702e-04 4.16614568e-04 2.74939111e-04
 4.84566559e-04 6.32254594e-05 2.85161237e-05 2.18974479e-03
 3.84277094e-03 4.75980381e-03 3.70146570e-04 2.65979459e-07
 1.52477465e-03 5.37026075e-08 2.06161842e+00 5.75904709e+00
 1.85778151e-03 4.83406710e-02 4.22866499e-01 6.41268526e-05
 5.76294762e-02 2.03623860e-03 3.05706919e-02 2.26410833e+00
 2.20071511e+00 9.81088065e+00 7.56510520e+01 2.56917877e+00
 1.49606571e-02 3.67435724e-08 7.46219708e-03 1.99356944e-07
 1.50615167e-04 1.03950620e+00 6.97396021e+00 2.15849594e-04
 1.28735748e-02 2.23363174e-03 6.04924180e-09 8.31426480e-09
 2.57112968e-06 1.60626252e-01 2.00671985e-01 8.89786533e-05
 1.78950784e-01 2.84404786e-01 9.02919108e-06 1.53612270e+00
 1.40501393e-01 3.17821897e-01 2.53448697e+00 1.53474066e+02
 6.70206495e-03 2.58011334e+02 1.11491504e+01 1.30583077e+00
 4.93391051e+00 4.46258143e-01 2.87126409e+00 7.47193801e-02
 1.85996568e-01 1.71825377e+00 1.08409567e-01 6.26184362e-02
 3.68980579e-03 1.80171676e-05 1.08501266e-02 3.10552730e-02
 3.78311037e-03 1.52295053e-05 4.44589753e-04 2.11025090e-07
 1.11721911e-06 2.04374510e-06 3.44714727e-08 2.03775479e-06
 2.15323277e-03 9.45782197e-02 1.97262998e-02 1.95485949e-04
 5.84749514e+00 9.50833674e+00 3.35345397e-02 7.47401075e-01
 8.48618810e-01 1.60269794e+02 3.57937317e+02 4.12089535e-02
 1.57639929e+02 2.13135694e+02 1.75479550e+00 8.62349497e+01
 2.08043517e-02 2.29542193e-02 1.50566740e-06 6.44064812e-02
 9.84193924e-03 5.07811647e-03 2.25572308e-06 1.88315569e-03
 2.01736228e-05 3.17394326e+00 6.27109290e-04 1.42696090e-02
 1.80208412e-07 1.26577328e-06 4.77845514e-06 8.95321634e-07
 3.10966321e-07 3.32248570e-07 1.11732459e-05 1.56277596e-05
 2.54703506e-07 5.62079649e-06 6.94389701e-04 3.09248679e-03
 2.33667906e-03 6.07166846e-05 1.99883523e-01 2.13964198e-03
 8.75122080e-03 4.24091741e-04 7.49074311e-06 1.00375707e-04
 2.78853098e-01 1.05759451e-05 1.38043609e-06 4.99302784e-07

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
         Bc        Bh             calc_name
0  0.503026  6.612844  train_cluster_2+BV_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_r_naive_random/20240402-191922_analysis.csv
dict_keys(['cluster_2+BV_r_naive_random'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_r_naive_random to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV_r_naive_random/cluster_2+BV_r_naive_random0_1712081962.pkl
Analysis Dump {'cluster_2+BV_r_naive_random': {'train_dfs': [    0.0      0.5      5.0  peptide             calc_name
0   0.0  0.10968  0.27760       77  train_cluster_2+BV_1
1   0.0  0.42124  0.57346       10  train_cluster_2+BV_1
2   0.0  0.22849  0.44235        4  train_cluster_2+BV_1
3   0.0  0.20112  0.35374       83  train_cluster_2+BV_1
4   0.0  0.00143  0.01381       62  train_cluster_2+BV_1
5   0.0  0.16788  0.29654       67  train_cluster_2+BV_1
6   0.0  0.35518  0.67374       30  train_cluster_2+BV_1
7   0.0  0.00251  0.02348       45  train_cluster_2+BV_1
8   0.0  0.00000  0.00002       95  train_cluster_2+BV_1
9   0.0  0.39491  0.53762       11  train_cluster_2+BV_1
10  0.0  0.19403  0.24824       81  train_cluster_2+BV_1
11  0.0  0.10232  0.27259       79  train_cluster_2+BV_1
12  0.0  0.34498  0.45316        0  train_cluster_2+BV_1
13  0.0  0.09503  0.25328       80  train_cluster_2+BV_1
14  0.0  0.05175  0.25572       18  train_cluster_2+BV_1
15  0.0  0.17978  0.31684       69  train_cluster_2+BV_1
16  0.0  0.17953  0.28913       56  train_cluster_2+BV_1
17  0.0  0.12297  0.30903       76  train_cluster_2+BV_1
18  0.0  0.23320  0.29141      106  train_cluster_2+BV_1
19  0.0  0.00167  0.01567       42  train_cluster_2+BV_1
20  0.0  0.23062  0.40689       12  train_cluster_2+BV_1
21  0.0  0.16800  0.27683       36  train_cluster_2+BV_1
22  0.0  0.14115  0.26107       64  train_cluster_2+BV_1
23  0.0  0.24137  0.44800       26  train_cluster_2+BV_1
24  0.0  0.00031  0.00308       22  train_cluster_2+BV_1
25  0.0  0.26203  0.50826       31  train_cluster_2+BV_1
26  0.0  0.21735  0.27197       47  train_cluster_2+BV_1
27  0.0  0.23325  0.29190      100  train_cluster_2+BV_1
28  0.0  0.46736  0.57268       15  train_cluster_2+BV_1
29  0.0  0.00223  0.02087       44  train_cluster_2+BV_1
30  0.0  0.36676  0.60158       88  train_cluster_2+BV_1
31  0.0  0.37186  0.51943       89  train_cluster_2+BV_1
32  0.0  0.34993  0.49011        9  train_cluster_2+BV_1
33  0.0  0.35284  0.72801       33  train_cluster_2+BV_1
34  0.0  0.20945  0.33730       55  train_cluster_2+BV_1
35  0.0  0.24697  0.30905      103  train_cluster_2+BV_1
36  0.0  0.25724  0.41607       28  train_cluster_2+BV_1
37  0.0  0.11760  0.19380       40  train_cluster_2+BV_1
38  0.0  0.32917  0.49596        5  train_cluster_2+BV_1
39  0.0  0.32140  0.49889       53  train_cluster_2+BV_1
40  0.0  0.24602  0.30012      107  train_cluster_2+BV_1
41  0.0  0.13067  0.21533       39  train_cluster_2+BV_1
42  0.0  0.16437  0.32452       35  train_cluster_2+BV_1
43  0.0  0.40915  0.54234       16  train_cluster_2+BV_1
44  0.0  0.46687  0.74695       78  train_cluster_2+BV_1
45  0.0  0.23718  0.50307       34  train_cluster_2+BV_1
46  0.0  0.13147  0.24629       66  train_cluster_2+BV_1
47  0.0  0.24498  0.42859        7  train_cluster_2+BV_1
48  0.0  0.00183  0.01709       43  train_cluster_2+BV_1
49  0.0  0.15275  0.28124       65  train_cluster_2+BV_1
50  0.0  0.22621  0.38343       72  train_cluster_2+BV_1
51  0.0  0.16231  0.29070       27  train_cluster_2+BV_1
52  0.0  0.04315  0.21335       19  train_cluster_2+BV_1
53  0.0  0.34345  0.48140       90  train_cluster_2+BV_1], 'val_dfs': [    0.0      0.5      5.0  peptide           calc_name
0   0.0  0.20788  0.40376        1  val_cluster_2+BV_1
1   0.0  0.30579  0.46181        2  val_cluster_2+BV_1
2   0.0  0.35558  0.51033        3  val_cluster_2+BV_1
3   0.0  0.37639  0.53929        6  val_cluster_2+BV_1
4   0.0  0.38152  0.53248        8  val_cluster_2+BV_1
5   0.0  0.40069  0.53869       13  val_cluster_2+BV_1
6   0.0  0.36087  0.48722       14  val_cluster_2+BV_1
7   0.0  0.52030  0.62409       17  val_cluster_2+BV_1
8   0.0  0.04315  0.21335       20  val_cluster_2+BV_1
9   0.0  0.00027  0.00272       21  val_cluster_2+BV_1
10  0.0  0.00029  0.00288       23  val_cluster_2+BV_1
11  0.0  0.15547  0.34966       24  val_cluster_2+BV_1
12  0.0  0.15547  0.34966       25  val_cluster_2+BV_1
13  0.0  0.23354  0.44610       29  val_cluster_2+BV_1
14  0.0  0.27475  0.50282       32  val_cluster_2+BV_1
15  0.0  0.19600  0.32297       37  val_cluster_2+BV_1
16  0.0  0.16800  0.27683       38  val_cluster_2+BV_1
17  0.0  0.06295  0.11189       41  val_cluster_2+BV_1
18  0.0  0.00308  0.02929       46  val_cluster_2+BV_1
19  0.0  0.17842  0.25555       48  val_cluster_2+BV_1
20  0.0  0.45075  0.55001       49  val_cluster_2+BV_1
21  0.0  0.35921  0.47501       50  val_cluster_2+BV_1
22  0.0  0.17155  0.31021       51  val_cluster_2+BV_1
23  0.0  0.24731  0.44321       52  val_cluster_2+BV_1
24  0.0  0.22177  0.35713       54  val_cluster_2+BV_1
25  0.0  0.00111  0.01078       57  val_cluster_2+BV_1
26  0.0  0.00180  0.01738       58  val_cluster_2+BV_1
27  0.0  0.00126  0.01219       59  val_cluster_2+BV_1
28  0.0  0.00118  0.01141       60  val_cluster_2+BV_1
29  0.0  0.00122  0.01183       61  val_cluster_2+BV_1
30  0.0  0.00153  0.01487       63  val_cluster_2+BV_1
31  0.0  0.16653  0.30569       68  val_cluster_2+BV_1
32  0.0  0.25144  0.46261       70  val_cluster_2+BV_1
33  0.0  0.18697  0.39226       71  val_cluster_2+BV_1
34  0.0  0.16815  0.35205       73  val_cluster_2+BV_1
35  0.0  0.16051  0.33605       74  val_cluster_2+BV_1
36  0.0  0.16293  0.32173       75  val_cluster_2+BV_1
37  0.0  0.18907  0.30108       82  val_cluster_2+BV_1
38  0.0  0.20625  0.32845       84  val_cluster_2+BV_1
39  0.0  0.21788  0.38322       85  val_cluster_2+BV_1
40  0.0  0.27719  0.35463       86  val_cluster_2+BV_1
41  0.0  0.26146  0.45986       87  val_cluster_2+BV_1
42  0.0  0.29769  0.41751       91  val_cluster_2+BV_1
43  0.0  0.27735  0.40363       92  val_cluster_2+BV_1
44  0.0  0.00000  0.00002       93  val_cluster_2+BV_1
45  0.0  0.00000  0.00002       94  val_cluster_2+BV_1
46  0.0  0.01941  0.12166       96  val_cluster_2+BV_1
47  0.0  0.02326  0.14564       97  val_cluster_2+BV_1
48  0.0  0.02567  0.16012       98  val_cluster_2+BV_1
49  0.0  0.22098  0.27654       99  val_cluster_2+BV_1
50  0.0  0.22098  0.27654      101  val_cluster_2+BV_1
51  0.0  0.26241  0.32836      102  val_cluster_2+BV_1
52  0.0  0.20993  0.26271      104  val_cluster_2+BV_1
53  0.0  0.27984  0.34967      105  val_cluster_2+BV_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                            name split_type
0    cluster_2+BV_r_naive_random          r
1    cluster_2+BV_r_naive_random          r
2    cluster_2+BV_r_naive_random          r
3    cluster_2+BV_r_naive_random          r
4    cluster_2+BV_r_naive_random          r
5    cluster_2+BV_r_naive_random          r
6    cluster_2+BV_r_naive_random          r
7    cluster_2+BV_r_naive_random          r
8    cluster_2+BV_r_naive_random          r
9    cluster_2+BV_r_naive_random          r
10   cluster_2+BV_r_naive_random          r
11   cluster_2+BV_r_naive_random          r
12   cluster_2+BV_r_naive_random          r
13   cluster_2+BV_r_naive_random          r
14   cluster_2+BV_r_naive_random          r
15   cluster_2+BV_r_naive_random          r
16   cluster_2+BV_r_naive_random          r
17   cluster_2+BV_r_naive_random          r
18   cluster_2+BV_r_naive_random          r
19   cluster_2+BV_r_naive_random          r
20   cluster_2+BV_r_naive_random          r
21   cluster_2+BV_r_naive_random          r
22   cluster_2+BV_r_naive_random          r
23   cluster_2+BV_r_naive_random          r
24   cluster_2+BV_r_naive_random          r
25   cluster_2+BV_r_naive_random          r
26   cluster_2+BV_r_naive_random          r
27   cluster_2+BV_r_naive_random          r
28   cluster_2+BV_r_naive_random          r
29   cluster_2+BV_r_naive_random          r
30   cluster_2+BV_r_naive_random          r
31   cluster_2+BV_r_naive_random          r
32   cluster_2+BV_r_naive_random          r
33   cluster_2+BV_r_naive_random          r
34   cluster_2+BV_r_naive_random          r
35   cluster_2+BV_r_naive_random          r
36   cluster_2+BV_r_naive_random          r
37   cluster_2+BV_r_naive_random          r
38   cluster_2+BV_r_naive_random          r
39   cluster_2+BV_r_naive_random          r
40   cluster_2+BV_r_naive_random          r
41   cluster_2+BV_r_naive_random          r
42   cluster_2+BV_r_naive_random          r
43   cluster_2+BV_r_naive_random          r
44   cluster_2+BV_r_naive_random          r
45   cluster_2+BV_r_naive_random          r
46   cluster_2+BV_r_naive_random          r
47   cluster_2+BV_r_naive_random          r
48   cluster_2+BV_r_naive_random          r
49   cluster_2+BV_r_naive_random          r
50   cluster_2+BV_r_naive_random          r
51   cluster_2+BV_r_naive_random          r
52   cluster_2+BV_r_naive_random          r
53   cluster_2+BV_r_naive_random          r
54   cluster_2+BV_r_naive_random          r
55   cluster_2+BV_r_naive_random          r
56   cluster_2+BV_r_naive_random          r
57   cluster_2+BV_r_naive_random          r
58   cluster_2+BV_r_naive_random          r
59   cluster_2+BV_r_naive_random          r
60   cluster_2+BV_r_naive_random          r
61   cluster_2+BV_r_naive_random          r
62   cluster_2+BV_r_naive_random          r
63   cluster_2+BV_r_naive_random          r
64   cluster_2+BV_r_naive_random          r
65   cluster_2+BV_r_naive_random          r
66   cluster_2+BV_r_naive_random          r
67   cluster_2+BV_r_naive_random          r
68   cluster_2+BV_r_naive_random          r
69   cluster_2+BV_r_naive_random          r
70   cluster_2+BV_r_naive_random          r
71   cluster_2+BV_r_naive_random          r
72   cluster_2+BV_r_naive_random          r
73   cluster_2+BV_r_naive_random          r
74   cluster_2+BV_r_naive_random          r
75   cluster_2+BV_r_naive_random          r
76   cluster_2+BV_r_naive_random          r
77   cluster_2+BV_r_naive_random          r
78   cluster_2+BV_r_naive_random          r
79   cluster_2+BV_r_naive_random          r
80   cluster_2+BV_r_naive_random          r
81   cluster_2+BV_r_naive_random          r
82   cluster_2+BV_r_naive_random          r
83   cluster_2+BV_r_naive_random          r
84   cluster_2+BV_r_naive_random          r
85   cluster_2+BV_r_naive_random          r
86   cluster_2+BV_r_naive_random          r
87   cluster_2+BV_r_naive_random          r
88   cluster_2+BV_r_naive_random          r
89   cluster_2+BV_r_naive_random          r
90   cluster_2+BV_r_naive_random          r
91   cluster_2+BV_r_naive_random          r
92   cluster_2+BV_r_naive_random          r
93   cluster_2+BV_r_naive_random          r
94   cluster_2+BV_r_naive_random          r
95   cluster_2+BV_r_naive_random          r
96   cluster_2+BV_r_naive_random          r
97   cluster_2+BV_r_naive_random          r
98   cluster_2+BV_r_naive_random          r
99   cluster_2+BV_r_naive_random          r
100  cluster_2+BV_r_naive_random          r
101  cluster_2+BV_r_naive_random          r
102  cluster_2+BV_r_naive_random          r
103  cluster_2+BV_r_naive_random          r
104  cluster_2+BV_r_naive_random          r
105  cluster_2+BV_r_naive_random          r
106  cluster_2+BV_r_naive_random          r
107  cluster_2+BV_r_naive_random          r  , 'merge_df':      0.0      0.5      5.0  peptide             calc_name  \
0    0.0  0.41879  0.44438        0          Experimental
1    0.0  0.37096  0.45204        1          Experimental
2    0.0  0.40040  0.48544        2          Experimental
3    0.0  0.45875  0.51503        3          Experimental
4    0.0  0.41726  0.49519        4          Experimental
5    0.0  0.44176  0.50927        5          Experimental
6    0.0  0.48987  0.54090        6          Experimental
7    0.0  0.41316  0.48254        7          Experimental
8    0.0  0.46617  0.51066        8          Experimental
9    0.0  0.46825  0.52028        9          Experimental
10   0.0  0.48273  0.53102       10          Experimental
11   0.0  0.50258  0.53988       11          Experimental
12   0.0  0.47373  0.50144       12          Experimental
13   0.0  0.52057  0.54102       13          Experimental
14   0.0  0.52823  0.55640       14          Experimental
15   0.0  0.55802  0.57504       15          Experimental
16   0.0  0.55641  0.57196       16          Experimental
17   0.0  0.52928  0.54827       17          Experimental
18   0.0  0.17163  0.27883       18          Experimental
19   0.0  0.16883  0.28686       19          Experimental
20   0.0  0.16341  0.27353       20          Experimental
21   0.0  0.32309  0.41205       21          Experimental
22   0.0  0.31355  0.39928       22          Experimental

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

envs ['# conda environments:', '#', 'base                     /home/alexi/anaconda3', 'HDXER_ENV             *  /home/alexi/anaconda3/envs/HDXER_ENV', 'PLUMED_310               /home/alexi/anaconda3/envs/PLUMED_310', 'openfold_env             /home/alexi/anaconda3/envs/openfold_env', 'plumed-masterclass-2022     /home/alexi/anaconda3/envs/plumed-masterclass-2022', '                         /home/alexi/localcolabfold/colabfold-conda', '                         /home/alexi/localcolabfold/conda', '']
name base
name HDXER_ENV
Environment 'HDXER_ENV' found.
Path to 'HDXER_ENV' environment: /home/alexi/anaconda3/envs/HDXER_ENV
PATH /home/alexi/anaconda3/envs/HDXER_ENV:/home/alexi/anaconda3/envs/HDXER_ENV/bin:/home/alexi/anaconda3/condabin:/home/alexi/.vscode/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
calc_hdx
/home/alexi/Documents/HDXer/HDXer/calc_hdx.py
Experiment name cluster_2+BV_s_naive_sequential already exists. Attempting to change name to cluster_2+BV_s_naive_sequential0
Preparing HDX data for Experimental
Path /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP_apo/HOIP_apo.dat
AVG: ncol = 5, len(names) = 3
                                                 HDX  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...
1                                                NaN

                                                 SEG     calc_name  \
0  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...  Experimental
1                                                NaN  cluster_2+BV

  experimental                                                top  \
0        False                                                NaN
1          NaN  /home/alexi/Documents/ValDX/raw_data/HOIP/HOIP...

                                                traj
0                                                NaN
1  [/home/alexi/Documents/ValDX/results/HOIPapo_t...
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
Running VDX loop
Random seeds: [42]
Splitting segments for cluster_2+BV by N-terminal and C-terminal
train_segs
   ResStr  ResEnd  peptide             calc_name
0       1       7        0  train_cluster_2+BV_1
1       6      18        1  train_cluster_2+BV_1
2       6      21        2  train_cluster_2+BV_1
3       6      25        3  train_cluster_2+BV_1
4       7      18        4  train_cluster_2+BV_1
Saved train cluster_2+BV_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/train_residue_segs__cluster_2+BV_.txt
Train Peptide numbers: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]
Saved val cluster_2+BV_1 segments to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/val_residue_segs__cluster_2+BV_.txt
Val Peptide numbers: [ 54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107]
train_HDX_data
    0.0      0.5      5.0  peptide             calc_name  \
0   0.0  0.41879  0.44438        0  train_cluster_2+BV_1
1   0.0  0.37096  0.45204        1  train_cluster_2+BV_1
2   0.0  0.40040  0.48544        2  train_cluster_2+BV_1
3   0.0  0.45875  0.51503        3  train_cluster_2+BV_1
4   0.0  0.41726  0.49519        4  train_cluster_2+BV_1
5   0.0  0.44176  0.50927        5  train_cluster_2+BV_1
6   0.0  0.48987  0.54090        6  train_cluster_2+BV_1
7   0.0  0.41316  0.48254        7  train_cluster_2+BV_1
8   0.0  0.46617  0.51066        8  train_cluster_2+BV_1
9   0.0  0.46825  0.52028        9  train_cluster_2+BV_1
10  0.0  0.48273  0.53102       10  train_cluster_2+BV_1
11  0.0  0.50258  0.53988       11  train_cluster_2+BV_1
12  0.0  0.47373  0.50144       12  train_cluster_2+BV_1
13  0.0  0.52057  0.54102       13  train_cluster_2+BV_1
14  0.0  0.52823  0.55640       14  train_cluster_2+BV_1
15  0.0  0.55802  0.57504       15  train_cluster_2+BV_1
16  0.0  0.55641  0.57196       16  train_cluster_2+BV_1
17  0.0  0.52928  0.54827       17  train_cluster_2+BV_1
18  0.0  0.17163  0.27883       18  train_cluster_2+BV_1
19  0.0  0.16883  0.28686       19  train_cluster_2+BV_1
20  0.0  0.16341  0.27353       20  train_cluster_2+BV_1
21  0.0  0.32309  0.41205       21  train_cluster_2+BV_1
22  0.0  0.31355  0.39928       22  train_cluster_2+BV_1
23  0.0  0.34392  0.42213       23  train_cluster_2+BV_1
24  0.0  0.35604  0.35617       24  train_cluster_2+BV_1
25  0.0  0.34105  0.35125       25  train_cluster_2+BV_1
26  0.0  0.34135  0.38830       26  train_cluster_2+BV_1
27  0.0  0.28512  0.29602       27  train_cluster_2+BV_1
28  0.0  0.28439  0.33185       28  train_cluster_2+BV_1
29  0.0  0.32954  0.39085       29  train_cluster_2+BV_1
30  0.0  0.26192  0.34619       30  train_cluster_2+BV_1
31  0.0  0.31421  0.37857       31  train_cluster_2+BV_1
32  0.0  0.32314  0.38565       32  train_cluster_2+BV_1
33  0.0  0.29666  0.37860       33  train_cluster_2+BV_1
34  0.0  0.38440  0.44775       34  train_cluster_2+BV_1
35  0.0  0.33633  0.46390       35  train_cluster_2+BV_1
36  0.0  0.34716  0.45807       36  train_cluster_2+BV_1
37  0.0  0.34165  0.44393       37  train_cluster_2+BV_1
38  0.0  0.30725  0.43533       38  train_cluster_2+BV_1
39  0.0  0.33252  0.48976       39  train_cluster_2+BV_1
40  0.0  0.28369  0.42940       40  train_cluster_2+BV_1
41  0.0  0.35906  0.50293       41  train_cluster_2+BV_1
42  0.0  0.33575  0.45181       42  train_cluster_2+BV_1
43  0.0  0.33443  0.43697       43  train_cluster_2+BV_1
44  0.0  0.37082  0.47284       44  train_cluster_2+BV_1
45  0.0  0.37847  0.48848       45  train_cluster_2+BV_1
46  0.0  0.22218  0.31040       46  train_cluster_2+BV_1
47  0.0  0.18217  0.28305       47  train_cluster_2+BV_1
48  0.0  0.25719  0.37045       48  train_cluster_2+BV_1
49  0.0  0.49756  0.50850       49  train_cluster_2+BV_1
50  0.0  0.55024  0.54326       50  train_cluster_2+BV_1
51  0.0  0.24310  0.29208       51  train_cluster_2+BV_1
52  0.0  0.19173  0.23972       52  train_cluster_2+BV_1
53  0.0  0.18105  0.23003       53  train_cluster_2+BV_1

                                                 path  ResStr  ResEnd
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       1       7
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       6      18
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       6      21
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       6      25
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      18
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      21
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       7      25
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      18
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      20
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      21
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      24
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...       8      25
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      18
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      20
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      21
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      23
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      11      25
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      19      25
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      32
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      26      33
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      27      33
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      33      40
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      34      40
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      34      41
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      48
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      49
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      41      51
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      49
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      51
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      42      65
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      61
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      49      65
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      50      65
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      61
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      52      65
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      74      84
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      76      84
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      84
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      85
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      87
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      88
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      77      97
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      85      97
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      86      97
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      88      97
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      89      97
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     104
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     106
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...      98     108
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     113     120
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     114     120
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     117     131
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     121     131
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...     121     132
    ResStr  ResEnd  0.0      0.5      5.0  peptide             calc_name  \
0        1       7  0.0  0.41879  0.44438        0  train_cluster_2+BV_1
1        6      18  0.0  0.37096  0.45204        1  train_cluster_2+BV_1
2        6      21  0.0  0.40040  0.48544        2  train_cluster_2+BV_1
3        6      25  0.0  0.45875  0.51503        3  train_cluster_2+BV_1
4        7      18  0.0  0.41726  0.49519        4  train_cluster_2+BV_1
5        7      21  0.0  0.44176  0.50927        5  train_cluster_2+BV_1
6        7      25  0.0  0.48987  0.54090        6  train_cluster_2+BV_1
7        8      18  0.0  0.41316  0.48254        7  train_cluster_2+BV_1
8        8      20  0.0  0.46617  0.51066        8  train_cluster_2+BV_1
9        8      21  0.0  0.46825  0.52028        9  train_cluster_2+BV_1
10       8      24  0.0  0.48273  0.53102       10  train_cluster_2+BV_1
11       8      25  0.0  0.50258  0.53988       11  train_cluster_2+BV_1
12      11      18  0.0  0.47373  0.50144       12  train_cluster_2+BV_1
13      11      20  0.0  0.52057  0.54102       13  train_cluster_2+BV_1
14      11      21  0.0  0.52823  0.55640       14  train_cluster_2+BV_1
15      11      23  0.0  0.55802  0.57504       15  train_cluster_2+BV_1
16      11      25  0.0  0.55641  0.57196       16  train_cluster_2+BV_1
17      19      25  0.0  0.52928  0.54827       17  train_cluster_2+BV_1
18      26      32  0.0  0.17163  0.27883       18  train_cluster_2+BV_1
19      26      33  0.0  0.16883  0.28686       19  train_cluster_2+BV_1
20      27      33  0.0  0.16341  0.27353       20  train_cluster_2+BV_1
21      33      40  0.0  0.32309  0.41205       21  train_cluster_2+BV_1
22      34      40  0.0  0.31355  0.39928       22  train_cluster_2+BV_1
23      34      41  0.0  0.34392  0.42213       23  train_cluster_2+BV_1
24      41      48  0.0  0.35604  0.35617       24  train_cluster_2+BV_1
25      41      49  0.0  0.34105  0.35125       25  train_cluster_2+BV_1
26      41      51  0.0  0.34135  0.38830       26  train_cluster_2+BV_1
27      42      49  0.0  0.28512  0.29602       27  train_cluster_2+BV_1
28      42      51  0.0  0.28439  0.33185       28  train_cluster_2+BV_1
29      42      65  0.0  0.32954  0.39085       29  train_cluster_2+BV_1
30      49      61  0.0  0.26192  0.34619       30  train_cluster_2+BV_1
31      49      65  0.0  0.31421  0.37857       31  train_cluster_2+BV_1
32      50      65  0.0  0.32314  0.38565       32  train_cluster_2+BV_1
33      52      61  0.0  0.29666  0.37860       33  train_cluster_2+BV_1
34      52      65  0.0  0.38440  0.44775       34  train_cluster_2+BV_1
35      74      84  0.0  0.33633  0.46390       35  train_cluster_2+BV_1
36      76      84  0.0  0.34716  0.45807       36  train_cluster_2+BV_1
37      77      84  0.0  0.34165  0.44393       37  train_cluster_2+BV_1
38      77      85  0.0  0.30725  0.43533       38  train_cluster_2+BV_1
39      77      87  0.0  0.33252  0.48976       39  train_cluster_2+BV_1
40      77      88  0.0  0.28369  0.42940       40  train_cluster_2+BV_1
41      77      97  0.0  0.35906  0.50293       41  train_cluster_2+BV_1
42      85      97  0.0  0.33575  0.45181       42  train_cluster_2+BV_1
43      86      97  0.0  0.33443  0.43697       43  train_cluster_2+BV_1
44      88      97  0.0  0.37082  0.47284       44  train_cluster_2+BV_1
45      89      97  0.0  0.37847  0.48848       45  train_cluster_2+BV_1
46      98     104  0.0  0.22218  0.31040       46  train_cluster_2+BV_1
47      98     106  0.0  0.18217  0.28305       47  train_cluster_2+BV_1
48      98     108  0.0  0.25719  0.37045       48  train_cluster_2+BV_1
49     113     120  0.0  0.49756  0.50850       49  train_cluster_2+BV_1
50     114     120  0.0  0.55024  0.54326       50  train_cluster_2+BV_1
51     117     131  0.0  0.24310  0.29208       51  train_cluster_2+BV_1
52     121     131  0.0  0.19173  0.23972       52  train_cluster_2+BV_1
53     121     132  0.0  0.18105  0.23003       53  train_cluster_2+BV_1

                                                 path
0   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
1   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
2   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
3   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
4   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
5   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
6   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
7   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
8   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
9   /home/alexi/Documents/ValDX/data/HOIPapo_test_...
10  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
11  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
12  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
13  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
14  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
15  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
16  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
17  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
18  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
19  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
20  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
21  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
22  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
23  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
24  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
25  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
26  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
27  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
28  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
29  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
30  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
31  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
32  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
33  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
34  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
35  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
36  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
37  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
38  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
39  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
40  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
41  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
42  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
43  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
44  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
45  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
46  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
47  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
48  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
49  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
50  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
51  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
52  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
53  /home/alexi/Documents/ValDX/data/HOIPapo_test_...
#	ResStr	ResEnd	0.0	0.5	5.0	 times/min

Saved train cluster_2+BV HDX data to /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/train_cluster_2+BV_1_expt_dfracs.dat
    ResStr  ResEnd  0.0      0.5      5.0  peptide           calc_name  \
0      132     149  0.0  0.26140  0.30267       54  val_cluster_2+BV_1
1      132     150  0.0  0.26392  0.30614       55  val_cluster_2+BV_1
2      132     153  0.0  0.26061  0.32801       56  val_cluster_2+BV_1
3      150     169  0.0  0.45297  0.53974       57  val_cluster_2+BV_1
4      151     162  0.0  0.31622  0.45372       58  val_cluster_2+BV_1
5      151     167  0.0  0.43711  0.52972       59  val_cluster_2+BV_1
6      151     169  0.0  0.47628  0.54735       60  val_cluster_2+BV_1
7      151     170  0.0  0.49249  0.57156       61  val_cluster_2+BV_1
8      154     169  0.0  0.50341  0.53212       62  val_cluster_2+BV_1
9      155     169  0.0  0.53500  0.53827       63  val_cluster_2+BV_1
10     169     183  0.0  0.26524  0.35365       64  val_cluster_2+BV_1
11     170     183  0.0  0.25454  0.32548       65  val_cluster_2+BV_1
12     170     185  0.0  0.25152  0.35786       66  val_cluster_2+BV_1
13     170     186  0.0  0.28164  0.36568       67  val_cluster_2+BV_1
14     171     183  0.0  0.24177  0.30174       68  val_cluster_2+BV_1
15     171     186  0.0  0.27969  0.36567       69  val_cluster_2+BV_1
16     184     195  0.0  0.38633  0.44869       70  val_cluster_2+BV_1
17     184     208  0.0  0.24871  0.31226       71  val_cluster_2+BV_1
18     187     195  0.0  0.36820  0.37879       72  val_cluster_2+BV_1
19     187     208  0.0  0.22903  0.26839       73  val_cluster_2+BV_1
20     187     209  0.0  0.21687  0.25989       74  val_cluster_2+BV_1
21     188     208  0.0  0.20479  0.23593       75  val_cluster_2+BV_1
22     194     208  0.0  0.11684  0.15140       76  val_cluster_2+BV_1
23     196     208  0.0  0.13267  0.18143       77  val_cluster_2+BV_1
24     213     223  0.0  0.35203  0.42601       78  val_cluster_2+BV_1
25     224     238  0.0  0.20249  0.21472       79  val_cluster_2+BV_1
26     224     239  0.0  0.16260  0.17496       80  val_cluster_2+BV_1
27     247     257  0.0  0.05688  0.07274       81  val_cluster_2+BV_1
28     247     259  0.0  0.07600  0.11464       82  val_cluster_2+BV_1
29     247     260  0.0  0.08147  0.13526       83  val_cluster_2+BV_1
30     248     259  0.0  0.08527  0.13242       84  val_cluster_2+BV_1

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/reweighting_gamma_3x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/reweighting_gamma_2x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/reweighting_gamma_5x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/reweighting_gamma_4x10^0



Contacts readContacts read

Hbonds readHbonds read

Contacts read
Hbonds read
Segments and experimental dfracs read
Segments and experimental dfracs read
Segments and experimental dfracs read
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output WeightsSum of Output Weights

1.0000000000000002Sum of Output Weights1.0000000000000002

1.0000000000000002

Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.41409990340834957, 7.141322755032981), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.41409990340834957, 7.141322755032981), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.41409990340834957, 7.141322755032981), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.41409990340834957, 7.141322755032981)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/train_cluster_2+BV_1/reweighting_gamma_2x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.39023  0.50546        0
1  0.0  0.30921  0.49797        1
2  0.0  0.38619  0.53803        2
3  0.0  0.43579  0.58496        3
4  0.0  0.33974  0.54394        4
Experimental cluster_2+BV False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat
REWIGHTING val_cluster_2+BV_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 0.41409990340834957, 'bv_bh': 7.141322755032981}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.41409990340834957, 7.141322755032981)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential0/val_cluster_2+BV_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(54, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.30785  0.43509        0
1  0.0  0.29076  0.41097        1
2  0.0  0.24923  0.35234        2
3  0.0  0.00253  0.02427        3
4  0.0  0.00387  0.03685        4
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2+BV_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[ 7.24181775 19.04562054 14.52812086  5.7310651   3.32588262 12.38228503
  6.89980244  5.19778643 11.3124432   4.8046599   0.8876334  10.24158019
 15.32397128 16.41981371  7.00525287  8.98459968  2.86546212  4.11553006
 12.7659423   3.09684633  3.85903799  7.29683793 16.78431217 13.51177073
  5.59879764  8.87608057 18.34364739 17.44960202 14.78479452 14.26654588
 14.59734422 16.35922206 15.36088897 19.5741744  16.93455067 13.68989222
 12.07588573 13.60536497  7.25192209  5.26561193  3.59126645 12.61545839
 11.62480042 12.31317585 21.82185671  6.23911889  3.83341802 14.7643815
  7.74049527  2.33656783  3.59290047  3.34397629  6.5691545   4.11131794
  2.52293105  7.4327083  14.93386298 11.10211562  9.38549836 13.58813968
 18.67709961  6.55365793 12.99926829 17.98760599  6.11268736  2.83926573
  8.90144702 18.29850747 14.99953878 14.69445134 17.4659752  17.37491475
 16.39773751 17.86695275 17.89705497 15.89712148 17.67807594 16.49050452
 15.77806044 15.42898917 14.8371005   9.9946741  12.1956086   3.55917895
 17.80241176 18.52066453  9.75892455 21.76156926 10.05193672  5.22504501
  4.37515437 10.600494    9.52505542  3.13705986  0.89467039  2.62259115
  3.63906872  6.07834314 10.10162541 22.94901972  9.95526265 19.01353603
  4.74558676  4.9394117  12.89654551  6.96674777  8.79567848 19.67404032
 23.58357669 18.13900673  5.35540915  5.67507534 14.05230085  9.11112879
  7.76687556 15.14272117  8.27692231  3.34009842  6.19424944 20.46403355
 14.94253289  2.35356651 11.96146717  7.56754763  7.71773113  5.04160284
 14.70801699 19.7302967  16.60185374 17.37101401 15.58088537 18.27853631
 16.34254152 15.49461387 18.8678768  14.61078315  2.91144042 11.18035823
 14.92784896 11.83940644 10.80140216 13.17508533 12.53888932 13.54744889
 13.46003303 14.85222454 14.77745958 11.9530131  12.0842809  12.09466828
 13.79249002 18.98083063 10.97432149 22.00031919  4.75509235  6.03600561
 13.52921032  8.14788785  7.59819919 15.39053201  8.51858865 10.42031505
  8.54766491  5.36035513  5.59224136  4.2669947   3.81755201  6.12823858
  9.55296638 21.48229455 10.03079833 21.72027799 15.54060319  6.34237104
  6.03007482 15.72184506  9.69200977 11.28555582 23.08113451 23.99094769
 19.58611731  7.89861874  8.70105178 15.59478281  8.32147845  7.52307622
 16.49257452  7.09688679  8.85219016  8.22774424  4.45241122  2.21162355
 12.99937318  2.50428575  2.98650216  5.45989427  4.71910959  8.2455015
  4.48239263  7.76736074  7.47461133  5.56850277  7.78630671  7.85902935
 11.628917   16.82302151  9.54845081  7.88664124 11.26903953 15.1516312
 13.01509075 19.75537314 19.16414656 17.35241943 20.22692784 18.08177491
 13.20280388  9.18912429 12.34611162 13.69578751  4.14328904  3.78098808
 11.05268218  6.59499431  6.18715473  1.24714779  0.98375426  9.95039607
  1.86733664  1.88441542  4.09162334  1.70049788 10.6685312   9.25383337
 19.91953535  9.33331842  8.77574704  8.58122431 17.44481727 11.22619724
 16.5889904   4.94959072 11.84532156  9.1902393  19.92323919 18.58389606
 17.49030664 18.2470134  18.71590543 17.94110921 17.20807813 15.96514814
 18.10304067 17.83053413 13.97919207 11.81410798 13.34040743 14.84790305
  6.99831837 10.4869143  10.81801772 13.25138843 16.19142066 14.85108645
  5.32153803 17.19643991 18.36086763 19.50131586 15.00353545 12.77328646
 12.04049819  7.85496135  7.21085982  6.51514203  3.90190823 13.14910021
  0.13612186  0.82819981 10.10988274  2.93585519 13.53368611 17.73932276
 17.28208076 14.49423777 16.53102945 18.23925183 17.25888449 15.99256279
 16.02134788]
LogPf_by_res [ 7.24181775 19.04562054 14.52812086  5.7310651   3.32588262 12.38228503
  6.89980244  5.19778643 11.3124432   4.8046599   0.8876334  10.24158019
 15.32397128 16.41981371  7.00525287  8.98459968  2.86546212  4.11553006
 12.7659423   3.09684633  3.85903799  7.29683793 16.78431217 13.51177073
  5.59879764  8.87608057 18.34364739 17.44960202 14.78479452 14.26654588
 14.59734422 16.35922206 15.36088897 19.5741744  16.93455067 13.68989222
 12.07588573 13.60536497  7.25192209  5.26561193  3.59126645 12.61545839
 11.62480042 12.31317585 21.82185671  6.23911889  3.83341802 14.7643815
  7.74049527  2.33656783  3.59290047  3.34397629  6.5691545   4.11131794
  2.52293105  7.4327083  14.93386298 11.10211562  9.38549836 13.58813968
 18.67709961  6.55365793 12.99926829 17.98760599  6.11268736  2.83926573
  8.90144702 18.29850747 14.99953878 14.69445134 17.4659752  17.37491475
 16.39773751 17.86695275 17.89705497 15.89712148 17.67807594 16.49050452
 15.77806044 15.42898917 14.8371005   9.9946741  12.1956086   3.55917895
 17.80241176 18.52066453  9.75892455 21.76156926 10.05193672  5.22504501
  4.37515437 10.600494    9.52505542  3.13705986  0.89467039  2.62259115
  3.63906872  6.07834314 10.10162541 22.94901972  9.95526265 19.01353603
  4.74558676  4.9394117  12.89654551  6.96674777  8.79567848 19.67404032
 23.58357669 18.13900673  5.35540915  5.67507534 14.05230085  9.11112879
  7.76687556 15.14272117  8.27692231  3.34009842  6.19424944 20.46403355
 14.94253289  2.35356651 11.96146717  7.56754763  7.71773113  5.04160284
 14.70801699 19.7302967  16.60185374 17.37101401 15.58088537 18.27853631
 16.34254152 15.49461387 18.8678768  14.61078315  2.91144042 11.18035823
 14.92784896 11.83940644 10.80140216 13.17508533 12.53888932 13.54744889
 13.46003303 14.85222454 14.77745958 11.9530131  12.0842809  12.09466828
 13.79249002 18.98083063 10.97432149 22.00031919  4.75509235  6.03600561
 13.52921032  8.14788785  7.59819919 15.39053201  8.51858865 10.42031505
  8.54766491  5.36035513  5.59224136  4.2669947   3.81755201  6.12823858
  9.55296638 21.48229455 10.03079833 21.72027799 15.54060319  6.34237104
  6.03007482 15.72184506  9.69200977 11.28555582 23.08113451 23.99094769
 19.58611731  7.89861874  8.70105178 15.59478281  8.32147845  7.52307622
 16.49257452  7.09688679  8.85219016  8.22774424  4.45241122  2.21162355
 12.99937318  2.50428575  2.98650216  5.45989427  4.71910959  8.2455015
  4.48239263  7.76736074  7.47461133  5.56850277  7.78630671  7.85902935
 11.628917   16.82302151  9.54845081  7.88664124 11.26903953 15.1516312
 13.01509075 19.75537314 19.16414656 17.35241943 20.22692784 18.08177491
 13.20280388  9.18912429 12.34611162 13.69578751  4.14328904  3.78098808
 11.05268218  6.59499431  6.18715473  1.24714779  0.98375426  9.95039607
  1.86733664  1.88441542  4.09162334  1.70049788 10.6685312   9.25383337
 19.91953535  9.33331842  8.77574704  8.58122431 17.44481727 11.22619724
 16.5889904   4.94959072 11.84532156  9.1902393  19.92323919 18.58389606
 17.49030664 18.2470134  18.71590543 17.94110921 17.20807813 15.96514814
 18.10304067 17.83053413 13.97919207 11.81410798 13.34040743 14.84790305
  6.99831837 10.4869143  10.81801772 13.25138843 16.19142066 14.85108645
  5.32153803 17.19643991 18.36086763 19.50131586 15.00353545 12.77328646
 12.04049819  7.85496135  7.21085982  6.51514203  3.90190823 13.14910021
  0.13612186  0.82819981 10.10988274  2.93585519 13.53368611 17.73932276
 17.28208076 14.49423777 16.53102945 18.23925183 17.25888449 15.99256279
 16.02134788]
Pf_by_res [1.39663040e+03 1.86813348e+08 2.03930753e+06 3.08297462e+02
 2.78235453e+01 2.38538269e+05 9.92078701e+02 1.80871427e+02
 8.18336005e+04 1.22077966e+02 2.42937349e+00 2.80454081e+04
 4.51976827e+06 1.35217993e+07 1.10240879e+03 7.97924986e+03
 1.75571648e+01 6.12846904e+01 3.50088864e+05 2.21280566e+01
 4.74197111e+01 1.47562651e+03 1.94685747e+07 7.38052862e+05
 2.70101453e+02 7.15867773e+03 9.25858968e+07 3.78674332e+07
 2.63605625e+06 1.56993673e+06 2.18547602e+06 1.27268190e+07
 4.68974594e+06 3.16924586e+08 2.26246521e+07 8.81951387e+05
 1.75586263e+05 8.10466240e+05 1.41081395e+03 1.93564721e+02
 3.62799936e+01 3.01178499e+05 1.11837300e+05 2.22609823e+05
 2.99993575e+09 5.12406825e+02 4.62202504e+01 2.58279189e+06
 2.29961102e+03 1.03456674e+01 3.63393242e+01 2.83315576e+01
 7.12766943e+02 6.10270947e+01 1.24650790e+01 1.69037943e+03
 3.05980878e+06 6.63113013e+04 1.19143443e+04 7.96625281e+05
 1.29229391e+08 7.01806645e+02 4.42089792e+05 6.48512010e+07
 4.51550565e+02 1.71032025e+01 7.34259075e+03 8.84995007e+07
 3.26750997e+06 2.40834739e+06 3.84925472e+07 3.51422530e+07
 1.32265604e+07 5.74802949e+07 5.92368851e+07 8.01737384e+06
 4.75872747e+07 1.45122623e+07 7.11745263e+06 5.02024438e+06
 2.77760748e+06 2.19094668e+04 1.97918103e+05 3.51343384e+01
 5.38876436e+07 1.10515299e+08 1.73080078e+04 2.82442109e+09
 2.32006767e+04 1.85869537e+02 7.94521034e+01 4.01546689e+04
 1.36986891e+04 2.30360380e+01 2.44652925e+00 1.37713611e+01
 3.80563790e+01 4.36305698e+02 2.43826091e+04 9.26046151e+09
 2.10627773e+04 1.80914668e+08 1.15075308e+02 1.39688047e+02
 3.98931704e+05 1.06076727e+03 6.60563587e+03 3.50208874e+08
 1.74669557e+10 7.54519609e+07 2.11750597e+02 2.91510300e+02
 1.26717536e+06 9.05551091e+03 2.36108269e+03 3.77051130e+06
 3.93207403e+03 2.82219042e+01 4.89923589e+02 7.71643760e+08
 3.08645238e+06 1.05230334e+01 1.56602679e+05 1.93439063e+03
 2.24785371e+03 1.54717805e+02 2.44124078e+06 3.70475066e+08
 1.62215918e+07 3.50054392e+07 5.84376224e+06 8.67495950e+07
 1.25162896e+07 5.36074688e+06 1.56392088e+08 2.21504472e+06
 1.83832592e+01 7.17080457e+04 3.04146225e+06 1.38608187e+05
 4.90895843e+04 5.27068253e+05 2.78978311e+05 7.64860611e+05
 7.00838690e+05 2.81993542e+06 2.61679169e+06 1.55284330e+05
 1.77066544e+05 1.78915387e+05 9.77242417e+05 1.75093492e+08
 5.83562352e+04 3.58605731e+09 1.16174381e+02 4.18219166e+02
 7.51037091e+05 3.45607160e+03 1.99460075e+03 4.83084526e+06
 5.00698217e+03 3.35339973e+04 5.15470367e+03 2.12800506e+02
 2.68336383e+02 7.13070140e+01 4.54927061e+01 4.58627615e+02
 1.40864184e+04 2.13620036e+09 2.27153987e+04 2.71017215e+09
 5.61304097e+06 5.68141805e+02 4.15746135e+02 6.72838071e+06
 1.61877453e+04 7.96626257e+04 1.05684027e+10 2.62504164e+10
 3.20732278e+08 2.69355926e+03 6.00922927e+03 5.92554257e+06
 4.11123376e+03 1.85025033e+03 1.45423337e+07 1.20819984e+03
 6.98968072e+03 3.74338004e+03 8.58336589e+01 9.13052822e+00
 4.42136165e+05 1.22348171e+01 1.98162470e+01 2.35072569e+02
 1.12068421e+02 3.81044592e+03 8.84460383e+01 2.36222851e+03
 1.76271644e+03 2.62041468e+02 2.40740988e+03 2.58900614e+03
 1.12298637e+05 2.02369664e+07 1.40229536e+04 2.66148958e+03
 7.83577007e+04 3.80425676e+06 4.49140372e+05 3.79882724e+08
 2.10321224e+08 3.43605420e+07 6.08755850e+08 7.12549544e+07
 5.41882180e+05 9.79007391e+03 2.30063726e+05 8.87166106e+05
 6.30097227e+01 4.38593570e+01 6.31130085e+04 7.31424724e+02
 4.86460026e+02 3.48040194e+00 2.67447811e+00 2.09605225e+04
 6.47103874e+00 6.58250534e+00 5.98369487e+01 5.47667346e+00
 4.29817634e+04 1.04445268e+04 4.47655871e+08 1.13085959e+04
 6.47527945e+03 5.33062788e+03 3.76866799e+07 7.50715724e+04
 1.60142643e+07 1.41117195e+02 1.39430501e+05 9.80099606e+03
 4.49316989e+08 1.17729016e+08 3.94406135e+07 8.40576472e+07
 1.34342818e+08 6.19048576e+07 2.97422197e+07 8.58174768e+06
 7.27864717e+07 5.54246018e+07 1.17783913e+06 1.35145598e+05
 6.21820926e+05 2.80777538e+06 1.09479058e+03 3.58433845e+04
 4.99120490e+04 5.68859316e+05 1.07608021e+07 2.81672790e+06
 2.04698472e+02 2.93980797e+07 9.41940554e+07 2.94655035e+08
 3.28059528e+06 3.52669436e+05 1.69481353e+05 2.57849546e+03
 1.35405601e+03 6.75289868e+02 4.94968104e+01 5.13548735e+05
 1.14582152e+00 2.28919404e+00 2.45847777e+04 1.88376060e+01
 7.54406107e+05 5.05929482e+07 3.20267086e+07 1.97136699e+06
 1.51124498e+07 8.34077537e+07 3.12923584e+07 8.82026780e+06
 9.07784946e+06]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [2.93570685e+01 2.00164139e-05 2.20450686e-03 8.20019590e-01
 1.37525017e+02 1.75887960e-02 7.34933514e-01 5.43781230e+00
 4.07251337e-03 4.74413343e+00 2.22484565e+03 1.13483419e-01
 4.54650849e-04 1.38598870e-04 1.82159367e+00 4.17668876e-02
 3.78738793e+01 7.68143181e+01 3.01034229e-02 1.57706975e+02
 7.88560961e+01 2.59309081e+00 1.92070214e-05 4.21411815e-03
 3.39834348e+00 4.87485121e-01 2.79414757e-05 4.61879097e-05
 9.15881954e-04 1.01604286e-03 4.60519614e-04 9.72913674e-05
 7.97342402e-05 2.35417230e-06 1.47303229e-05 8.07884971e-04
 7.38420321e-03 1.00939058e-03 9.40425573e-01 1.68254997e+00
 1.75035837e+01 8.39402416e-03 7.31488502e-03 1.46301862e-03
 1.27550517e-06 1.42291603e+00 1.14277803e+02 1.62444407e-03
 9.79805325e-01 8.87228897e+01 6.05922867e+00 2.34705747e+01
 3.54688109e+00 1.72691739e+01 5.71609112e+01 1.36398620e+00
 1.72623489e-04 3.09889333e-03 1.53717753e-01 1.70427664e-03
 7.26830058e-06 2.32582321e+00 4.75645826e-03 1.02535948e-05
 1.34303641e+00 5.36681658e+01 1.14010504e-01 7.68870781e-06
 4.35088150e-04 1.38380548e-04 1.16793192e-05 3.28824808e-05
 1.20599986e-04 2.65017888e-05 7.41655058e-06 8.29396201e-05
 3.27569413e-05 5.76844906e-05 5.25375229e-05 4.80916103e-05
 2.74867444e-04 8.95699572e-02 1.33754580e-02 1.89261552e+01
 1.78363088e-05 3.46235641e-06 1.75609133e-02 1.45165940e-06
 1.93773117e-01 7.82683105e+00 1.05363157e+02 2.62456979e-01
 1.06197713e-01 4.79056117e+01 4.40802211e+02 1.18527005e+02
 2.70624252e+01 1.21060731e+00 2.48721885e-02 9.68638108e-08
 5.12010114e-02 4.62722264e-05 7.27464881e+00 5.99287100e+01
 8.95149606e-03 1.89310222e+00 2.58749516e-01 3.29964357e-06
 3.47197794e-07 1.18884065e-05 5.21158149e+00 3.00704738e+01
 3.23561960e-03 2.21758981e-01 1.02254629e+00 2.07201994e-04
 1.94165690e-01 2.46721992e+01 2.10216029e+00 2.06717540e-06
 6.81294048e-04 1.86489004e+02 1.43878198e-02 2.54829673e+00
 4.68841591e+00 2.25555739e+01 4.62576536e-04 1.30027496e-06
 1.02967628e-04 1.77279552e-04 1.76238845e-04 1.03401472e-05
 1.60442187e-04 3.83326527e-04 3.22536892e-05 1.50456752e-03
 3.07873044e+01 6.71778800e-03 5.36675471e-04 1.44878951e-02
 2.96349925e-02 3.55571807e-03 1.76694787e-03 1.02143770e-03
 1.76675410e-03 3.10852965e-04 1.42897630e-04 5.77652349e-03
 8.80354654e-03 1.54933911e-02 2.52808614e-03 1.99307744e-06
 1.60955906e-02 9.73143645e-07 5.72379155e+00 1.66490802e+01
 5.45924758e-03 2.78106696e-01 1.70977199e+00 2.81041885e-04
 2.83934478e-01 9.93822563e-03 1.51562051e-01 7.15849162e+00
 7.31332063e+00 2.45279881e+01 1.71732466e+02 9.57930442e+00
 9.20435991e-02 4.71142403e-07 5.08714145e-02 2.69027885e-06
 6.81704190e-04 4.05823722e+00 2.01356640e+01 8.03310824e-04
 1.03182920e-01 2.52080679e-02 1.09341448e-07 2.31024468e-07
 3.28587855e-05 8.75926452e-01 1.30009594e+00 4.07442242e-04
 1.06861682e+00 1.43074978e+00 5.01371994e-05 4.27223765e+00
 3.45411536e-01 1.86007414e+00 6.59381185e+00 2.46773359e+02
 2.49596296e-02 4.41770482e+02 2.11725306e+01 3.56116603e+00
 1.35928624e+01 1.02758646e+00 7.51823318e+00 2.62707379e-01
 9.26001569e-01 5.68099171e+00 5.77090784e-01 3.38579841e-01
 2.35732627e-02 1.72444269e-04 8.43246753e-02 1.68915462e-01
 9.97039795e-03 9.82933996e-05 2.09127951e-03 2.36126447e-06
 8.70785273e-06 1.27859844e-05 3.37560041e-07 1.25886486e-05
 4.66540458e-03 2.64245869e-01 3.55587124e-02 5.95373136e-04
 1.42359551e+01 2.14156823e+01 7.12320254e-02 3.08052359e+00
 3.20440217e+00 2.09490714e+02 4.42135239e+02 8.94112310e-02
 2.35407436e+02 3.19450047e+02 4.22498079e+00 1.24244545e+02
 4.06920855e-02 1.67457810e-01 1.74521884e-05 4.77953328e-01
 6.47941296e-02 3.20638605e-02 1.53676088e-05 1.37188803e-02
 1.14363433e-04 9.18785726e+00 1.28361976e-03 1.02689009e-01
 2.09045747e-06 1.10131274e-05 3.28738458e-05 5.73082241e-06
 2.78342628e-06 2.51807957e-06 7.23470453e-05 7.74851423e-05
 1.99868112e-06 4.15998337e-05 2.24754398e-03 7.44718724e-03
 6.59369482e-03 2.36827328e-04 8.98386345e-01 2.03416027e-02
 2.16067167e-02 9.28515807e-04 3.89896676e-05 3.91786331e-04
 8.74338458e-01 6.83085732e-05 1.14490824e-05 5.29030011e-06

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
       Bc        Bh             calc_name
0  0.4141  7.141323  train_cluster_2+BV_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_s_naive_sequential/20240402-191926_analysis.csv
dict_keys(['cluster_2+BV_s_naive_sequential'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_s_naive_sequential to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV_s_naive_sequential/cluster_2+BV_s_naive_sequential0_1712081966.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2+BV_s_naive_sequential': {'train_dfs': [    0.0      0.5      5.0  peptide             calc_name
0   0.0  0.39023  0.50546        0  train_cluster_2+BV_1
1   0.0  0.30921  0.49797        1  train_cluster_2+BV_1
2   0.0  0.38619  0.53803        2  train_cluster_2+BV_1
3   0.0  0.43579  0.58496        3  train_cluster_2+BV_1
4   0.0  0.33974  0.54394        4  train_cluster_2+BV_1
5   0.0  0.41560  0.57647        5  train_cluster_2+BV_1
6   0.0  0.46119  0.61712        6  train_cluster_2+BV_1
7   0.0  0.34332  0.49609        7  train_cluster_2+BV_1
8   0.0  0.46270  0.58771        8  train_cluster_2+BV_1
9   0.0  0.42461  0.54329        9  train_cluster_2+BV_1
10  0.0  0.50218  0.63442       10  train_cluster_2+BV_1
11  0.0  0.47080  0.59477       11  train_cluster_2+BV_1
12  0.0  0.30769  0.49209       12  train_cluster_2+BV_1
13  0.0  0.46151  0.60496       13  train_cluster_2+BV_1
14  0.0  0.41592  0.54994       14  train_cluster_2+BV_1
15  0.0  0.51327  0.62495       15  train_cluster_2+BV_1
16  0.0  0.47119  0.60687       16  train_cluster_2+BV_1
17  0.0  0.57385  0.67527       17  train_cluster_2+BV_1
18  0.0  0.14926  0.38338       18  train_cluster_2+BV_1
19  0.0  0.12447  0.32033       19  train_cluster_2+BV_1
20  0.0  0.12447  0.32033       20  train_cluster_2+BV_1
21  0.0  0.00063  0.00618       21  train_cluster_2+BV_1
22  0.0  0.00069  0.00682       22  train_cluster_2+BV_1
23  0.0  0.00067  0.00657       23  train_cluster_2+BV_1
24  0.0  0.23913  0.43486       24  train_cluster_2+BV_1
25  0.0  0.23913  0.43486       25  train_cluster_2+BV_1
26  0.0  0.32718  0.55572       26  train_cluster_2+BV_1
27  0.0  0.21647  0.34219       27  train_cluster_2+BV_1
28  0.0  0.32119  0.50132       28  train_cluster_2+BV_1
29  0.0  0.32732  0.52167       29  train_cluster_2+BV_1
30  0.0  0.49986  0.75827       30  train_cluster_2+BV_1
31  0.0  0.37167  0.59347       31  train_cluster_2+BV_1
32  0.0  0.37888  0.56747       32  train_cluster_2+BV_1
33  0.0  0.52837  0.79693       33  train_cluster_2+BV_1
34  0.0  0.35862  0.57804       34  train_cluster_2+BV_1
35  0.0  0.24829  0.38442       35  train_cluster_2+BV_1
36  0.0  0.22068  0.34804       36  train_cluster_2+BV_1
37  0.0  0.25746  0.40603       37  train_cluster_2+BV_1
38  0.0  0.22068  0.34804       38  train_cluster_2+BV_1
39  0.0  0.17165  0.27078       39  train_cluster_2+BV_1
40  0.0  0.15449  0.24372       40  train_cluster_2+BV_1
41  0.0  0.08398  0.15081       41  train_cluster_2+BV_1
42  0.0  0.00423  0.03576       42  train_cluster_2+BV_1
43  0.0  0.00462  0.03900       43  train_cluster_2+BV_1
44  0.0  0.00564  0.04758       44  train_cluster_2+BV_1
45  0.0  0.00634  0.05353       45  train_cluster_2+BV_1
46  0.0  0.01746  0.12348       46  train_cluster_2+BV_1
47  0.0  0.26060  0.34261       47  train_cluster_2+BV_1
48  0.0  0.22267  0.36452       48  train_cluster_2+BV_1
49  0.0  0.49882  0.62006       49  train_cluster_2+BV_1
50  0.0  0.41529  0.55674       50  train_cluster_2+BV_1
51  0.0  0.26499  0.37376       51  train_cluster_2+BV_1
52  0.0  0.37858  0.50178       52  train_cluster_2+BV_1
53  0.0  0.44073  0.55160       53  train_cluster_2+BV_1], 'val_dfs': [    0.0      0.5      5.0  peptide           calc_name
0   0.0  0.30785  0.43509       54  val_cluster_2+BV_1
1   0.0  0.29076  0.41097       55  val_cluster_2+BV_1
2   0.0  0.24923  0.35234       56  val_cluster_2+BV_1
3   0.0  0.00253  0.02427       57  val_cluster_2+BV_1
4   0.0  0.00387  0.03685       58  val_cluster_2+BV_1
5   0.0  0.00284  0.02712       59  val_cluster_2+BV_1
6   0.0  0.00268  0.02565       60  val_cluster_2+BV_1
7   0.0  0.00277  0.02662       61  val_cluster_2+BV_1
8   0.0  0.00323  0.03095       62  val_cluster_2+BV_1
9   0.0  0.00348  0.03332       63  val_cluster_2+BV_1
10  0.0  0.21533  0.36176       64  val_cluster_2+BV_1
11  0.0  0.23291  0.38832       65  val_cluster_2+BV_1
12  0.0  0.20211  0.35489       66  val_cluster_2+BV_1
13  0.0  0.25344  0.39790       67  val_cluster_2+BV_1
14  0.0  0.25373  0.42022       68  val_cluster_2+BV_1
15  0.0  0.27127  0.42365       69  val_cluster_2+BV_1
16  0.0  0.37187  0.53230       70  val_cluster_2+BV_1
17  0.0  0.31388  0.50727       71  val_cluster_2+BV_1
18  0.0  0.30918  0.44940       72  val_cluster_2+BV_1
19  0.0  0.28171  0.47211       73  val_cluster_2+BV_1
20  0.0  0.26891  0.45066       74  val_cluster_2+BV_1
21  0.0  0.27217  0.44580       75  val_cluster_2+BV_1
22  0.0  0.24592  0.45161       76  val_cluster_2+BV_1
23  0.0  0.21450  0.44326       77  val_cluster_2+BV_1
24  0.0  0.59980  0.83463       78  val_cluster_2+BV_1
25  0.0  0.18934  0.40954       79  val_cluster_2+BV_1
26  0.0  0.17589  0.38103       80  val_cluster_2+BV_1
27  0.0  0.21406  0.29223       81  val_cluster_2+BV_1
28  0.0  0.24678  0.35183       82  val_cluster_2+BV_1
29  0.0  0.28922  0.40169       83  val_cluster_2+BV_1
30  0.0  0.26921  0.38381       84  val_cluster_2+BV_1
31  0.0  0.31332  0.43516       85  val_cluster_2+BV_1
32  0.0  0.30580  0.41745       86  val_cluster_2+BV_1
33  0.0  0.37598  0.52218       87  val_cluster_2+BV_1
34  0.0  0.51911  0.63793       88  val_cluster_2+BV_1
35  0.0  0.39557  0.63048       89  val_cluster_2+BV_1
36  0.0  0.36636  0.59338       90  val_cluster_2+BV_1
37  0.0  0.31772  0.51626       91  val_cluster_2+BV_1
38  0.0  0.31312  0.48616       92  val_cluster_2+BV_1
39  0.0  0.00001  0.00010       93  val_cluster_2+BV_1
40  0.0  0.00001  0.00010       94  val_cluster_2+BV_1
41  0.0  0.00001  0.00011       95  val_cluster_2+BV_1
42  0.0  0.06130  0.18050       96  val_cluster_2+BV_1
43  0.0  0.07345  0.21546       97  val_cluster_2+BV_1
44  0.0  0.08119  0.23534       98  val_cluster_2+BV_1
45  0.0  0.24525  0.30858       99  val_cluster_2+BV_1
46  0.0  0.25888  0.32572      100  val_cluster_2+BV_1
47  0.0  0.24525  0.30858      101  val_cluster_2+BV_1
48  0.0  0.29123  0.36633      102  val_cluster_2+BV_1
49  0.0  0.27410  0.34478      103  val_cluster_2+BV_1
50  0.0  0.23299  0.29314      104  val_cluster_2+BV_1
51  0.0  0.31051  0.38937      105  val_cluster_2+BV_1
52  0.0  0.25876  0.32456      106  val_cluster_2+BV_1
53  0.0  0.27093  0.31931      107  val_cluster_2+BV_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                                name split_type
0    cluster_2+BV_s_naive_sequential          s
1    cluster_2+BV_s_naive_sequential          s
2    cluster_2+BV_s_naive_sequential          s
3    cluster_2+BV_s_naive_sequential          s
4    cluster_2+BV_s_naive_sequential          s
5    cluster_2+BV_s_naive_sequential          s
6    cluster_2+BV_s_naive_sequential          s
7    cluster_2+BV_s_naive_sequential          s
8    cluster_2+BV_s_naive_sequential          s
9    cluster_2+BV_s_naive_sequential          s
10   cluster_2+BV_s_naive_sequential          s
11   cluster_2+BV_s_naive_sequential          s
12   cluster_2+BV_s_naive_sequential          s
13   cluster_2+BV_s_naive_sequential          s
14   cluster_2+BV_s_naive_sequential          s
15   cluster_2+BV_s_naive_sequential          s
16   cluster_2+BV_s_naive_sequential          s
17   cluster_2+BV_s_naive_sequential          s
18   cluster_2+BV_s_naive_sequential          s
19   cluster_2+BV_s_naive_sequential          s
20   cluster_2+BV_s_naive_sequential          s
21   cluster_2+BV_s_naive_sequential          s
22   cluster_2+BV_s_naive_sequential          s
23   cluster_2+BV_s_naive_sequential          s
24   cluster_2+BV_s_naive_sequential          s
25   cluster_2+BV_s_naive_sequential          s
26   cluster_2+BV_s_naive_sequential          s
27   cluster_2+BV_s_naive_sequential          s
28   cluster_2+BV_s_naive_sequential          s
29   cluster_2+BV_s_naive_sequential          s
30   cluster_2+BV_s_naive_sequential          s
31   cluster_2+BV_s_naive_sequential          s
32   cluster_2+BV_s_naive_sequential          s
33   cluster_2+BV_s_naive_sequential          s
34   cluster_2+BV_s_naive_sequential          s
35   cluster_2+BV_s_naive_sequential          s
36   cluster_2+BV_s_naive_sequential          s
37   cluster_2+BV_s_naive_sequential          s
38   cluster_2+BV_s_naive_sequential          s
39   cluster_2+BV_s_naive_sequential          s
40   cluster_2+BV_s_naive_sequential          s
41   cluster_2+BV_s_naive_sequential          s
42   cluster_2+BV_s_naive_sequential          s
43   cluster_2+BV_s_naive_sequential          s
44   cluster_2+BV_s_naive_sequential          s
45   cluster_2+BV_s_naive_sequential          s
46   cluster_2+BV_s_naive_sequential          s
47   cluster_2+BV_s_naive_sequential          s
48   cluster_2+BV_s_naive_sequential          s
49   cluster_2+BV_s_naive_sequential          s
50   cluster_2+BV_s_naive_sequential          s
51   cluster_2+BV_s_naive_sequential          s
52   cluster_2+BV_s_naive_sequential          s
53   cluster_2+BV_s_naive_sequential          s
54   cluster_2+BV_s_naive_sequential          s
55   cluster_2+BV_s_naive_sequential          s
56   cluster_2+BV_s_naive_sequential          s
57   cluster_2+BV_s_naive_sequential          s
58   cluster_2+BV_s_naive_sequential          s
59   cluster_2+BV_s_naive_sequential          s
60   cluster_2+BV_s_naive_sequential          s
61   cluster_2+BV_s_naive_sequential          s
62   cluster_2+BV_s_naive_sequential          s
63   cluster_2+BV_s_naive_sequential          s
64   cluster_2+BV_s_naive_sequential          s
65   cluster_2+BV_s_naive_sequential          s
66   cluster_2+BV_s_naive_sequential          s
67   cluster_2+BV_s_naive_sequential          s
68   cluster_2+BV_s_naive_sequential          s
69   cluster_2+BV_s_naive_sequential          s
70   cluster_2+BV_s_naive_sequential          s
71   cluster_2+BV_s_naive_sequential          s
72   cluster_2+BV_s_naive_sequential          s
73   cluster_2+BV_s_naive_sequential          s
74   cluster_2+BV_s_naive_sequential          s
75   cluster_2+BV_s_naive_sequential          s
76   cluster_2+BV_s_naive_sequential          s
77   cluster_2+BV_s_naive_sequential          s
78   cluster_2+BV_s_naive_sequential          s
79   cluster_2+BV_s_naive_sequential          s
80   cluster_2+BV_s_naive_sequential          s
81   cluster_2+BV_s_naive_sequential          s
82   cluster_2+BV_s_naive_sequential          s
83   cluster_2+BV_s_naive_sequential          s
84   cluster_2+BV_s_naive_sequential          s
85   cluster_2+BV_s_naive_sequential          s
86   cluster_2+BV_s_naive_sequential          s
87   cluster_2+BV_s_naive_sequential          s
88   cluster_2+BV_s_naive_sequential          s
89   cluster_2+BV_s_naive_sequential          s
90   cluster_2+BV_s_naive_sequential          s
91   cluster_2+BV_s_naive_sequential          s
92   cluster_2+BV_s_naive_sequential          s
93   cluster_2+BV_s_naive_sequential          s
94   cluster_2+BV_s_naive_sequential          s
95   cluster_2+BV_s_naive_sequential          s
96   cluster_2+BV_s_naive_sequential          s
97   cluster_2+BV_s_naive_sequential          s
98   cluster_2+BV_s_naive_sequential          s
99   cluster_2+BV_s_naive_sequential          s
100  cluster_2+BV_s_naive_sequential          s
101  cluster_2+BV_s_naive_sequential          s
102  cluster_2+BV_s_naive_sequential          s
103  cluster_2+BV_s_naive_sequential          s
104  cluster_2+BV_s_naive_sequential          s
105  cluster_2+BV_s_naive_sequential          s
106  cluster_2+BV_s_naive_sequential          s
107  cluster_2+BV_s_naive_sequential          s  , 'merge_df':      0.0      0.5      5.0  peptide             calc_name  \
0    0.0  0.41879  0.44438        0          Experimental
1    0.0  0.37096  0.45204        1          Experimental
2    0.0  0.40040  0.48544        2          Experimental
3    0.0  0.45875  0.51503        3          Experimental
4    0.0  0.41726  0.49519        4          Experimental
5    0.0  0.44176  0.50927        5          Experimental
6    0.0  0.48987  0.54090        6          Experimental
7    0.0  0.41316  0.48254        7          Experimental
8    0.0  0.46617  0.51066        8          Experimental
9    0.0  0.46825  0.52028        9          Experimental
10   0.0  0.48273  0.53102       10          Experimental
11   0.0  0.50258  0.53988       11          Experimental
12   0.0  0.47373  0.50144       12          Experimental
13   0.0  0.52057  0.54102       13          Experimental
14   0.0  0.52823  0.55640       14          Experimental
15   0.0  0.55802  0.57504       15          Experimental
16   0.0  0.55641  0.57196       16          Experimental
17   0.0  0.52928  0.54827       17          Experimental
18   0.0  0.17163  0.27883       18          Experimental
19   0.0  0.16883  0.28686       19          Experimental
20   0.0  0.16341  0.27353       20          Experimental
21   0.0  0.32309  0.41205       21          Experimental
22   0.0  0.31355  0.39928       22          Experimental
23   0.0  0.34392  0.42213       23          Experimental
24   0.0  0.35604  0.35617       24          Experimental
25   0.0  0.34105  0.35125       25          Experimental
26   0.0  0.34135  0.38830       26          Experimental
27   0.0  0.28512  0.29602       27          Experimental
28   0.0  0.28439  0.33185       28          Experimental
29   0.0  0.32954  0.39085       29          Experimental
30   0.0  0.26192  0.34619       30          Experimental
31   0.0  0.31421  0.37857       31          Experimental
32   0.0  0.32314  0.38565       32          Experimental
33   0.0  0.29666  0.37860       33          Experimental
34   0.0  0.38440  0.44775       34          Experimental
35   0.0  0.33633  0.46390       35          Experimental
36   0.0  0.34716  0.45807       36          Experimental
37   0.0  0.34165  0.44393       37          Experimental
38   0.0  0.30725  0.43533       38          Experimental
39   0.0  0.33252  0.48976       39          Experimental
40   0.0  0.28369  0.42940       40          Experimental
41   0.0  0.35906  0.50293       41          Experimental
42   0.0  0.33575  0.45181       42          Experimental
43   0.0  0.33443  0.43697       43          Experimental
44   0.0  0.37082  0.47284       44          Experimental
45   0.0  0.37847  0.48848       45          Experimental
46   0.0  0.22218  0.31040       46          Experimental
47   0.0  0.18217  0.28305       47          Experimental
48   0.0  0.25719  0.37045       48          Experimental
49   0.0  0.49756  0.50850       49          Experimental
50   0.0  0.55024  0.54326       50          Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/train_cluster_2+BV_1/reweighting_gamma_2x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/train_cluster_2+BV_1/reweighting_gamma_3x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/train_cluster_2+BV_1/reweighting_gamma_4x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/train_cluster_2+BV_1/reweighting_gamma_5x10^0



Contacts readContacts read

Hbonds readHbonds read

Contacts readContacts read

Hbonds readHbonds read

Segments and experimental dfracs read
Segments and experimental dfracs read
Segments and experimental dfracs read
Segments and experimental dfracs read
Sum of Output WeightsSum of Output Weights

1.0000000000000002
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.44307870625331947, 8.739727063273913), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.44307870625331947, 8.739727063273913), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.44307870625331947, 8.739727063273913), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.44307870625331947, 8.739727063273913)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/train_cluster_2+BV_1/reweighting_gamma_2x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(46, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.20654  0.35846        0
1  0.0  0.19732  0.31776        1
2  0.0  0.23020  0.37072        2
3  0.0  0.19732  0.31776        3
4  0.0  0.15347  0.24715        4
Experimental cluster_2+BV False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat
REWIGHTING val_cluster_2+BV_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 0.44307870625331947, 'bv_bh': 8.739727063273913}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.44307870625331947, 8.739727063273913)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence0/val_cluster_2+BV_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(50, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.37343  0.49041        0
1  0.0  0.22142  0.44756        1
2  0.0  0.31665  0.49501        2
3  0.0  0.37129  0.54855        3
4  0.0  0.24351  0.49180        4
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2+BV_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44
45       89      97       45

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[ 7.74860176 21.35208095 16.51844564  6.13212631  3.55862862 14.22244375
  7.38265214  5.56152867 12.98010789  5.14089107  0.94975018 11.93193191
 17.30884752 18.54251957  7.49548202  9.61334396  3.06598779  4.40353577
 14.63294944  3.31356433  4.12909432  7.80747227 18.93252572 14.45732743
  5.99060274  9.62223994 20.60098356 19.6443727  16.79308138 16.23856558
 16.50234008 18.47768771 17.40949105 21.91762313 19.09327795 15.62155757
 13.89460256 15.53111509  7.86828826  5.63410062  3.84258407 14.47193463
 12.72188668 13.17485462 24.44760803  6.67573381  4.10168146 16.89624914
  8.28217684  2.50008136  3.84433244  3.5779885   7.02886538  4.39902888
  2.69948633  8.22917569 16.58813039 12.3135314  10.47678488 15.48000975
 20.94093852  7.13729365 14.94647059 20.3450356   6.54045457  3.03795817
  9.64938154 20.67769403 17.14786278 16.66374134 19.62921705 19.53178418
 18.64390778 20.21593902 20.24814779 18.10825851 20.01384457 18.74316664
 17.98086557 17.48235692 16.84904774 11.32530274 14.02270366  3.80825108
 20.02187215 20.7903884  10.56686554 24.38310165 10.88038277  5.59069482
  4.68132864 11.96834361 10.19162091  3.356592    0.95727962  2.80612066
  4.00260661  6.50370694 10.8085394  25.52864087 10.65193414 21.31775116
  5.07768397  5.28507283 14.77269229  7.45428232  9.41120201 22.02447768
 26.20760427 20.38202211  5.73018187  6.07221837 15.94818531  9.87373689
  8.43541252 17.30106511  8.98115245  3.69884854  6.87774296 22.99476411
 16.96185832  2.51826961 13.77217696  8.22213558  8.25781967  5.39441533
 16.83594023 22.0846709  18.8623081  19.68529438 17.64488284 20.65632528
 18.58484916 17.58084402 21.33728003 16.22081437  3.11518367 12.54183901
 16.91347218 13.29980612 12.09711934 14.76192267 14.08120552 15.34629821
 15.25276497 16.74238236 16.64368346 13.64028346 13.87091059 13.69607099
 15.31210375 21.40776632 11.74230694 24.51355007  5.08785476  6.58341591
 15.44963112  8.71807884  8.25493214 17.44120852  9.23973066 11.49714998
  9.27084168  5.73547397  5.98358764  4.56559993  4.08470514  6.55709408
 10.34649437 24.08428324 10.8577651  24.33892081 17.60178171  6.78621157
  6.57707008 17.92071622 10.37025876 12.07532151 25.79501037 26.64348319
 21.84022861  8.45136583  9.30995331 17.65975284  8.90381735  8.04954276
 18.6203722   7.8605424  10.00524126  8.8035236   4.76399195  2.36639345
 14.69586615  2.67953622  3.19549824  5.93215207  5.04935392  9.32155222
  4.79607146  8.52974861  7.99768628  5.95818782  8.33119418  8.40900596
 12.78515572 18.72167261 10.21665351  8.43855014 12.83069016 16.95201989
 14.59005537 22.1115022  21.60391074 19.57522535 22.74106569 20.44579448
 15.22539197 10.33614233 14.3087482  15.62786542  4.43323733  4.04558247
 12.68936527  7.05651347  6.62013319  1.33442346  1.0525976  11.37251355
  1.99801327  2.01628723  4.37795605  1.8194991  12.27833131  9.90141868
 22.28715251  9.9864661   9.38987576  9.18174029 19.63925312 12.23822799
 18.72353529  5.29596417 13.64790345  9.83337428 22.29111554 20.85804489
 19.68792584 20.62259639 20.99929231 20.17027567 19.38594692 18.05603641
 20.34353913 20.05196252 15.93110269 13.52433235 15.24761576 16.86060626
  7.48806224 11.22079088 12.33127342 15.27737649 18.29814353 16.86401244
  5.69394044 19.37349425 20.61940888 21.83966593 17.02712985 14.64080754
 13.85673858  8.61115461  7.71547738  6.97107311  4.17496463 15.04292082
  0.1456477   0.88615741 11.79101824  3.14130699 15.45442012 19.95436816
 19.46512826 16.4821914  18.78652751 20.48928238 19.44030871 18.21037883
 18.11616902]
LogPf_by_res [ 7.74860176 21.35208095 16.51844564  6.13212631  3.55862862 14.22244375
  7.38265214  5.56152867 12.98010789  5.14089107  0.94975018 11.93193191
 17.30884752 18.54251957  7.49548202  9.61334396  3.06598779  4.40353577
 14.63294944  3.31356433  4.12909432  7.80747227 18.93252572 14.45732743
  5.99060274  9.62223994 20.60098356 19.6443727  16.79308138 16.23856558
 16.50234008 18.47768771 17.40949105 21.91762313 19.09327795 15.62155757
 13.89460256 15.53111509  7.86828826  5.63410062  3.84258407 14.47193463
 12.72188668 13.17485462 24.44760803  6.67573381  4.10168146 16.89624914
  8.28217684  2.50008136  3.84433244  3.5779885   7.02886538  4.39902888
  2.69948633  8.22917569 16.58813039 12.3135314  10.47678488 15.48000975
 20.94093852  7.13729365 14.94647059 20.3450356   6.54045457  3.03795817
  9.64938154 20.67769403 17.14786278 16.66374134 19.62921705 19.53178418
 18.64390778 20.21593902 20.24814779 18.10825851 20.01384457 18.74316664
 17.98086557 17.48235692 16.84904774 11.32530274 14.02270366  3.80825108
 20.02187215 20.7903884  10.56686554 24.38310165 10.88038277  5.59069482
  4.68132864 11.96834361 10.19162091  3.356592    0.95727962  2.80612066
  4.00260661  6.50370694 10.8085394  25.52864087 10.65193414 21.31775116
  5.07768397  5.28507283 14.77269229  7.45428232  9.41120201 22.02447768
 26.20760427 20.38202211  5.73018187  6.07221837 15.94818531  9.87373689
  8.43541252 17.30106511  8.98115245  3.69884854  6.87774296 22.99476411
 16.96185832  2.51826961 13.77217696  8.22213558  8.25781967  5.39441533
 16.83594023 22.0846709  18.8623081  19.68529438 17.64488284 20.65632528
 18.58484916 17.58084402 21.33728003 16.22081437  3.11518367 12.54183901
 16.91347218 13.29980612 12.09711934 14.76192267 14.08120552 15.34629821
 15.25276497 16.74238236 16.64368346 13.64028346 13.87091059 13.69607099
 15.31210375 21.40776632 11.74230694 24.51355007  5.08785476  6.58341591
 15.44963112  8.71807884  8.25493214 17.44120852  9.23973066 11.49714998
  9.27084168  5.73547397  5.98358764  4.56559993  4.08470514  6.55709408
 10.34649437 24.08428324 10.8577651  24.33892081 17.60178171  6.78621157
  6.57707008 17.92071622 10.37025876 12.07532151 25.79501037 26.64348319
 21.84022861  8.45136583  9.30995331 17.65975284  8.90381735  8.04954276
 18.6203722   7.8605424  10.00524126  8.8035236   4.76399195  2.36639345
 14.69586615  2.67953622  3.19549824  5.93215207  5.04935392  9.32155222
  4.79607146  8.52974861  7.99768628  5.95818782  8.33119418  8.40900596
 12.78515572 18.72167261 10.21665351  8.43855014 12.83069016 16.95201989
 14.59005537 22.1115022  21.60391074 19.57522535 22.74106569 20.44579448
 15.22539197 10.33614233 14.3087482  15.62786542  4.43323733  4.04558247
 12.68936527  7.05651347  6.62013319  1.33442346  1.0525976  11.37251355
  1.99801327  2.01628723  4.37795605  1.8194991  12.27833131  9.90141868
 22.28715251  9.9864661   9.38987576  9.18174029 19.63925312 12.23822799
 18.72353529  5.29596417 13.64790345  9.83337428 22.29111554 20.85804489
 19.68792584 20.62259639 20.99929231 20.17027567 19.38594692 18.05603641
 20.34353913 20.05196252 15.93110269 13.52433235 15.24761576 16.86060626
  7.48806224 11.22079088 12.33127342 15.27737649 18.29814353 16.86401244
  5.69394044 19.37349425 20.61940888 21.83966593 17.02712985 14.64080754
 13.85673858  8.61115461  7.71547738  6.97107311  4.17496463 15.04292082
  0.1456477   0.88615741 11.79101824  3.14130699 15.45442012 19.95436816
 19.46512826 16.4821914  18.78652751 20.48928238 19.44030871 18.21037883
 18.11616902]
Pf_by_res [2.31832857e+03 1.87538713e+09 1.49234692e+07 4.60414103e+02
 3.51150080e+01 1.50220374e+06 1.60784836e+03 2.60220324e+02
 4.33699808e+05 1.70867955e+02 2.58506379e+00 1.52045016e+05
 3.28955359e+07 1.12957203e+08 1.79989214e+03 1.49631226e+04
 2.14556452e+01 8.17393696e+01 2.26469225e+06 2.74829091e+01
 6.21216351e+01 2.45890711e+03 1.66836645e+08 1.89992968e+06
 3.99655424e+02 1.50968281e+04 8.84898546e+08 3.39971619e+08
 1.96400494e+07 1.12802682e+07 1.46850434e+07 1.05866318e+08
 3.63785927e+07 3.30143524e+09 1.95931947e+08 6.08634061e+06
 1.08230389e+06 5.56003570e+06 2.61308882e+03 2.79807150e+02
 4.66458549e+01 1.92788601e+06 3.35000293e+05 5.26946664e+05
 4.14439616e+10 7.92929100e+02 6.04418329e+01 2.17744788e+07
 3.95278960e+03 1.21834852e+01 4.67274803e+01 3.58014536e+01
 1.12874919e+03 8.13718085e+01 1.48720904e+01 3.74874234e+03
 1.60004978e+07 2.22688986e+05 3.54821446e+04 5.28302681e+06
 1.24318009e+09 1.25801914e+03 3.09862984e+06 6.85072751e+08
 6.92601344e+02 2.08626019e+01 1.55121915e+04 9.55450992e+08
 2.80041362e+07 1.72572230e+07 3.34857978e+08 3.03770845e+08
 1.25010435e+08 6.02102959e+08 6.21811651e+08 7.31672529e+07
 4.91928812e+08 1.38055542e+08 6.44155464e+07 3.91283145e+07
 2.07705722e+07 8.28927383e+04 1.23022011e+06 4.50715436e+01
 4.95893700e+08 1.06942654e+09 3.88267817e+04 3.88549628e+10
 5.31239303e+04 2.67921712e+02 1.07913355e+02 1.57683259e+05
 2.66787036e+04 2.86912444e+01 2.60460132e+00 1.65456075e+01
 5.47406517e+01 6.67611847e+02 4.94412016e+04 1.22165299e+11
 4.22742798e+04 1.81209806e+09 1.60402130e+02 1.97368557e+02
 2.60434638e+06 1.72724394e+03 1.22245562e+04 3.67374599e+09
 2.40889527e+11 7.10885623e+08 3.08025284e+02 4.33641592e+02
 8.43740464e+06 1.94137507e+04 4.60737022e+03 3.26405230e+07
 7.95179091e+03 4.04007577e+01 9.70433583e+02 9.69391405e+09
 2.32509912e+07 1.24071090e+01 9.57591883e+05 3.72244349e+03
 3.85767391e+03 2.20173380e+02 2.05000981e+07 3.90167155e+09
 1.55523608e+08 3.54172407e+08 4.60336332e+07 9.35250798e+08
 1.17841276e+08 4.31781019e+07 1.84783409e+09 1.10817966e+07
 2.25375694e+01 2.79802426e+05 2.21527495e+07 5.97079840e+05
 1.79354457e+05 2.57644905e+06 1.30433713e+06 4.62181578e+06
 4.20912341e+06 1.86691382e+07 1.69145280e+07 8.39266402e+05
 1.05696335e+06 8.87417631e+05 4.46644680e+06 1.98278115e+09
 1.25782177e+05 4.42689811e+10 1.62041870e+02 7.23004838e+02
 5.12494895e+06 6.11242486e+03 3.84655083e+03 3.75509231e+07
 1.02982644e+04 9.84348294e+04 1.06236899e+04 3.09659706e+02
 3.96861615e+02 9.61202420e+01 5.94244133e+01 7.04222302e+02
 3.11476591e+04 2.88184960e+10 5.19358771e+04 3.71756872e+10
 4.40916824e+07 8.85552349e+02 7.18431298e+02 6.06552179e+07
 3.18967296e+04 1.75487222e+05 1.59452255e+11 3.72492666e+11
 3.05555967e+09 4.68146245e+03 1.10474323e+04 4.67232677e+07
 7.36001574e+03 3.13236240e+03 1.22102596e+08 2.59292640e+03
 2.21422153e+04 6.65766165e+03 1.17212901e+02 1.06588811e+01
 2.41175715e+06 1.45783306e+01 2.44223388e+01 3.76964897e+02
 1.55921694e+02 1.11763165e+04 1.21033995e+02 5.06317286e+03
 2.97406887e+03 3.86908341e+02 4.15137207e+03 4.48729775e+03
 3.56880303e+05 1.35119835e+08 2.73549701e+04 4.62184908e+03
 3.73506302e+05 2.30233596e+07 2.16960433e+06 4.00777554e+09
 2.41245499e+09 3.17257831e+08 7.52175774e+09 7.57697267e+08
 4.09546972e+06 3.08268803e+04 1.63760964e+06 6.12485366e+06
 8.42035706e+01 5.71444610e+01 3.24280859e+05 1.16039236e+03
 7.50044988e+02 3.79780574e+00 2.86508381e+00 8.69000204e+04
 7.37439065e+00 7.51038878e+00 7.96750149e+01 6.16876776e+00
 2.14986671e+05 1.99586652e+04 4.77735322e+09 2.17303701e+04
 1.19666126e+04 9.71805027e+03 3.38235554e+08 2.06535583e+05
 1.35371755e+08 1.99529914e+02 8.45686034e+05 1.86457642e+04
 4.79632359e+09 1.14428393e+09 3.55105626e+08 9.04231884e+08
 1.31788275e+09 5.75227213e+08 2.62548640e+08 6.94443599e+07
 6.84048329e+08 5.11042095e+08 8.29449579e+06 7.47382478e+05
 4.18750548e+06 2.10120420e+07 1.78658675e+03 7.46668039e+04
 2.26675196e+05 4.31400166e+06 8.84672980e+07 2.10837348e+07
 2.97061870e+02 2.59299482e+08 9.01354222e+08 3.05384084e+09
 2.48192434e+07 2.28255854e+06 1.04208970e+06 5.49258680e+03
 2.24279332e+03 1.06536540e+03 6.50375394e+01 3.41238093e+06
 1.15678858e+00 2.42579041e+00 1.32060871e+05 2.31340831e+01
 5.14955120e+06 4.63523741e+08 2.84182803e+08 1.43921201e+07
 1.44173430e+08 7.91374910e+08 2.77216324e+08 8.10339560e+07
 7.37483381e+07]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.76855751e+01 1.99389941e-06 3.01248147e-04 5.49092561e-01
 1.08968608e+02 2.79296399e-03 4.53470554e-01 3.77966199e+00
 7.68431126e-04 3.38948375e+00 2.09085017e+03 2.09325428e-02
 6.24679437e-05 1.65912934e-05 1.11570067e+00 2.22726527e-02
 3.09922137e+01 5.75920970e+01 4.65355640e-03 1.26978875e+02
 6.01937358e+01 1.55615213e+00 2.24131413e-06 1.63703004e-03
 2.29672226e+00 2.31157755e-01 2.92348382e-06 5.14459880e-06
 1.22928222e-04 1.41408251e-04 6.85360298e-05 1.16959732e-05
 1.02789388e-05 2.25991131e-07 1.70093973e-06 1.17067926e-04
 1.19796728e-03 1.47135205e-04 5.07738394e-01 1.16395280e+00
 1.36138549e+01 1.31133251e-03 2.44201874e-03 6.18055559e-04
 9.23278906e-08 9.19517125e-01 8.73889558e+01 1.92684335e-04
 5.70020505e-01 7.53394860e+01 4.71217950e+00 1.85734900e+01
 2.23973547e+00 1.29515065e+01 4.79095578e+01 6.15047398e-01
 3.30111522e-05 9.22774194e-04 5.16159963e-02 2.56987123e-04
 7.55544643e-07 1.29749868e+00 6.78616598e-04 9.70638431e-07
 8.75610269e-01 4.39972691e+01 5.39660995e-02 7.12173421e-07
 5.07658889e-05 1.93118228e-05 1.34255945e-06 3.80406638e-06
 1.27599187e-05 2.53001686e-06 7.06537669e-07 9.08819060e-06
 3.16877875e-06 6.06373670e-06 5.80501683e-06 6.17025393e-06
 3.67574789e-05 2.36743296e-02 2.15184685e-03 1.47533873e+01
 1.93823122e-06 3.57802375e-07 7.82821571e-03 1.05523133e-07
 8.46260320e-02 5.42983042e+00 7.75744992e+01 6.68357135e-02
 5.45292411e-02 3.84631450e+01 4.14050126e+02 9.86532638e+01
 1.88141332e+01 7.91170603e-01 1.22660621e-02 7.34254000e-09
 2.55104406e-02 4.61968624e-06 5.21896093e+00 4.24146815e+01
 1.37118303e-03 1.16262725e+00 1.39817353e-01 3.14546641e-07
 2.51753929e-08 1.26181140e-06 3.58267827e+00 2.02145113e+01
 4.85942964e-04 1.03439099e-01 5.24011798e-01 2.39352004e-05
 9.60128197e-02 1.72347372e+01 1.06127604e+00 1.64548911e-07
 9.04383654e-05 1.58169805e+02 2.35295553e-03 1.32423805e+00
 2.73192431e+00 1.58500037e+01 5.50856244e-05 1.23464890e-07
 1.07398410e-05 1.75218296e-05 2.23727270e-05 9.59104854e-07
 1.70410653e-05 4.75916354e-05 2.72980233e-06 3.00735022e-04
 2.51123351e+01 1.72164143e-03 7.36828710e-05 3.36327028e-03
 8.11114195e-03 7.27398862e-04 3.77923868e-04 1.69036911e-04
 2.94172802e-04 4.69537092e-05 2.21072281e-05 1.06879482e-03
 1.47480379e-03 3.12367703e-03 5.53136110e-04 1.76002727e-07
 7.46749731e-03 7.88305670e-08 4.10361803e+00 9.63059174e+00
 8.00026979e-04 1.57246375e-01 8.86589739e-01 3.61554323e-05
 1.38048006e-01 3.38567592e-03 7.35391817e-02 4.91936990e+00
 4.94487231e+00 1.81961422e+01 1.31470790e+02 6.23856064e+00
 4.16263915e-02 3.49239103e-08 2.22498305e-02 1.96126000e-07
 8.67835689e-05 2.60363402e+00 1.16522269e+01 8.91099108e-05
 5.23658335e-02 1.14432313e-02 7.24708760e-09 1.62808265e-08
 3.44908110e-06 5.03979222e-01 7.07184655e-01 5.16726777e-05
 5.96919041e-01 8.45127386e-01 5.97130533e-06 1.99069161e+00
 1.09036803e-01 1.04585736e+00 4.82857256e+00 2.11389084e+02
 4.57573222e-03 3.70754458e+02 1.71793578e+01 2.22071725e+00
 9.76984403e+00 3.50344644e-01 5.49397663e+00 1.22566398e-01
 5.48836715e-01 3.84756607e+00 3.34659008e-01 1.95348144e-01
 7.41773989e-03 2.58270660e-05 4.32272823e-02 9.72698883e-02
 2.09168481e-03 1.62414754e-05 4.32925968e-04 2.23815823e-07
 7.59162865e-07 1.38478333e-06 2.73196315e-08 1.18385485e-06
 6.17291734e-04 8.39198311e-02 4.99555550e-03 8.62379571e-05
 1.06527974e+01 1.64369046e+01 1.38634992e-02 1.94173212e+00
 2.07829342e+00 1.91982407e+02 4.12721266e+02 2.15662333e-02
 2.06570374e+02 2.79983061e+02 3.17301426e+00 1.10305142e+02
 8.13546990e-03 8.76319919e-02 1.63533534e-06 2.48729361e-01
 3.50608908e-02 1.75879424e-02 1.71228053e-06 4.98653985e-03
 1.35290131e-05 6.49809655e+00 2.11633797e-04 5.39776523e-02
 1.95832921e-07 1.13307948e-06 3.65120841e-06 5.32738844e-07
 2.83737935e-07 2.70990930e-07 8.19566886e-06 9.57540599e-06
 2.12670568e-07 4.51167181e-06 3.19156862e-04 1.34663924e-03
 9.79126460e-04 3.16465169e-05 5.50516174e-01 9.76487339e-03
 4.75762465e-03 1.22437335e-04 4.74254450e-06 5.23415563e-05

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
         Bc        Bh             calc_name
0  0.443079  8.739727  train_cluster_2+BV_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_R3_k_sequence/20240402-191930_analysis.csv
dict_keys(['cluster_2+BV_R3_k_sequence'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_R3_k_sequence to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV_R3_k_sequence/cluster_2+BV_R3_k_sequence0_1712081970.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2+BV_R3_k_sequence': {'train_dfs': [    0.0      0.5      5.0  peptide             calc_name
0   0.0  0.20654  0.35846       35  train_cluster_2+BV_1
1   0.0  0.19732  0.31776       36  train_cluster_2+BV_1
2   0.0  0.23020  0.37072       37  train_cluster_2+BV_1
3   0.0  0.19732  0.31776       38  train_cluster_2+BV_1
4   0.0  0.15347  0.24715       39  train_cluster_2+BV_1
5   0.0  0.13812  0.22244       40  train_cluster_2+BV_1
6   0.0  0.07337  0.12353       41  train_cluster_2+BV_1
7   0.0  0.00107  0.01023       42  train_cluster_2+BV_1
8   0.0  0.00117  0.01116       43  train_cluster_2+BV_1
9   0.0  0.00143  0.01363       44  train_cluster_2+BV_1
10  0.0  0.00161  0.01533       45  train_cluster_2+BV_1
11  0.0  0.00764  0.06473       46  train_cluster_2+BV_1
12  0.0  0.24745  0.29854       47  train_cluster_2+BV_1
13  0.0  0.20202  0.27473       48  train_cluster_2+BV_1
14  0.0  0.00072  0.00710       62  train_cluster_2+BV_1
15  0.0  0.00077  0.00765       63  train_cluster_2+BV_1
16  0.0  0.18227  0.31441       64  train_cluster_2+BV_1
17  0.0  0.19739  0.34000       65  train_cluster_2+BV_1
18  0.0  0.21528  0.37031       68  train_cluster_2+BV_1
19  0.0  0.20210  0.23709       81  train_cluster_2+BV_1
20  0.0  0.22076  0.28648       82  train_cluster_2+BV_1
21  0.0  0.25349  0.34137       83  train_cluster_2+BV_1
22  0.0  0.24083  0.31253       84  train_cluster_2+BV_1
23  0.0  0.27461  0.36981       85  train_cluster_2+BV_1
24  0.0  0.28871  0.33870       86  train_cluster_2+BV_1
25  0.0  0.32954  0.44378       87  train_cluster_2+BV_1
26  0.0  0.46485  0.58457       88  train_cluster_2+BV_1
27  0.0  0.35799  0.50745       89  train_cluster_2+BV_1
28  0.0  0.33113  0.47489       90  train_cluster_2+BV_1
29  0.0  0.28704  0.41219       91  train_cluster_2+BV_1
30  0.0  0.27806  0.39911       92  train_cluster_2+BV_1
31  0.0  0.00000  0.00001       93  train_cluster_2+BV_1
32  0.0  0.00000  0.00001       94  train_cluster_2+BV_1
33  0.0  0.00000  0.00001       95  train_cluster_2+BV_1
34  0.0  0.04204  0.16039       96  train_cluster_2+BV_1
35  0.0  0.05044  0.19231       97  train_cluster_2+BV_1
36  0.0  0.05596  0.21293       98  train_cluster_2+BV_1
37  0.0  0.23347  0.27926       99  train_cluster_2+BV_1
38  0.0  0.24644  0.29477      100  train_cluster_2+BV_1
39  0.0  0.23347  0.27926      101  train_cluster_2+BV_1
40  0.0  0.27724  0.33160      102  train_cluster_2+BV_1
41  0.0  0.26094  0.31210      103  train_cluster_2+BV_1
42  0.0  0.22180  0.26529      104  train_cluster_2+BV_1
43  0.0  0.29571  0.35350      105  train_cluster_2+BV_1
44  0.0  0.24642  0.29459      106  train_cluster_2+BV_1
45  0.0  0.25970  0.30083      107  train_cluster_2+BV_1], 'val_dfs': [    0.0      0.5      5.0  peptide           calc_name
0   0.0  0.37343  0.49041        0  val_cluster_2+BV_1
1   0.0  0.22142  0.44756        1  val_cluster_2+BV_1
2   0.0  0.31665  0.49501        2  val_cluster_2+BV_1
3   0.0  0.37129  0.54855        3  val_cluster_2+BV_1
4   0.0  0.24351  0.49180        4  val_cluster_2+BV_1
5   0.0  0.34097  0.53269        5  val_cluster_2+BV_1
6   0.0  0.39310  0.58051        6  val_cluster_2+BV_1
7   0.0  0.24803  0.44684        7  val_cluster_2+BV_1
8   0.0  0.38445  0.54742        8  val_cluster_2+BV_1
9   0.0  0.35247  0.50238        9  val_cluster_2+BV_1
10  0.0  0.43199  0.59815       10  val_cluster_2+BV_1
11  0.0  0.40499  0.56077       11  val_cluster_2+BV_1
12  0.0  0.19756  0.43111       12  val_cluster_2+BV_1
13  0.0  0.37552  0.55753       13  val_cluster_2+BV_1
14  0.0  0.33804  0.50247       14  val_cluster_2+BV_1
15  0.0  0.44837  0.58539       15  val_cluster_2+BV_1
16  0.0  0.40218  0.56918       16  val_cluster_2+BV_1
17  0.0  0.54180  0.65846       17  val_cluster_2+BV_1
18  0.0  0.09106  0.33431       18  val_cluster_2+BV_1
19  0.0  0.07590  0.27871       19  val_cluster_2+BV_1
20  0.0  0.07590  0.27871       20  val_cluster_2+BV_1
21  0.0  0.00010  0.00100       21  val_cluster_2+BV_1
22  0.0  0.00011  0.00111       22  val_cluster_2+BV_1
23  0.0  0.00011  0.00105       23  val_cluster_2+BV_1
24  0.0  0.19131  0.40337       24  val_cluster_2+BV_1
25  0.0  0.19131  0.40337       25  val_cluster_2+BV_1
26  0.0  0.27728  0.51567       26  val_cluster_2+BV_1
27  0.0  0.18583  0.31709       27  val_cluster_2+BV_1
28  0.0  0.28392  0.46500       28  val_cluster_2+BV_1
29  0.0  0.27303  0.47175       29  val_cluster_2+BV_1
30  0.0  0.41751  0.70643       30  val_cluster_2+BV_1
31  0.0  0.30791  0.53362       31  val_cluster_2+BV_1
32  0.0  0.31874  0.51334       32  val_cluster_2+BV_1
33  0.0  0.42952  0.74404       33  val_cluster_2+BV_1
34  0.0  0.28852  0.51549       34  val_cluster_2+BV_1
35  0.0  0.47792  0.59430       49  val_cluster_2+BV_1
36  0.0  0.39090  0.52668       50  val_cluster_2+BV_1
37  0.0  0.22646  0.34259       51  val_cluster_2+BV_1
38  0.0  0.32502  0.47494       52  val_cluster_2+BV_1
39  0.0  0.39251  0.52745       53  val_cluster_2+BV_1
40  0.0  0.26812  0.39578       54  val_cluster_2+BV_1
41  0.0  0.25384  0.40092       72  val_cluster_2+BV_1
42  0.0  0.22493  0.42762       73  val_cluster_2+BV_1
43  0.0  0.21471  0.40818       74  val_cluster_2+BV_1
44  0.0  0.22531  0.40331       75  val_cluster_2+BV_1
45  0.0  0.19235  0.41236       76  val_cluster_2+BV_1
46  0.0  0.16375  0.39771       77  val_cluster_2+BV_1
47  0.0  0.51842  0.76285       78  val_cluster_2+BV_1
48  0.0  0.14384  0.31866       79  val_cluster_2+BV_1
49  0.0  0.13358  0.29606       80  val_cluster_2+BV_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name                        name  \
0    0.0  0.41879  0.44438        0  Experimental  cluster_2+BV_R3_k_sequence
1    0.0  0.37096  0.45204        1  Experimental  cluster_2+BV_R3_k_sequence
2    0.0  0.40040  0.48544        2  Experimental  cluster_2+BV_R3_k_sequence
3    0.0  0.45875  0.51503        3  Experimental  cluster_2+BV_R3_k_sequence
4    0.0  0.41726  0.49519        4  Experimental  cluster_2+BV_R3_k_sequence
5    0.0  0.44176  0.50927        5  Experimental  cluster_2+BV_R3_k_sequence
6    0.0  0.48987  0.54090        6  Experimental  cluster_2+BV_R3_k_sequence
7    0.0  0.41316  0.48254        7  Experimental  cluster_2+BV_R3_k_sequence
8    0.0  0.46617  0.51066        8  Experimental  cluster_2+BV_R3_k_sequence
9    0.0  0.46825  0.52028        9  Experimental  cluster_2+BV_R3_k_sequence
10   0.0  0.48273  0.53102       10  Experimental  cluster_2+BV_R3_k_sequence
11   0.0  0.50258  0.53988       11  Experimental  cluster_2+BV_R3_k_sequence
12   0.0  0.47373  0.50144       12  Experimental  cluster_2+BV_R3_k_sequence
13   0.0  0.52057  0.54102       13  Experimental  cluster_2+BV_R3_k_sequence
14   0.0  0.52823  0.55640       14  Experimental  cluster_2+BV_R3_k_sequence
15   0.0  0.55802  0.57504       15  Experimental  cluster_2+BV_R3_k_sequence
16   0.0  0.55641  0.57196       16  Experimental  cluster_2+BV_R3_k_sequence
17   0.0  0.52928  0.54827       17  Experimental  cluster_2+BV_R3_k_sequence
18   0.0  0.17163  0.27883       18  Experimental  cluster_2+BV_R3_k_sequence
19   0.0  0.16883  0.28686       19  Experimental  cluster_2+BV_R3_k_sequence
20   0.0  0.16341  0.27353       20  Experimental  cluster_2+BV_R3_k_sequence
21   0.0  0.32309  0.41205       21  Experimental  cluster_2+BV_R3_k_sequence
22   0.0  0.31355  0.39928       22  Experimental  cluster_2+BV_R3_k_sequence
23   0.0  0.34392  0.42213       23  Experimental  cluster_2+BV_R3_k_sequence
24   0.0  0.35604  0.35617       24  Experimental  cluster_2+BV_R3_k_sequence
25   0.0  0.34105  0.35125       25  Experimental  cluster_2+BV_R3_k_sequence
26   0.0  0.34135  0.38830       26  Experimental  cluster_2+BV_R3_k_sequence
27   0.0  0.28512  0.29602       27  Experimental  cluster_2+BV_R3_k_sequence
28   0.0  0.28439  0.33185       28  Experimental  cluster_2+BV_R3_k_sequence
29   0.0  0.32954  0.39085       29  Experimental  cluster_2+BV_R3_k_sequence
30   0.0  0.26192  0.34619       30  Experimental  cluster_2+BV_R3_k_sequence
31   0.0  0.31421  0.37857       31  Experimental  cluster_2+BV_R3_k_sequence
32   0.0  0.32314  0.38565       32  Experimental  cluster_2+BV_R3_k_sequence
33   0.0  0.29666  0.37860       33  Experimental  cluster_2+BV_R3_k_sequence
34   0.0  0.38440  0.44775       34  Experimental  cluster_2+BV_R3_k_sequence
35   0.0  0.33633  0.46390       35  Experimental  cluster_2+BV_R3_k_sequence
36   0.0  0.34716  0.45807       36  Experimental  cluster_2+BV_R3_k_sequence
37   0.0  0.34165  0.44393       37  Experimental  cluster_2+BV_R3_k_sequence
38   0.0  0.30725  0.43533       38  Experimental  cluster_2+BV_R3_k_sequence
39   0.0  0.33252  0.48976       39  Experimental  cluster_2+BV_R3_k_sequence
40   0.0  0.28369  0.42940       40  Experimental  cluster_2+BV_R3_k_sequence
41   0.0  0.35906  0.50293       41  Experimental  cluster_2+BV_R3_k_sequence
42   0.0  0.33575  0.45181       42  Experimental  cluster_2+BV_R3_k_sequence
43   0.0  0.33443  0.43697       43  Experimental  cluster_2+BV_R3_k_sequence
44   0.0  0.37082  0.47284       44  Experimental  cluster_2+BV_R3_k_sequence
45   0.0  0.37847  0.48848       45  Experimental  cluster_2+BV_R3_k_sequence
46   0.0  0.22218  0.31040       46  Experimental  cluster_2+BV_R3_k_sequence
47   0.0  0.18217  0.28305       47  Experimental  cluster_2+BV_R3_k_sequence
48   0.0  0.25719  0.37045       48  Experimental  cluster_2+BV_R3_k_sequence
49   0.0  0.49756  0.50850       49  Experimental  cluster_2+BV_R3_k_sequence
50   0.0  0.55024  0.54326       50  Experimental  cluster_2+BV_R3_k_sequence
51   0.0  0.24310  0.29208       51  Experimental  cluster_2+BV_R3_k_sequence
52   0.0  0.19173  0.23972       52  Experimental  cluster_2+BV_R3_k_sequence
53   0.0  0.18105  0.23003       53  Experimental  cluster_2+BV_R3_k_sequence
54   0.0  0.26140  0.30267       54  Experimental  cluster_2+BV_R3_k_sequence
55   0.0  0.26392  0.30614       55  Experimental  cluster_2+BV_R3_k_sequence
56   0.0  0.26061  0.32801       56  Experimental  cluster_2+BV_R3_k_sequence
57   0.0  0.45297  0.53974       57  Experimental  cluster_2+BV_R3_k_sequence
58   0.0  0.31622  0.45372       58  Experimental  cluster_2+BV_R3_k_sequence
59   0.0  0.43711  0.52972       59  Experimental  cluster_2+BV_R3_k_sequence
60   0.0  0.47628  0.54735       60  Experimental  cluster_2+BV_R3_k_sequence
61   0.0  0.49249  0.57156       61  Experimental  cluster_2+BV_R3_k_sequence
62   0.0  0.50341  0.53212       62  Experimental  cluster_2+BV_R3_k_sequence
63   0.0  0.53500  0.53827       63  Experimental  cluster_2+BV_R3_k_sequence
64   0.0  0.26524  0.35365       64  Experimental  cluster_2+BV_R3_k_sequence
65   0.0  0.25454  0.32548       65  Experimental  cluster_2+BV_R3_k_sequence
66   0.0  0.25152  0.35786       66  Experimental  cluster_2+BV_R3_k_sequence
67   0.0  0.28164  0.36568       67  Experimental  cluster_2+BV_R3_k_sequence
68   0.0  0.24177  0.30174       68  Experimental  cluster_2+BV_R3_k_sequence
69   0.0  0.27969  0.36567       69  Experimental  cluster_2+BV_R3_k_sequence
70   0.0  0.38633  0.44869       70  Experimental  cluster_2+BV_R3_k_sequence
71   0.0  0.24871  0.31226       71  Experimental  cluster_2+BV_R3_k_sequence
72   0.0  0.36820  0.37879       72  Experimental  cluster_2+BV_R3_k_sequence
73   0.0  0.22903  0.26839       73  Experimental  cluster_2+BV_R3_k_sequence
74   0.0  0.21687  0.25989       74  Experimental  cluster_2+BV_R3_k_sequence
75   0.0  0.20479  0.23593       75  Experimental  cluster_2+BV_R3_k_sequence
76   0.0  0.11684  0.15140       76  Experimental  cluster_2+BV_R3_k_sequence
77   0.0  0.13267  0.18143       77  Experimental  cluster_2+BV_R3_k_sequence
78   0.0  0.35203  0.42601       78  Experimental  cluster_2+BV_R3_k_sequence
79   0.0  0.20249  0.21472       79  Experimental  cluster_2+BV_R3_k_sequence
80   0.0  0.16260  0.17496       80  Experimental  cluster_2+BV_R3_k_sequence
81   0.0  0.05688  0.07274       81  Experimental  cluster_2+BV_R3_k_sequence
82   0.0  0.07600  0.11464       82  Experimental  cluster_2+BV_R3_k_sequence
83   0.0  0.08147  0.13526       83  Experimental  cluster_2+BV_R3_k_sequence
84   0.0  0.08527  0.13242       84  Experimental  cluster_2+BV_R3_k_sequence
85   0.0  0.08569  0.14304       85  Experimental  cluster_2+BV_R3_k_sequence
86   0.0  0.06291  0.07885       86  Experimental  cluster_2+BV_R3_k_sequence
87   0.0  0.09393  0.16201       87  Experimental  cluster_2+BV_R3_k_sequence
88   0.0  0.10385  0.19651       88  Experimental  cluster_2+BV_R3_k_sequence
89   0.0  0.53877  0.49943       89  Experimental  cluster_2+BV_R3_k_sequence
90   0.0  0.51417  0.47866       90  Experimental  cluster_2+BV_R3_k_sequence
91   0.0  0.50107  0.49072       91  Experimental  cluster_2+BV_R3_k_sequence
92   0.0  0.45551  0.47280       92  Experimental  cluster_2+BV_R3_k_sequence
93   0.0  0.06500  0.10668       93  Experimental  cluster_2+BV_R3_k_sequence
94   0.0  0.06362  0.10593       94  Experimental  cluster_2+BV_R3_k_sequence
95   0.0  0.04358  0.04371       95  Experimental  cluster_2+BV_R3_k_sequence
96   0.0  0.08151  0.10674       96  Experimental  cluster_2+BV_R3_k_sequence
97   0.0  0.08795  0.11537       97  Experimental  cluster_2+BV_R3_k_sequence
98   0.0  0.09261  0.12297       98  Experimental  cluster_2+BV_R3_k_sequence
99   0.0  0.17298  0.20225       99  Experimental  cluster_2+BV_R3_k_sequence
100  0.0  0.20729  0.23030      100  Experimental  cluster_2+BV_R3_k_sequence
101  0.0  0.20401  0.23454      101  Experimental  cluster_2+BV_R3_k_sequence
102  0.0  0.21943  0.23426      102  Experimental  cluster_2+BV_R3_k_sequence
103  0.0  0.21731  0.24442      103  Experimental  cluster_2+BV_R3_k_sequence
104  0.0  0.22028  0.25199      104  Experimental  cluster_2+BV_R3_k_sequence
105  0.0  0.22217  0.24175      105  Experimental  cluster_2+BV_R3_k_sequence
106  0.0  0.22454  0.24966      106  Experimental  cluster_2+BV_R3_k_sequence
107  0.0  0.23913  0.27068      107  Experimental  cluster_2+BV_R3_k_sequence

    split_type
0           R3
1           R3
2           R3
3           R3
4           R3
5           R3
6           R3
7           R3
8           R3
9           R3
10          R3
11          R3
12          R3
13          R3
14          R3
15          R3
16          R3
17          R3
18          R3
19          R3
20          R3
21          R3
22          R3
23          R3
24          R3
25          R3
26          R3
27          R3
28          R3
29          R3
30          R3
31          R3
32          R3
33          R3
34          R3
35          R3
36          R3
37          R3
38          R3
39          R3
40          R3
41          R3
42          R3
43          R3
44          R3
45          R3
46          R3
47          R3
48          R3
49          R3
50          R3
51          R3
52          R3
53          R3
54          R3
55          R3
56          R3
57          R3
58          R3
59          R3
60          R3
61          R3
62          R3
63          R3
64          R3
65          R3
66          R3
67          R3
68          R3
69          R3
70          R3
71          R3
72          R3
73          R3
74          R3
75          R3
76          R3
77          R3
78          R3
79          R3
80          R3
81          R3
82          R3
83          R3
84          R3
85          R3
86          R3
87          R3
88          R3
89          R3
90          R3
91          R3
92          R3
93          R3
94          R3
95          R3
96          R3
97          R3
98          R3
99          R3
100         R3
101         R3
102         R3
103         R3
104         R3
105         R3
106         R3
107         R3  , 'merge_df':      0.0      0.5      5.0  peptide             calc_name  \
0    0.0  0.41879  0.44438        0          Experimental
1    0.0  0.37096  0.45204        1          Experimental
2    0.0  0.40040  0.48544        2          Experimental
3    0.0  0.45875  0.51503        3          Experimental
4    0.0  0.41726  0.49519        4          Experimental
5    0.0  0.44176  0.50927        5          Experimental
6    0.0  0.48987  0.54090        6          Experimental
7    0.0  0.41316  0.48254        7          Experimental
8    0.0  0.46617  0.51066        8          Experimental
9    0.0  0.46825  0.52028        9          Experimental
10   0.0  0.48273  0.53102       10          Experimental
11   0.0  0.50258  0.53988       11          Experimental
12   0.0  0.47373  0.50144       12          Experimental
13   0.0  0.52057  0.54102       13          Experimental
14   0.0  0.52823  0.55640       14          Experimental
15   0.0  0.55802  0.57504       15          Experimental
16   0.0  0.55641  0.57196       16          Experimental
17   0.0  0.52928  0.54827       17          Experimental
18   0.0  0.17163  0.27883       18          Experimental
19   0.0  0.16883  0.28686       19          Experimental
20   0.0  0.16341  0.27353       20          Experimental
21   0.0  0.32309  0.41205       21          Experimental
22   0.0  0.31355  0.39928       22          Experimental
23   0.0  0.34392  0.42213       23          Experimental
24   0.0  0.35604  0.35617       24          Experimental
25   0.0  0.34105  0.35125       25          Experimental
26   0.0  0.34135  0.38830       26          Experimental
27   0.0  0.28512  0.29602       27          Experimental
28   0.0  0.28439  0.33185       28          Experimental
29   0.0  0.32954  0.39085       29          Experimental
30   0.0  0.26192  0.34619       30          Experimental
31   0.0  0.31421  0.37857       31          Experimental
32   0.0  0.32314  0.38565       32          Experimental
33   0.0  0.29666  0.37860       33          Experimental
34   0.0  0.38440  0.44775       34          Experimental
35   0.0  0.33633  0.46390       35          Experimental
36   0.0  0.34716  0.45807       36          Experimental
37   0.0  0.34165  0.44393       37          Experimental
38   0.0  0.30725  0.43533       38          Experimental
39   0.0  0.33252  0.48976       39          Experimental
40   0.0  0.28369  0.42940       40          Experimental
41   0.0  0.35906  0.50293       41          Experimental
42   0.0  0.33575  0.45181       42          Experimental
43   0.0  0.33443  0.43697       43          Experimental
44   0.0  0.37082  0.47284       44          Experimental
45   0.0  0.37847  0.48848       45          Experimental
46   0.0  0.22218  0.31040       46          Experimental
47   0.0  0.18217  0.28305       47          Experimental
48   0.0  0.25719  0.37045       48          Experimental
49   0.0  0.49756  0.50850       49          Experimental
50   0.0  0.55024  0.54326       50          Experimental
51   0.0  0.24310  0.29208       51          Experimental
52   0.0  0.19173  0.23972       52          Experimental
53   0.0  0.18105  0.23003       53          Experimental
54   0.0  0.26140  0.30267       54          Experimental
55   0.0  0.26392  0.30614       55          Experimental
56   0.0  0.26061  0.32801       56          Experimental
57   0.0  0.45297  0.53974       57          Experimental
58   0.0  0.31622  0.45372       58          Experimental
59   0.0  0.43711  0.52972       59          Experimental
60   0.0  0.47628  0.54735       60          Experimental
61   0.0  0.49249  0.57156       61          Experimental
62   0.0  0.50341  0.53212       62          Experimental
63   0.0  0.53500  0.53827       63          Experimental
64   0.0  0.26524  0.35365       64          Experimental
65   0.0  0.25454  0.32548       65          Experimental
66   0.0  0.25152  0.35786       66          Experimental
67   0.0  0.28164  0.36568       67          Experimental
68   0.0  0.24177  0.30174       68          Experimental
69   0.0  0.27969  0.36567       69          Experimental
70   0.0  0.38633  0.44869       70          Experimental
71   0.0  0.24871  0.31226       71          Experimental

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:741: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["calc_name"] = train_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:742: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["calc_name"] = val_rep_name
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:756: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_segs["path"] = [train_segs_path]*len(train_segs)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:757: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_segs["path"] = [val_segs_path]*len(val_segs)

/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/train_cluster_2+BV_1/reweighting_gamma_2x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/train_cluster_2+BV_1/reweighting_gamma_3x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/train_cluster_2+BV_1/reweighting_gamma_5x10^0/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/train_cluster_2+BV_1/reweighting_gamma_4x10^0



Contacts readContacts read

Contacts readHbonds read
Hbonds readContacts read
Hbonds read


Hbonds read
Segments and experimental dfracs readSegments and experimental dfracs read
Segments and experimental dfracs read

Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.06419179429240347, 92.31286198484956), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.06419179429240347, 92.31286198484956), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.06419179429240347, 92.31286198484956), (array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.06419179429240347, 92.31286198484956)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/train_cluster_2+BV_1/reweighting_gamma_2x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(35, 4)
   0.0     0.5      5.0  peptide
0  0.0  0.0000  0.00000        0
1  0.0  0.0000  0.00000        1
2  0.0  0.0000  0.00000        2
3  0.0  0.0046  0.04201        3
4  0.0  0.0046  0.04201        4
Experimental cluster_2+BV False 1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat
REWIGHTING val_cluster_2+BV_1 with Exponent: 0
[{'do_reweight': False, 'do_params': False, 'stepfactor': 0.001, 'basegamma': 1, 'predictHDX_dir': ['/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0'], 'kint_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV0/prep_cluster_2+BV0_0/out__prep_cluster_2+BV0_0Intrinsic_rates.dat', 'exp_file': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1/val_cluster_2+BV_1_expt_dfracs.dat', 'times': [0, 0.5, 5.0], 'restart_interval': 100, 'out_prefix': '/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1/reweighting_gamma_', 'exponent': 0, 'random_initial': False, 'temp': 300, 'iniweights': array([1.43524773, 1.13784148, 0.88859965, 1.29105018, 0.99098678,
       1.00513752, 0.55652092, 1.17227849, 0.82076138, 0.70157588]), 'bv_bc': 0.06419179429240347, 'bv_bh': 92.31286198484956}]
Trying concurrent.futures
/home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1/reweighting_gamma_3x10^0
Contacts read
Hbonds read
Segments and experimental dfracs read
Sum of Output Weights
1.0000000000000002
Finished reweighting
[(array([0.14352477, 0.11378415, 0.08885996, 0.12910502, 0.09909868,
       0.10051375, 0.05565209, 0.11722785, 0.08207614, 0.07015759]), 0.06419179429240347, 92.31286198484956)]
RW_do_reweighting is False
Path /home/alexi/Documents/ValDX/data/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours0/val_cluster_2+BV_1/reweighting_gamma_3x10^0final_segment_fractions.dat
RW: ncol = 3, len(names) = 3
(73, 4)
   0.0      0.5      5.0  peptide
0  0.0  0.50000  0.50000        0
1  0.0  0.36448  0.37171        1
2  0.0  0.35817  0.36754        2
3  0.0  0.33661  0.36373        3
4  0.0  0.40093  0.40888        4
Structures loaded cluster_2+BV:
cluster_2+BV Topology: <Universe with 3369 atoms>
cluster_2+BV Trajectory: <Universe with 3369 atoms>
cluster_2+BV Traj: no frames 10
rates: {2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
{2: 41000.97419937, 3: 3739.33329324, 4: 4495.66742529, 5: 252.80995882, 6: 3826.43355178, 7: 4195.60095885, 8: 729.11188642, 9: 983.54486858, 10: 333.26843198, 12: 579.15415845, 13: 5404.98105428, 14: 3182.68880137, 15: 2054.91648422, 16: 1874.10610808, 17: 2008.14087714, 18: 333.26843198, 19: 664.95794037, 20: 4707.54170199, 21: 10538.87311791, 22: 3489.74887473, 23: 3739.33329324, 24: 3826.43355121, 25: 373.93332921, 26: 3110.24195868, 28: 917.89750993, 29: 3489.74888161, 30: 2586.98658088, 31: 1749.01758506, 32: 2414.31635313, 33: 1595.12299874, 34: 1006.45457116, 35: 1238.20962611, 36: 373.93332921, 37: 746.09508122, 38: 333.26843198, 39: 712.51527077, 40: 1296.56464798, 41: 818.07699064, 42: 1326.76552124, 43: 325.68231538, 44: 635.02990259, 45: 2528.09959386, 46: 818.07699266, 47: 325.6823152, 48: 3826.43355178, 50: 729.11188632, 51: 5281.94866501, 52: 4195.60095885, 53: 2253.17112184, 55: 917.89750993, 56: 220.18827496, 57: 664.95794037, 58: 2528.09959386, 59: 1053.88750906, 60: 712.51527346, 61: 2305.65421729, 62: 528.19486726, 63: 205.49164965, 64: 1831.44624546, 65: 1357.66985789, 66: 818.07698781, 67: 3410.31249277, 68: 2151.76171416, 69: 528.19486691, 70: 983.54490469, 71: 155.88135935, 72: 856.63176813, 73: 528.19486726, 74: 939.2780565, 75: 1632.27818324, 76: 2102.78164213, 77: 664.9579403, 78: 606.44884922, 80: 917.89750993, 81: 837.13247276, 82: 680.44680228, 83: 1421.65486872, 84: 333.26843198, 85: 449.56674376, 86: 1155.56446091, 87: 1595.12299703, 88: 1523.33063516, 89: 439.33335478, 90: 664.95794037, 91: 1558.81356322, 92: 837.13245595, 93: 373.93333091, 94: 241.43163609, 95: 763.47386758, 96: 1962.43000752, 97: 2647.24526348, 99: 664.95794074, 100: 961.15665275, 101: 382.64335574, 102: 303.9444227, 103: 4100.09742062, 104: 4495.66742529, 105: 1454.76946397, 106: 8371.32448013, 107: 10538.87311796, 108: 1454.76946256, 109: 1357.66985831, 110: 1078.43550401, 111: 270.89075045, 112: 400.67678148, 113: 1103.55549088, 114: 1078.43550416, 115: 1632.27818324, 116: 1029.89791222, 117: 528.19486726, 118: 606.44884922, 119: 897.00359232, 120: 1078.43550179, 121: 8371.32447976, 123: 837.13244934, 124: 8371.32448013, 125: 3571.0355703, 126: 2008.14087584, 127: 1709.20508419, 128: 1155.56445915, 129: 6064.48848683, 130: 897.00357939, 131: 1103.55549137, 132: 8765.85284799, 133: 4100.09742056, 134: 2008.14087449, 135: 2414.31635313, 136: 781.25745875, 137: 763.47386677, 138: 696.29644347, 139: 1029.89791222, 140: 1595.12299874, 141: 2102.78163897, 142: 1962.43000852, 143: 2253.17112184, 144: 4929.40130759, 145: 10538.87311791, 146: 3489.74887473, 147: 1129.26070603, 148: 481.71945087, 149: 1670.29882678, 150: 6205.74857055, 151: 1029.89790963, 152: 897.00357963, 153: 2008.14087449, 154: 2054.91648422, 155: 5044.22181393, 156: 3332.68434065, 158: 565.97099671, 159: 481.71944856, 160: 1632.27818379, 161: 2008.14087714, 162: 1454.76946397, 163: 1874.10610904, 164: 492.94013356, 165: 781.25746219, 166: 1238.20962721, 167: 876.58528604, 168: 373.93332969, 169: 897.00358062, 170: 1558.81356338, 171: 2772.00606657, 172: 2470.55300714, 173: 348.97488878, 174: 939.27806859, 175: 3489.74888161, 177: 664.95794074, 178: 6962.96441884, 179: 4100.09742056, 180: 961.15665275, 181: 3410.31249277, 182: 1357.66985789, 183: 1421.65486872, 184: 333.26843198, 185: 781.25746219, 186: 1523.33063592, 187: 1962.43000852, 188: 1749.01759097, 189: 7812.57457663, 190: 4393.33353933, 191: 1296.56465099, 192: 1006.45457116, 193: 1155.56446091, 194: 7291.11882291, 195: 3826.43355121, 196: 2305.65421729, 197: 8371.32448013, 198: 5404.98105315, 199: 1670.29882908, 200: 2008.14087584, 201: 1155.56445955, 202: 6064.48848683, 203: 10538.87311796, 204: 2359.35980401, 205: 7812.57457663, 206: 2414.31635295, 207: 4393.33353955, 208: 2647.24524348, 209: 729.11188408, 210: 781.2574583, 211: 1421.65486872, 212: 1155.56446029, 213: 5161.71683367, 214: 2414.3163534, 215: 6962.96441884, 217: 565.97099671, 219: 2253.17112016, 220: 11035.55490664, 221: 5404.98105315, 222: 419.56009632, 223: 837.13244881, 224: 1523.33063516, 225: 3915.56263922, 226: 664.9579403, 227: 620.57486181, 228: 1632.27818678, 229: 1488.65540644, 230: 1389.29405688, 232: 876.58528579, 233: 2647.24526348, 234: 3489.74888161, 235: 1182.48101311, 236: 449.56674376, 237: 781.2574583, 238: 373.93332969, 239: 939.2780565, 240: 2647.24526348, 241: 325.68232447, 242: 837.1324483, 243: 2008.14087584, 244: 333.26843198, 245: 939.2780565, 246: 553.08792429, 247: 897.00358062, 248: 1831.44624467, 249: 439.33335478, 250: 205.49164965, 251: 897.00358062, 252: 2528.09960415, 253: 2586.98658673, 254: 8180.76987097, 255: 528.19486719, 256: 897.00357973, 257: 939.27805629, 258: 4495.66742366, 259: 2253.17111984, 260: 1558.81356322, 263: 729.11188632, 264: 1182.48101644, 265: 1874.10611777, 266: 1523.33063592, 267: 2102.78164041, 268: 252.80995882, 270: 680.44680228, 271: 1749.01759097, 272: 1749.01759097, 273: 7812.57457663, 274: 5404.98105315, 275: 419.56009632, 276: 170.92050876, 277: 579.15415444, 278: 1029.89791222, 279: 1831.44624467, 280: 1296.56464798, 281: 178.97574618, 283: 2253.17112016, 284: 2470.55300714, 285: 492.94013356, 286: 939.2780565, 287: 2647.24526348, 288: 649.82165206, 289: 897.00359232, 290: 5281.94866501, 291: 4195.60095885, 292: 1709.2050866, 293: 1296.56464798, 294: 763.47386864, 296: 729.11188632, 297: 1182.48101644, 298: 1006.45457341, 299: 1421.65486872, 300: 1182.48101644, 301: 492.94013356, 302: 3256.82314717, 303: 5161.71683355, 304: 2008.14087714, 305: 1006.45457572, 306: 939.27805779, 307: 1296.56464832, 308: 1296.56464798, 309: 481.71944856, 310: 373.93332969, 311: 155.88135718, 312: 2151.76171492, 313: 664.9579403, 314: 145.47694677, 315: 2305.65421698, 316: 2647.24524348, 317: 1006.45457572, 318: 4100.09742231, 319: 664.9579403, 320: 983.54490469, 322: 729.11188632, 323: 1078.43550179, 324: 528.19486691, 325: 419.56009763, 326: 1103.55549088, 327: 178.97574618, 328: 712.51526984, 329: 696.29644347, 330: 235.93598383, 331: 606.44884922, 332: 763.47386864, 333: 2008.14087584, 334: 1078.43550179, 335: 1558.81356322, 336: 1078.43550416, 337: 1129.26060126, 338: 373.93332969, 339: 620.57486181, 340: 348.97488863, 341: 1103.55549137, 343: 837.13244934, 345: 191.77596574, 346: 781.25746219, 347: 1182.48101644, 348: 1454.76946312, 349: 1129.26070603, 352: 729.11188632, 353: 680.44680228, 354: 1632.27818379, 355: 2008.14087714, 356: 1523.33063592, 357: 553.08792429, 358: 205.49164965, 359: 897.00358062, 360: 1831.44624467, 361: 439.33335478, 362: 664.95794037, 363: 1558.81356322, 364: 696.29644347, 365: 178.97574618, 367: 191.77596574, 368: 729.11188502, 369: 2151.76171741, 370: 4707.54170246, 371: 470.75417045, 373: 876.58528579, 374: 2528.09957708, 375: 2528.09957708, 376: 33.32687155}
Recalculating test_cluster_2+BV_1
     ResStr  ResEnd  peptide
0         1       7        0
1         6      18        1
2         6      21        2
3         6      25        3
4         7      18        4
5         7      21        5
6         7      25        6
7         8      18        7
8         8      20        8
9         8      21        9
10        8      24       10
11        8      25       11
12       11      18       12
13       11      20       13
14       11      21       14
15       11      23       15
16       11      25       16
17       19      25       17
18       26      32       18
19       26      33       19
20       27      33       20
21       33      40       21
22       34      40       22
23       34      41       23
24       41      48       24
25       41      49       25
26       41      51       26
27       42      49       27
28       42      51       28
29       42      65       29
30       49      61       30
31       49      65       31
32       50      65       32
33       52      61       33
34       52      65       34
35       74      84       35
36       76      84       36
37       77      84       37
38       77      85       38
39       77      87       39
40       77      88       40
41       77      97       41
42       85      97       42
43       86      97       43
44       88      97       44

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:300: RuntimeWarning: invalid value encountered in scalar divide
  alpha = np.rad2deg(np.arccos(np.dot(y, z) / (ly * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:301: RuntimeWarning: invalid value encountered in scalar divide
  beta = np.rad2deg(np.arccos(np.dot(x, z) / (lx * lz)))
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/lib/mdamath.py:302: RuntimeWarning: invalid value encountered in scalar divide
  gamma = np.rad2deg(np.arccos(np.dot(x, y) / (lx * ly)))

LogPf_by_res shape
(289,)
[1.12259209e+00 8.37804298e+01 8.30801486e+01 8.88402410e-01
 5.15562479e-01 8.27475113e+01 1.06957450e+00 8.05736090e-01
 7.44771211e+01 7.44795489e-01 1.37596701e-01 8.24156694e+01
 7.81277212e+01 8.33733898e+01 1.08592093e+00 1.39274984e+00
 4.44190287e-01 6.37969864e-01 8.28069840e+01 4.80058366e-01
 5.98209685e-01 1.13112106e+00 8.34298926e+01 2.09453033e+00
 8.67898938e-01 1.17537074e+01 8.36716133e+01 8.35330226e+01
 8.31199369e+01 8.30396005e+01 7.56050555e+01 8.33639971e+01
 8.32092403e+01 8.38623637e+01 8.34531818e+01 8.29502103e+01
 8.27000148e+01 8.29371073e+01 1.01625374e+01 8.16250076e-01
 5.56701016e-01 8.27836567e+01 2.53437310e+01 1.90872986e+00
 9.45885684e+01 9.67158488e-01 5.94238200e-01 9.34945522e+01
 1.19989470e+00 3.62203613e-01 5.56954314e-01 5.18367275e-01
 1.01831904e+00 6.37316921e-01 3.91092753e-01 2.40915827e+01
 5.28877315e+01 3.77904215e+01 3.75243197e+01 8.02219182e+01
 8.23259505e+01 1.13936965e+01 8.81451365e+01 9.39942011e+01
 9.47559674e-01 4.40129447e-01 1.17576396e+01 9.40423956e+01
 9.35310052e+01 8.03934133e+01 8.08230418e+01 8.08089260e+01
 9.37477473e+01 9.39754981e+01 9.39801644e+01 9.36701442e+01
 9.39462193e+01 9.37621276e+01 9.36516879e+01 8.32197969e+01
 8.31280451e+01 5.39489969e+01 8.27185736e+01 5.51726966e-01
 8.35877135e+01 8.36990537e+01 1.18905617e+01 9.45792229e+01
 1.19359830e+01 8.09961586e-01 6.78215587e-01 5.36133462e+01
 1.47652872e+00 4.86292075e-01 1.38687541e-01 4.06541586e-01
 9.60249010e+00 9.42235797e-01 1.56590585e+00 8.43855162e+01
 1.54321739e+00 8.37754562e+01 7.35638252e-01 7.65684071e-01
 8.28272295e+01 1.07995205e+00 1.36346418e+00 8.38778445e+01
 8.44838822e+01 8.36398909e+01 8.30170014e-01 8.79723144e-01
 7.79305929e+01 1.17901435e+01 1.15817637e+01 9.35532006e+01
 1.16608287e+01 1.08955458e+01 2.17157624e+01 9.43780851e+01
 8.31443887e+01 3.64838668e-01 8.26822781e+01 1.15508649e+01
 1.19636591e+00 7.81525255e-01 9.34858149e+01 8.38865651e+01
 9.37793884e+01 9.38986200e+01 8.32433431e+01 9.40392998e+01
 9.37391911e+01 8.55768323e+01 9.83123483e+01 5.10422615e+01
 4.51317625e-01 4.98058075e+01 8.04295935e+01 5.42910992e+01
 4.64891667e+01 5.72349034e+01 5.71362833e+01 7.27297867e+01
 7.27162359e+01 7.29320468e+01 7.13679019e+01 7.24826249e+01
 7.99887971e+01 6.45532460e+01 4.81631686e+01 9.41481661e+01
 1.70118704e+00 8.42384531e+01 7.37111763e-01 1.13134525e+01
 8.29253022e+01 1.26304676e+00 1.15556163e+01 8.32138354e+01
 1.16982907e+01 3.04732679e+01 1.17027980e+01 8.30936717e-01
 8.66882614e-01 6.61449190e-01 5.91778726e-01 9.49970351e-01
 1.18586350e+01 9.45359311e+01 1.19327063e+01 9.45728222e+01
 8.32370987e+01 9.83164145e-01 1.13125332e+01 9.36429737e+01
 1.50240918e+00 1.74943310e+00 9.47837757e+01 8.45470309e+01
 7.63783913e+01 1.22440625e+00 1.34879560e+00 8.32454974e+01
 1.28995595e+00 1.16619144e+00 8.33846688e+01 2.32665696e+01
 4.56673460e+01 1.27542572e+00 6.90191577e-01 3.42835346e-01
 6.73316412e+01 3.88202446e-01 4.62953337e-01 8.33219055e+00
 7.31533887e-01 4.27055787e+01 6.94839152e-01 1.93701542e+01
 1.15867864e+00 8.63202771e-01 1.20699617e+00 1.21826929e+00
 3.02310577e+01 6.24933185e+01 1.48015536e+00 1.22254955e+00
 6.59216756e+01 6.37867828e+01 5.71539611e+01 8.38904523e+01
 9.41765829e+01 8.64099138e+01 9.43413301e+01 9.40087988e+01
 9.32524839e+01 4.32613219e+01 9.31196836e+01 8.29511242e+01
 6.42272929e-01 5.86110760e-01 7.33739606e+01 1.02232460e+00
 9.59103252e-01 1.93326909e-01 1.52496899e-01 6.17944091e+01
 2.89465631e-01 2.92113102e-01 6.34263958e-01 2.63603081e-01
 7.33144114e+01 1.43448516e+00 8.39158999e+01 1.44680656e+00
 1.36037450e+00 1.33022051e+00 8.35322809e+01 2.05366455e+01
 8.33996147e+01 7.67261974e-01 8.26642738e+01 1.42462711e+00
 8.39164741e+01 8.37088555e+01 8.35393325e+01 9.40344132e+01
 8.37293190e+01 8.36092138e+01 8.34955828e+01 8.33029097e+01
 8.36343156e+01 8.35920729e+01 8.29950562e+01 7.51736115e+01
 8.28960349e+01 8.31297197e+01 1.08484597e+00 1.62563150e+00
 6.44544074e+01 9.32600153e+01 8.33379854e+01 8.31302131e+01
 8.24919474e-01 8.34937787e+01 8.36742827e+01 8.38510696e+01
 8.31538451e+01 8.28081225e+01 8.26945291e+01 1.83605662e+01
 1.11779314e+00 1.00994628e+00 6.04855226e-01 8.28663793e+01
 2.11009628e-02 1.28383589e-01 8.23952543e+01 4.55102286e-01
 8.29259960e+01 8.35779338e+01 8.35070543e+01 8.30748962e+01
 9.37684096e+01 8.36554304e+01 8.35034585e+01 9.36849390e+01
 8.33116215e+01]
LogPf_by_res [1.12259209e+00 8.37804298e+01 8.30801486e+01 8.88402410e-01
 5.15562479e-01 8.27475113e+01 1.06957450e+00 8.05736090e-01
 7.44771211e+01 7.44795489e-01 1.37596701e-01 8.24156694e+01
 7.81277212e+01 8.33733898e+01 1.08592093e+00 1.39274984e+00
 4.44190287e-01 6.37969864e-01 8.28069840e+01 4.80058366e-01
 5.98209685e-01 1.13112106e+00 8.34298926e+01 2.09453033e+00
 8.67898938e-01 1.17537074e+01 8.36716133e+01 8.35330226e+01
 8.31199369e+01 8.30396005e+01 7.56050555e+01 8.33639971e+01
 8.32092403e+01 8.38623637e+01 8.34531818e+01 8.29502103e+01
 8.27000148e+01 8.29371073e+01 1.01625374e+01 8.16250076e-01
 5.56701016e-01 8.27836567e+01 2.53437310e+01 1.90872986e+00
 9.45885684e+01 9.67158488e-01 5.94238200e-01 9.34945522e+01
 1.19989470e+00 3.62203613e-01 5.56954314e-01 5.18367275e-01
 1.01831904e+00 6.37316921e-01 3.91092753e-01 2.40915827e+01
 5.28877315e+01 3.77904215e+01 3.75243197e+01 8.02219182e+01
 8.23259505e+01 1.13936965e+01 8.81451365e+01 9.39942011e+01
 9.47559674e-01 4.40129447e-01 1.17576396e+01 9.40423956e+01
 9.35310052e+01 8.03934133e+01 8.08230418e+01 8.08089260e+01
 9.37477473e+01 9.39754981e+01 9.39801644e+01 9.36701442e+01
 9.39462193e+01 9.37621276e+01 9.36516879e+01 8.32197969e+01
 8.31280451e+01 5.39489969e+01 8.27185736e+01 5.51726966e-01
 8.35877135e+01 8.36990537e+01 1.18905617e+01 9.45792229e+01
 1.19359830e+01 8.09961586e-01 6.78215587e-01 5.36133462e+01
 1.47652872e+00 4.86292075e-01 1.38687541e-01 4.06541586e-01
 9.60249010e+00 9.42235797e-01 1.56590585e+00 8.43855162e+01
 1.54321739e+00 8.37754562e+01 7.35638252e-01 7.65684071e-01
 8.28272295e+01 1.07995205e+00 1.36346418e+00 8.38778445e+01
 8.44838822e+01 8.36398909e+01 8.30170014e-01 8.79723144e-01
 7.79305929e+01 1.17901435e+01 1.15817637e+01 9.35532006e+01
 1.16608287e+01 1.08955458e+01 2.17157624e+01 9.43780851e+01
 8.31443887e+01 3.64838668e-01 8.26822781e+01 1.15508649e+01
 1.19636591e+00 7.81525255e-01 9.34858149e+01 8.38865651e+01
 9.37793884e+01 9.38986200e+01 8.32433431e+01 9.40392998e+01
 9.37391911e+01 8.55768323e+01 9.83123483e+01 5.10422615e+01
 4.51317625e-01 4.98058075e+01 8.04295935e+01 5.42910992e+01
 4.64891667e+01 5.72349034e+01 5.71362833e+01 7.27297867e+01
 7.27162359e+01 7.29320468e+01 7.13679019e+01 7.24826249e+01
 7.99887971e+01 6.45532460e+01 4.81631686e+01 9.41481661e+01
 1.70118704e+00 8.42384531e+01 7.37111763e-01 1.13134525e+01
 8.29253022e+01 1.26304676e+00 1.15556163e+01 8.32138354e+01
 1.16982907e+01 3.04732679e+01 1.17027980e+01 8.30936717e-01
 8.66882614e-01 6.61449190e-01 5.91778726e-01 9.49970351e-01
 1.18586350e+01 9.45359311e+01 1.19327063e+01 9.45728222e+01
 8.32370987e+01 9.83164145e-01 1.13125332e+01 9.36429737e+01
 1.50240918e+00 1.74943310e+00 9.47837757e+01 8.45470309e+01
 7.63783913e+01 1.22440625e+00 1.34879560e+00 8.32454974e+01
 1.28995595e+00 1.16619144e+00 8.33846688e+01 2.32665696e+01
 4.56673460e+01 1.27542572e+00 6.90191577e-01 3.42835346e-01
 6.73316412e+01 3.88202446e-01 4.62953337e-01 8.33219055e+00
 7.31533887e-01 4.27055787e+01 6.94839152e-01 1.93701542e+01
 1.15867864e+00 8.63202771e-01 1.20699617e+00 1.21826929e+00
 3.02310577e+01 6.24933185e+01 1.48015536e+00 1.22254955e+00
 6.59216756e+01 6.37867828e+01 5.71539611e+01 8.38904523e+01
 9.41765829e+01 8.64099138e+01 9.43413301e+01 9.40087988e+01
 9.32524839e+01 4.32613219e+01 9.31196836e+01 8.29511242e+01
 6.42272929e-01 5.86110760e-01 7.33739606e+01 1.02232460e+00
 9.59103252e-01 1.93326909e-01 1.52496899e-01 6.17944091e+01
 2.89465631e-01 2.92113102e-01 6.34263958e-01 2.63603081e-01
 7.33144114e+01 1.43448516e+00 8.39158999e+01 1.44680656e+00
 1.36037450e+00 1.33022051e+00 8.35322809e+01 2.05366455e+01
 8.33996147e+01 7.67261974e-01 8.26642738e+01 1.42462711e+00
 8.39164741e+01 8.37088555e+01 8.35393325e+01 9.40344132e+01
 8.37293190e+01 8.36092138e+01 8.34955828e+01 8.33029097e+01
 8.36343156e+01 8.35920729e+01 8.29950562e+01 7.51736115e+01
 8.28960349e+01 8.31297197e+01 1.08484597e+00 1.62563150e+00
 6.44544074e+01 9.32600153e+01 8.33379854e+01 8.31302131e+01
 8.24919474e-01 8.34937787e+01 8.36742827e+01 8.38510696e+01
 8.31538451e+01 8.28081225e+01 8.26945291e+01 1.83605662e+01
 1.11779314e+00 1.00994628e+00 6.04855226e-01 8.28663793e+01
 2.11009628e-02 1.28383589e-01 8.23952543e+01 4.55102286e-01
 8.29259960e+01 8.35779338e+01 8.35070543e+01 8.30748962e+01
 9.37684096e+01 8.36554304e+01 8.35034585e+01 9.36849390e+01
 8.33116215e+01]
Pf_by_res [3.07280888e+00 2.42872515e+36 1.20573002e+36 2.43124242e+00
 1.67458015e+00 8.64544900e+35 2.91413928e+00 2.23834352e+00
 2.21310849e+32 2.10601069e+00 1.14751267e+00 6.20398104e+35
 8.51997298e+33 1.61660201e+36 2.96216651e+00 4.02590545e+00
 1.55922716e+00 1.89263467e+00 9.17521455e+35 1.61616873e+00
 1.81885955e+00 3.09912885e+00 1.71057443e+36 8.12162559e+00
 2.38190107e+00 1.27224358e+05 2.17831133e+36 1.89640370e+36
 1.25467119e+36 1.15781789e+36 6.83688700e+32 1.60148896e+36
 1.37187299e+36 2.63609958e+36 1.75087996e+36 1.05881144e+36
 8.24441907e+35 1.04502832e+36 2.59139682e+04 2.26200158e+00
 1.74490658e+00 8.96365868e+35 1.01541250e+11 6.74451688e+00
 1.20030970e+41 2.63045935e+00 1.81165030e+00 4.01946382e+40
 3.31976734e+00 1.43649140e+00 1.74534861e+00 1.67928360e+00
 2.76853704e+00 1.89139929e+00 1.47859565e+00 2.90296256e+10
 9.30786211e+22 2.58328022e+16 1.97972544e+16 6.91729647e+34
 5.67160569e+35 8.87604557e+04 1.90961758e+38 6.62464921e+40
 2.57940738e+00 1.55290823e+00 1.27725613e+05 6.95173930e+40
 4.16868850e+40 8.21137323e+34 1.26183058e+35 1.24414401e+35
 5.17761013e+40 6.50189928e+40 6.53231000e+40 4.79100629e+40
 6.31429145e+40 5.25260363e+40 4.70339316e+40 1.38643198e+36
 1.26488570e+36 2.68999607e+23 8.39885481e+35 1.73624887e+00
 2.00300827e+36 2.23891262e+36 1.45883213e+05 1.18914449e+41
 1.52662216e+05 2.24782164e+00 1.97035866e+00 1.92300502e+23
 4.37772295e+00 1.62627492e+00 1.14876510e+00 1.50161559e+00
 1.48015931e+04 2.56571142e+00 4.78700928e+00 4.44799234e+36
 4.67962225e+00 2.41667566e+36 2.08681348e+00 2.15046494e+00
 9.36286436e+35 2.94453836e+00 3.90971381e+00 2.67722586e+36
 4.90776592e+36 2.11029455e+36 2.29370867e+00 2.41023233e+00
 6.99562447e+33 1.31945397e+05 1.07126293e+05 4.26224889e+40
 1.15940075e+05 5.39355894e+04 2.69796170e+09 9.72482043e+40
 1.28572838e+36 1.44028163e+00 8.09948010e+35 1.03866828e+05
 3.30807323e+00 2.18480211e+00 3.98449731e+40 2.70067496e+36
 5.34405490e+40 6.02077670e+40 1.41946459e+36 6.93025115e+40
 5.13349834e+40 1.46401682e+37 4.97176252e+42 1.47018678e+22
 1.57037999e+00 4.26960172e+21 8.51390202e+34 3.78725714e+23
 1.54877579e+20 7.19122238e+24 6.51587230e+24 3.85607123e+31
 3.80417085e+31 4.72047276e+31 9.87838548e+30 3.01164671e+31
 5.47889800e+34 1.08422282e+28 8.26034778e+20 7.72732210e+40
 5.48044903e+00 3.83968295e+36 2.08989069e+00 8.19162379e+04
 1.03276416e+36 3.53617897e+00 1.04361522e+05 1.37819143e+36
 1.20365799e+05 1.71542648e+13 1.20909544e+05 2.29546794e+00
 2.37948152e+00 1.93759825e+00 1.80720007e+00 2.58563300e+00
 1.41299216e+05 1.13876268e+41 1.52162796e+05 1.18155735e+41
 1.41062857e+36 2.67290032e+00 8.18409617e+04 4.66258473e+40
 4.49249930e+00 5.75134131e+00 1.45905192e+41 5.22767979e+36
 1.48154173e+33 3.40214546e+00 3.85278243e+00 1.42252586e+36
 3.63262652e+00 3.20974481e+00 1.63493894e+36 1.27216304e+10
 6.80889076e+19 3.58022524e+00 1.99409752e+00 1.40893676e+00
 1.74485850e+29 1.47432823e+00 1.58875920e+00 4.15551043e+03
 2.07826599e+00 3.52206354e+18 2.00338681e+00 2.58434848e+08
 3.18572101e+00 2.37074149e+00 3.34342648e+00 3.38133056e+00
 1.34642303e+13 1.38198517e+27 4.39362821e+00 3.39583457e+00
 4.26010139e+28 5.03787963e+27 6.63208262e+24 2.71119353e+36
 7.95005729e+40 3.36781902e+37 9.37387371e+40 6.72206258e+40
 3.15528931e+40 6.13978837e+18 2.76289720e+40 1.05977949e+36
 1.90079635e+00 1.79698590e+00 7.34355270e+31 2.77964883e+00
 2.60935549e+00 1.21327936e+00 1.16473885e+00 6.87022352e+26
 1.33571353e+00 1.33925448e+00 1.88563373e+00 1.30161146e+00
 6.91901549e+31 4.19748344e+00 2.78107238e+36 4.24952222e+00
 3.89765270e+00 3.78187725e+00 1.89499764e+36 8.29758700e+08
 1.65955814e+36 2.15386085e+00 7.95495922e+35 4.15630773e+00
 2.78266959e+36 2.26096601e+36 1.90840753e+36 6.89646887e+40
 2.30770985e+36 2.04653968e+36 1.82671527e+36 1.50658626e+36
 2.09856179e+36 2.01175924e+36 1.10737559e+36 4.44103958e+32
 1.00297595e+36 1.26700560e+36 2.95898402e+00 5.08162705e+00
 9.82185344e+27 3.17914260e+40 1.56036851e+36 1.26763099e+36
 2.28169702e+00 1.82342266e+36 2.18413388e+36 2.60649448e+36
 1.29794431e+36 9.18566608e+35 8.19931724e+35 9.41656623e+07
 3.05809795e+00 2.74545353e+00 1.83098711e+00 9.73668871e+35
 1.02132516e+00 1.13698906e+00 6.07861016e+35 1.57633461e+00
 1.03348095e+36 1.98351482e+36 1.84779115e+36 1.19941365e+36
 5.28570425e+40 2.14334363e+36 1.84115884e+36 4.86241549e+40
 1.51976870e+36]
kints [41000.97419937  3739.33329324  4495.66742529   252.80995882
  3826.43355178  4195.60095885   729.11188642   983.54486858
   333.26843198   579.15415845  5404.98105428  3182.68880137
  2054.91648422  1874.10610808  2008.14087714   333.26843198
   664.95794037  4707.54170199 10538.87311791  3489.74887473
  3739.33329324  3826.43355121   373.93332921  3110.24195868
   917.89750993  3489.74888161  2586.98658088  1749.01758506
  2414.31635313  1595.12299874  1006.45457116  1238.20962611
   373.93332921   746.09508122   333.26843198   712.51527077
  1296.56464798   818.07699064  1326.76552124   325.68231538
   635.02990259  2528.09959386   818.07699266   325.6823152
  3826.43355178   729.11188632  5281.94866501  4195.60095885
  2253.17112184   917.89750993   220.18827496   664.95794037
  2528.09959386  1053.88750906   712.51527346  2305.65421729
   528.19486726   205.49164965  1831.44624546  1357.66985789
   939.2780565   1632.27818324  2102.78164213   664.9579403
   606.44884922   917.89750993   837.13247276   680.44680228
  1421.65486872   333.26843198   449.56674376  1155.56446091
  1595.12299703  1523.33063516   439.33335478   664.95794037
  1558.81356322   837.13245595   373.93333091   241.43163609
   763.47386758  1962.43000752  2647.24526348   664.95794074
   961.15665275   382.64335574   303.9444227   4100.09742062
  4495.66742529  1454.76946397  8371.32448013 10538.87311796
  1454.76946256  1103.55549088  1078.43550416  1632.27818324
  1029.89791222   528.19486726   606.44884922   897.00359232
  1078.43550179  8371.32447976   837.13244934  8371.32448013
  3571.0355703   2008.14087584  1709.20508419  1155.56445915
  6064.48848683   897.00357939  1103.55549137  8765.85284799
  4100.09742056  2008.14087449  2414.31635313   781.25745875
   763.47386677   696.29644347  1029.89791222  1595.12299874
  2102.78163897  1962.43000852  2253.17112184  4929.40130759
 10538.87311791  3489.74887473  1129.26070603   481.71945087
  1670.29882678  6205.74857055  1029.89790963   897.00357963
  2008.14087449  2054.91648422  5044.22181393  3332.68434065
   565.97099671   481.71944856  1632.27818379  2008.14087714
  1454.76946397  1874.10610904   492.94013356   781.25746219
  1238.20962721   876.58528604   373.93332969   897.00358062
  1558.81356338  2772.00606657  2470.55300714   348.97488878
   939.27806859  3489.74888161   664.95794074  6962.96441884
  4100.09742056   961.15665275  3410.31249277  1357.66985789
  1421.65486872   333.26843198   781.25746219  1523.33063592
  1962.43000852  1749.01759097  7812.57457663  4393.33353933
  1296.56465099  1006.45457116  1155.56446091  7291.11882291
  3826.43355121  2305.65421729  8371.32448013  5404.98105315
  1670.29882908  2008.14087584  1155.56445955  6064.48848683
 10538.87311796  2359.35980401  7812.57457663  2414.31635295
  4393.33353955  2647.24524348   729.11188408  5161.71683367
  2414.3163534   6962.96441884   565.97099671  2253.17112016
 11035.55490664  5404.98105315   419.56009632   837.13244881
  1523.33063516  3915.56263922   664.9579403    620.57486181
  1632.27818678  1488.65540644  1389.29405688   876.58528579
  2647.24526348  3489.74888161  1182.48101311   449.56674376
   781.2574583    373.93332969   939.2780565    897.00358062
  1831.44624467   439.33335478   205.49164965   897.00358062
  2528.09960415  2586.98658673  8180.76987097   528.19486719
   897.00357973   939.27805629  4495.66742366  2253.17111984
  1558.81356322   729.11188632  1182.48101644  1874.10611777
  1523.33063592  2102.78164041   252.80995882   680.44680228
  1749.01759097  1749.01759097  7812.57457663  5404.98105315
   419.56009632   170.92050876   579.15415444  1029.89791222
  1831.44624467  1296.56464798   178.97574618  1006.45457572
   939.27805779  1296.56464832  1296.56464798   481.71944856
   373.93332969   155.88135718  2151.76171492   664.9579403
   145.47694677  2305.65421698  2647.24524348  1006.45457572
  4100.09742231   664.9579403    983.54490469   729.11188632
  1078.43550179   528.19486691   419.56009763  1103.55549088
   178.97574618  2008.14087584  1078.43550179  1558.81356322
  1078.43550416  1129.26060126   373.93332969   620.57486181
   348.97488863  1103.55549137   837.13244934   191.77596574
   781.25746219  1182.48101644  1454.76946312  1129.26070603
   729.11188632   680.44680228  1632.27818379  2008.14087714
  1523.33063592   553.08792429   205.49164965   897.00358062
  1831.44624467]
kobs_by_res [1.33431579e+04 1.53962802e-33 3.72858546e-33 1.03983855e+02
 2.28501069e+03 4.85295900e-33 2.50198023e+02 4.39407473e+02
 1.50588384e-30 2.75000579e+02 4.71017115e+03 5.13007500e-33
 2.41188146e-31 1.15928725e-33 6.77929776e+02 8.27809884e+01
 4.26466366e+02 2.48729550e+03 1.14862416e-32 2.15927261e+03
 2.05586698e+03 1.23468037e+03 2.18601028e-34 3.82958057e+02
 3.85363406e+02 2.74298801e-02 1.18761104e-33 9.22281257e-34
 1.92426221e-33 1.37769766e-33 1.47209479e-30 7.73161513e-34
 2.72571390e-34 2.83029931e-34 1.90343393e-34 6.72938770e-34
 1.57265738e-33 7.82827578e-34 5.11988558e-02 1.43979703e+02
 3.63933469e+02 2.82038806e-33 8.05659765e-09 4.82884573e+01
 3.18787188e-38 2.77180443e+02 2.91554538e+03 1.04382105e-37
 6.78713564e+02 6.38985732e+02 1.26157189e+02 3.95977153e+02
 9.13153611e+02 5.57199907e+02 4.81886493e+02 7.94241803e-08
 5.67471736e-21 7.95467901e-15 9.25101134e-14 1.96271746e-32
 1.65610606e-33 1.83897004e-02 1.10115327e-35 1.00376325e-38
 2.35111698e+02 5.91082908e+02 6.55414725e-03 9.78815190e-39
 3.41031687e-38 4.05861995e-33 3.56281384e-33 9.28802819e-33
 3.08080940e-38 2.34290100e-38 6.72554356e-39 1.38792959e-38
 2.46870702e-38 1.59374762e-38 7.95028862e-39 1.74138825e-34
 6.03591193e-34 7.29528949e-21 3.15191216e-33 3.82985384e+02
 4.79856556e-34 1.70905891e-34 2.08347771e-03 3.44793879e-38
 2.94484617e-02 6.47190791e+02 4.24862978e+03 5.48041893e-20
 3.32311907e+02 6.78578681e+02 9.38778086e+02 1.08701468e+03
 6.95802070e-02 2.05866826e+02 1.26686374e+02 2.01664824e-34
 2.30453538e+02 3.46398344e-33 4.01153460e+02 3.89279747e+03
 3.81404176e-33 6.81988357e+02 4.37168849e+02 4.31627558e-34
 1.23569228e-33 4.25060842e-34 4.81122780e+02 3.63693274e+03
 5.86094557e-31 1.52194841e-02 2.25371035e-02 1.83297006e-38
 6.58507306e-03 1.29097772e-02 3.81731851e-07 1.64025959e-38
 1.63547890e-33 1.36253214e+03 2.78187130e-33 4.74588603e-02
 3.18580406e+03 1.59728374e+03 2.83413595e-38 1.78370022e-34
 3.12552707e-38 1.03072226e-37 7.25553789e-34 1.29433055e-38
 3.91183700e-38 1.40361535e-34 1.01457417e-39 2.26684418e-19
 3.60403851e+02 1.12825383e-19 1.91719165e-32 5.30236211e-21
 9.39302820e-18 2.60610229e-22 7.56522090e-23 2.02604520e-29
 3.25487386e-29 1.85698622e-29 3.78536888e-29 2.97844889e-29

/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"
/home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

concat plot_df
plotting nan_df
nan_df
nan_df + expt_df
plotting MSE for nan_df
Finished evaluating HDX
         Bc         Bh             calc_name
0  0.064192  92.312862  train_cluster_2+BV_1
Analysis dumped to /home/alexi/Documents/ValDX/results/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV/Benchmark/cluster_2+BV_Sp_res_neighbours/20240402-191934_analysis.csv
dict_keys(['cluster_2+BV_Sp_res_neighbours'])
dict_keys(['train_dfs', 'val_dfs', 'expt_df', 'merge_df', 'expt_segs', 'train_segs', 'val_segs', 'n_reps', 'times', 'expt_name', 'calc_name', 'train_rep_names', 'val_rep_names', 'HDX_data', 'train_gammas', 'val_gammas', 'weights', 'BV_constants', 'LogPfs'])
Key: train_dfs
<class 'list'>
Key: val_dfs
<class 'list'>
Key: expt_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df expt_df
Key: merge_df
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df merge_df
Key: expt_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df expt_segs
Key: train_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df train_segs
Key: val_segs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df val_segs
Key: n_reps
<class 'int'>
Key: times
<class 'list'>
Key: expt_name
<class 'str'>
Key: calc_name
<class 'str'>
Key: train_rep_names
<class 'list'>
Key: val_rep_names
<class 'list'>
Key: HDX_data
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df HDX_data
Key: train_gammas
<class 'list'>
Key: val_gammas
<class 'list'>
Key: weights
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df weights
Key: BV_constants
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df BV_constants
Key: LogPfs
<class 'pandas.core.frame.DataFrame'>
Adding cluster_2+BV_Sp_res_neighbours to df LogPfs
Saving experiment to:  /home/alexi/Documents/ValDX/logs/HOIPapo_test_mean1-Refine-Ensemble/cluster_2+BV_Sp_res_neighbours/cluster_2+BV_Sp_res_neighbours0_1712081975.pkl
Analysis Dump

/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1663: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["name"] = [name]*len(dump)
/home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1664: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dump["split_type"] = [self.settings.split_mode]*len(dump)
/home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:961: UserWarning: Reader has no dt information, set to 1.0 ps
  pickle.dump(self, f)

{'cluster_2+BV_Sp_res_neighbours': {'train_dfs': [    0.0      0.5      5.0  peptide             calc_name
0   0.0  0.00000  0.00000       21  train_cluster_2+BV_1
1   0.0  0.00000  0.00000       22  train_cluster_2+BV_1
2   0.0  0.00000  0.00000       23  train_cluster_2+BV_1
3   0.0  0.00460  0.04201       24  train_cluster_2+BV_1
4   0.0  0.00460  0.04201       25  train_cluster_2+BV_1
5   0.0  0.00116  0.01138       27  train_cluster_2+BV_1
6   0.0  0.25474  0.29256       33  train_cluster_2+BV_1
7   0.0  0.16983  0.19504       34  train_cluster_2+BV_1
8   0.0  0.22360  0.23557       35  train_cluster_2+BV_1
9   0.0  0.28618  0.29032       36  train_cluster_2+BV_1
10  0.0  0.33388  0.33871       37  train_cluster_2+BV_1
11  0.0  0.28618  0.29032       38  train_cluster_2+BV_1
12  0.0  0.22259  0.22580       39  train_cluster_2+BV_1
13  0.0  0.20033  0.20322       40  train_cluster_2+BV_1
14  0.0  0.10544  0.10696       41  train_cluster_2+BV_1
15  0.0  0.00000  0.00000       42  train_cluster_2+BV_1
16  0.0  0.00000  0.00000       43  train_cluster_2+BV_1
17  0.0  0.00000  0.00000       44  train_cluster_2+BV_1
18  0.0  0.00000  0.00000       45  train_cluster_2+BV_1
19  0.0  0.00261  0.02455       46  train_cluster_2+BV_1
20  0.0  0.25196  0.26841       47  train_cluster_2+BV_1
21  0.0  0.20160  0.21502       48  train_cluster_2+BV_1
22  0.0  0.57814  0.63067       49  train_cluster_2+BV_1
23  0.0  0.67237  0.71564       50  train_cluster_2+BV_1
24  0.0  0.38951  0.42338       51  train_cluster_2+BV_1
25  0.0  0.34040  0.38933       52  train_cluster_2+BV_1
26  0.0  0.40636  0.45040       53  train_cluster_2+BV_1
27  0.0  0.17953  0.20506       54  train_cluster_2+BV_1
28  0.0  0.16955  0.19367       55  train_cluster_2+BV_1
29  0.0  0.14533  0.16600       56  train_cluster_2+BV_1
30  0.0  0.00000  0.00000       58  train_cluster_2+BV_1
31  0.0  0.00000  0.00000       59  train_cluster_2+BV_1
32  0.0  0.08661  0.11410       89  train_cluster_2+BV_1
33  0.0  0.15687  0.18225       90  train_cluster_2+BV_1
34  0.0  0.13596  0.15795       91  train_cluster_2+BV_1], 'val_dfs': [    0.0      0.5      5.0  peptide           calc_name
0   0.0  0.50000  0.50000        0  val_cluster_2+BV_1
1   0.0  0.36448  0.37171        1  val_cluster_2+BV_1
2   0.0  0.35817  0.36754        2  val_cluster_2+BV_1
3   0.0  0.33661  0.36373        3  val_cluster_2+BV_1
4   0.0  0.40093  0.40888        4  val_cluster_2+BV_1
5   0.0  0.38572  0.39582        5  val_cluster_2+BV_1
6   0.0  0.35641  0.38513        6  val_cluster_2+BV_1
7   0.0  0.33436  0.34320        7  val_cluster_2+BV_1
8   0.0  0.36495  0.37687        8  val_cluster_2+BV_1
9   0.0  0.33453  0.34547        9  val_cluster_2+BV_1
10  0.0  0.33727  0.36981       10  val_cluster_2+BV_1
11  0.0  0.31619  0.34670       11  val_cluster_2+BV_1
12  0.0  0.28704  0.29840       12  val_cluster_2+BV_1
13  0.0  0.33494  0.34951       13  val_cluster_2+BV_1
14  0.0  0.30144  0.31456       14  val_cluster_2+BV_1
15  0.0  0.33685  0.36595       15  val_cluster_2+BV_1
16  0.0  0.28993  0.32480       16  val_cluster_2+BV_1
17  0.0  0.34065  0.40025       17  val_cluster_2+BV_1
18  0.0  0.00378  0.03593       18  val_cluster_2+BV_1
19  0.0  0.00315  0.02994       19  val_cluster_2+BV_1
20  0.0  0.00315  0.02994       20  val_cluster_2+BV_1
21  0.0  0.11511  0.14793       26  val_cluster_2+BV_1
22  0.0  0.12634  0.13819       28  val_cluster_2+BV_1
23  0.0  0.14518  0.16410       29  val_cluster_2+BV_1
24  0.0  0.27652  0.30707       30  val_cluster_2+BV_1
25  0.0  0.20278  0.22519       31  val_cluster_2+BV_1
26  0.0  0.21700  0.23861       32  val_cluster_2+BV_1
27  0.0  0.00000  0.00000       57  val_cluster_2+BV_1
28  0.0  0.00000  0.00000       60  val_cluster_2+BV_1
29  0.0  0.00000  0.00000       61  val_cluster_2+BV_1
30  0.0  0.00000  0.00000       62  val_cluster_2+BV_1
31  0.0  0.00000  0.00000       63  val_cluster_2+BV_1
32  0.0  0.23567  0.27341       64  val_cluster_2+BV_1
33  0.0  0.25531  0.29619       65  val_cluster_2+BV_1
34  0.0  0.21884  0.25388       66  val_cluster_2+BV_1
35  0.0  0.27091  0.30362       67  val_cluster_2+BV_1
36  0.0  0.27852  0.32312       68  val_cluster_2+BV_1
37  0.0  0.29026  0.32531       69  val_cluster_2+BV_1
38  0.0  0.12375  0.18812       70  val_cluster_2+BV_1
39  0.0  0.27864  0.36064       71  val_cluster_2+BV_1
40  0.0  0.04515  0.13365       72  val_cluster_2+BV_1
41  0.0  0.27083  0.36453       73  val_cluster_2+BV_1
42  0.0  0.25852  0.34797       74  val_cluster_2+BV_1
43  0.0  0.28437  0.38276       75  val_cluster_2+BV_1
44  0.0  0.38044  0.47043       76  val_cluster_2+BV_1
45  0.0  0.36051  0.46550       77  val_cluster_2+BV_1
46  0.0  0.25829  0.31262       78  val_cluster_2+BV_1
47  0.0  0.23395  0.25941       79  val_cluster_2+BV_1
48  0.0  0.21724  0.24088       80  val_cluster_2+BV_1
49  0.0  0.11253  0.17378       81  val_cluster_2+BV_1
50  0.0  0.17711  0.22815       82  val_cluster_2+BV_1
51  0.0  0.24041  0.28753       83  val_cluster_2+BV_1
52  0.0  0.19321  0.24889       84  val_cluster_2+BV_1
53  0.0  0.26044  0.31149       85  val_cluster_2+BV_1
54  0.0  0.16076  0.24826       86  val_cluster_2+BV_1
55  0.0  0.31253  0.37378       87  val_cluster_2+BV_1
56  0.0  0.44647  0.53398       88  val_cluster_2+BV_1
57  0.0  0.11375  0.13603       92  val_cluster_2+BV_1
58  0.0  0.00000  0.00000       93  val_cluster_2+BV_1
59  0.0  0.00000  0.00000       94  val_cluster_2+BV_1
60  0.0  0.00000  0.00000       95  val_cluster_2+BV_1
61  0.0  0.16667  0.16667       96  val_cluster_2+BV_1
62  0.0  0.20000  0.20000       97  val_cluster_2+BV_1
63  0.0  0.22222  0.22222       98  val_cluster_2+BV_1
64  0.0  0.21127  0.21752       99  val_cluster_2+BV_1
65  0.0  0.22301  0.22961      100  val_cluster_2+BV_1
66  0.0  0.21127  0.21752      101  val_cluster_2+BV_1
67  0.0  0.25089  0.25831      102  val_cluster_2+BV_1
68  0.0  0.23613  0.24311      103  val_cluster_2+BV_1
69  0.0  0.20071  0.20665      104  val_cluster_2+BV_1
70  0.0  0.26761  0.27553      105  val_cluster_2+BV_1
71  0.0  0.22301  0.22961      106  val_cluster_2+BV_1
72  0.0  0.23613  0.24311      107  val_cluster_2+BV_1], 'expt_df':      0.0      0.5      5.0  peptide     calc_name  \
0    0.0  0.41879  0.44438        0  Experimental
1    0.0  0.37096  0.45204        1  Experimental
2    0.0  0.40040  0.48544        2  Experimental
3    0.0  0.45875  0.51503        3  Experimental
4    0.0  0.41726  0.49519        4  Experimental
5    0.0  0.44176  0.50927        5  Experimental
6    0.0  0.48987  0.54090        6  Experimental
7    0.0  0.41316  0.48254        7  Experimental
8    0.0  0.46617  0.51066        8  Experimental
9    0.0  0.46825  0.52028        9  Experimental
10   0.0  0.48273  0.53102       10  Experimental
11   0.0  0.50258  0.53988       11  Experimental
12   0.0  0.47373  0.50144       12  Experimental
13   0.0  0.52057  0.54102       13  Experimental
14   0.0  0.52823  0.55640       14  Experimental
15   0.0  0.55802  0.57504       15  Experimental
16   0.0  0.55641  0.57196       16  Experimental
17   0.0  0.52928  0.54827       17  Experimental
18   0.0  0.17163  0.27883       18  Experimental
19   0.0  0.16883  0.28686       19  Experimental
20   0.0  0.16341  0.27353       20  Experimental
21   0.0  0.32309  0.41205       21  Experimental
22   0.0  0.31355  0.39928       22  Experimental
23   0.0  0.34392  0.42213       23  Experimental
24   0.0  0.35604  0.35617       24  Experimental
25   0.0  0.34105  0.35125       25  Experimental
26   0.0  0.34135  0.38830       26  Experimental
27   0.0  0.28512  0.29602       27  Experimental
28   0.0  0.28439  0.33185       28  Experimental
29   0.0  0.32954  0.39085       29  Experimental
30   0.0  0.26192  0.34619       30  Experimental
31   0.0  0.31421  0.37857       31  Experimental
32   0.0  0.32314  0.38565       32  Experimental
33   0.0  0.29666  0.37860       33  Experimental
34   0.0  0.38440  0.44775       34  Experimental
35   0.0  0.33633  0.46390       35  Experimental
36   0.0  0.34716  0.45807       36  Experimental
37   0.0  0.34165  0.44393       37  Experimental
38   0.0  0.30725  0.43533       38  Experimental
39   0.0  0.33252  0.48976       39  Experimental
40   0.0  0.28369  0.42940       40  Experimental
41   0.0  0.35906  0.50293       41  Experimental
42   0.0  0.33575  0.45181       42  Experimental
43   0.0  0.33443  0.43697       43  Experimental
44   0.0  0.37082  0.47284       44  Experimental
45   0.0  0.37847  0.48848       45  Experimental
46   0.0  0.22218  0.31040       46  Experimental
47   0.0  0.18217  0.28305       47  Experimental
48   0.0  0.25719  0.37045       48  Experimental
49   0.0  0.49756  0.50850       49  Experimental
50   0.0  0.55024  0.54326       50  Experimental
51   0.0  0.24310  0.29208       51  Experimental
52   0.0  0.19173  0.23972       52  Experimental
53   0.0  0.18105  0.23003       53  Experimental
54   0.0  0.26140  0.30267       54  Experimental
55   0.0  0.26392  0.30614       55  Experimental
56   0.0  0.26061  0.32801       56  Experimental
57   0.0  0.45297  0.53974       57  Experimental
58   0.0  0.31622  0.45372       58  Experimental
59   0.0  0.43711  0.52972       59  Experimental
60   0.0  0.47628  0.54735       60  Experimental
61   0.0  0.49249  0.57156       61  Experimental
62   0.0  0.50341  0.53212       62  Experimental
63   0.0  0.53500  0.53827       63  Experimental
64   0.0  0.26524  0.35365       64  Experimental
65   0.0  0.25454  0.32548       65  Experimental
66   0.0  0.25152  0.35786       66  Experimental
67   0.0  0.28164  0.36568       67  Experimental
68   0.0  0.24177  0.30174       68  Experimental
69   0.0  0.27969  0.36567       69  Experimental
70   0.0  0.38633  0.44869       70  Experimental
71   0.0  0.24871  0.31226       71  Experimental
72   0.0  0.36820  0.37879       72  Experimental
73   0.0  0.22903  0.26839       73  Experimental
74   0.0  0.21687  0.25989       74  Experimental
75   0.0  0.20479  0.23593       75  Experimental
76   0.0  0.11684  0.15140       76  Experimental
77   0.0  0.13267  0.18143       77  Experimental
78   0.0  0.35203  0.42601       78  Experimental
79   0.0  0.20249  0.21472       79  Experimental
80   0.0  0.16260  0.17496       80  Experimental
81   0.0  0.05688  0.07274       81  Experimental
82   0.0  0.07600  0.11464       82  Experimental
83   0.0  0.08147  0.13526       83  Experimental
84   0.0  0.08527  0.13242       84  Experimental
85   0.0  0.08569  0.14304       85  Experimental
86   0.0  0.06291  0.07885       86  Experimental
87   0.0  0.09393  0.16201       87  Experimental
88   0.0  0.10385  0.19651       88  Experimental
89   0.0  0.53877  0.49943       89  Experimental
90   0.0  0.51417  0.47866       90  Experimental
91   0.0  0.50107  0.49072       91  Experimental
92   0.0  0.45551  0.47280       92  Experimental
93   0.0  0.06500  0.10668       93  Experimental
94   0.0  0.06362  0.10593       94  Experimental
95   0.0  0.04358  0.04371       95  Experimental
96   0.0  0.08151  0.10674       96  Experimental
97   0.0  0.08795  0.11537       97  Experimental
98   0.0  0.09261  0.12297       98  Experimental
99   0.0  0.17298  0.20225       99  Experimental
100  0.0  0.20729  0.23030      100  Experimental
101  0.0  0.20401  0.23454      101  Experimental
102  0.0  0.21943  0.23426      102  Experimental
103  0.0  0.21731  0.24442      103  Experimental
104  0.0  0.22028  0.25199      104  Experimental
105  0.0  0.22217  0.24175      105  Experimental
106  0.0  0.22454  0.24966      106  Experimental
107  0.0  0.23913  0.27068      107  Experimental

                               name split_type
0    cluster_2+BV_Sp_res_neighbours         Sp
1    cluster_2+BV_Sp_res_neighbours         Sp
2    cluster_2+BV_Sp_res_neighbours         Sp
3    cluster_2+BV_Sp_res_neighbours         Sp
4    cluster_2+BV_Sp_res_neighbours         Sp
5    cluster_2+BV_Sp_res_neighbours         Sp
6    cluster_2+BV_Sp_res_neighbours         Sp
7    cluster_2+BV_Sp_res_neighbours         Sp
8    cluster_2+BV_Sp_res_neighbours         Sp
9    cluster_2+BV_Sp_res_neighbours         Sp
10   cluster_2+BV_Sp_res_neighbours         Sp
11   cluster_2+BV_Sp_res_neighbours         Sp
12   cluster_2+BV_Sp_res_neighbours         Sp
13   cluster_2+BV_Sp_res_neighbours         Sp
14   cluster_2+BV_Sp_res_neighbours         Sp
15   cluster_2+BV_Sp_res_neighbours         Sp
16   cluster_2+BV_Sp_res_neighbours         Sp
17   cluster_2+BV_Sp_res_neighbours         Sp
18   cluster_2+BV_Sp_res_neighbours         Sp
19   cluster_2+BV_Sp_res_neighbours         Sp
20   cluster_2+BV_Sp_res_neighbours         Sp
21   cluster_2+BV_Sp_res_neighbours         Sp
22   cluster_2+BV_Sp_res_neighbours         Sp
23   cluster_2+BV_Sp_res_neighbours         Sp
24   cluster_2+BV_Sp_res_neighbours         Sp
25   cluster_2+BV_Sp_res_neighbours         Sp
26   cluster_2+BV_Sp_res_neighbours         Sp
27   cluster_2+BV_Sp_res_neighbours         Sp
28   cluster_2+BV_Sp_res_neighbours         Sp
29   cluster_2+BV_Sp_res_neighbours         Sp
30   cluster_2+BV_Sp_res_neighbours         Sp
31   cluster_2+BV_Sp_res_neighbours         Sp
32   cluster_2+BV_Sp_res_neighbours         Sp
33   cluster_2+BV_Sp_res_neighbours         Sp
34   cluster_2+BV_Sp_res_neighbours         Sp
35   cluster_2+BV_Sp_res_neighbours         Sp
36   cluster_2+BV_Sp_res_neighbours         Sp
37   cluster_2+BV_Sp_res_neighbours         Sp
38   cluster_2+BV_Sp_res_neighbours         Sp
39   cluster_2+BV_Sp_res_neighbours         Sp
40   cluster_2+BV_Sp_res_neighbours         Sp
41   cluster_2+BV_Sp_res_neighbours         Sp
42   cluster_2+BV_Sp_res_neighbours         Sp
43   cluster_2+BV_Sp_res_neighbours         Sp
44   cluster_2+BV_Sp_res_neighbours         Sp
45   cluster_2+BV_Sp_res_neighbours         Sp
46   cluster_2+BV_Sp_res_neighbours         Sp
47   cluster_2+BV_Sp_res_neighbours         Sp
48   cluster_2+BV_Sp_res_neighbours         Sp
49   cluster_2+BV_Sp_res_neighbours         Sp
50   cluster_2+BV_Sp_res_neighbours         Sp
51   cluster_2+BV_Sp_res_neighbours         Sp
52   cluster_2+BV_Sp_res_neighbours         Sp
53   cluster_2+BV_Sp_res_neighbours         Sp
54   cluster_2+BV_Sp_res_neighbours         Sp
55   cluster_2+BV_Sp_res_neighbours         Sp
56   cluster_2+BV_Sp_res_neighbours         Sp
57   cluster_2+BV_Sp_res_neighbours         Sp
58   cluster_2+BV_Sp_res_neighbours         Sp
59   cluster_2+BV_Sp_res_neighbours         Sp
60   cluster_2+BV_Sp_res_neighbours         Sp
61   cluster_2+BV_Sp_res_neighbours         Sp
62   cluster_2+BV_Sp_res_neighbours         Sp
63   cluster_2+BV_Sp_res_neighbours         Sp
64   cluster_2+BV_Sp_res_neighbours         Sp
65   cluster_2+BV_Sp_res_neighbours         Sp
66   cluster_2+BV_Sp_res_neighbours         Sp
67   cluster_2+BV_Sp_res_neighbours         Sp
68   cluster_2+BV_Sp_res_neighbours         Sp
69   cluster_2+BV_Sp_res_neighbours         Sp
70   cluster_2+BV_Sp_res_neighbours         Sp
71   cluster_2+BV_Sp_res_neighbours         Sp
72   cluster_2+BV_Sp_res_neighbours         Sp
73   cluster_2+BV_Sp_res_neighbours         Sp
74   cluster_2+BV_Sp_res_neighbours         Sp
75   cluster_2+BV_Sp_res_neighbours         Sp
76   cluster_2+BV_Sp_res_neighbours         Sp
77   cluster_2+BV_Sp_res_neighbours         Sp
78   cluster_2+BV_Sp_res_neighbours         Sp
79   cluster_2+BV_Sp_res_neighbours         Sp
80   cluster_2+BV_Sp_res_neighbours         Sp
81   cluster_2+BV_Sp_res_neighbours         Sp
82   cluster_2+BV_Sp_res_neighbours         Sp
83   cluster_2+BV_Sp_res_neighbours         Sp
84   cluster_2+BV_Sp_res_neighbours         Sp
85   cluster_2+BV_Sp_res_neighbours         Sp
86   cluster_2+BV_Sp_res_neighbours         Sp
87   cluster_2+BV_Sp_res_neighbours         Sp
88   cluster_2+BV_Sp_res_neighbours         Sp
89   cluster_2+BV_Sp_res_neighbours         Sp
90   cluster_2+BV_Sp_res_neighbours         Sp
91   cluster_2+BV_Sp_res_neighbours         Sp
92   cluster_2+BV_Sp_res_neighbours         Sp
93   cluster_2+BV_Sp_res_neighbours         Sp
94   cluster_2+BV_Sp_res_neighbours         Sp
95   cluster_2+BV_Sp_res_neighbours         Sp
96   cluster_2+BV_Sp_res_neighbours         Sp
97   cluster_2+BV_Sp_res_neighbours         Sp
98   cluster_2+BV_Sp_res_neighbours         Sp
99   cluster_2+BV_Sp_res_neighbours         Sp
100  cluster_2+BV_Sp_res_neighbours         Sp
101  cluster_2+BV_Sp_res_neighbours         Sp
102  cluster_2+BV_Sp_res_neighbours         Sp
103  cluster_2+BV_Sp_res_neighbours         Sp
104  cluster_2+BV_Sp_res_neighbours         Sp
105  cluster_2+BV_Sp_res_neighbours         Sp
106  cluster_2+BV_Sp_res_neighbours         Sp
107  cluster_2+BV_Sp_res_neighbours         Sp  , 'merge_df':      0.0      0.5      5.0  peptide             calc_name  \
0    0.0  0.41879  0.44438        0          Experimental
1    0.0  0.37096  0.45204        1          Experimental
2    0.0  0.40040  0.48544        2          Experimental
3    0.0  0.45875  0.51503        3          Experimental
4    0.0  0.41726  0.49519        4          Experimental
5    0.0  0.44176  0.50927        5          Experimental
6    0.0  0.48987  0.54090        6          Experimental
7    0.0  0.41316  0.48254        7          Experimental
8    0.0  0.46617  0.51066        8          Experimental
9    0.0  0.46825  0.52028        9          Experimental
10   0.0  0.48273  0.53102       10          Experimental
11   0.0  0.50258  0.53988       11          Experimental
12   0.0  0.47373  0.50144       12          Experimental
13   0.0  0.52057  0.54102       13          Experimental
14   0.0  0.52823  0.55640       14          Experimental
15   0.0  0.55802  0.57504       15          Experimental
16   0.0  0.55641  0.57196       16          Experimental
17   0.0  0.52928  0.54827       17          Experimental
18   0.0  0.17163  0.27883       18          Experimental
19   0.0  0.16883  0.28686       19          Experimental
20   0.0  0.16341  0.27353       20          Experimental
21   0.0  0.32309  0.41205       21          Experimental
22   0.0  0.31355  0.39928       22          Experimental
23   0.0  0.34392  0.42213       23          Experimental
24   0.0  0.35604  0.35617       24          Experimental
25   0.0  0.34105  0.35125       25          Experimental
26   0.0  0.34135  0.38830       26          Experimental
27   0.0  0.28512  0.29602       27          Experimental
28   0.0  0.28439  0.33185       28          Experimental
29   0.0  0.32954  0.39085       29          Experimental
30   0.0  0.26192  0.34619       30          Experimental
31   0.0  0.31421  0.37857       31          Experimental
32   0.0  0.32314  0.38565       32          Experimental
33   0.0  0.29666  0.37860       33          Experimental
34   0.0  0.38440  0.44775       34          Experimental
35   0.0  0.33633  0.46390       35          Experimental
36   0.0  0.34716  0.45807       36          Experimental
37   0.0  0.34165  0.44393       37          Experimental
38   0.0  0.30725  0.43533       38          Experimental
39   0.0  0.33252  0.48976       39          Experimental
40   0.0  0.28369  0.42940       40          Experimental
41   0.0  0.35906  0.50293       41          Experimental
42   0.0  0.33575  0.45181       42          Experimental
43   0.0  0.33443  0.43697       43          Experimental
44   0.0  0.37082  0.47284       44          Experimental
45   0.0  0.37847  0.48848       45          Experimental
46   0.0  0.22218  0.31040       46          Experimental
47   0.0  0.18217  0.28305       47          Experimental
48   0.0  0.25719  0.37045       48          Experimental
49   0.0  0.49756  0.50850       49          Experimental
50   0.0  0.55024  0.54326       50          Experimental
51   0.0  0.24310  0.29208       51          Experimental
52   0.0  0.19173  0.23972       52          Experimental
53   0.0  0.18105  0.23003       53          Experimental

In [24]:
s = io.StringIO()
ps = pstats.Stats(pr, stream=s).sort_stats('cumulative')
ps.print_stats()

print(s.getvalue())

         53663779 function calls (53059378 primitive calls) in 383.024 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000  383.035  127.678 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3472(run_code)
     13/3    0.000    0.000  383.035  127.678 {built-in method builtins.exec}
        1    0.001    0.001  383.035  383.035 /tmp/ipykernel_3229600/1471063739.py:9(<module>)
        1    0.003    0.003  383.034  383.034 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1032(run_refine_ensemble)
       13    0.001    0.000  315.480   24.268 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:731(run_VDX)
        3    0.004    0.001  303.630  101.210 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:820(run_benchmark_ensemble)
       13    0.001    0.000  284.048   21.850 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1260(validate_HDX)
    16496  281.229    0.017  281.229    0.017 {method 'acquire' of '_thread.lock' objects}
     2762    0.014    0.000  280.572    0.102 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/threading.py:270(wait)
       13    0.002    0.000  280.466   21.574 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:561(recalculate_test_and_val)
     2910    0.004    0.000  280.194    0.096 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:478(_chain_from_iterable_of_lists)
     2910    0.006    0.000  280.189    0.096 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/_base.py:612(result_iterator)
     2871    0.009    0.000  280.182    0.098 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/_base.py:416(result)
       13    0.029    0.002  279.787   21.522 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:472(recalculate_dataset)
       13    0.005    0.000  277.668   21.359 /home/alexi/Documents/ValDX/ValDX/helpful_funcs.py:555(calc_traj_LogP_byres)
       51    0.001    0.000   77.217    1.514 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:452(run)
       51    0.001    0.000   76.740    1.505 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:984(communicate)
        4    0.000    0.000   61.938   15.485 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:240(pre_process_features)
     7462   57.655    0.008   57.655    0.008 {built-in method posix.waitpid}
      125    0.000    0.000   57.652    0.461 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:1078(wait)
      125    0.000    0.000   57.651    0.461 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:1790(_wait)
       52    0.000    0.000   57.651    1.109 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:1777(_try_wait)
       21    0.000    0.000   18.865    0.898 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:118(load_HDXer)
       17    0.001    0.000   15.358    0.903 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:37(__init__)
       22    0.002    0.000   15.094    0.686 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:1831(_communicate)
       65    0.001    0.000   15.089    0.232 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/selectors.py:402(select)
       65   15.088    0.232   15.088    0.232 {method 'poll' of 'select.poll' objects}
       26    0.002    0.000    7.869    0.303 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:298(calc_reweight_HDX)
       13    0.002    0.000    7.179    0.552 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1307(evaluate_HDX)
       41    0.000    0.000    6.520    0.159 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/pyplot.py:840(savefig)
       41    0.000    0.000    5.445    0.133 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/figure.py:2169(savefig)
       41    0.001    0.000    5.445    0.133 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backend_bases.py:2083(print_figure)
       41    0.001    0.000    5.432    0.132 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backend_bases.py:1600(wrapper)
       41    0.008    0.000    5.431    0.132 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py:460(print_png)
       13    0.000    0.000    4.967    0.382 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:1226(train_HDX)
       39    0.000    0.000    4.392    0.113 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:650(map)
       39    0.001    0.000    4.392    0.113 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/_base.py:583(map)
       39    0.002    0.000    4.391    0.113 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/_base.py:608(<listcomp>)
     2871    0.006    0.000    4.388    0.002 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:611(submit)
     2871    0.003    0.000    4.356    0.002 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:573(_start_queue_management_thread)
       39    0.022    0.001    4.337    0.111 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:600(_adjust_process_count)
      780    0.030    0.000    4.266    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/multiprocessing/process.py:110(start)
       25    0.001    0.000    4.243    0.170 /home/alexi/Documents/ValDX/ValDX/helpful_funcs.py:18(conda_to_env_dict)
      780    0.019    0.000    4.214    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/multiprocessing/context.py:274(_Popen)
      780    0.011    0.000    4.191    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/multiprocessing/popen_fork.py:15(__init__)
     1796    3.997    0.002    3.997    0.002 {method 'read' of '_io.BufferedReader' objects}
       41    0.001    0.000    3.915    0.095 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/image.py:1492(imsave)
       41    0.001    0.000    3.911    0.095 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/PIL/Image.py:2354(save)
       41    0.001    0.000    3.740    0.091 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/PIL/PngImagePlugin.py:1227(_save)
       41    0.000    0.000    3.738    0.091 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/PIL/ImageFile.py:517(_save)
       41    0.001    0.000    3.737    0.091 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/PIL/ImageFile.py:545(_encode_tile)
      110    3.730    0.034    3.730    0.034 {method 'encode' of 'ImagingEncoder' objects}
      780    0.029    0.000    3.664    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/multiprocessing/popen_fork.py:66(_launch)
      780    3.579    0.005    3.588    0.005 {built-in method posix.fork}
33391/10747    0.036    0.000    3.360    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py:384(wrapper)
       13    0.009    0.001    2.975    0.229 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:1369(plot_R_agreement_trainval)
    11218    0.021    0.000    2.920    0.000 {built-in method builtins.print}
       82    0.001    0.000    2.582    0.031 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py:400(draw)
      444    0.002    0.000    2.433    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/frame.py:1084(__repr__)
 14012/82    0.019    0.000    2.421    0.030 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/artist.py:33(draw_wrapper)
       82    0.002    0.000    2.421    0.030 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/figure.py:1819(draw)
      444    0.003    0.000    2.412    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/frame.py:1190(to_string)
      444    0.001    0.000    2.392    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1111(to_string)
      444    0.001    0.000    2.386    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/string.py:29(to_string)
      444    0.002    0.000    2.384    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/string.py:41(_get_string_representation)
   184/82    0.002    0.000    2.347    0.029 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/image.py:113(_draw_list_compositing_images)
      102    0.001    0.000    2.329    0.023 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_base.py:2666(draw)
       38    0.002    0.000    2.308    0.061 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/seaborn/categorical.py:1574(boxplot)
      444    0.000    0.000    2.231    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/string.py:35(_get_strcols)
      444    0.001    0.000    2.230    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:611(get_strcols)
      444    0.013    0.000    2.167    0.005 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:845(_get_strcols_without_index)
     2607    0.010    0.000    1.894    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:892(format_col)
       13    0.004    0.000    1.880    0.145 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:746(plot_dfracs_compare_MSE)
       85    0.001    0.000    1.797    0.021 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/core/universe.py:317(__init__)
     2760    0.011    0.000    1.796    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1251(format_array)
     2760    0.004    0.000    1.747    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1362(get_result)
        3    0.000    0.000    1.741    0.580 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:2036(split_benchmark_BV_boxplot_by_split_type)
       38    0.007    0.000    1.525    0.040 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/seaborn/categorical.py:583(plot_boxes)
       83    0.001    0.000    1.494    0.018 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/core/universe.py:104(_topology_from_file_like)
       83    0.011    0.000    1.467    0.018 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/topology/PDBParser.py:200(parse)
       83    0.710    0.009    1.386    0.017 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/topology/PDBParser.py:224(_parseatoms)
       31    0.001    0.000    1.365    0.044 /home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:824(prepare_structures)
        7    0.000    0.000    1.228    0.175 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/base.py:1135(wrapper)
        6    0.001    0.000    1.212    0.202 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1447(fit)
      204    0.003    0.000    1.156    0.006 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axis.py:1156(draw)
        2    0.002    0.001    1.131    0.565 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:1002(plot_paired_errors)
       13    0.003    0.000    1.079    0.083 /home/alexi/Documents/ValDX/ValDX/Experiment_ABC.py:86(split_segments)
       41    0.000    0.000    1.075    0.026 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backend_bases.py:1997(draw_idle)
281491/208353    0.199    0.000    1.068    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
        3    0.000    0.000    1.038    0.346 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:2151(plot_cluster_weights)
        1    0.004    0.004    0.985    0.985 /home/alexi/Documents/ValDX/ValDX/helpful_funcs.py:744(cluster_traj_by_density)
      110    0.006    0.000    0.848    0.008 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_axes.py:3790(bxp)
   107/83    0.000    0.000    0.841    0.010 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py:439(wrapper)
       22    0.000    0.000    0.803    0.036 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:899(write)
       22    0.000    0.000    0.802    0.036 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:976(_write_next_frame)
       22    0.150    0.007    0.800    0.036 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py:1074(_write_timestep)
     1158    0.033    0.000    0.792    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1366(_format_strings)
       60    0.000    0.000    0.786    0.013 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:960(_init_centroids)
       60    0.073    0.001    0.785    0.013 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:178(_kmeans_plusplus)
        3    0.000    0.000    0.756    0.252 /home/alexi/Documents/ValDX/ValDX/HDX_plots.py:1908(split_benchmark_plot_MSE_by_split)
       16    0.000    0.000    0.748    0.047 /home/alexi/Documents/ValDX/ValDX/ValidationDX.py:97(load_structures)
    80361    0.056    0.000    0.713    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1389(_format)
      764    0.002    0.000    0.702    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1613(_format_strings)
      764    0.011    0.000    0.700    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1514(get_result_as_array)
       39    0.000    0.000    0.687    0.018 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/_base.py:643(__exit__)
       39    0.004    0.000    0.687    0.018 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/concurrent/futures/process.py:679(shutdown)
     4935    0.002    0.000    0.680    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/threading.py:1017(_wait_for_tstate_lock)
       78    0.000    0.000    0.677    0.009 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/threading.py:979(join)
      800    0.002    0.000    0.666    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1539(format_values_with)
     7941    0.009    0.000    0.643    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/ops/common.py:67(new_method)
     6004    0.010    0.000    0.639    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py:268(_get_agg_font)
       52    0.000    0.000    0.631    0.012 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/figure.py:1254(add_subplot)
       52    0.000    0.000    0.628    0.012 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_subplots.py:18(__init__)
       52    0.001    0.000    0.622    0.012 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_base.py:434(__init__)
144541/82932    0.087    0.000    0.615    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/printing.py:164(pprint_thing)
     4238    0.008    0.000    0.607    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py:215(get_text_width_height_descent)
     1546    0.006    0.000    0.604    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_axes.py:1510(plot)
     1536    0.002    0.000    0.602    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axes/_axes.py:4003(doplot)
     6191    0.037    0.000    0.601    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/text.py:266(_get_layout)
30072/29491    0.087    0.000    0.591    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/series.py:368(__init__)
4853950/4822654    0.345    0.000    0.562    0.000 {built-in method builtins.isinstance}
     3416    0.041    0.000    0.558    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/text.py:665(draw)
       78    0.001    0.000    0.556    0.007 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/legend.py:588(draw)
    12404    0.008    0.000    0.549    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/posixpath.py:387(realpath)
     3557    0.016    0.000    0.544    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/text.py:861(get_window_extent)
      800    0.004    0.000    0.536    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/format.py:1986(_trim_zeros_float)
8395/6757    0.016    0.000    0.526    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/indexing.py:1089(__getitem__)
      780    0.009    0.000    0.517    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/multiprocessing/util.py:433(_flush_std_streams)
     6615    0.004    0.000    0.512    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/arraylike.py:38(__eq__)
     6615    0.021    0.000    0.508    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/series.py:6086(_cmp_method)
     1560    0.028    0.000    0.507    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/ipykernel/iostream.py:592(flush)
       52    0.001    0.000    0.481    0.009 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:736(__init__)
       52    0.005    0.000    0.477    0.009 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/subprocess.py:1568(_execute_child)
12467/12404    0.084    0.000    0.471    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/posixpath.py:396(_joinrealpath)
     4288    0.014    0.000    0.464    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/core/indexing.py:831(__setitem__)
      504    0.001    0.000    0.447    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axis.py:1089(_get_tick_bboxes)
     4084    0.008    0.000    0.447    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/io/formats/printing.py:98(_pprint_seq)
      504    0.002    0.000    0.446    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axis.py:1091(<listcomp>)
      606    0.002    0.000    0.444    0.001 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axis.py:1375(get_major_ticks)
     1218    0.005    0.000    0.442    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/axis.py:283(draw)
    48056    0.012    0.000    0.439    0.000 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/pandas/_config/config.py:260(__call__)
       24    0.000    0.000    0.433    0.018 /home/alexi/anaconda3/envs/HDXER_ENV/lib/python3.8/site-packages/matplotlib/pyplot.py:1140(subplots)

In [25]:
# # BPTI data
# BPTI_dir = "/Users/alexi/Library/CloudStorage/OneDrive-Nexus365/Rotation_Projects/Rotation_3/Project/ValDX/raw_data/HDXer_tutorial/BPTI"
# # BPTI_dir = "/home/alexi/Documents/ValDX/raw_data/HDXer_tutorial/BPTI"

In [26]:
# expt_dir = os.path.join(BPTI_dir, "BPTI_expt_data")

# os.listdir(expt_dir)

# segs_name = "BPTI_residue_segs.txt"
# segs_path = os.path.join(expt_dir, segs_name)

# hdx_name = "BPTI_expt_dfracs.dat"
# hdx_path = os.path.join(expt_dir, hdx_name)
# print(hdx_path)

# rates_name = "BPTI_Intrinsic_rates.dat"
# rates_path = os.path.join(expt_dir, rates_name)

In [27]:
# sim_name = 'BPTI_MD'

# sim_dir = os.path.join(BPTI_dir, "BPTI_simulations")

# os.listdir(sim_dir)

# md_reps = 1
# rep_dirs = ["Run_"+str(i+1) for i in range(md_reps)]

# top_name = "bpti_5pti_eq6_protonly.gro"

# top_path = os.path.join(sim_dir, rep_dirs[0], top_name)

# traj_name = "bpti_5pti_reimg_protonly.xtc"

# traj_paths = [os.path.join(sim_dir, rep_dir, traj_name) for rep_dir in rep_dirs]

# print(top_path)
# print(traj_paths)

In [28]:
# def run_split_test(split_mode, name, system):

#     # settings.split_mode = 'R'
#     settings.split_mode = split_mode
#     settings.name = "_".join([name, split_mode])
#     settings.times = [0.0, 0.5, 5.0]
#     VDX = ValDXer(settings)

#     VDX.load_HDX_data(HDX_path=hdx_path, SEG_path=segs_path, calc_name=expt_name)
#     # VDX.load_intrinsic_rates(path=rates_path, calc_name=expt_name)

#     VDX.load_structures(top_path=top_path, traj_paths=traj_paths, calc_name=test_name)

#     run_outputs = VDX.run_VDX(calc_name=test_name, expt_name=expt_name)
#     analysis_dump, df, name = VDX.dump_analysis()
#     save_path = VDX.save_experiment()

#     return run_outputs, analysis_dump, df, name, save_path

In [29]:

# splits = ['r', 'SR', 'R3']
# split_names = ['AvsB', 'LvsX', 'mixAandB']
# system = 'BPTITtut_test'

# raw_run_outputs = {}
# analysis_dumps = {}
# analysis_df = pd.DataFrame()
# names = []
# save_paths = []


# for split, split_name in zip(splits, split_names):
#     run_outputs, analysis_dump, df, name, save_path = run_split_test(split, split_name, system)
#     raw_run_outputs[name] = run_outputs
#     analysis_dumps.update(analysis_dump)
#     analysis_df = pd.concat([analysis_df, df])
#     names.append(name)
#     save_paths.append(save_path)

In [30]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named df
# Replace 'your_dataframe' with your actual DataFrame variable
df = analysis_df

# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('MSE over Time by Type for each Named Split Mode')

# Create boxplots
g = g.map(sns.boxplot, "time", "mse", "Type", palette="Set3")

# Adding some additional options for better visualization
g.add_legend(title='Type')
g.set_axis_labels("Time", "MSE")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

NameError: name 'analysis_df' is not defined

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named df
# Replace 'your_dataframe' with your actual DataFrame variable
df = analysis_df

# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('R over Time by Type for each Named Split Mode')

# Create boxplots
g = g.map(sns.boxplot, "time", "R", "Type", palette="Set3")

# Adding some additional options for better visualization
g.add_legend(title='Type')
g.set_axis_labels("Time", "R")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

In [ ]:
# plot LogPfs by Residues colour by calc_name facet wrap by name
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
LogPfs = pd.concat([analysis_dumps[i]["LogPfs"] for i in names])

print(LogPfs)

LogPfs_df = LogPfs.explode(['LogPf','Residues'])


# Create a FacetGrid, using 'name' for each subplot
g = sns.FacetGrid(LogPfs_df, col="name", col_wrap=3, height=4, aspect=1.5)
g.fig.suptitle('LogPfs over Residues for each Named Split Mode')

# Create lineplots
g = g.map(sns.lineplot, "Residues", "LogPf", "calc_name", palette="Set2")

# Adding some additional options for better visualization
g.add_legend(title='calc_name')
g.set_axis_labels("Residues", "LogPf")
g.set_titles("{col_name}")

# Adjust the arrangement of the plots
plt.subplots_adjust(top=0.9)

# Show plot
plt.show()

In [ ]:
# from MDAnalysis.analysis.dssp import DSSP

In [ ]:
# VDX.paths.head()

In [ ]:
# print(top_path)

In [ ]:
# pdb_test = mda.Universe(top_path)

# # write out as a pdb and add header
# pdb_test.atoms.write('test.pdb')
# with open('test.pdb', 'r') as original: data = original.read()
# with open('test.pdb', 'w') as modified: modified.write('HEADER    '+sim_name+'\n'+data)

In [ ]:


# def PDB_to_DSSP(top_path: str, dssp_path: str=None, sim_name: str=None):
#     """
#     Run DSSP on a PDB file to generate a DSSP file. Reads the output and returns a list of secondary structure elements.
#     Secondary structure elements are reduced to a single character: H (alpha helix), S (beta sheet), or L (loop).
#     Args:
#     - top_path (str): The path to the topology file to create the PDB file from.
#     - dssp_path (str): The path to save the DSSP file.
#     - sim_name (str): Simulation name to be included in the HEADER of the PDB file.
#     Returns:
#     - List of tuples, each containing the residue number and its secondary structure element.
#     """
#     temp_pdb = "do_mkdssp.pdb"

#     if sim_name is None:
#         sim_name = "DSSP HEADER"
#     if dssp_path is None:
#         dssp_path = "dssp_file.dssp"
#     print(top_path)
#     pdb_test = mda.Universe(top_path)

#     # write out as a pdb and add header
#     pdb_test.atoms.write(temp_pdb)


#     with open(temp_pdb, 'r') as original: data = original.read()
#     with open(temp_pdb, 'w') as modified: modified.write('HEADER    '+sim_name+'\n'+data)

#     # Run mkdssp to generate DSSP file
#     try:
#         subprocess.run(['mkdssp', temp_pdb,  dssp_path], check=True)
#     except subprocess.CalledProcessError as e:
#         print(f"Error running DSSP: {e}")
#         return []

#     # Parse the DSSP file
#     secondary_structures = []
#     with open(dssp_path, 'r') as dssp_file:
#         # Skip header lines
#         for line in dssp_file:
#             if line.startswith('  #  RESIDUE AA'):
#                 break
#         # Read the secondary structure assignments
#         for line in dssp_file:
#             if len(line) > 13:  # Ensure line has enough data
#                 residue_num = line[5:10].strip()
#                 ss = line[16]
#                 # Simplify the secondary structure to H, S, or L
#                 if ss in 'GHI':
#                     ss = 'H'  # Helix
#                 elif ss in 'EB':
#                     ss = 'S'  # Sheet
#                 else:
#                     ss = 'L'  # Loop or other
#                 secondary_structures.append((residue_num, ss))

#     # Cleanup temp PDB file
#     os.remove(temp_pdb)
#     os.remove(dssp_path)
#     print(len(secondary_structures))
#     print(len(pdb_test.residues))
#     return secondary_structures